betagouv/mon-service-securise

src/depotDonnees.js, src/depots/depotDonneesAutorisations.js, src/depots/depotDonneesHomologations.js, src/erreurs.js, src/modeles/autorisations/ajoutContributeurSurServices.js, src/modeles/autorisations/autorisationBase.js, src/modeles/autorisations/autorisationContributeur.js, src/modeles/autorisations/gestionDroits.js, src/routes/privees/routesApiPrivee.js, src/routes/procedures.js, test/constructeurs/constructeurAutorisation.js, test/depots/depotDonneesAutorisations.spec.js, test/depots/depotDonneesHomologations.spec.js, test/modeles/autorisations/ajoutContributeurSurServices.spec.js, test/modeles/autorisations/autorisationBase.spec.js, test/routes/privees/routesApiPrivee.spec.js
Cette PR a pour objectif de donner à l'API la possibilité de piloter les droits qui sont accordés au nouveau contributeur invité.
Le choix de mettre les droits en écriture se fait juste au moment d'appeler la persistance.
Plusieurs choses :
- Le dépôt prend désormais un objet du domaine : une `AutorisationBase` (ou une sous-classe)
- Il utilise `.donneesAPersister()` pour rester le plus ignorant possible de comment sont gérés les droits
- Ces droits sont injectés directement dans `procedure.ajoutContributeurSurServices()` qui est appelée par l'API
Dans cette PR, l'API appelle systématiquement avec `tousDroitsEnEcriture()`.
La suite est de prendre en paramètre une indication sur les droits à appliquer : `LECTURE` ou `ECRITURE`.
=> Pilotage des droits accordés par la couche API

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depotDonnees.js, src/depots/depotDonneesAutorisations.js, src/modeles/autorisations/autorisationBase.js, src/routes/privees/routesApiService.js, test/constructeurs/constructeurAutorisation.js, test/depots/depotDonneesAutorisations.spec.js, test/modeles/autorisations/autorisationBase.spec.js, test/routes/privees/routesApiService.spec.js
Cette PR ajoute la route qui permet de modifier une autorisation, avec une requête de la forme :
```http
PATCH /api/service/59398409-5a5b-4555-90ac-40955b6f77d6/autorisations/5f94f7c8-bd00-4abd-80dc-27f60fd7ddba
Content-Type: application/json
{
"droits": {
"HOMOLOGUER": 1
}
}
```
On ajoute au `depotDonneesAutorisations` la capacité de sauvegarder un objet `autorisation` tout entier.
=> Route `PATCH /autorisations/:idAutorisation`

svelte/lib/gestionContributeurs/ChampAvecSuggestions.svelte, svelte/lib/gestionContributeurs/InvitationContributeur.svelte
… en changeant la casse de l'email.
Avant ce commit, `christophe@beta.gouv.fr` et `CHRISTOPHE@beta.gouv.fr` pouvaient être ajoutés simultanément.
=> [CORRECTION] Empêche d'inviter la même personne 2 fois

src/vues/motDePasse/edition.pug, src/vues/tableauDeBord.pug, src/vues/utilisateur/edition.pug
Le tableau de bord est la seule page privée où on veut afficher ce bouton des « Nouveautés ».
=> Affiche « Nouveautés » sur le tableau de bord

.github/workflows/node.js.yml
… car c'est la version qui fait tourner MSS en PROD.
=> Utilise `node 18` pour la CI

src/modeles/autorisations/autorisationBase.js, src/modeles/objetsApi/objetGetIndicesCyber.js, src/routes/privees/routesService.js, src/vues/service/formulaireEtapierRecommandation.pug, src/vues/service/mesures.pug, test/routes/privees/routesService.spec.js
Pour voir l'indice cyber, il faut `LECTURE` sur `SECURISER`.
Cette PR masque la carte `Indice Cyber` pour les utilisateurs qui n'ont pas ce droit.
AVANT 👇 
APRÈS 👇
=> Masque l'indice cyber aux utilisateurs n'ayant pas le droit de le voir

src/http/middleware.js, src/routes/privees/routesApiService.js, src/routes/privees/routesApiServicePdf.js, src/routes/privees/routesService.js, test/http/middleware.spec.js, test/mocks/middleware.js, test/routes/privees/routesApiService.spec.js, test/routes/privees/routesApiServicePdf.spec.js, test/routes/privees/routesService.spec.js
… pour qu'il mette l'autorisation dans la `requete`.
Ça simplifie le travail des routes, qui ont directement accès à l'object `Autorisation`.
=> Enrichissement du middleware `chargeAutorisationsService`

public/modules/soumetsHomologation.mjs, test_public/modules/soumetsHomologation.spec.mjs
… depuis la page « Décrire ».
Cette PR ajoute de la logique d'aiguillage : 
* à l'édition d'un service, on reste sur « Décrire » (ce que faisait systématiquement l'existant)
* à la création, on passe à « Sécuriser »
=> Navigation vers « Sécuriser » ou « Décrire »

public/assets/styles/menuNavigation.css, src/vues/fragments/menuNavigation.pug
Cette PR ajoute les `hover` et `active` 👇
=> Couleurs `hover` et `active` des éléments du menu

svelte/lib/gestionContributeurs/GestionContributeurs.svelte, svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte
Cette PR ajuste 2 choses vues en démo.
**Ajout d'une marge sur chaque ligne de contributeur**
| AVANT | APRÈS |
| ![image](https://github.com/betagouv/mon-service-securise/assets/24898521/1d919b2d-2ba7-4012-a2ec-acb19770caa3) | ![image](https://github.com/betagouv/mon-service-securise/assets/24898521/7eab1ba7-ca13-4d0c-a803-f43ba6c4557c) | 
**Change les couleurs de survol de choix des droits**
Pour réutiliser les même couleurs que sur la personnalisation fine de droits.
=> Contributeurs Svelte : ajustements graphiques

test/depots/depotDonneesAutorisations.spec.js
…dans `ajouteUneAutorisation`, afin de supprimer les utilisations directes de constructeur `AutorisationBase` et de données brutes.
=> Utilise systématiquement `uneAutorisation` au lieu de données brute

test/constructeurs/constructeurService.js, test/modeles/homologation.spec.js
… Afin de ne plus utiliser directement les données d'homologation `createur` et `contributeurs`, pour faciliter la suppression de cette notion dans le modèle.
=> Utilise systématiquement le constructeur de service dans les tests qi utilise les contributeurs et créateurs

migrations/20231020062200_ajouteChampEstProprietaire.js
On ajoute le champ `estProprietaire` pour démarrer le développement des fonctionnalités de service à propriétaires multiple.
Le champ `type` est pour l'instant conservé : il sera supprimé à la fin du dev. de cette feature.
=> [MIGRATION] Ajoute le champ `estProprietaire`

src/adaptateurs/adaptateurPostgres.js
...afin de ne plus utiliser le `type = createur`
=> Utilise `estProprietaire` dans la méthode `homologations`

src/depots/depotDonneesHomologations.js, src/modeles/autorisations/autorisationBase.js, test/depots/depotDonneesAutorisations.spec.js, test/modeles/autorisations/autorisationBase.spec.js, test/modeles/objetsApi/objetGetIndicesCyber.spec.js, test/modeles/objetsApi/objetGetServices.spec.js, test/routes/privees/routesApiService.spec.js
Afin de pouvoir instancier directement les autorisations de propriétaire sans se soucier des droits, qui seront par définition métier toujours en `ECRITURE` sur toutes les rubriques
=> Force tous les droits en écriture pour un proprietaire

src/routes/privees/routesApiService.js
... au lieu d'utiliser `type = createur`.
On peut maintenant, en tant que contributeur, voir le **OU LES** propriétaires d'un service.
=> Filtre les propriétaires via `estProprietaire` dans l'affichage des autorisations d'un service

consoleAdministration.js, src/depots/depotDonneesHomologations.js, src/routes/privees/routesApiService.js, test/depots/depotDonneesHomologations.spec.js, test/routes/privees/routesApiService.spec.js
On fait cette modification pour deux raisons:
- On ne veut plus se reposer sur `homologation.createur` car ce champ va disparaître
- La duplication est donc maintenant disponible pour TOUT les propriétaires
=> Passe l'identifiant de l'utilisateur propriétaire au moment de la duplication

test/constructeurs/constructeurService.js, test/constructeurs/constructeurUtilisateur.js, test/modeles/objetsApi/objetGetService.spec.js, test/modeles/objetsApi/objetGetServices.spec.js
Afin de faciliter la transition `createur` -> `proprietaires`
=> Utilise le constructeur de Service dans les tests d'`objetGetService`

test/constructeurs/constructeurService.js, test/routes/privees/routesApiPrivee.spec.js
Afin de faciliter la transition `createur` -> `proprietaires`
=> Utilise le constructeur de service dans les tests `routesApiPrivee`

test/constructeurs/constructeurAutorisation.js, test/depots/depotDonneesAutorisations.spec.js, test/depots/depotDonneesHomologations.spec.js, test/depots/depotDonneesUtilisateurs.spec.js, test/modeles/autorisations/ajoutContributeurSurServices.spec.js, test/modeles/objetsApi/objetGetIndicesCyber.spec.js, test/modeles/objetsApi/objetGetService.spec.js, test/modeles/objetsApi/objetGetServices.spec.js, test/routes/privees/routesApiPrivee.spec.js, test/routes/privees/routesApiService.spec.js
Afin de supprimer tous les références à `createur` dans le projet
=> Renomme `Createur` en `Proprietaire` dans le constructeur d'autorisation de test

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesUtilisateurs.js
... en `proprietaire` afin de coller avec la nouvelle implémentation.
=> Renomme les fonctions utilisant `createur`

src/depots/depotDonneesHomologations.js
Cette fonction utilisait sytématiquement l'`id` et l'`email` du créateur de service, et non pas de celui qui réalisait l'action de modification de description.
Cela nous permet aussi de supprimer la dépendance à `createur`.
=> Corrige la fonction `ajouteDescriptionServiceAHomologation`

src/depots/depotDonneesHomologations.js, src/routes/privees/routesApiService.js, test/depots/depotDonneesHomologations.spec.js, test/routes/privees/routesApiService.spec.js
Cette fonction utilisait sytématiquement l'`id` et l'`email` du créateur de service, et non pas de celui qui réalisait l'action d'ajout de mesures.
Cela nous permet aussi de supprimer la dépendance à `createur`.
=> Corrige la fonction `ajouteMesuresAHomologation`

src/depots/depotDonneesHomologations.js
Cette fonction utilisait sytématiquement l'`email` du créateur de service.
On préfère lire l'utilisateur en base ici pour supprimer la dépendance avec `service.createur`.
=> Supprime la dépendance à `service.createur` dans la fonction `nouveauService`

src/depots/depotDonneesAutorisations.js, src/erreurs.js, src/routes/privees/routesApiPrivee.js, test/depots/depotDonneesAutorisations.spec.js, test/routes/privees/routesApiPrivee.spec.js
Avec cette PR le dépôt de données accepte de supprimer n'importe quelle autorisation à condition qu'elle ne concerne pas l'utilisateur courant.
Donc la suppression de propriétaire devient possible…sans toutefois pouvoir se supprimer soi-même.
L'API passe donc désormais l'ID de l'utilisateur courant au dépôt.
=> Ajoute la capacité de supprimer un propriétaire

public/service/risques.js, public/service/rolesResponsabilites.js
... sur les rubriques "Risques" et "Contacts".
On ne faisait pas le `preventDefault`, donc le seul bouton du formulaire agissait comme un submit, ce qui entrainait un rechargement de la page et donc une concurence entre notre `POST` réel et le rechargement.
On avait donc dans certains cas des données qui n'était pas sauvegardée.
=> [HOTFIX] Corrige la soumissions des formulaires

src/mss.js
Afin de garantir un cache pendant une heure et rendre la navigation plus fluide.
=> Ajoute un `max-age` sur les fichiers statiques afin de pouvoir les ajouter au `cache`

.env.template, server.js, src/adaptateurs/adaptateurProtection.js, src/http/middleware.js, src/routes/privees/routesApiPrivee.js, src/routes/privees/routesApiService.js, src/routes/publiques/routesApiPublique.js, test/mocks/middleware.js, test/routes/privees/routesApiService.spec.js, test/routes/publiques/routesApiPublique.spec.js, test/routes/testeurMSS.js
On souhaite ajouter du `rate-limit` plus fin sur certaines routes afin de sécuriser les points sensibles.
Les routes :
- `POST /token`
- `POST /reinitialisationMotDePasse`
- `POST /utilisateur`
- `POST /api/service`
- `COPY /api/service/:id`
=> Ajoute un `rate-limit` sur les endpoints sensibles

.env.template, src/http/configurationServeur.js, src/mss.js
... Afin de ne pas utiliser de cache lors du dev local.
=> Extrais la variable de `cache-control` en variable d'environnement

svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte, svelte/lib/gestionContributeurs/personnalisation/TagLectureEcriture.svelte
Afin de les mettres tous de la même couleur, en suivant le figma :point_down:
=> Uniformise les couleurs des `:hover` et `.nom` du menu de droit

README.md, docker-compose.yml
Pour faciliter le travail en local, cette PR :
- ouvre le port `5432` de Postgres
- exécute MSS en `--inspect` pour y brancher un debugger.
Exemple de branchement du debugger dans IntelliJ 👇
=> Outillage du dev en local 

src/routes/privees/routesApiService.js, test/routes/privees/routesApiService.spec.js
… pour éviter des problèmes de suppression de l'unique propriétaire restant.
=> Empêche l'utilisateur courant de modifier ses propres autorisations

src/routes/privees/routesApiService.js, test/routes/privees/routesApiService.spec.js
… pour éviter une attaque comme :
- j'ai les droits sur A, pas sur B
- je fais un `PATCH /service/A/autorisations/une-autorisation-de-B`
- MSS me laisse modifier l'autorisation de B, car il a seulement vérifié mes droits sur A
Avec cette PR, cette traversée de A vers B devient bloquée.
=> Empêche de modifier une autorisation n'appartenant pas au service ciblé

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesUtilisateurs.js, src/modeles/autorisations/autorisationBase.js, src/modeles/autorisations/fabriqueAutorisation.js, test/constructeurs/constructeurAutorisation.js, test/modeles/autorisations/autorisationBase.spec.js
Ce champ est osbolète. C'est désormais `estProprietaire` qui est utilisé.
=> Suppression du champ `type` de `Autorisation`

src/modeles/autorisations/ajoutContributeurSurServices.js, src/modeles/autorisations/autorisationBase.js, src/modeles/autorisations/gestionDroits.js, svelte/lib/gestionContributeurs/gestionContributeurs.d.ts, svelte/lib/gestionContributeurs/invitation/ListeInvitations.svelte, svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte, test/modeles/autorisations/ajoutContributeurSurServices.spec.js, test/modeles/autorisations/autorisationBase.spec.js, test/routes/privees/routesApiService.spec.js
Cette PR permet à un utilisateur de nommer un autre propriétaire 👇 
qui donne comme résultat 👇
=> Ajout de la possibilité de nommer un « Propriétaire »

donneesReferentiel.js, src/referentiel.js, test/referentiel.spec.js
Afin de préparer la nouvelle page indice cyber, nous mettons à jours le référentiel pour y incorporer :
- une durée d'homologation recommandée
- un conseil avant homologation
- une explication de la tranche de l'indice cyber
=> Mise à jour du référentiel de l'indice cyber

src/adaptateurs/adaptateurProtection.js
Ça permettra d'avoir directement l'info quand on regarde les erreurs dans Sentry.
=> Ajoute le type de requête dans l'erreur « Trop de trafic »

src/modeles/autorisations/autorisationBase.js, test/modeles/autorisations/autorisationBase.spec.js
Maintenant que MSS autorisation la nomination d'autres propriétaires, on peut sereinement utiliser `estProprietaire` dans `peutHomologuer()`.
=> Homologuer réservé aux propriétaires

migrations/20231124110131_supprimeTypeAutorisation.js
Ce champ est devenu inutile maintenant que MSS utilise systématiquement `estProprietaire`.
=> [MIGRATION] Supprime le champ `type` de `autorisations`

src/depots/depotDonneesHomologations.js, src/modeles/autorisations/ajoutContributeurSurServices.js, src/modeles/autorisations/autorisation.js, src/modeles/autorisations/fabriqueAutorisation.js, src/modeles/homologation.js, src/modeles/objetsApi/objetGetIndicesCyber.js, src/modeles/objetsApi/objetGetService.js, src/modeles/objetsApi/objetGetServices.js, src/routes/privees/routesApiServicePdf.js, src/routes/privees/routesService.js, test/constructeurs/constructeurAutorisation.js, test/modeles/autorisations/autorisation.spec.js, test/routes/privees/routesApiService.spec.js
Il n'y a plus de classes filles, donc inutile de suffixer avec `Base`.
=> [SOIN] Renomme `AutorisationBase` en `Autorisation`

src/vues/erreurAccesRefuse.pug
Car inutile sur cette page. (Retour démo)
=> Supprime le lien "Découvrez nos nouveautés" sur la page d'erreur de droit d'accès

public/assets/images/fond_recommandation_anssi.svg, public/assets/images/icone_explication_tranche.svg, public/assets/images/icone_recommandation_anssi.svg, public/assets/styles/homologation/indiceCyber.css, public/assets/styles/radarIndiceCyber.css, src/routes/privees/routesService.js, src/vues/fragments/radarIndiceCyber.pug, src/vues/service/indiceCyber.pug, test/routes/privees/routesService.spec.js
On ajoute la nouvelle page `Indice cyber` :point_down: 
Elle n'est pour l'instant accessible que par l'url. 
Le graphique est un SVG.
=> Ajout de la page `Indice cyber`

src/routes/publiques/routesBibliotheques.js
Afin d'éviter de polluer notre Sentry avec les erreurs `400` de Matomo lorsque celui-ci dysfonctionne cette PR cesse d'appeler le `error handler` global (branché à Sentry) sur ce type d'erreur.
🧹 On en profite pour passer quelques soins : `async/await` et `guard clause`.
=> Cesse de polluer Sentry avec les erreurs remontées par les bibliothèques distantes

public/modules/parametresDescriptionService.mjs, src/modeles/descriptionService.js, src/routes/privees/routesApiService.js, test/constructeurs/constructeurDescriptionService.js, test/modeles/descriptionService.spec.js, test/modeles/homologation.spec.js, test/routes/privees/routesApiService.spec.js
Cette PR ajoute le champ `nombreOrganisationsUtilisatrices` sur les **CRÉATIONS** de service.
La valeur du champ est codée en dur. 
En BDD, chaque service créé ou édité reçoit donc 👇 
C'est le premier pas sur le chemin de la feature complète autour du champ.
=> Ajout du champ `nombreOrganisationsUtilisatrices` à `DescriptionService`

src/vues/service/indiceCyber.pug
Afin d'afficher un message supplémentaire si l'indice cyber est < 2.
=> Ajoute un conditionnement pour l'affichage de la durée d'homologation conseillée

public/assets/styles/radarIndiceCyber.css, src/vues/fragments/indiceCyber/radarIndiceCyber.pug
On rajoute un comportement `hover` sur le diagramme radar.
Les données sont affichées lors du click sur le point.
=> Ajoute un point au survol du graphique radar

donneesReferentiel.js, public/assets/images/coche_blanche.svg, public/assets/styles/homologation/indiceCyber.css, src/referentiel.js, src/vues/service/indiceCyber.pug, test/referentiel.spec.js
On affiche maintenant les tranches sous forme de liste :point_down:
=> Modification de l'affichage des tranches indice cyber

src/depots/depotDonneesHomologations.js, src/modeles/journalMSS/erreurs.js, src/modeles/journalMSS/evenementCompletudeServiceModifiee.js, test/modeles/journalMSS/constructeurEvenementCompletudeServiceModifiee.js, test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js
… dans l'événement existant `COMPLETUDE_SERVICE_MODIFIEE`.
L'événement ressemble désormais à :
```js
{
"type": "COMPLETUDE_SERVICE_MODIFIEE",
"donnees": {
"idService": "…",
"detailIndiceCyber": [   ],
"nombreTotalMesures": 33,
"nombreMesuresCompletes": 0,
"detailMesures": [],
"nombreOrganisationsUtilisatrices": {  // <-- Nouveau champ
"borneBasse": 1,
"borneHaute": 1
}
},
"date": 1701705532045
}
```
=> Envoie jusqu'à Metabase le nombre d'organisations utilisatrices d'un service

public/assets/images/coche_blanche.svg, public/assets/styles/homologation/indiceCyber.css
On remplace par un `bullet` blanc
=> Supprime la coche blanche sur la valeur de l'indice cyber

donneesReferentiel.js, src/pdf/modeles/annexeAvis.pug
Ce screenshot montre ce qui a disparu 👇 
Cette PR remet en place les données utilisées pour la génération du PDF.
Et au passage corrige une coquille.
=> [CORRECTION] Réparation d'une disparition de données dans le PDF dossier d'homologation

public/assets/styles/headerLarge.css, public/assets/styles/homologation/descriptionService.css, public/assets/styles/homologation/formulaire.css, public/assets/styles/homologation/mesures.css, public/assets/styles/homologation/risques.css, public/assets/styles/homologation/rolesResponsabilites.css, public/assets/styles/menuNavigation.css, public/assets/styles/mss.css, public/assets/styles/parcoursService.css, src/vues/fragments/formulaireDescriptionService.pug, src/vues/parcoursService.pug, src/vues/service/descriptionService.pug, src/vues/service/formulaireEtapier.pug, src/vues/service/mesures.pug, src/vues/service/risques.pug, src/vues/service/rolesResponsabilites.pug, test/routes/privees/routesService.spec.js
On met à jour l'affichage des titres et sous-titres de toute les pages 'Service'
On en profite pour réaligner le nom du service dans le header.
=> Titres et sous-titres des pages du service

src/depotDonnees.js, src/depots/depotDonneesHomologations.js, src/routes/privees/routesApiService.js, test/depots/depotDonneesHomologations.spec.js, test/routes/privees/routesApiService.spec.js
… lors de la modification de la description du service.
Depuis 870e24b99c04485d6c8787bdb37cc7b7cd8495bd la promesse de `adaptateurJournalMSS.consigneEvenement` était ignorée, donc le code non exécuté.
Cette PR :
- répare ce bug 
- passe du code en `async/await` 
- change du vocabulaire `homologation` en `service`
=> [CORRECTION] Réparation de l'envoi de complétude à Metabase

donneesReferentiel.js, public/service/mesures.js, src/pdf/modeles/ressources/styles.css, src/pdf/modeles/syntheseSecurite.pug
Afin de correspondre au nouveau statut :point_down: 
Les valeurs en base restent les mêmes, il s'agit seulement d'une modification cosmétique.
=> [SECURISER] Modifie les labels des statuts

public/assets/styles/homologation/mesures.css
Afin de coller avec le figma :point_down:
=> [SECURISER] Ajoute un comportement `hover` et `active` sur le cartouche de l'indice cyber

public/assets/styles/homologation/mesures.css, src/routes/privees/routesService.js, src/vues/fragments/jaugeProgressionMesures.pug, src/vues/parcoursService.pug, src/vues/service/mesures.pug
On l'affiche à coté de l'indice cyber en attendant la refonte de la page.
Cette jauge ne peut pour l'instant pas être animée à cause d'un blocage de l'animation par les CSP.
Ce bug est uniquement présent sur Firefox.
=> [SECURISER] Ajout de la jauge de progression de complétude des mesures

public/assets/styles/homologation/mesures.css, src/vues/fragments/jaugeProgressionMesures.pug
Pour que le texte du pourcentage soit de la même taille que le corps de texte à côté
=> Augmente la taille de la jauge de progression

public/assets/images/icone_enregistrement_en_cours.svg, public/assets/images/icone_enregistrement_termine.svg, public/assets/images/logo_mss_petit.svg, public/service/mesures-v2.js, src/routes/privees/routesService.js, src/vues/service/mesures-v2.pug, src/vues/service/mesures.pug, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.api.ts, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts, svelte/lib/tableauDesMesures/tableauDesMesures.ts
On ajoute le nouveau composant de visualisation des mesures au format tableau.
=> [SECURISER] Vue tableau des mesures

public/assets/styles/tiroir.css, public/service/mesures-v2.js, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.api.ts
On peut désormais ajouter une mesure spécifique via un bouton "Ajouter" présent au dessus du tableau des mesures.
Ce bouton déclenche l'affichage du tiroir de mesure :point_down: 
Pour l'instant, on est obligé de `window.location.reload()` la page pour ne pas casser le fonctionnement existant sur l'ancienne page des mesures.
À l'avenir, on pourra imaginer fermer le tiroir et rafraichir le tableau en utilisant des `events` sur le `document.body`
=> [SECURISER] Ajout de mesure spécifique via le tiroir

public/assets/styles/homologation/mesures.css, public/service/mesures.js, src/vues/service/mesures.pug
Cette PR ajoute de l'auto-save sur « Sécuriser » dans sa version actuellement en PROD.
Changer une valeur du formulaire déclenche la sauvegarde 👇 
Même approche que pour le composant Svelte `TableauDesMesures` : on ne **change pas** l'archi des intéractions entre front et back.
Donc cette PR :
- utilise le code existant pour la sauvegarde
- branche ce code sur des `event handlers` qui écoutent les `change|blur` des champs et la suppression des mesures spécifiques
- utilise `reportValidity()` pour ne pas déclencher la sauvegarde lorsque le formulaire est invalide
=> Activation de l'auto-save sur la page « Sécuriser » v1

src/mss.js, test/mss.spec.js
Cette PR vérifie le format de `idReset` dans la route `/initialisationMotDePasse/:idReset`.
S'il ne s'agit pas d'un `UUID` alors le dépôt de données n'est pas sollicité. Une erreur `400` est retournée directement.
On se passe d'adaptateur ici. On se branche directement sur `uuid.validate()` par souci de simplicité.
=> [SÉCURITÉ] Verification du format de `idReset`

server.js, src/bus/abonnements/mesuresServiceModifiees/consigneDansJournal.js, src/bus/abonnements/mesuresServiceModifiees/envoieTrackingDeCompletude.js, src/bus/busEvenements.js, src/bus/cablage.js, src/bus/evenementMesuresServiceModifiees.js, src/depotDonnees.js, src/depots/depotDonneesHomologations.js, test/bus/abonnements/mesuresServiceModifiees/consigneDansJournal.spec.js, test/bus/abonnements/mesuresServiceModifiees/envoieTrackingDeCompletude.spec.js, test/bus/busEvenements.spec.js, test/constructeurs/constructeurDepotDonneesServices.js, test/depots/depotDonneesHomologations.spec.js
… pour déporter le code qui alimente le journal MSS et celui qui envoie les données de tracking.
📍 Avec cette PR, lorsque `depotDonneesHomologations.ajouteMesuresAHomologation()` est appelée :
- à la fin de la fonction, un événement `EvenementMesuresServiceModifiees` est publié sur le `busEvenements`
- les abonnées à `EvenementMesuresServiceModifiees` sont alors appelés
- ils sont au nombre de 2
- `consigneDansJournal()` qui alimente le journal MSS
- `envoieTrackingCompletude()` qui envoie les données de tracking
---------
🎉  Ça permet d'alléger considérablement les responsabilités de la fonction du dépôt.
La PR est 100% fonctionnelle et iso-fonctionnalité : les mêmes données sont publiées sur les mêmes canaux.
Le code de dépôt devient :
```js
const ajouteMesuresAHomologation = async ( …
```
=> Création d'un bus d'événements

public/assets/images/chevron_noir.svg, public/modules/tableauDeBord/actions/ActionMesure.mjs, public/service/mesures-v2.js, svelte/lib/mesure/Mesure.svelte, svelte/lib/mesure/entete/EnteteTiroir.svelte, svelte/lib/mesure/mesure.api.ts, svelte/lib/mesure/mesure.d.ts, svelte/lib/mesure/mesure.store.ts, svelte/lib/mesure/mesure.ts, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
On ajoute la modification des mesures par le tiroir 'Mesure' existant.
Toute la payload de mesures est passée au bundle Svelte lors de l'instanciation.
Le bundle "écrase" la valeur de la mesure à éditer avant de la renvoyer vers l'API.
=> [SECURISER] Édition de mesure via le tiroir

public/assets/styles/formulaire.css, public/modules/tableauDeBord/actions/ActionMesure.mjs, public/service/mesures-v2.js, src/vues/service/mesures-v2.pug, svelte/lib/mesure/Mesure.svelte, svelte/lib/mesure/mesure.d.ts, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts
On ajoute le mode "Lecture seule" sur le tableau des mesures et le tiroir des mesures.
On réutilise les mécanismes mit en place dans le Pug et JQuery, à savoir :
- `disabled` pour les `select`
- `readonly` pour les `input` et `textarea`
=> [SECURISER] Lecture seule des mesures

src/vues/parcoursService.pug, src/vues/service/mesures-v2.pug, src/vues/service/mesures.pug, src/vues/tableauDeBord.pug, svelte/vite.config.mts
On remarque un problème avec les composants "Partagés" en Svelte :
Leur feuilles de styles CSS respectives sont compilés dans des fichiers séparés, ce qui créer des dépendences entre le contexte d'utilisation et la déclaration de `style` associée.
On choisit donc de compiler tous les styles des composants `Svelte` dans un fichier unique : `style.css`
=> [Svelte] Feuille de style unique pour les composants

svelte/lib/mesure/entete/EnteteTiroir.svelte, svelte/lib/mesure/mesure.store.ts, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/ui/CartoucheReferentiel.svelte, svelte/lib/ui/types.d.ts
On harmonise les couleurs des cartouches `Référentiel` entre le tiroir des mesures et le tableau des mesures :point_down: 
Pour cela, on extrait un composant partagé `CartoucheReferentiel`
=> [SECURISER] Cartouche du référentiel

svelte/lib/mesure/Mesure.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/ui/SelectionStatut.svelte, svelte/lib/ui/types.d.ts
On extrait un composant réutilisable pour la sélection de statut (Tableau et tiroir des mesures).
On en profite pour styliser le composant en fonction de la valeur sélectionée.
=> [SECURISER] Composant de sélection du statut

src/routes/privees/routesApiService.js, test/routes/privees/routesApiService.spec.js
... afin de préparer l'implémentation des indicateurs "autonomes" de la page SECURISER.
On veut pouvoir rafraichir les valeurs des indicateurs de l'indice cyber et du taux de complétude.
Pour cela, on aura besoin d'une route dedié afin que les composants Svelte puisse eux-même faire les appels API.
=> [SECURISER] Ajoute une route pour obtenir l'indice cyber d'un service

svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
Les "cartouches" des catégories de mesures ne portaient pas le même style que sur le Figma :point_down: 
On corrige cet affichage :point_down:
=> [CORRECTION] Cartouche des catégories

src/routes/privees/routesApiService.js, test/routes/privees/routesApiService.spec.js
... afin de préparer l'implémentation des indicateurs "autonomes" de la page SECURISER.
On veut pouvoir rafraichir les valeurs des indicateurs de l'indice cyber et du taux de complétude.
Pour cela, on aura besoin d'une route dedié afin que les composants Svelte puisse eux-même faire les appels API.
=> [SECURISER] Ajoute une route pour obtenir le pourcentage de complétude des mesures d'un service

public/service/mesures-v2.js, public/service/mesures.js, svelte/lib/mesure/Mesure.svelte, svelte/lib/mesure/suppression/SuppressionMesureSpecifique.svelte, svelte/lib/tableauDesMesures/TableauDesMesures.svelte
On utilise un évenement du DOM sur `document.body` intitulé `mesure-modifiee` afin de communiquer entre tous les composants.
Cet évenement est émit par :
- Le tableau des mesures lors de la modification d'un statut
- Le tiroir de mesure lors de l'ajout, la modification ou la suppression d'une mesure
Il est écouté par :
- Le tableau des mesures pour recharger toutes les mesures
- Les indicateurs (Dans le PR #1235) pour recharger leur valeurs
- Le script `mesure.js` et `mesure-v2.js` pour fermer le tiroir si besoin
L'évenement porte un champ facultatif `doitFermerTiroir` pour instruire une action coté jQuery.
=> [SECURISER] Emission de l'évenement `mesure-modifiee`

svelte/lib/mesure/Mesure.svelte
... remplacé par un tiret pour rester cohérent avec les autres champs.
=> [CORRECTION] Corrige le wording "Non renseigné"

public/assets/styles/homologation/mesures.css, public/service/mesures-v2.js, public/service/mesures.js, src/vues/fragments/jaugeProgressionMesures.pug, src/vues/service/mesures-v2.pug, src/vues/service/mesures.pug, svelte/lib/completudeMesures/CompletudeMesures.svelte, svelte/lib/completudeMesures/completudeMesure.api.ts, svelte/lib/completudeMesures/completudeMesure.d.ts, svelte/lib/completudeMesures/completudeMesure.ts, svelte/lib/completudeMesures/confetti/Confetti.svelte
On créer un composant Svelte `CompletudeMesure` qui vient remplacer la jauge de progression `pug` actuelle.
On ajoute une animation au moment du passage au delà des 49% de complétude.
=> [SECURISER] Composant Svelte de complétude des mesures

src/adaptateurs/adaptateurProtection.js
On sait que MSS se fait parfois scanner.
Ça pollue notre Sentry car chaque scan donne lieu à + de 2 500 events Sentry. Et ces events ne nous servent à rien.
Donc on passe en `console.warn` pour ces events.
=> Cesse de loguer les erreurs `Navigation` dans Sentry

svelte/lib/mesure/Mesure.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/ui/SelectionStatut.svelte
Suite à des retours de l'équipe, on corrige: 
- L'espacement entre les astérisques rouges des champs requis et le label
- L'espacement au dessus du bouton "Enregistrer" dans le tiroir
- Un titre de mesure spécifique trop long et sans espace peut entrainer un dépassement dans le tableau
=> [SECURISER] Derniers correctifs UI

svelte/lib/mesure/mesure.store.ts
... sinon le store passe la valeur par référence, qui sera donc elle même modifié lors des modifications apportées dans le tiroir.
Cette valeur est par la suite réutilisée au moment de l'instanciation, elle garde donc les anciennes valeurs.
Pour reproduire :
- Ajouter une mesure
- Remplir les champs et enregistrer
- Ajouter une nouvelle mesure
- :arrow_right: Le tiroir est bien vide
=> [CORRECTION] Reinitialise la mesure par défaut au moment de l'instanciation du bundle

public/assets/styles/homologation/mesures.css
... car les indicateurs étaient alignés à droite de la page
=> [CORRECITON] Corrige l'alignement des indicateurs

svelte/lib/directives/surligneTexte.ts, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.store.ts, svelte/lib/tableauDesMesures/tableauDesMesures.ts, svelte/lib/ui/SelectionStatut.svelte
On souhaite pouvoir rechercher des mesures, via un champ texte, en se basant sur :
- L'intitulé d'une mesure
- Le commentaire
- La description dans le cas d'une mesure générale
```mermaid
graph LR
D -- dérivé --> A[$mesures] 
C -- dérivé --> B[$rechercheTextuelle]
D{$mesuresFiltrees} -- dérivé --> C[$predicats] 
E[$nombreResultats] -- dérivé --> A
E -- dérivé --> D
```
Le store `$predicats` contient :
- Une liste des predicats actifs
- Une liste des filtres à appliquer pour chaque prédicat
sous la forme :
```typescript
type Predicats = {
actifs: IdFiltre[],
predicats: Record<IdFiltre, () => boolean>
}
```
=> [SECURISER] Recherche des mesures

public/assets/images/icone_filtre.svg, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.store.ts, svelte/lib/ui/MenuFlottant.svelte
On ajoute les filtres dans le tableau des mesures.
On utilise les même stores `derived` que dans la PR #1250
Le cas du référentiel `ANSSI` est particulier car il y'a des "sous-référentiels" pour `Indispensable` et `Recommandé`.
=> [SECURISER] Ajout des filtres

svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
...car ce chevron avait du disparaître lors de l'ajout du surlignage de la recherche.
On s'aligne avec la maquette Figma.
=> [SECURISER] Ajoute le chevron sur la ligne de mesure

svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.store.ts, svelte/lib/ui/SelectionStatut.svelte
La propagation des évènements diffère entre Chrome et Firefox.
Sur Chrome, lors de la modification d'un statut de mesure depuis le tableau, l'élèment est supprimé du DOM avant de pouvoir propagé son évènement de modification.
On a donc affaire à un `race-condition` entre la propagation des évènements, la mise à jour du DOM et le `setter` du store
Pour corriger :
- on se branche sur l'évènement `on:input` qui est trigger avant le `on:change`
- on fait remonter la nouvelle valeur du statut
- on modifie cette valeur directement dans le store
- on enregistre les mesures
=> [CORRECTION] Corrige la sauvegarde des mesures sur Chrome

svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
... car les légendes s'affiche "centrées" par défaut sur chrome.
=> [CORRECTION] Corrige l'alignement des légendes de filtre dans chrome

svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.store.ts
Reproduction du bug:
- Coche "ANSSI" : les sous-filtres sont cochés
- Décoche un sous-filtre : "ANSSI" passe en affichage "sélection partielle"
- Clique une fois "ANSSI" : on repasse en "sélection totale"
- Clique de nouveau "ANSSI" : on revient en "partielle" de l'étape 2
Le bug est ce retour à l'étape 2 : on veut plutôt effacer complètement les filtres ANSSI.
C'est ce que fait ce commit. Les fonctions "ajouteFiltre" et "supprimeFiltre" étaient inversées.
=> [CORRECTION] Permets le décochage complet des filtres "ANSSI"

src/vues/tableauDeBord.pug, svelte/lib/tableauDesMesures/TableauDesMesures.svelte
Afin d'indiquer les champs dans lesquels on recherche, et non des exemples.
=> Modifie le wording des `placeholder` de recherche

svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte, svelte/lib/ui/MenuFlottant.svelte
Le menu flottant n'était plus positionné correctement dans le tiroir des contributeurs.
Comme on a maintenant une seule feuille de style pour tous les bundles Svelte, les css `:global` s'applique à tous les composants.
On choisit de pouvoir paramétrer la position du menu flottant.
=> [CORRECTION] Ajoute un paramètre pour positionner le menu flottant à la demande

svelte/lib/gestionContributeurs/invitation/InvitationContributeur.svelte, svelte/lib/gestionContributeurs/invitation/ListeInvitations.svelte, svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte, svelte/lib/gestionContributeurs/personnalisation/TagLectureEcriture.svelte, svelte/lib/ui/FermetureSurClicEnDehors.svelte, svelte/lib/ui/MenuFlottant.svelte
On rend le menu déroulant de sélection des contributeurs accessible. (Utilisation de `button`)
On en profite pour ajouter un attribut à `MenuFlottant` qui permet de choisir si un click interne au menu doit le fermer ou non.
=> [ACCESSIBILITÉ] Menu des contributeurs - Rôle

.env.template, donneesReferentiel.js, src/adaptateurs/adaptateurEnvironnement.js, src/moteurRegles.js, svelte/lib/mesure/entete/EnteteTiroir.svelte, svelte/lib/mesure/mesure.d.ts, svelte/lib/mesure/mesure.store.ts, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts, svelte/lib/ui/types.d.ts, test/moteurRegles.spec.js
On ajoute les 6 mesures CNIL au moteur de règles.
Ces mesures ont le comportement suivant :
- On affiche les mesures CNIL si au moins une case du step DECRIRE champ “Données à caractère personnel et autres données sensibles stockées par le service”
- Leurs notes impactent le calcul de l’indice cyber ANSSI
- Chaque mesure est "indispensable"
- Elles sont liées à une catégorie : gouvernance
Le moteur de règles s'occupe de filtrer ces mesures via un feature flag `AVEC_MESURES_CNIL`
=> Ajout du référentiel CNIL

public/service/mesures.js, src/http/middleware.js, src/routes/privees/routesService.js, src/vues/service/mesures.pug, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts, svelte/lib/tableauDesMesures/tableauDesMesures.store.ts, test/http/middleware.spec.js, test/mocks/middleware.js, test/routes/privees/routesService.spec.js
On ajoute le filtre pour le référentiel CNIL.
Ce filtre est affiché conditonnelement via un feature flag `avecMesuresCNIL`, exposé dans les `locals` du pug.
=> Ajout du filtre pour le référentiel CNIL

src/modeles/mesures.js, src/modeles/mesuresGenerales.js, src/modeles/objetsApi/objetGetMesures.js, src/mss.js, src/routes/privees/routesApiPrivee.js, src/routes/privees/routesApiService.js, test/modeles/mesures.spec.js, test/modeles/objetsApi/objetGetMesures.spec.js, test/routes/privees/routesApiService.spec.js
On veut pouvoir facilement, pour un service, obtenir la liste des toutes les mesures sous un format exploitable.
Il s'agit donc de réconcilier les `mesuresGenerales` d'un service avec les données complémentaires disponible dans les `donneesReferentiel`, par le biais du `moteurRegles`.
```mermaid
graph LR
A(Service) -- contient --> B(Mesures)
A -- contient --> G(DescriptionService)
B -- instancie --> C(MesuresGenerales)
B -- instancie --> D(MesuresSpecifiques)
E(MoteurRegles) -- conditionne --> B
H(referentiel) -- alimenté par --> F(donnesReferentiel)
E -- alimenté par --> H
E -- alimenté par --> G
```
Cette méthode peut être utilisé :
- Au niveau de l'API
- Pour facilement savoir quels référentiels de mesures sont utilisés
- etc...
=> [MESURES] Ajoute une méthode pour enrichir les mesures

public/assets/styles/homologation/mesures.css, src/vues/service/mesures.pug, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
On utilise une barre "sticky" pour la barre d'actions de SÉCURISER.
On en profite pour afficher le nombre de mesures filtrées à l'intérieur du menu.
[Screencast from 19-01-2024 14:38:11.webm](https://github.com/betagouv/mon-service-securise/assets/1643465/ac1388d1-a6eb-43f4-8a4e-451a9137de9c)
=> Ajoute un header sticky pour le tableau des mesures

public/assets/styles/homologation/mesures.css
... afin de conserver un affichage acceptable sur les petites résolutions :point_down:
=> [CORRECTION] Ajoute un "padding" minimum pour les petits écrans

donneesReferentiel.js, src/modeles/objetsPDF/objetPDFAnnexeMesures.js, src/pdf/modeles/annexeMesures.pug, src/pdf/modeles/ressources/styles.css, src/pdf/modeles/syntheseSecurite.pug, src/referentiel.js, src/routes/privees/routesApiServicePdf.js, test/modeles/objetsPDF/objetPDFAnnexeMesures.spec.js, test/referentiel.spec.js
... afin de prendre en compte l'arrivé d'un nouveau référentiel.
=> Ajoute "et la CNIL" dans les PDFs

svelte/lib/tableauDesMesures/tableauDesMesures.store.ts
... car ce bug affichait les mesures ANSSI dans tous les cas.
=> [CORRECTION] Filtre les mesures en fonction de leur référentiel

public/assets/styles/homologation/mesures.css
… sinon les indicateurs se chevauchent avec l'affichage de "X/Y mesures filtrées"
=> [CORRECTION] Ajoute l'espace de `margin` du tableau des mesures à la `width`

src/routes/privees/routesService.js, src/vues/service/indiceCyber.pug
On réutilise le même mécanisme que pour le PDF synthèse de sécurité.
=> Ajoute l'affichage conditonnel des référentiels dans la page indice cyber

svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
On affiche systématiquement les sous-référentiels "Indispensable" et "Recommandé"
=> Ne masque pas les "sous-catégories" indispensable et recommandée du référentiel ANSSI

donneesReferentiel.js, server.js, src/modeles/journalMSS/erreurs.js, src/modeles/journalMSS/evenementRetourUtilisateurMesure.js, src/mss.js, src/referentiel.js, src/routes/privees/routesApiPrivee.js, src/routes/privees/routesApiService.js, test/modeles/journalMSS/evenementRetourUtilisateurMesure.spec.js, test/referentiel.spec.js, test/routes/privees/routesApiService.spec.js, test/routes/testeurMSS.js
On ajoute une route afin de récupérer les "feedbacks" utilisateur sur les mesures de sécurité, depuis le tableau des mesures, via le tiroir.
Cette route agit comme un "proxy", valide les données, puis les consigne dans Metabase.
La partie front sera faite des une autre PR.
=> [SÉCURISER] Route pour les retours utilisateur sur les mesures

src/depots/depotDonneesHomologations.js
... en appellant la persistance qu'une fois, à la fin.
Cette optimisation permet de passer, en local, de ≈ 2 secondes par appel à 500ms.
Le plus gros du temps consommé est maintenant dans le fait qu'on `await` tous les consommateurs dans le bus d'événement
=> Améliore les performances de l'enregistrement des mesures générales

package-lock.json, package.json, src/adaptateurs/adaptateurCsv.js, src/mss.js, src/routes/privees/routesService.js, test/routes/privees/routesService.spec.js, test/routes/testeurMSS.js
Cette PR ajoute la route `/service/:id/mesures/export.csv` qui sort les mesures dans un fichier CSV 👇 
La route a un paramètre en _query string_ : `avecDonneesAdditionnelles`.
Ce paramètre conditionne l'export des 2 dernières colonnes du CSV.
Cette PR ajoute `"csv-writer"` et `"string-strip-html"` pour industrialiser l'export.
Le premier export, celui des services, est refactoré pour utiliser `csv-writer`.
=> Nouvelle route pour exporter en CSV les mesures d'un service

public/scripts/menuNavigation.js, svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte, svelte/lib/ui/menuNavigation.store.ts
On masque "mesure affichées" lorsque le menu de navigation est ouvert, pour éviter le chevauchement avec les indicateurs.
[Screencast from 30-01-2024 10:05:43.webm](https://github.com/betagouv/mon-service-securise/assets/1643465/7023579a-40a1-4167-9754-a3cd753f7239)
Pour cela, on observe l'élément `menu-navigation` grâce au [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). Cela nous permet de créer un `store` Svelte qui est capable de connaitre l'état d'ouverture du menu, alors que le composant du menu n'est pas dans les bundles Svelte.
On en profite pour ajouter le statut "actif" sur le bouton du filtre.
Au passage on rajoute `SameSite=strict` au cookie du menu de navigation, car Firefox se plaint :
```
Cookie “etat-menu-navigation” does not have a …
```
=> [SÉCURISER] Barre sticky - Masquage lors de l'ouverture du menu de navigation

creeUtilisateurDemo.js, src/bus/busEvenements.js, test/bus/busEvenements.spec.js
... car on ne souhaite pas obtenir le résultat des promesses, mais uniquement loguer les erreurs éventuelles.
On opte donc pour une stratégie "Fire & Forget, but catch errors".
=> [PERFORMANCE] N'attends pas l'exécution de tous les handlers lors de la publication

src/adaptateurs/adaptateurTrackingSendinblue.js
… comme ça arrive parfois sur les erreurs de PROD. Sans le `?.` on se retrouve à planter à cause du code dans le `catch`…
=> [CORRECTION] Cesse de planter si l'exception n'a pas de `response`

src/bus/busEvenements.js
...pour éviter les crash si il n'y a aucun abonné
=> [CORRECTION] Conditionne la boucle `forEach`

public/assets/styles/formulaire.css
... car tout les CTA "Nouvel item" sont en gras dans les maquettes.
=> Ajoute `bold` sur les `nouvel-item` pour harmoniser MSS

src/vues/service/indiceCyber.pug
Afin de rajouter la mention "Il est un indicateur de la qualité de la démarche de sécurisation du service."
=> Modifie le wording de la description de l'indice cyber

public/assets/styles/tableauDeBord.css
...car sinon il passe dèrriere les liens vers le tiroir contributeurs
=> [CORRECTION] Incrémente le `z-index` du menu flottant de tri des contributeurs

src/bus/abonnements/consigneProprietaireCreeUnServiceDansJournal.js, src/bus/cablage.js, src/modeles/journalMSS/erreurs.js, src/modeles/journalMSS/evenementCollaboratifServiceModifie.js, test/bus/abonnements/consigneProprietaireCreeUnServiceDansJournal.spec.js, test/modeles/journalMSS/evenementCollaboratifServiceModifie.spec.js
On veut désormais avoir des infos sur le collaboratif dans notre Metabase : savoir combien de collaborateurs ont les services, avec quel type de rôle, etc.
On va s'appuyer sur le design existant et y ajouter de nouveaux éléments :
- Côté Journal : un nouvel événement `EvenementCollaboratifServiceModifie` qui sera consigné par `adaptateurJournal`
- Côté MSS : un nouvel événement `EvenementAutorisationsModifiees` qui sera publié par `depotDonneesAutorisations`
- Pour faire le lien entre les deux :
- un nouvel abonné au Bus `consigneProprietaireCreeUnServiceDansJournal()` déclenché à la création de service
- un nouvel abonné au Bus `consigneChangementAutorisationsDansJournal()` déclenché lors des ajouts / modifications / suppressions d'autorisations
Un schéma un peu plus global, qui montre …
=> [COLLABORATIF] Tracker le lien entre un créateur de service et son nouveau service

src/depotDonnees.js
… sinon `ajouteContributeurAuService()` plante.
=> [CORRECTION] Passe le `bus` au `depotDonneesAutorisations`

src/depots/depotDonneesHomologations.js
Sans ça, la consignation d'événement ne se faisait pas.
=> [CORRECTION] Ajoute le `await` manquant

donneesReferentiel.js, src/modeles/mesure.js, src/modeles/objetsPDF/objetPDFAnnexeMesures.js, src/modeles/statistiquesMesuresGenerales.js, src/pdf/graphiques/camembert.js, src/pdf/modeles/annexeMesures.pug, src/pdf/modeles/ressources/styles.css, src/pdf/modeles/syntheseSecurite.pug, svelte/lib/ui/SelectionStatut.svelte, test/modeles/mesure.spec.js, test/modeles/mesuresGenerales.spec.js, test/modeles/mesuresSpecifiques.spec.js, test/modeles/statistiquesMesuresGenerales.spec.js, test/pdf/graphiques/camembert.spec.js
On rajoute le nouveau statut "A lancer" dans les mesures.
Cette PR se base sur le travail de remaniement sur les statistiques qui a été fait précédemment.
Le nouveau statut est donc disponible dans la page Sécuriser.
On le rajoute aussi dans les PDF annexes
... et de synthèse sécurité
=> Nouveau statut "À lancer"

src/pdf/graphiques/camembert.js, src/pdf/modeles/ressources/styles.css, src/pdf/modeles/syntheseSecurite.pug, test/pdf/graphiques/camembert.spec.js
Corrige les camemberts lorsque les angles sont supérieurs mais proche de l'angle minimum
...car sinon, l'angle "corrigé" devient inférieur à l'angle miminum. De plus, on corrige :
- un problème au niveau de l'affichage des statuts qui n'ont aucune mesure
- un problème de couleur dans les "barres" par catégorie
- un problème lorsque la "présentation" du service est vide
=> [CORRECTION] Diagramme camembert de la synthèse sécurité

public/assets/styles/homologation/mesures.css
...afin de masquer les cartouches textuels si le conteneur est trop petit
=> [SÉCURISER] Ajoute des `container-queries` sur les indicateurs de la barre d'outils

consoleAdministration.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesHomologations.js, test/depots/depotDonneesHomologations.spec.js
Nous avons besoin de générer manuellement des événements de `EvenementCompletudeServiceModifiee` pour tous les services.
De cette façon nous aurons dans Metabase les données de complétude à jour après le déploiement du référentiel CNIL qui a eu lieu il y a quelques semaines.
Cette PR répare la `consoleAdministration` car la génération d'événements de complétude n'avait pas été maintenue.
=> [ADMIN] Répare la génération d'événements de complétude pour tous les services

consoleAdministration.js
… au lieu de le placer à la racine de l'objet où il sera finalement non persisté.
Avec cette PR, on a bien le champ au bon endroit 👇 
Avant, il était placé à la racine de l'objet… et donc totalement ignoré par la persistance.
=> [CORRECTION] Place `genereParAdministrateur` dans les `donnees`

.env.template, package-lock.json, package.json, src/adaptateurs/adaptateurEnvironnement.js, src/adaptateurs/adaptateurGestionErreurSentry.js, src/adaptateurs/adaptateurGestionErreurVide.js, src/http/middleware.js, src/mss.js, test/mocks/middleware.js, test/mss.spec.js
… qui ne servira que les IP mentionnées dans la variable d'environnement `ADRESSES_IP_AUTORISEES`.
On en profite pour changer la signature de `controleurErreurs()` dans l'adaptateur de gestion d'erreur vide : désormais la signature correspond à celle du l'adaptateur Sentry, qui fait foi.
=> [SÉCURITÉ] Ajoute un filtrage d'IP

.env.template, scripts/clever-cloud/post-build-clever.sh, scripts/clever-cloud/pre-run-clever.sh, server.js, src/adaptateurs/adaptateurChiffrement.js, src/adaptateurs/adaptateurChiffrementVault.js, src/adaptateurs/adaptateurEnvironnement.js, src/adaptateurs/fabriqueAdaptateurChiffrement.js, src/depotDonnees.js, src/depots/depotDonneesHomologations.js, src/depots/depotDonneesUtilisateurs.js, src/http/middleware.js, src/modeles/journalMSS/evenement.js, test/constructeurs/constructeurDepotDonneesServices.js, test/depots/depotDonneesAutorisations.spec.js, test/depots/depotDonneesHomologations.spec.js, test/mocks/adaptateurChiffrement.js
Nous allons bientôt avoir un « Vault as a service » à disposition. Le code chiffrera donc les données métier avant de les stocker.
Le but est que le code puisse supporter cette fonctionnalité dès que le Vault sera disponible.
Cette PR est la première sur ce chemin du support total du chiffrement.
Ici on ajoute le support de `chiffre` et `dechiffre` dans `adaptateurChiffrementVault`.
Ce nouvel adaptateur est utilisé si `AVEC_CHIFFREMENT_VAULT=true`. Sinon, c'est le chiffrement déjà en place (qui ne fait rien, donc) qui est utilisé.
La PR modifie `depotDonneesHomologations` pour que la sauvegarde et la lecture de **un** service passe par le chiffrement / déchiffrement.
- attention particulière sur la duplication de services, qui requête les noms de service en BDD : ce ne sera plus possible. …
=> Implémente partiellement le support du chiffrement par Vault

test/constructeurs/constructeurAutorisation.js, test/constructeurs/constructeurService.js, test/depots/depotDonneesAutorisations.spec.js, test/depots/depotDonneesHomologations.spec.js, test/depots/depotDonneesUtilisateurs.spec.js, test/modeles/autorisations/ajoutContributeurSurServices.spec.js, test/modeles/objetsApi/objetGetIndicesCyber.spec.js, test/modeles/objetsApi/objetGetService.spec.js, test/modeles/objetsApi/objetGetServices.spec.js, test/routes/privees/routesApiPrivee.spec.js, test/routes/privees/routesApiService.spec.js
Pour rendre plus lisibles et plus robustes les tests.
=> [SOIN] Utilise le constructeur de `depot`

public/assets/styles/tableauDeBord.css
... afin qu'il ai la même taille que le cartouche "Contributeurs"
=> Harmonise la hauteur du score indice cyber dans le tableau de bord

src/adaptateurs/adaptateurPostgres.js
... car sinon on n'attend pas que la méthode soit exécutée avant de continuer
=> [CORRECTION] Ajoute un await sur les appels des méthodes `metsAJourTable` et `ajouteLigneDansTable`

src/adaptateurs/adaptateurPersistanceMemoire.js, src/depots/depotDonneesAutorisations.js, test/depots/depotDonneesAutorisations.spec.js
On veut désormais avoir des infos sur le collaboratif dans notre Metabase : savoir combien de collaborateurs ont les services, avec quel type de rôle, etc.
- #1323  
- #1325 
Cette PR implémente les flèches montrées en jaune à droite dans le schéma 👇 
On se glisse dans le design existant, avec `await publieAutorisationsDuService()` dans le dépôt.
=> [COLLABORATIF] Publication des modifications d'autorisations sur le bus

consoleAdministration.js, src/bus/abonnements/consigneAutorisationsModifieesDansJournal.js, src/bus/cablage.js, test/bus/abonnements/consigneAutorisationsModifieesDansJournal.spec.js
On câble les événements de modification/ajout/suppression du collaboratif vers l'adaptateur Journal MSS, afin de stocker cette donnée coté Metabase.
Tous les événements on été développé dans des PRs précédentes.
Il s'agit juste ici de "brancher" l'adaptateur `JournalMSS ` depuis le `bus`.
On en profite pour rajouter une méthode à la `consoleAdministration` pour pouvoir faire un rattrapage des autorisations des services existants.
=> Câble les modifications d'autorisations vers un envoi au journal MSS

public/assets/styles/entete.responsive.css
...car les éléments s'affichaient sur la même ligne 
| ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/74673ea6-ede4-499b-87bc-231919d0f744) | ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/b941b7f5-02a7-4fa3-bde2-812fb0f7fef4) |
=> [CORRECTION] Affiche correctement les éléments de connexion au format mobile

public/motDePasse/edition.js, src/routes/privees/routesApiPrivee.js, src/routes/publiques/routesApiPublique.js, src/vues/fragments/formulaireUtilisateur.pug, src/vues/fragments/utilisateur/preferencesCommunication.pug, src/vues/motDePasse/edition.pug, test/routes/privees/routesApiPrivee.spec.js, test/routes/publiques/routesApiPublique.spec.js
Afin de pouvoir proposer l'inscription à l'infolettre pour des utilisateurs qui ont étés invités, on rajoute les préférences de communication dans l'écran de création de mot de passe :point_down:
=> Acceptation de l'infolettre lors de l'invitation

consoleAdministration.js, creeUtilisateurDemo.js
Depuis 3c68582390c7344cd6b70f171de93b3a8337f4f8 on n'utilise plus de valeur par défaut. On avait oublié de mettre à jour ces 2 appelants de `creerDepot()`.
=> [CORRECTION] Répare l'injection de dépendances de l'adaptateur chiffrement

src/bus/abonnements/consigneAutorisationsModifieesDansJournal.js, src/bus/abonnements/consigneCompletudeDansJournal.js, src/bus/abonnements/consigneNouveauServiceDansJournal.js, src/bus/abonnements/consigneProprietaireCreeUnServiceDansJournal.js, src/bus/abonnements/envoieTrackingDeCompletude.js, src/bus/abonnements/envoieTrackingDeNouveauService.js, src/bus/cablage.js, src/bus/evenementDescriptionServiceModifiee.js, src/depotDonnees.js, src/depots/depotDonneesHomologations.js, test/bus/abonnements/consigneAutorisationsModifieesDansJournal.spec.js, test/bus/abonnements/consigneCompletudeDansJournal.spec.js, test/bus/abonnements/consigneNouveauServiceDansJournal.spec.js, test/bus/abonnements/consigneProprietaireCreeUnServiceDansJournal.spec.js, test/bus/abonnements/envoieTrackingDeCompletude.spec.js, test/bus/abonnements/envoieTrackingDeNouveauService.spec.js, test/bus/evenementDescriptionServiceModifiee.spec.js, test/constructeurs/constructeurDepotDonneesServices.js, test/depots/depotDonneesHomologations.spec.js
On veut désormais envoyer dans Metabase des données de l'étape DÉCRIRE.
Typiquement : type de service, provenance, fonctionnalités, …
Avec le design en place, c'est l'événement Metabase `EvenementCompletudeServiceModifiee` envoyé par l'abonné `consigneCompletudeDansJournal` qui est le bon candidat pour porter ces nouvelles données.
Cet abonné est déclenché lors de la CRÉATION d'un service _(chemin du haut dans le schéma 👇 )_
Mais il n'est pas déclenché lors de la MODIFICATION d'un service _(chemin du bas dans le schéma 👇 )_
Autrement dit : on a un problème car `EvenementCompletudeServiceModifiee` est instancié à 2 endroits différents. Une fois dans l'abonné (ça, c'est bien) et une fois dans le dépôt (ça, c'est pas bien).
- Après cette PR, on a donc `consigneCompletudeDansJournal` qui est …
=> Utilisation de `busEvenements` dans `ajouteDescriptionService`

public/assets/images/icone_telecharger_tampon.svg, public/assets/styles/etapesDossier.css, public/assets/styles/tiroir.css, public/modules/tableauDeBord/actions/ActionTelechargementTamponHomologation.js, public/service/homologation/dossiers.js, src/routes/privees/routesService.js, src/vues/parcoursService.pug, src/vues/service/dossiers.pug, src/vues/tiroirs/tiroirTelechargementTamponHomologation.pug
- une action héritant de `ActionAbstraite`
- un fichier `.pug` associé
- un déclenchement de l'ouverture via le `gestionnaireTiroir.afficheContenuAction()`
- un dossier d'homologation est actif et `activee` (donc non-périmé)
- l'utilisateur possède les droits requis (au moins `LECTURE` sur `DECRIRE` et `HOMOLOGUER`)
=> Ajout du tiroir de téléchargement du tampon d'homologation

src/modeles/dossiers.js, src/routes/privees/routesService.js, test/modeles/dossiers.spec.js
On corrige ici un problème `legacy` du statut de saisie des dossiers d'homologation.
Depuis le commit [5fbbb68](https://github.com/betagouv/mon-service-securise/commit/5fbbb68a86519449a4c1dd66edbecc61c63c9eee) il est maintenant possible de savoir précisément si un dossier est en cours de validité ou non.
=> [HOMOLOGUER] Coche verte dans le menu de navigation

public/assets/styles/homologation/mesures.css
... dans la page SÉCURISER, pour prendre en compte l'ouverture/fermeture du menu de navigation.
[Screencast from 28-02-2024 16:53:36.webm](https://github.com/betagouv/mon-service-securise/assets/1643465/1bbbf7b4-b001-481c-9335-605422b0375d)
=> Modifie le seuil à partir duquel on masque les indicateurs

public/assets/styles/homologation/risques.css, src/vues/service/risques.pug, src/vues/service/rolesResponsabilites.pug
...afin d'harmoniser toutes les pages du parcours service.
=> Suppression des sous titres sur les pages `Risques` et  `Contacts utiles`

public/assets/styles/tableauDeBord.css, public/modules/tableauDeBord/tableauDesServices.mjs, src/modeles/objetsApi/objetGetService.js, test/modeles/objetsApi/objetGetService.spec.js, test/routes/privees/routesApiService.spec.js
On ajoute un lien vers la rubrique `HOMOLOGUER` depuis le statut d'homologation du tableau de bord, avec un lien direct vers l'étape courante si elle existe.
=> [TDB] Lien vers la rubrique HOMOLOGUER

public/assets/styles/nouvellesFonctionnalites/modaleNouvellesFonctionnalites.css
... afin d'afficher la pagination correctement.
L’explication :
https://stackoverflow.com/a/51785787/8526334
| ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/863b03db-3214-435b-99ca-92c56b64baf6) | ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/f913fd95-4ef5-45dc-b9b5-15519261d1c5) |
=> [CORRECTION] Bordure des "ronds" de pagination du carrousel

consoleAdministration.js, src/bus/abonnements/consigneCompletudeDansJournal.js, src/modeles/journalMSS/erreurs.js, src/modeles/journalMSS/evenementCompletudeServiceModifiee.js, test/modeles/journalMSS/constructeurEvenementCompletudeServiceModifiee.js, test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js
En vue de rajouter des nouvelles données dans l'événement `EvenementCompletudeServiceModifiee`, on remanie son fonctionnement.
Comme toutes les données proviennent du `service`, on ne passe plus que ce dernier en `donnees`.
=> [REMANIEMENT] Événement de complétude du service modifiée

src/modeles/journalMSS/evenementCompletudeServiceModifiee.js, test/constructeurs/constructeurService.js, test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js
On souhaite rajouter dans l'événement `EvenementCompletudeServiceModifiee` les informations suivantes :
- Type de services
- Provenance
- Statut
- :heavy_plus_sign: Nombre d’accès
- Liste des features
- :heavy_plus_sign: Nombre features custom
- Liste des données à caractère personnel
- :heavy_plus_sign: Nombre données à caractère personnel custom
- Localisation données
- Durée maximale dysfonctionnement
- Impact si atteinte à la sécurité
_Les :heavy_plus_sign:  indiquent que ce n’est PAS la donnée brute, mais seulement le compte._
Toutes ces données sont disponible dans la `descriptionService` de l'objet `service`, qui est maintenant passé à l'événement depuis la PR #1369
=> [DECRIRE] Ajout de propriétés complementaires dans l'événement `EvenementCompletudeServiceModifiee`

src/vues/service/dossiers.pug
Cette information n'a pas de sens pour les homologations passées.
=> Retire l'affichage du statut de l'homologation pour les dossiers passés

src/adaptateurs/adaptateurProtection.js
... car en mode `trust proxy`, express remplace `requete.ip` par l'IP du client final, à savoir, l'addresse "la plus à gauche" de `x-forwarded-for`
=> Supprime l'utilisation de `x-real-ip`

src/modeles/dossiers.js, test/modeles/dossiers.spec.js
…afin de les afficher dans un ordre cohérent sur le front.
| ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/9d4a094d-f38e-451d-a014-ed234a0dad57) | ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/e6a599b9-bafd-4fa9-98a4-150e585ca9c8) |
=> Tri les dossiers archives dans l'ordre décroissant des date de prochaine homologation

public/modules/tableauDeBord/actions/ActionTelechargementTamponHomologation.js, src/adaptateurs/adaptateurPdf.configurationTamponHomologation.js, src/adaptateurs/adaptateurPdf.js, src/vues/service/dossiers.pug, src/vues/tiroirs/tiroirTelechargementTamponHomologation.pug
... suite à une décision du produit.
=> Renomme "cartouche" en "encart" pour le tampon d'homologation

src/modeles/objetsApi/objetGetService.js, src/referentiel.js, src/routes/privees/routesService.js, src/vues/service/dossiers.pug, test/modeles/objetsApi/objetGetService.spec.js, test/referentiel.spec.js, test/routes/privees/routesService.spec.js
Lors d'une démo, on a remarqué un bug :
Un utilisateur qui n'a pas le droit d'homologation (donc qui n'est pas propriétaire) peut tout de même accéder aux étapes 5 et 6 du parcours HOMOLOGUER.
On corrige donc dans cette PR :
- Le lien affiché dans le tableau de bord, pointant désormais vers la dernière étape DISPONIBLE par l'utilisateur
- La redirection vers l'URL de la dernière étape DISPONIBLE pour un utilisateur
- L'affichage du nombre d'étapes totales d'un dossier d'homologation
=> [CORRECTION] Droit d'accès aux étapes d'homologation

src/bus/abonnements/consigneNouvelUtilisateurInscritDansJournal.js, src/bus/abonnements/consigneProfilUtilisateurModifieDansJournal.js, src/bus/cablage.js, src/bus/evenementUtilisateurInscrit.js, src/bus/evenementUtilisateurModifie.js, src/depotDonnees.js, src/depots/depotDonneesUtilisateurs.js, test/bus/abonnements/consigneNouvelUtilisateurInscritDansJournal.spec.js, test/bus/abonnements/consigneProfilUtilisateurModifieDansJournal.spec.js, test/bus/evenementUtilisateurInscrit.spec.js, test/bus/evenementUtilisateurModifie.spec.js, test/depots/depotDonneesUtilisateurs.spec.js
Actuellement, le `depotDonneesUtilisateur` consigne lui même des évènements dans le journal, via l'`adaptateurJournal`.
On souhaite déplacer cette reponsabilité, grâce au `busEvenements` mit en place.
Les deux évènements concernés sont `ProfilUtilisateurModifie` et `NouvelUtilisateurInscrit`.
=> [SOIN] Extrait la consignation d'évènements associés à l'utilisateur vers le bus d'évènements

server.js, src/bus/abonnements/consigneNouvelleHomologationCreeeDansJournal.js, src/bus/abonnements/consigneServiceSupprimeDansJournal.js, src/bus/cablage.js, src/bus/evenementDossierHomologationFinalise.js, src/bus/evenementServiceSupprime.js, src/depotDonnees.js, src/depots/depotDonneesHomologations.js, test/bus/abonnements/consigneNouvelleHomologationCreeeDansJournal.spec.js, test/bus/abonnements/consigneServiceSupprimeDansJournal.spec.js, test/bus/evenementDossierHomologationFinalise.spec.js, test/bus/evenementServiceSupprime.spec.js, test/constructeurs/constructeurDepotDonneesServices.js, test/depots/depotDonneesHomologations.spec.js, test/depots/depotVide.js
On supprime la dépendance du `depotDonneesHomologation` à l'`adaptateurJournalMSS`.
Désormais, les événements sont envoyés vers le `busEvenements`, qui re-dispatch vers des `listeners` de `consignationDansJournalMSS`.
> Cette PR marque la fin de l'utilisation d'un `adaptateurJournalMSS` dans les `depotDonnees`. C'est un gros ménage qui est étalé sur de nombreuses PR précédente, et qui nous permet de fonctionner uniquement avec le `busEvenements` désormais
=> [SOIN] Utilise le `busEvenements` pour les consignation dans le journal du `depotDonneesHomologation`

donneesReferentiel.js, src/modeles/notificationExpirationHomologation.js, src/referentiel.js, test/modeles/notificationExpirationHomologation.spec.js
On ajoute ce nouveau modèle, qui a pour but de stocker les notifications de rappels (par email) de l'expiration d'un dossier d'homologation.
> Pour l'instant, rien n'est stocké en base.
> Cette table sera ensuite exploité par un `cron` qui fera l'envoi d'email.
Les délais d'attente sont disponible dans [ce document](https://lab-anssi-docs.cleverapps.io/doc/emails-rappels-echeance-homologation-r4WUUFeXAD).
=> Ajoute le modèle `NotificationExpirationHomologation`

server.js, src/bus/abonnements/sauvegardeNotificationsExpirationHomologation.js, src/bus/abonnements/supprimeNotificationsExpirationHomologation.js, src/bus/cablage.js, src/depotDonnees.js, test/bus/abonnements/sauvegardeNotificationsExpirationHomologation.spec.js, test/bus/abonnements/supprimeNotificationsExpirationHomologation.spec.js
On utilise le `busEvenements` pour sauvegarder les notifications d'expiration d'homologation.
On en profite aussi pour supprimer les notifications existantes pour un service au moment de la sauvegarde, et aussi les supprimer au moment de la suppression d'un service.
> [!WARNING]  
> Pour l'instant, le dépôt données a un "bouchon" qui loggue les actions de `sauvegarde` et `suppression`
=> Sauvegarde des notifications d'expiration d'homologation

public/connexion.js, src/http/middleware.js, src/http/redirection.js, src/mss.js, src/vues/connexion.pug, test/http/middleware.spec.js
On souhaite pouvoir rediriger nos utilisateurs vers la page originalement demandée après connexion.
Aujourd'hui, le middleware `verificationJWT` redirige vers la page `/connexion` si jamais le `token` n'est pas présent ou invalide.
Au moment de cette redirection, on peut récupérer l'URL initialement demandée afin de la faire transiter jusqu'à une redirection après connexion.
On filtre volontairement les routes qui commence par `/api` car la redirection ne devrait pas se faire depuis ces appels.
On suit les bonnes pratiques : 
- On ajoute depuis le backend l'url HOST de notre application
- On s'assure que l'url de redirection commence toujours par un `/`
=> Redirection après connexion

src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesUtilisateurs.spec.js
Bug rencontré en PROD :
- un utilisateur arrive sur la page d'initialisation de mot de passe après son inscription
- il valide la page
Attendu : ça fonctionne
Observé : le dépôt crash car le code de l'API l'appelle avec des données partielles :
```
await depotDonnees.metsAJourUtilisateur(u.id, { infolettreAcceptee: true });
```
On avait prévu ce cas dans `depotDonneesUtilisateur.nouvelUtilisateur()` mais on avait oublié `metsAJourUtilisateur()`.
Ce commit rajoute le test et la correction.
=> [CORRECTION] Autorise la mise à jour partielle de profil utilisateur

src/bus/abonnements/consigneProfilUtilisateurModifieDansJournal.js, test/bus/abonnements/consigneProfilUtilisateurModifieDansJournal.spec.js, test/constructeurs/constructeurUtilisateur.js
Car dans le cas d'une invitation, le SIRET de l'entité de l'utilisateur n'est pas encore renseigné
=> [CORRECTION] N'appelle pas la recherche entreprise pour les évènements du journal ProfilUtilisateurModifié pour une invitation

.env.template, cron.json, scripts/taches/tacheEnvoieMailsNotificationExpiration.js, src/adaptateurs/adaptateurMailMemoire.js, src/adaptateurs/adaptateurMailSendinblue.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depotDonnees.js, src/depots/depotDonneesNotificationsExpirationHomologation.js, src/modeles/notificationExpirationHomologation.js, src/taches/envoieMailsNotificationExpirationHomologation.js, test/constructeurs/constructeurAdaptateurPersistanceMemoire.js, test/depots/depotDonneesNotificationsExpirationHomologation.spec.js, test/taches/envoieMailsNotificationExpirationHomologation.spec.js
On ajoute une tâche qui a pour but, chaque jour, d'envoyer les emails de notification d'expiration d'homologation.
Cette tâche :
- Lis les notifications du jour
- Envoi un email pour chaque notification
- Supprime la notification
> [!CAUTION]
> Deux variables d'environnement sont à ajouter :
> `SENDINBLUE_TEMPLATE_NOTIFICATION_EXPIRATION_HOMOLOGATION` et `SENDINBLUE_TEMPLATE_NOTIFICATION_HOMOLOGATION_EXPIREE`
> Les IDs de template sont disponible dans Outline
=> Ajout de la tâche d'envoi de mail de notification d'expiration

src/adaptateurs/adaptateurPdf.configurationTamponHomologation.js, src/pdf/modeles/tamponHomologation.base64.pug
On ajoute un lien autour de l'image `html` fournies dans l'archive du tampon d'homologation.
On en profite pour modifier les instructions.
=> [TAMPON HOMOLOGATION] Ajout d'un lien de redirection vers MSS

src/http/middleware.js, src/routes/privees/routesApiService.js, src/routes/privees/routesApiServicePdf.js, src/routes/privees/routesService.js, test/http/middleware.spec.js, test/mocks/middleware.js, test/routes/privees/routesApiService.spec.js, test/routes/privees/routesApiServicePdf.spec.js, test/routes/privees/routesService.spec.js
... afin de placer un `service` dans la requête, et non plus une `homologation`.
Cette PR fait partie de la tâche de fond qui consiste à remplacer les `homologations` par des `services`.
> [!NOTE]  
> Il reste aujourd'hui **_882 occurences_** du mot "homologation" dans le projet, contre _**994 avant cette PR**_.
> 
> ![](https://geps.dev/progress/11?dangerColor=1f6feb)
=> [SOIN] Remplace le middleware `trouveService`

src/erreurs.js, src/modeles/entite.js, src/modeles/utilisateur.js, test/depots/depotDonneesHomologations.spec.js, test/modeles/utilisateur.spec.js
...Reproduction du bug : essayer de dupliquer un service qui n'a pas encore de SIRET.
Attendu : la duplication n'est pas possible car la donnée est obligatoire.
Observé : MSS crash.
Ce commit change le type d'exception levé par la vérification de présence de SIRET pour rentrer dans le flow d'affichage du tiroir avec le message incitant à compléter la page décrire
=> [CORRECTION] Interdit la duplication de service sans SIRET

.env.template, src/vues/base.pug
… pour la Google Search Console.
On va se servir de la console pour améliorer notre référencement.
> [!IMPORTANT]
> Il faut créer `GOOGLE_SEARCH_CONSOLE_VERIFICATION` en variable d'env.
=> Ajoute une balise <meta> de vérification

src/vues/base.pug
... afin de suivre le format standard d'une page HTML.
Sans ça, la vérification de la Google Search console ne peut pas être effectuée
=> [CORRECTION] Ajoute une balise `head`

src/vues/aPropos.pug, src/vues/accessibilite.pug, src/vues/base.pug, src/vues/cgu.pug, src/vues/connexion.pug, src/vues/home.pug, src/vues/inscription.pug, src/vues/mentionsLegales.pug, src/vues/securite.pug, src/vues/statistiques.pug
... afin de renforcer notre SEO.
On utilise une nouvelle méthode pour déclarer la balise `meta` dans le template de `base.pug`, et modifier cette variable dans les fichiers `enfant`.
Cette même mêthode pourrait être utilisée pour les `title` de page.
=> [SEO] Ajoute les balises `meta` de description

public/assets/styles/tableauDeBord.css, public/modules/tableauDeBord/tableauDesServices.mjs, src/modeles/descriptionService.js, src/modeles/entite.js, src/modeles/objetsApi/objetGetService.js, test/modeles/descriptionService.spec.js, test/modeles/objetsApi/objetGetService.spec.js, test/modeles/objetsApi/objetGetServices.spec.js, test/routes/privees/routesApiService.spec.js
...comme dans le cas du SIRET non renseigné.
Cela permet d'indiquer à l'utilisateur qu'il doit compléter sa saisie. 
Cela fait suite à l'obligation de renseigner le SIRET de l'organisation responsable du service, en l'absence de possibilité de rattrapage automatique des données.
Cette PR corrige par la même occasion le retour de statutSaisie qui avait cassé suite au changement de l'organisation responsable d'une propriété atomique à une Entite. Ce bug faisait que la page décrire avait une check verte alors qu'elle ne devrait pas si le SIRET n'est pas renseigné.
=> Affiche un message d'information sur le tableau de services si la description du service est incomplète

consoleAdministration.js, src/adaptateurs/adaptateurUUID.js, src/depotDonnees.js, src/depots/depotDonneesAutorisations.js, src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesHomologations.spec.js, test/depots/depotDonneesNotificationsExpirationHomologation.spec.js
...pour ne plus utiliser un singleton. En utilisant un singleton, les tests qui redéfinissent la fonction genereUUID ont un effet de bord sur d'autres tests
=> [SOIN] Ajoute fabrique adaptateurUUID

.env.template, src/adaptateurs/adaptateurEnvironnement.js, src/http/middleware.js, test/http/middleware.spec.js
... afin de pouvoir l'utiliser dans nos `.pug`.
Pour l'instant, il ne s'agit que d'une variable d'environnement, afin de pouvoir le tester en environnement de PR.
Par la suite, on ira directement lire cette valeur depuis la persistance, pour l'utilisateur courant.
=> [VISITE GUIDÉE] Ajoute un middleware qui charge l'état de la visite guidée

public/modules/tableauDeBord/actions/ActionContributeurs.mjs, public/scripts/menuNavigation.js, svelte/lib/gestionContributeurs/GestionContributeurs.svelte, svelte/lib/gestionContributeurs/gestionContributeurs.d.ts, svelte/lib/gestionContributeurs/gestionContributeurs.ts, svelte/lib/gestionContributeurs/invitation/InvitationContributeur.svelte, svelte/lib/gestionContributeurs/kit/ChampAvecSuggestions.svelte, svelte/lib/gestionContributeurs/modeVisiteGuidee/donneesVisiteGuidee.ts
On ajoute le mode `visiteGuidee` au composant `Svelte` de `GestionContributeurs`.
De plus, on permet de pouvoir instancier et ouvrir le tiroir via un `event` du DOM.
Cela servira ensuite au composant `VisiteGuidee` pour déclencher l'ouverture du tiroir de manière simple.
=> [VISITE GUIDÉE] Permet l'ouverture du composant 'Contributeurs' en mode 'visite guidée'

src/mss.js, svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte, svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
On corrige quelque bugs :
- Il était possible de fermer le tiroir des mesures
- Le pourcentage de mesures complétées affichait `null`
- L'erreur de saisie des checkbox déclenchait un scroll sur la page Décrire
- Pour l'instant, on force le scroll en haut de page. On pourra enlever cela lorsque le bug sera résolu
=> [CORRECTION] Hotfix sur l'étape SÉCURISER

public/assets/styles/menuNavigation.css, public/scripts/menuNavigation.js, src/vues/fragments/menuNavigation.pug, svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte
On ne veut plus que le bouton se mette en mode « replié » 👇 
Il doit toujours resté en mode « déplié » 👇 
Cette PR supprime le repli.
Cette suppression rend inutile le chargement de « nombre de contributeurs » puisque celui-ci n'est plus jamais affiché. 
Donc la PR enlève tout le code qui alimentait ce nombre de contributeurs.
=> [MENU] Toujours garder le bouton de gestion des contributeurs ouvert

public/scripts/menuNavigation.js, svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte
... sur l'étape DECRIRE de la visite, pour que le pointeur soit au bon endroit si le menu était fermé.
Si le menu était fermé avant cette étape, il retrouve cet état par la suite car cette fermeture n'est pas sauvegardée.
Pour corriger cet affichage :
=> [VISITE GUIDEE] Force l'ouverture du menu navigation

svelte/lib/visiteGuidee/etapes/homologuer/EtapeHomologuer.svelte
... pour que le bouton "Nouvelle homologation" qui est mis en valeur ne soit pas cliquable, le service affiché dans la visite guidée n'existant pas réellement.
=> [VISITE GUIDEE] Désactive le bouton suivant du formulaire homologation

.env.template, src/adaptateurs/adaptateurEnvironnement.js, src/depots/depotDonneesParcoursUtilisateur.js, src/http/middleware.js, src/modeles/etatVisiteGuidee.js, src/modeles/parcoursUtilisateur.js, test/depots/depotDonneesParcoursUtilisateur.spec.js, test/http/middleware.spec.js, test/modeles/parcoursUtilisateur.spec.js
On enrichit le modèle `parcoursUtilisateur` avec un nouveau modèle `EtatVisiteGuidee`.
Ce modèle va permettre de suivre l'utilisateur au cours de la visite guidée, et d'afficher les modales en conséquences.
Dans cette PR, on se contente de créer une valeur par défaut, et de modifier le middleware pour qu'il la prenne en compte.
=> [VISITE GUIDEE] Sauvegarde l'état de la visite guidée de l'utilisateur

src/modeles/etatVisiteGuidee.js, src/referentiel.js, test/modeles/etatVisiteGuidee.spec.js
... afin de pouvoir alimenter le menu de navigation.
> [!WARNING]  
> Le nombre d'étapes restantes est une méthode, afin d'éviter de persister ce chiffre qui n'est pas statique (il dépend du référentiel). 
> Il faudra donc exécuter la méthode avant de la passer au bundle `Svelte`.
=> [VISITE GUIDEE] Ajoute les étapes "vues" et le nombre d'étapes restantes

public/scripts/menuNavigation.js, svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte, svelte/lib/visiteGuidee/etapes/homologuer/EtapeHomologuer.svelte
On corrige :
- L'appel API inutile pour le tiroir des contributeurs, en mode visite guidée
- La possibilité de "cliquer à nouveau" sur la gestion des contributeurs
- La possibilité de "cliquer à nouveau" sur les téléchargements de documents
=> [CORRECTION] Corrige les erreurs du menu de navigation pendant la visite guidée

src/mss.js, src/routes/connecte/routesConnectePage.js, src/routes/connecte/routesConnectePageService.js, src/routes/nonConnecte/routesNonConnectePage.js, src/vues/statistiques.pug, test/mss.spec.js, test/routes/connecte/routesConnectePage.spec.js, test/routes/connecte/routesConnectePageService.spec.js, test/routes/nonConnecte/routesNonConnectePage.spec.js
On déplace toutes les routes "orphelines" vers les routeurs pertinents.
Au passage, on modifie l'utilisation du middleware `verificationJWT` au profit de `verificationCGUAcceptees` pour toutes les pages sauf `/motDePasse/initialisation`.
On en profite aussi pour charger l'état de la visite guidée sur toutes les pages "connectées"
=> [SOIN] Réorganisation des routeurs et harmonisation des middlewares

public/scripts/menuNavigation.js, src/vues/mssConnecte.pug, src/vues/parcoursService.pug, src/vues/service/mesures.pug, src/vues/tableauDeBord.pug, svelte/lib/visiteGuidee/kit/MenuNavigation.svelte
...lorsque la visite est en pause et pas définitivement terminée.
En dehors de la visite guidée, refermer le menu ne force pas le retour sur le tableau de bord pour ne pas dérouter l'utilisateur.
=> [VISITE GUIDEE] Affiche le menu de visite guidée sur toutes les pages connectées

src/http/middleware.js
… dans le cas où la visite guidée n'est pas activée.
Sinon, en cas de visite guidée désactivée, toutes les routes connectées deviennent inaccessibles.
=> [CORRECTION] Ajoute le return qui casse la chaîne de middleware

src/routes/connecte/routesConnectePageService.js
... pour éviter de couper la chaine au milieu d'un caractère spéciale (exemple: `&#x27;`), ce qui entraine une erreur du formattage du nom de fichier.
Cette erreur a été remontée par Sentry.
=> [CORRECTION] Applique le "décodage" HTML avant de couper la chaine de caractère

src/modeles/autorisations/ajoutContributeurSurServices.js, src/routes/nonConnecte/routesNonConnecteApi.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js
... à l'inscription, et lors de l'invitation d'un contributeur.
Cela permettra de "crasher" avant le création coté MSS si Brevo ne réponds pas, et donc ne pas avoir à faire un rollback.
=> [SOIN] Inversion de l'ordre des appels Brevo/MSS lors de la création d'un utilisateur

src/adaptateurs/adaptateurMailMemoire.js, src/adaptateurs/adaptateurMailSendinblue.js, src/bus/abonnements/relieEntrepriseEtContactBrevo.js, src/bus/cablage.js, src/erreurs.js, test/bus/abonnements/relieEntrepriseEtContactBrevo.spec.js
Lors de l'inscription d'un nouvel utilisateur, on veut le relier à une `Entreprise` coté Brevo.
Le scenario est le suivant :
```mermaid
graph TB
A[Nouvel Utilisateur Inscrit] --> B{Possède une entité ?}
B -. Oui (Inscription volontaire) .-> C[Recupère ID Contact Brevo]
C --> D["Recupère ID Entreprise Brevo via SIRET (via SIRET)"]
D --> E{Entreprise existe ?}
E -. Oui .-> F[Relie contact à entreprise]
E -. Non .-> G["Créé entreprise Brevo (SIRET, nom, nature juridique)"]
G --> F
B -. Non (Invitation) .-> Z["🛑 Ne fait rien"]
classDef mss fill:#0079d0,stroke:#0079d0,stroke-width:2px;
classDef brevo fill:#0c996e,stroke:#d3fec9,stroke-width:2px;
classDef stop stroke:#ff6584,stroke-width:2px;
class A mss
class C,D,G,F brevo
class Z stop
```
On ajoute donc un nouvel abonné …
=> [BREVO/ENTREPRISE] Relie un nouvel utilisateur à une entreprise Brevo

public/service/mesures.js
Car on ne vérifiais pas si la visite guidée était en pause. Il était donc possible de :
- Démarrer la visite guidée
- La mettre en pause
- Se rendre sur la page "Sécuriser" d'un service
- Voir apparaître les mesures "factices" de la visite guidée
=> [CORRECTION] Affichage des mesures en mode "visite guidée"

public/assets/styles/tiroir.css, svelte/lib/gestionContributeurs/invitation/ListeInvitations.svelte
Pour éviter les débordements de tiroir :
| ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/6638b5e7-fece-4afe-9020-5ba1c4e761cd) | ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/017d1085-3084-4b54-91bf-72911f3fd6cd) |
=> [CORRECTION] Ajoute une `ellipsis` si l'adresse email d'un contributeur est trop longue

src/vues/service/indiceCyber.pug
Pour montrer que l'ANSSI ne recommande pas l'homologation
=> [WORDING] N'affiche pas de durée d'homologation conseillée avec un indice cyber inférieur à 2

src/adaptateurs/adaptateurMailMemoire.js, src/adaptateurs/adaptateurMailSendinblue.js, src/bus/abonnements/modifieLienEntrepriseEtContactBrevo.js, src/bus/abonnements/relieEntrepriseEtContactBrevo.js, src/bus/cablage.js, src/crm/crmBrevo.js, test/bus/abonnements/modifieLienEntrepriseEtContactBrevo.spec.js, test/bus/abonnements/relieEntrepriseEtContactBrevo.spec.js, test/crm/crmBrevo.spec.js
Pour cela, on vérifie d'abord si l'utilisateur a une entreprise dans Brevo, et si oui, on "délie" l'utilisateur de l'entreprise.
On exécute ensuite le même code que pour la liaison faite au moment de l'inscription. 
Pour mutualisé le code, on créé une classe `CrmBrevo` qui contient les méthodes utiles.
=> [BREVO/ENTREPRISE] Modifie l'entreprise de l'utilisateur dans Brevo lors de la modification de son profil

donneesReferentiel.js, migrations/20240528090117_ajoutEstimationNombreServicesVideUtilisateur.js, public/assets/styles/formulaire.css, public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js, public/tableauDeBord.js, src/modeles/utilisateur.js, src/referentiel.js, src/routes/connecte/routesConnectePage.js, src/routes/mappeur/utilisateur.js, src/routes/nonConnecte/routesNonConnectePage.js, src/vues/fragments/formulaireUtilisateur.pug, test/constructeurs/constructeurUtilisateur.js, test/modeles/utilisateur.spec.js, test/routes/connecte/routesConnecteApi.spec.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js
On souhaite ajouter une nouvelle question à l'inscription et dans le profil utilisateur : 
> Combien de services publics numériques avez-vous à sécuriser ?
___
Cette information se retrouve dans le modèle `Utilisateur` sous la forme d'un objet 
```js
estimationNombreServices : {
borneBasse: 1,
borneHaute: 10
}
```
Des valeurs spécifiques existent :
- `{ borneBasse: 0, borneHaute: 0 }` par défaut, pour un utilisateur qui n'a pas mis à jour son champ (via la migration)
- `{ borneBasse: -1, borneHaute: -1 }` pour le choix "Je ne sais pas"
Petite particularité du front, on construit les `value` du `select` de la forme `borneBasse_borneHaute` pour éviter l'utilisation du "-" qui cause des problèmes avec les nombres négatifs.
=> [INSCRIPTION/PROFIL] Ajout de la question sur l'estimation du nombre de services

src/bus/cablage.js, src/bus/evenementServiceSupprime.js, src/depots/depotDonneesHomologations.js, test/depots/depotDonneesHomologations.spec.js
A la suppression d'un service, on souhaite recalculer pour tous les contributeurs leurs contributions et envoyer à Brevo cette information
=> [Brevo] Mise à jour des contacts à la suppression d'un service

src/adaptateurs/adaptateurRechercheEntrepriseAPI.js
... afin que l'équipe puisse identifier les sources des requêtes entrantes.
Cette demande émane de l'issue #1452.
> [!WARNING]  
> Il faut ajouter la variable d'environnement `IDENTIFIANT_MTM_API_RECHERCHE_ENTREPRISE` en production
=> Ajoute le paramètre `utm` pour l'équipe API recherche entreprise

src/adaptateurs/adaptateurMailMemoire.js, src/adaptateurs/adaptateurMailSendinblue.js, src/bus/abonnements/metAJourContactBrevoDeLUtilisateur.js, src/bus/abonnements/metAJourContactBrevoDuContributeur.js, src/bus/cablage.js, src/crm/crmBrevo.js, src/routes/nonConnecte/routesNonConnecteApi.js, test/bus/abonnements/metAJourContactBrevoDeLUtilisateur.spec.js, test/bus/abonnements/metAJourContactBrevoDuContributeur.spec.js, test/constructeurs/constructeurUtilisateur.js, test/crm/crmBrevo.spec.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js
A la création et à la mise à jour du profil utilisateur.
Par l'occasion d'ajouter la mise à jour de contact, j'en ai profité pour mettre à jour nom et prénom qui font parti du même ensemble d'informations.
=> [Brevo] Transmettre le numéro de téléphone du contact

src/modeles/autorisations/ajoutContributeurSurServices.js, test/modeles/autorisations/ajoutContributeurSurServices.spec.js
La méthode créerContact a depuis peu un paramètre supplémentaire : le numéro de téléphone de la personne. Pour un invité, il n'y a pas de numéro, donc on transmet une chaîne vide. Sans cette correction, l'invitation d'un utilisateur sur un service devient impossible.
=> [CORRECTION] Passe un numéro de téléphone vide à la création de contact Brevo pour un invité

src/notifications/centreNotifications.js, src/referentiel.js, src/routes/connecte/routesConnecteApi.js, src/routes/connecte/routesConnecteApiNotifications.js, test/notifications/centreNotifications.spec.js, test/routes/connecte/routesConnecteApiNotifications.spec.js
Cette route permet de lire, pour tout utilisateur connecté, l'intégralité des "Nouveautés" présente sur MSS.
Cette PR est un prérequis pour la mise en place du "Centre de notifications"
=> [CENTRE DE NOTIFICATIONS] Ajoute une route pour les notifications de "Nouveautés"

migrations/20240604153657_creationTableNotifications.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depotDonnees.js, src/depots/depotDonneesNotifications.js, src/erreurs.js, src/notifications/centreNotifications.js, src/routes/connecte/routesConnecteApi.js, src/routes/connecte/routesConnecteApiNotifications.js, test/depots/depotDonneesNotifications.spec.js, test/notifications/centreNotifications.spec.js, test/routes/connecte/routesConnecteApiNotifications.spec.js
On ajoute ici un méthode à l'objet `CentreNotification` qui permet de marquer une notification de type "Nouveauté" comme lue.
On créer une `table` dédiée aux notifications de nouveauté, car ce sont les seules (pour l'instant) qui peuvent être marquée ainsi.
Le dépôt fait un simple passe plat vers l'adaptateur de persistance.
=> [CENTRE DE NOTIFICATIONS] Ajout du dépôt pour les nouveautés lues

donneesReferentiel.js, public/assets/images/notifications/tache.svg, src/notifications/centreNotifications.js, svelte/lib/centreNotifications/centreNotifications.d.ts, svelte/lib/centreNotifications/kit/Notification.svelte, test/constructeurs/constructeurUtilisateur.js, test/notifications/centreNotifications.spec.js
Suite à l'ajout du nouveau type de notification "tâche" pour représenter les actions que l'utilisateur doit accomplir, on les affiche dans le centre de notifications.
Elles n'ont pas d'horodatage et sont toujours affichées "non lues".
On ajoute le cas particulier de l'utilisateur invité qui a son profil vide : plutôt que d'afficher de multiples notifications pour chaque champ vide de son profil, on ne lui en affiche qu'une pour l'inviter à compléter son profil.
=> [NOTIFICATIONS] Ajoute l'affichage des notifications de type "tâche"

src/vues/motDePasse/edition.pug
Les gestionnaires de mot de passe (type Bitwarden ou Dashlane) complètent tous les champs de type mot de passe. Cette PR permet de ne pas compléter les nouveaux mots de passe.
=> [SOIN] Désactive l’autocomplétion pour les nouveaux mots de passe

svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte
... car le bandeau des nouveautés a été remplacé par le centre de notifications.
L’étape de visite guidée ne s’affichait plus.
=> [CORRECTION] Change la cible des nouveautés dans la visite guidée

src/notifications/centreNotifications.js, src/routes/connecte/routesConnecteApi.js, src/routes/connecte/routesConnecteApiNotifications.js, test/notifications/centreNotifications.spec.js, test/routes/testeurMSS.js
Car on ne souhaite pas afficher, dans le centre de notifications, les nouveautés dont la date de déploiement est postérieure à la date du jour
=> [CENTRE DE NOTIFICATIONS] Filtre les nouveautés futures

public/assets/styles/parcoursService.css
Le footer ne s'affiche plus correctement, à cause des nouvelles règles CSS sur `marges-fixes`
=> [CORRECTION] Corrige l'affiche du footer dans le parcours service

public/assets/images/fleche_gauche_bleue.svg, public/assets/styles/etapesDossier.css, public/assets/styles/homologation/descriptionService.css, public/assets/styles/parcoursService.css, public/modules/interactions/brancheValidationCasesACocher.mjs, public/modules/interactions/validation.mjs, public/modules/parametresDescriptionService.mjs, public/modules/soumetsHomologation.mjs, public/service/descriptionService.js, src/vues/fragments/avancementEtape.pug, src/vues/fragments/formulaireDescriptionService.pug, src/vues/service/creation.pug, src/vues/service/descriptionService.pug, src/vues/service/formulaireEtapier.pug
On modifie le formulaire de la description de service, pour le découper en plusieurs sous-étapes.
On choisit d'utiliser plusieurs `form` qui sont validés séparemment, avant de les valider tous avant l'envoi de la `payload`.
HTML ne permet pas d'avoir un `form` dans un autre.
On doit donc modifier légérement la logique de validation et de récupération des données.
=> [DÉCRIRE] Séparation du formulaire en deux étapes

public/service/descriptionService.js
Lorsque le nom de service existe déjà, on revient automatiquement à la première étape pour voir et corriger l’erreur de validation
=> [DECRIRE] Affiche le message en cas de doublon de nom

src/modeles/descriptionService.js, test/modeles/descriptionService.spec.js
…recommandé en fonction d'une description de service.
On choisit volontairement de réaliser cette estimation "en dur", car les règles métier ne devraient pas changer. De plus, il semble cohérent que le modèle `DescriptionService` puisse estimer son propre niveau de sécurité
=> [NIVEAU DE SÉCURITÉ] Ajoute une méthode permettant d'estimer le niveau de sécurité 

src/routes/connecte/routesConnecteApiService.js, test/routes/connecte/routesConnecteApiService.spec.js
…requis pour une description de service donnée.
Cette route sera utilisée dans la prochaine PR, afin d'insérer dans la `payload` de création ou modification de service, le niveau de sécurité suggéré par l'ANSSI.
Pour l'instant, l'utilisateur ne pourra pas modifier ce niveau.
=> [NIVEAU DE SÉCURITÉ] Ajoute une route permettant d'obtenir le niveau minimal de sécurité

src/vues/fragments/elementsAjoutables/elementsAjoutables.pug
… afin d'éviter que l'appuie sur "entrée" ne supprime le premier élément.
=> [CORRECTION] Empêche le bouton de suppression de "voler" le focus dans les points d'accès de DÉCRIRE

docker-compose.yml
... afin de le retrouver en cas de recréation du conteneur
=> Nomme le volume docker de la base

.env.template, consoleAdministration.js, src/adaptateurs/adaptateurMailSendinblue.js, src/routes/nonConnecte/routesNonConnecteApi.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js
Afin que notre pôle BizDev puisse utiliser Brevo normalement, nous souhaitons faire une bascule sur le fonctionnement des abonnements à l'infolettre et au mail marketing.
- Un utilisateur abonné à l'infolettre a le statut `SUBSCRIBED` dans **Brevo**
- Un utilisateur abonné aux mails marketing fait partie de la liste `MARKETING` dans **Brevo**
- Un utilisateur abonné à l'infolettre fait partie de la liste `NEWSLETTER` dans **Brevo**
- Un utilisateur abonné aux mails marketing a le statut `SUBSCRIBED` dans **Brevo**
On doit aussi modifier l'endpoint appelé par le webhook Brevo.
> - Un script de rattrapage doit être lancé lors de la MEP.
> - La variable d'environnement `SENDINBLUE_ID_LISTE_POUR_MAILS_TRANSACTIONNELS_DE_RELANCE` doit être changée en …
=> [BREVO] Modification des notions d'abonnement Infolettre/Transactionnels

public/assets/styles/homologation/mesures.css
... dans le cas des mesures avec un titre court, ou de l'affichage "aucun résultat"
=> [CORRECTION] Force le tableau des mesures à 100% de la largeur

creeUtilisateurDemo.js, test/creeUtilisateurDemo.spec.js
La `DescriptionService` ne comportait pas le nouveau champ `niveauSecurite`.
On en profite pour rajouter un test sur l'exécution de ce script.
=> [CORRECTION] Utilisateur de Démo

src/routes/connecte/routesConnecteApiService.js, test/routes/connecte/routesConnecteApiService.spec.js
... afin de déclencher l'affichage de l'erreur spécifique sur la première page du formulaire de DÉCRIRE
=> [CORRECTION] Erreur spécifique si le nom du service existe déjà lors de la modification d'un service

svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte, svelte/lib/tableauDesMesures/filtres/NombreResultatsFiltres.svelte
On ajoute maintenant une "pastille" indiquant qu'il y a des filtres actifs
=> [SECURISER] Modification de l'aspect des filtres actifs

src/modeles/homologation.js, src/modeles/mesures.js, test/modeles/homologation.spec.js, test/modeles/mesures.spec.js
L’objectif est de ne pas prendre en compte les mesures du service qui sont renseignées mais plus retournées par le moteur de règle.
Cette PR corrige deux points qui posaient problème :
- le statut par catégorie (pour le pdf des annexes)
- le statut de saisie pour les mesures (à compléter / complètes)
=> Filtre mesures applicables

svelte/lib/tableauDesMesures/filtres/IconeFiltre.svelte, svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
🐞 **Reproduction** :
- activer un filtre
- scroller vers le bas dans la boîte des filtres
**Attendu** : l'icône des filtres n'est plus visible et la pastille non plus
**Observé** : l'icône des filtres défile bien vers le haut, mais la pastille reste visible 👇 
Cette PR passe par un `:after` et un `relative` pour que la pastille ne sorte pas du flow de la page.
=> [CORRECTION] Évite de laisser toujours visible la pastille des filtres

src/modeles/homologation.js, test/modeles/homologation.spec.js
Ce filtre supprimait les mesures générales qui n'étaient pas présentes parmi les mesures personnalisées, avant de passer les mesures filtrées au constructeur de mesures.
Cela permet de ne pas écraser de mesure générale obsolète qui serait encore stockée en base, mais plus considérées par le moteur de règle.
Ainsi, en passant de niveau 3 à 2 puis de nouveau à 3, un utilisateur pourra retrouver les mesures de niveau 3 qu'il avait remplies, car elles ne seront pas supprimées par le passage au niveau 2.
Il n'y a pas d'impact sur les calculs et affichages des mesures et indices car ces calculs et affichages sont faits avec les mesures à considérer, donc de la donnée filtrée.
=> Supprime le filtre de mesures générales dans homologation

src/routes/connecte/routesConnecteApiService.js, test/routes/connecte/routesConnecteApi.spec.js, test/routes/connecte/routesConnecteApiService.spec.js, test/routes/connecte/routesConnecteApiServicePdf.spec.js, test/routes/connecte/routesConnecteApiVisiteGuidee.spec.js, test/routes/connecte/routesConnectePageService.spec.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js, test/routes/nonConnecte/routesNonConnecteApiBibliotheques.spec.js, test/routes/nonConnecte/routesNonConnecteApiStyles.spec.js, test/routes/nonConnecte/routesNonConnectePage.spec.js, test/routes/testeurMSS.js
L'objectif de cette PR est de cesser de faire crasher le runner de test WallabyJS.
Sur un test j'avais des `done() called multiple times`.
C'est le premier commit de cette PR qui corrige ça : en ajoutant un `else` devant le `if` on corrige le comportement.
Ensuite, j'ai passé les tests `verifieRequeteGenereErreurHTTP` en `async/await` pour gagner en concision.
=> [SOIN] Empêche un test de fail… et passe des tests en `async`

public/modules/interactions/validation.mjs, public/modules/soumetsHomologation.mjs, public/service/descriptionService.js
... en utilisant un `query string` : `?etape=N`.
Cela nous permettra de créer des liens direct vers les étapes concernées par des modifications.
Pour pouvoir s'assurer que les formulaires d'avant sont bien valide, tout de même, on renvoi l'indice du formulaire potentiellement invalide au moment de la `validation`, afin de pouvoir faire réagir le `front` en fonction.
=> [DÉCRIRE] Permet de naviguer directement vers une étape

src/http/middleware.js, src/routes/nonConnecte/routesNonConnecteApiBibliotheques.js, test/http/middleware.spec.js
... pour autoriser le chargement des images depuis les serveurs de Crisp, ainsi que les vidéos provenant de notre "S3-like storage".
=> [CMS CRISP] Mise à jour des `CSP`

donneesReferentiel.js, migrations/20240710075904_creationTableTachesService.js, migrations/20240711132023_ajouteDonneesATachesDeService.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depotDonnees.js, src/depots/depotDonneesNotifications.js, src/erreurs.js, src/notifications/centreNotifications.js, src/referentiel.js, src/routes/connecte/routesConnecteApiNotifications.js, svelte/lib/centreNotifications/centreNotifications.api.ts, svelte/lib/centreNotifications/centreNotifications.d.ts, svelte/lib/centreNotifications/kit/Notification.svelte, test/constructeurs/constructeurTacheDeService.js, test/depots/depotDonneesNotifications.spec.js, test/notifications/centreNotifications.spec.js, test/routes/connecte/routesConnecteApiNotifications.spec.js
Cette PR ajoute la possibilité de créer des notifications pour des **tâches de service**.
Exemple 👇 
Une notification de tâche de service :
- s'affiche dans l'onglet `À faire`
- concerne un unique service ; elle connaît d'ailleurs l'ID du service 
- contient un _Call To Action_
- lors du clic sur le CTA :
-  la notification est marquée comme lue
- le navigateur va vers la page associée à la notification
L'exemple de cette PR est la notification qui sera créée pour indiquer que les besoins de sécurité ont été modifiés (lorsque nous aurons supprimé la dernière question de DÉCRIRE). Ici au clic, on naviguera vers l'étape 3 du formulaire DÉCRIRE.
Pour qu'une notification de tâche de service existe, elle doit être insérée dans la nouvelle table `taches_service` : 
Toute la PR a été faite en …
=> [NOTIFICATIONS] Ajout des notifications de types « tâches de service »

migrations/20240712144020_creationTableSuggestionsActions.js, public/modules/tableauDeBord/tableauDesServices.mjs, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/modeles/homologation.js, src/modeles/objetsApi/objetGetService.js, test/constructeurs/constructeurAdaptateurPersistanceMemoire.js, test/constructeurs/constructeurService.js, test/depots/depotDonneesHomologations.spec.js, test/modeles/homologation.spec.js, test/modeles/objetsApi/objetGetService.spec.js, test/modeles/objetsApi/objetGetServices.spec.js
Cette PR introduit et utilise les suggestions d'actions comme source de données pour afficher la mention « Informations à mettre à jour » 👇 
Avant cette PR, cette mention s'affiche si le statut de saisie du service est `aCompleter`.
Dorénavant, MSS considère aussi la présence de suggestions d'actions pour déclencher cet affichage.
À terme, le statut de saisie sera totalement ignoré.
- une nouvelle table en BDD
- un nouveau « champ » dans la classe `Service`
- l'adaptateur de persistance qui fait la glue entre les 2
Pair-programming complet sur la PR.
=> [SUGGESTIONS D'ACTIONS] Indication sur le tableau de bord, en cas de présence de suggestions

src/notifications/centreNotifications.js, svelte/lib/centreNotifications/centreNotifications.d.ts, svelte/lib/centreNotifications/kit/Notification.svelte, test/notifications/centreNotifications.spec.js
Dans le centre de notifications, on souhaite voir l’horodatage pour les tâches de service, comme pour les nouveautés. 
Exemple : 
Fait en pair-programming avec @CadiChris
=> Ajoute l’horodatage pour les tâches de service

public/assets/styles/tiroir.css
… afin d'éviter les mauvais affichage suite au positionnement `sticky` de la barre d'action
=> [CORRECTION] Corrige l'affichage des tiroirs de duplication et d'invitation

donneesReferentiel.js, migrations/20240718092812_insereSuggestionsActionsPourOrganisationsUtilisatrices.js, public/assets/styles/homologation/descriptionService.css, src/bus/abonnements/supprimeSuggestionSiret.js, src/bus/abonnements/supprimeSuggestionsSurDesChampsObligatoires.js, src/bus/cablage.js, src/vues/fragments/formulaireDescriptionService.pug, test/bus/abonnements/supprimeSuggestionsSurDesChampsObligatoires.spec.js
En bâtissant sur #1602 on s'attaque désormais au champ `organisationsUtilisatrices` des `Services`.
Comme pour la suggestion `mise à jour SIRET`, la bannière s'affiche sur DECRIRE 👇
=> [SUGGESTIONS D'ACTIONS] Affichage de la suggestion « mise à jour des organisations utilisatrices » sur DÉCRIRE

public/modules/tableauDeBord/tableauDesServices.mjs, src/modeles/objetsApi/objetGetService.js, test/modeles/objetsApi/objetGetService.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
Inutile de donner du détail sur la suggestion.
Le front a simplement besoin de savoir s'il y en a une ou pas.
=> [SUGGESTIONS D'ACTIONS] Encapsule la suggestion d'action renvoyée par l'API

public/modules/suggestion/suggestionEntite.js, public/service/descriptionService.js, src/vues/fragments/formulaireDescriptionService.pug
Corrige deux soucis : 
- la bannière de suggestion d’action de mise à jour du nombre d’organisation utilisatrice était cachée par la mise à jour du SIRET
- cette même bannière n’était pas cachée lors de la mise à jour du nombre d’organisation utilisatrice
=> Corrige affichage bannières de suggestion d’action

public/assets/images/icone_enregistrement_termine.svg, public/assets/images/toasts/icone_info.svg, public/assets/images/toasts/icone_succes.svg, svelte/lib/mesure/Mesure.svelte, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/ui/Toaster.svelte, svelte/lib/ui/animations/transitions.ts, svelte/lib/ui/stores/toaster.store.ts
> [!WARNING]  
> En attente de validation design pour les ombres portées sur les toast ainsi que la taille de police
... afin de permettre l'affichage de "toast" indiquant le changement de statut des mesures.
On utilise un `store` qui possède une `queue` de toutes les notifications à afficher.
> [!NOTE]  
> Les CSPs ne nous permettant pas d'utiliser les `svelte:transition`, on ajoute nous même une transition en suivant l'API [décrite ici.](https://learn.svelte.dev/tutorial/custom-css-transitions)
=> [PLAN D'ACTION] Ajout du "Toaster" pour les changements de statuts

public/modules/tableauDeBord/tableauDesServices.mjs, src/modeles/objetsApi/objetGetService.js, src/referentiel.js, test/modeles/objetsApi/objetGetService.spec.js, test/referentiel.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
Après avoir MEP les suggestions d'actions, on peut nettoyer le code qui restait présent pour faire du « double run » avec l'ancienne abstraction.
=> [SUGGESTIONS D'ACTIONS] Nettoyage post-MEP

src/routes/connecte/routesConnecteApiService.js, test/routes/connecte/routesConnecteApiService.spec.js
Afin de permettre à l’utilisateur de ne plus voir la suggestion en cliquant sur la croix ou le bouton « J’ai compris »
=> Ajoute une route permettant d’acquitter une suggestion d’action

svelte/lib/tableauDesMesures/modeVisiteGuidee/donneesVisiteGuidee.ts
On avait oublié de les ajouter après e7b8aeaca5b26c0643753c87905bd3cc9f9457d4.
Cette PR les rajoute. J'ai repris les mêmes ID que dans `donneesReferentiel`.
Ce qui corrige l'affichage de la visite 👇
=> [CORRECTION] Ajoute les identifiants numériques à la visite guidée

svelte/lib/ui/Toaster.svelte
…car sinon, le `aside` reste au dessus de toute la page, et peut empêcher de fermer le tiroir.
=> [CORRECTION] N'affiche pas le toaster si aucune notifications n'est visible

public/modules/parametresDescriptionService.mjs, public/service/descriptionService.js
utilisatrice
... si le champ n’est pas rempli dans le cas d’une estimation des besoins de sécurité. 
Cela corrige un problème de chargement infini lorsqu’on veut aller sur l’étape 3 directement.
=> [CORRECTION] Assigne une valeur par défaut au nombre d’entité

.github/workflows/node.js.yml, .husky/pre-commit, docker-compose.yml, svelte/lib/mesure/mesure.d.ts, svelte/lib/mesure/mesure.store.ts, svelte/lib/mesure/mesure.ts
🪧 Cette PR s'attaque à 2 soucis : 
- les erreurs Typescript
- l'expressivité de notre pipeline de build
On veut éviter de découvrir par hasard les erreurs Typescript dans nos IDE 👇 
Cette PR vérifie le Typescript en pré-commit et dans une github action.
L'objectif est de ne pas aller en PROD avec des erreurs Typescript.
En retravaillant le fichier `nodejs.yml` des Github actions, on gagne en expressivité dans le pipeline de build 👇 
AVANT
APRÈS
La build est cassée, mais l'important ici est le nom des `steps`.
=> [DÉVELOPPEMENT] Rendre bloquantes les erreurs Typescript dans Svelte

package-lock.json, package.json
... sinon, on peut voir apparaitre, en local comme sur la CI, un message indiquant 
```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'MonServiceSécurisé@1.0.0',
npm warn EBADENGINE   required: { node: '18', npm: '9' },
npm warn EBADENGINE   current: { node: 'v18.20.4', npm: '10.7.0' }
npm warn EBADENGINE }
```
=> [DÉPENDANCES] Met à jour la version de `npm`

donneesReferentiel.js, svelte/lib/centreNotifications/CentreNotifications.svelte, svelte/lib/centreNotifications/kit/ListeNotifications.svelte, svelte/lib/ui/stores/notifications.store.ts, svelte/lib/ui/types.d.ts, svelte/test/ui/stores/notifications.store.spec.ts
On ajoute le `canalDiffusion` dans les nouveautés, afin de pouvoir trier celles qui vont dans le centre de notifications et celles qui vont être affichées dans la page "Sécuriser".
=> [NOTIFICATIONS] Canal de diffusion des 'Nouveautés'

src/notifications/centreNotifications.js, test/notifications/centreNotifications.spec.js
...sinon elles ne s'affichent pas dans le centre de notifications. C'est une régression suite à l'introduction du canal de diffusion pour les nouveautés.
=> [CORRECTION] Ajoute le canal de diffusion aux tâches de service et d'utilisateur

public/modules/soumetsHomologation.mjs, public/service/descriptionService.js
...si la soumission du formulaire a échoué à cause du nom du service déjà utilisé. 
Problème constaté : quand on remplit entièrement Décrire, mais qu'à la soumission on est renvoyé vers l'étape 1 pour modifier un nom de service déjà pris, au retour à l'étape 3 le bouton de soumission n'est pas grisé alors qu'aucun niveau n'est sélectionné.
Plutôt que de griser le bouton, j'ai préféré récupérer le niveau précédemment sélectionné par l'utilisateur pour le remettre en sélection. En effet, le reste du formulaire a ce comportement (aucune valeur oubliée) et ce champ devrait avoir le même comportement selon moi.
=> [CORRECTION] Remet le niveau de sécurité précédemment sélectionné

src/notifications/centreNotifications.js, test/notifications/centreNotifications.spec.js
On ne souhaite pas afficher dans le centre de notifications les tâches de service déjà lues, pour ne pas surcharger l'utilisateur.
=> [CENTRE NOTIFICATIONS] Ne pas afficher les tâches de service déjà lues

svelte/lib/ui/SelectionStatut.svelte
C'est une régression.
Le `undefined` se traduit en `value="undefined"` donc ne déclenchait plus la violation de contrainte `required`. Seule la chaîne vide déclenche ça.
=> [CORRECTION] Impose la sélection d'un statut dans le tiroir de mesure

donneesReferentiel.js, src/modeles/homologation.js, src/modeles/objetsApi/objetGetService.js, src/modeles/suggestionAction.js, test/depots/depotDonneesHomologations.spec.js, test/modeles/homologation.spec.js
S’il y a plusieurs suggestions d’actions sur un service, un clic sur le tableau de bord devrait rediriger vers l’étape 1 plutôt que l’étape 3. C’est le cas par exemple si le SIRET n’est pas renseigné ET que les besoins de sécurité doivent être contrôlés.
Pour cela, on ajoute une priorité à chaque nature de suggestion d’action dans le référentiel et on trie les routes en fonction de cette priorité.
=> Redirige vers suggestion d’action prioritaire

.env.template, src/adaptateurs/adaptateurCmsCrisp.js, src/cms/cmsCrisp.js, src/erreurs.js, src/routes/nonConnecte/routesNonConnectePage.js, test/cms/cmsCrisp.spec.js, test/routes/nonConnecte/routesNonConnectePage.spec.js, test/routes/testeurMSS.js
On souhaite afficher les articles Crisp du Helpdesk pour la catégorie `blog`, via leur slug
=> [CRISP] Ajout de la visualisation des articles de manière générique

TODO.md, svelte/lib/tableauDesMesures/BandeauActions.svelte, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/actionsTiroir.ts, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts
Cette PR ajoute la ligne de titre au-dessus des champs, pour préparer l'arrivée des champs du plan d'action 👇 
On en profite pour extraire `<BandeauActions />` pour gagner en lisibilité
=> [SÉCURISER] Ajout de la ligne de titre

.env.template, TODO.md, src/modeles/mesureGenerale.js, src/modeles/mesureSpecifique.js, src/routes/connecte/routesConnecteApiService.js, svelte/lib/featureFlags.ts, svelte/lib/tableauDesMesures/BandeauActions.svelte, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/aucunResultat/AucunResultat.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/stores/mesures.store.ts, svelte/lib/tableauDesMesures/tableauDesMesures.api.ts, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts, svelte/lib/ui/SelectionPriorite.svelte, svelte/lib/ui/types.d.ts, test/modeles/mesureGenerale.spec.js, test/modeles/mesureSpecifique.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
Ce nouveau champ est activé par le feature flag `VITE_FEATURE_FLAG_AVEC_PLAN_ACTION`. 
Pour l’instant, la colonne « Priorité » est affichée dans le tableau des mesures, mais pas encore dans le tiroir de la mesure.
=> Ajoute le champ `Priorité` du plan d’action au tableau des mesures

.github/workflows/deploiement.yml
On veut pouvoir déployer même si on a rebase.
Autrement dit : on force le déploiement via la CLI pour que le déploiement puisse toujours se faire.
=> [CI/CD] Autorise les déploiements sans `simple fast-forward` de git

svelte/lib/mesure/Mesure.svelte
Car actuellement, on l'affiche dès l'enregistrement de la mesure.
=> [CORRECTION] Affiche un toast de changement de statut de mesure uniquement lorsque le statut est bien modifié

.env.template, docker-compose.yml, src/adaptateurs/adaptateurPdf.puppeteer.js
Il s'agit de générer un PDF en utilisant une instance Browserless non embarquée dans MSS.
Cette possibilité va, à terme, remplacer la génération PDF via le Chromium embarqué dans MSS.
On s'inspire de #1474 qui était un POC de l'utilisation de Browserless.
> [!IMPORTANT]
> Cette nouvelle feature s'active à l'aide de variables d'environnement :
> `AVEC_GENERATION_PDF_EXTERNE`
> `GENERATION_PDF_URL_DU_SERVICE`
> `GENERATION_PDF_TOKEN_DU_SERVICE`
=> Ajoute la possibilité de générer un PDF via `puppeteer.connect()`

src/erreurs.js, src/modeles/mesure.js, src/modeles/mesureGenerale.js, src/modeles/mesureSpecifique.js, src/routes/connecte/routesConnecteApiService.js, test/modeles/mesure.spec.js, test/modeles/mesureGenerale.spec.js, test/modeles/mesureSpecifique.spec.js, test/modeles/objetsPDF/objetPDFAnnexeMesures.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
Lors d’une mise à jour d’une mesure générale ou des mesures spécifiques, une erreur 400 est renvoyée si la priorité n’est pas dans le référentiel.
=> Valide la priorité envoyée à l’API

migrations/20240802092436_supprimeIdHomologationDansAutorisation.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesAutorisations.js, src/modeles/autorisations/autorisation.js, src/modeles/homologation.js, src/routes/connecte/routesConnectePage.js, src/routes/connecte/routesConnectePageService.js, test/depots/depotDonneesAutorisations.spec.js, test/depots/depotDonneesHomologations.spec.js, test/modeles/autorisations/autorisation.spec.js, test/modeles/avis.spec.js, test/modeles/descriptionService.spec.js, test/modeles/homologation.spec.js, test/modeles/informationsHomologation.spec.js, test/modeles/mesureGenerale.spec.js, test/modeles/mesureSpecifique.spec.js, test/modeles/partiesPrenantes/partiePrenante.spec.js, test/modeles/rolesResponsabilites.spec.js
- fin du renommage des informations de service
- suppression de l’id d’homologation de la table `autorisations` (doublé avec le champ idService)
=> [SOIN] Nettoie le modèle pour remplacer homologation en service

clevercloud/cron.json
Inutile de lancer `node` : il s'agit d'un script shell à exécuter.
=> [CORRECTION] Exécute correctement le script

svelte/lib/tableauDesMesures/actionsTiroir.ts
... afin de ne pas avoir un entête vide.
=> [SÉCURISER] Ajoute un titre au tiroir lors de l'ajout d'une mesure spécifique

public/assets/images/icone_calendrier.svg, svelte/lib/tableauDesMesures/BandeauActions.svelte, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/ligne/SelectionEcheance.svelte, svelte/lib/tableauDesMesures/stores/mesures.store.ts, svelte/lib/tableauDesMesures/tableauDesMesures.api.ts, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts, svelte/lib/ui/types.d.ts
... afin de pouvoir assigner une date d'échéance pour une mesure.
Pour l'instant, le back-end n'en tient pas compte.
On utilise un subterfuge pour faire fonctionner le `<input type="date">` standard :
- On utilise un `input` de ce type, mais il est caché par dessus un bouton
- On affiche manuellement le sélecteur de date avec [showPicker()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker)
- On fait remonter l'événement de modification de valeur comme pour la priorité et le statut
=> [PLAN D'ACTION] Ajout du champ "Échéance" dans le tableau des mesures

src/routes/connecte/routesConnecteApiService.js, test/routes/connecte/routesConnecteApiService.spec.js
... car sinon, l'aseptisation les remplace par `&#x2F;`, qui créé une date invalide.
=> [CORRECTION] Décode les "/" des échéances

src/adaptateurs/adaptateurEnvironnement.js, src/http/middleware.js, src/mss.js, src/vues/conseilsCyber.pug, src/vues/fragments/composantSvelte.pug, src/vues/fragments/composantSvelteAvecVersion.pug, src/vues/mss.pug, src/vues/mssConnecte.pug, src/vues/parcoursService.pug, src/vues/service/decrire.pug, src/vues/service/indiceCyber.pug, src/vues/service/mesures.pug, src/vues/tableauDeBord.pug, test/http/middleware.spec.js, test/mocks/middleware.js, test/mss.spec.js
Aujourd'hui on remarque un "cache" lors des déploiements en DEMO et PRODUCTION de nos fichiers de styles `Svelte`.
Afin de contourner cela, on veut ajouter une version dans une `query string` pour ce fichier.
> [!TIP]
> Cette version représente le `short hash` du dernier commit
> [!WARNING]  
> Les variables d'environnement ne sont pas les mêmes chez [Scalingo](https://doc.scalingo.com/platform/app/environment#build-environment-variables) et [CleverCloud](https://developers.clever-cloud.com/doc/reference/reference-environment-variables/#set-by-the-deployment-process).
=> [CI/CD] Ajoute un `hash` aux fichiers compilés `Svelte`

src/adaptateurs/adaptateurEnvironnement.js
... plutôt que `SOURCE_VERSION`, car cette dernière n'est disponible qu'au moment du build sur Scalingo.
=> [CORRECTION] Utilise la variable `CONTAINER_VERSION`

src/routes/connecte/routesConnecteApiService.js, svelte/lib/mesure/Mesure.svelte, svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte, svelte/lib/mesure/mesure.d.ts, svelte/lib/modeles/mesure.ts, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/ligne/SelectionEcheance.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts, svelte/lib/ui/SelectionPriorite.svelte, svelte/lib/ui/stores/toaster.store.ts, svelte/lib/ui/types.d.ts, test/routes/connecte/routesConnecteApiService.spec.js
Lors de la mise à jour d'une mesure générale ou spécifique, le statut de la mesure est obligatoire, il ne peut être vide.
Désactive également le plan d'action dans le cas où le statut ne permet pas d'agir sur le plan d'action.
=> [CORRECTION] Un statut de mesure ne peut être vide dans l'API

src/adaptateurs/adaptateurCsv.js, src/adaptateurs/adaptateurEnvironnement.js
Cette PR rajoute les champs `Priorité` et `Échéance` dans l'export avec données additionnelles.
Il faut que le feature flag soit activé pour que les colonnes apparaissent.
Le champ « Responsables » n'est pas encore exporté. Il sera à rajouter lorsqu'il sera disponible.
=> [PLAN D'ACTION] Ajout des champs du plan d'action dans l'export des mesures

src/modeles/service.js, test/modeles/mesures.spec.js, test/modeles/service.spec.js
L'objectif actuel est d'ajouter dans Metabase les données de plan d'action qui sont associées aux mesures.
J'ai détecté un potentiel refactoring pour permettre cet ajout en supprimant au passage de la duplication.
Il faudrait refactorer `Service.completudeMesures()`… mais cette méthode était testée de très loin par `evenementCompletudeServiceModifiee.spec.js`.
Ces tests trop lointains empêchent de refactorer. Donc, on rajoute des tests plus proches et précis.
=> [SOIN] Rajoute des tests autour de `completudeMesures()`Plan action dans metabase

TODO.md, src/modeles/mesures.js, src/modeles/service.js, src/utilitaires/date.js, test/constructeurs/constructeurMesures.js, test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js, test/modeles/mesures.spec.js, test/modeles/service.spec.js
Cette PR rajoute `priorite` et `echeance` à l'événement Metabase `COMPLETUDE_SERVICE_MODIFIEE` 👇 
Plutôt grosse PR pour ce petit changement… car elle supprime la méthode `statutsMesuresPersonnalisees()` au profit de la réutilisation de `enrichiesAvecDonneesPersonnalisees()` qui contient tout le nécessaire.
=> [PLAN D'ACTION] Envoi des infos vers Metabase

public/assets/styles/palette.css, svelte/lib/gestionContributeurs/kit/Initiales.svelte
Le rôle est inconnu lorsqu'il est en cours de chargement.
Ou alors, lorsqu'on voit la liste des contributeurs sans être soi-même propriétaire : on ne voit pas le rôle des autres.
=> Utilise du gris pour les vignettes de rôle inconnu

src/notifications/centreNotifications.js, test/notifications/centreNotifications.spec.js
Le centre de notifications n'affiche plus la notification de « mettez à jour votre profil »
La notification est de retour.
Il manquait le `canalDiffusion` nécessaire à l'affichage.
=> [CORRECTION] Ré-affiche la notification de profil incomplet

src/adaptateurs/adaptateurCsv.js, src/routes/connecte/routesConnectePageService.js, test/routes/connecte/routesConnectePageService.spec.js
...la colonne contient le nom et prénom ou l'email si le profil est incomplet, séparés par une virgule pour les différents responsables
=> Ajoute les responsables dans l'export de mesures

public/modules/tableauDeBord/gestionnaireEvenements.mjs, public/scripts/menuNavigation.js, src/vues/service/mesures.pug, svelte/lib/gestionContributeurs/GestionContributeurs.svelte, svelte/lib/gestionContributeurs/gestionContributeurs.store.ts, svelte/lib/gestionContributeurs/invitation/InvitationContributeur.svelte, svelte/lib/gestionContributeurs/kit/LigneContributeur.svelte, svelte/lib/gestionContributeurs/personnalisation/PersonnalisationContributeur.svelte, svelte/lib/gestionContributeurs/stores/autorisations.store.ts, svelte/lib/gestionContributeurs/suppression/SuppressionContributeur.svelte, svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte, svelte/lib/mesure/mesure.api.ts, svelte/lib/mesure/mesure.d.ts, svelte/lib/mesure/mesure.store.ts, svelte/lib/tableauDesMesures/BandeauActions.svelte, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, svelte/lib/tableauDesMesures/actionsTiroir.ts, svelte/lib/ui/SelectionResponsables.svelte
Cette PR permet de sélectionner le(s) responsable(s) de mesure dans le tiroir de Mesure 👇 
Nous avons bien fait attention à synchroniser tous les éléments de la page entre eux.
Lorsqu'on invite / supprime / modifie les droits d'un collaborateur : le changement est reflété dans les choix possibles de responsables.
=> [PLAN D'ACTION] Ajout des responsables dans le tiroir de Mesure

svelte/lib/tableauDesMesures/ligne/SelectionEcheance.svelte
Avant ce commit, le bouton « Effacer » était sans effet. Désormais, on utilise l'input `type=date` simplement pour faire un `showPicker()` et avoir le joli calendrier. Fini le `bind:value`.
On change manuellement `echeance` via `modifieEcheance()`, ce qui déclenche le calcul de `dateFormattee` et donne un affichage correct.
Attention :
il faut que ça fonctionne dans les lignes du tableau (là où l'enregistrement se fait au `onChange`) **ET** dans le tiroir (là où l'enregistrement se fait au clic sur le bouton « Enregistrer » du tiroir)
=> [CORRECTION] Fais fonctionner le bouton « Effacer » du date-picker

src/depots/depotDonneesAutorisations.js, src/depots/depotDonneesServices.js, src/modeles/mesureGenerale.js, src/modeles/mesureSpecifique.js, src/modeles/mesures.js, src/modeles/mesuresGenerales.js, src/modeles/mesuresSpecifiques.js, src/modeles/service.js, svelte/lib/tableauDesMesures/TableauDesMesures.svelte, test/depots/depotDonneesAutorisations.spec.js, test/depots/depotDonneesServices.spec.js
Lors de la suppression d'un contributeur d'un service, on souhaite supprimer ses assignations en tant que responsable d'une mesure.
=> Supprime les responsables de mesures à la suppression d'un contributeur

migrations/20240812124743_stockeDateEcheanceAuFormatIsoUtc.js, src/modeles/mesureGenerale.js, src/modeles/mesureSpecifique.js, test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js, test/modeles/mesureGenerale.spec.js, test/modeles/mesureSpecifique.spec.js, test/modeles/service.spec.js
Par souci d'homogénéité avec le reste des dates stockées dans les services.
Si l'échéance est absente, alors le champ n'est pas du tout persisté.
=> [PLAN D'ACTION] Stocke les échéances au format ISO, en UTC

migrations/20240812132827_supprimeIdDonneesService.js, src/depots/depotDonneesServices.js
Le JSON des données de service contenait l'id dans certains cas, à cause d'une erreur dans un appel à `sauvegarde`.
=> [CORRECTION] Ne sauvegarde pas les id de service dans la colonne `données`

src/depotDonnees.js, src/depots/depotDonneesServices.js, test/constructeurs/constructeurDepotDonneesServices.js, test/depots/depotDonneesServices.spec.js
On prépare l'arrivée du chiffrement.
Le dépôt des services ne peut pas appeler directement la persistance pour récupérer un utilisateur. Car à l'avenir la persistance renverra des données chiffrées.
Donc, il passe par le dépôt des utilisateurs pour récupérer un utilisateur en clair.
=> [PRÉPARATION CHIFFREMENT] Le dépôt de services utilise le dépôt d'utilisateurs

creeUtilisateurDemo.js, migrations/20240813070055_ajouteColonneEmailHashUtilisateurs.js, migrations/20240813070846_insereEmailHashUtilisateurs.js, migrations/20240813121201_rendColonneEmailHashNonNullable.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesUtilisateurs.js, src/modeles/utilisateur.js, test/depots/depotDonneesUtilisateurs.spec.js, test/mocks/adaptateurChiffrement.js
Afin de préparer le chiffrement du profil utilisateur, on ajoute le hash d'email dans une colonne à part.
On ne souhaite plus, à terme, rechercher un utilisateur par email (qui est une donnée privée) mais par hash d'email (qui n'est pas réversible).
Cette PR ajoute la colonne de base de données, la remplis avec le hash de l'email pour les utilisateurs existants, effectue la recherche par email du dépôt de données en utilisant le hash de l'email dans la persistance, et insère le hash de l'email lors de l'ajout/mise à jour de l'utilisateur.
=> [PRÉPARATION CHIFFREMENT] L’inscription et le login utilisateur continuent à fonctionner

src/depots/depotDonneesServices.js, test/depots/depotDonneesServices.spec.js
... car actuellement, on ne passait pas par les méthodes de `dechiffre`.
On en profite pour le faire aussi dans la méthode `tous` qui est utilisée par la console d'administration.
=> [PRÉPARATION CHIFFREMENT] La duplication de service continue de fonctionner

migrations/20240813123753_ajouteColonneNomServiceHash.js, migrations/20240819091430_insereNomServiceHash.js, migrations/20240819092056_rendNomServiceHashNonNullable.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesServices.js, test/constructeurs/constructeurAdaptateurPersistanceMemoire.js, test/depots/depotDonneesServices.spec.js
Afin de préparer le chiffrement des données du service, on ajoute le hash du nom de service dans une colonne à part, afin de pouvoir continuer à rechercher par (hash de) nom de service après que les données aient été chiffrées.
Cette PR ajoute la colonne de base de données, la remplis avec la valeur du hash du nom existant, effectue la recherche par hash, gère l'ajout/mise à jour de service avec cette colonne.
Les données ne possèdent pas cette valeur.
=> [PRÉPARATION CHIFFREMENT] La création de service continue à fonctionner

svelte/lib/ui/SelectionPriorite.svelte
… car le style ne s'appliquait que lorsque le sélecteur avait une valeur.
=> [CORRECTION] Supprime la bordure sur le sélecteur de priorité lorsqu'il est désactivé ET vide

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesServices.js, test/constructeurs/constructeurAdaptateurPersistanceMemoire.js, test/depots/depotDonneesServices.spec.js
Chiffre les données des services.
On ne mets plus "à plat" les données qui sortent de la persistance afin de pouvoir facilement déchiffré grâce à `donneesPersistee.donnees`.
=> Chiffre le contenu d'un service

consoleAdministration.js, src/adaptateurs/adaptateurPostgres.js
Cette méthode ne fonctionne que si les données de la base ne sont pas chiffrées.
Cette méthode a également besoin que les variables d'env suivantes soient renseignées :
- `CHIFFREMENT_URL_BASE_DU_SERVICE`
- `CHIFFREMENT_CLE_DU_MOTEUR_TRANSIT`
- `CHIFFREMENT_TOKEN_VAULT`
- `VAULT_CLE_CHIFFREMENT_AES256`
Et que les utilisateurs ne soient pas en train de modifier les données.
=> [CHIFFREMENT] Ajoute une méthode dans la console d'admin pour chiffrer tous les utilisateurs et tous les services

svelte/lib/tableauDesMesures/TableauDesMesures.svelte
Si la mesure n’est pas enregistrée, les modifications sont perdues quand l’utilisateur ferme le tiroir ou s’il ouvre une autre mesure.
=> [CORRECTION] Ne conserve pas les données modifiées de la mesure dans le tiroir

svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
... car la ligne de la mesure ne permet plus l'ouverture, seulement le titre
=> [CORRECTION] Cible le titre de la mesure pour ouvrir le tiroir

svelte/lib/ui/SelectionEcheance.svelte
Il n’était pas possible d’effacer la date d’échéance pour les mesures qui avaient déjà une date. La solution est de fournir cette date à l’input à l’initialisation du composant.
=> [CORRECTION] Corrige l’effacement d’une date d’échéance de mesure déjà définie

migrations/20240827134814_creationTableActivitesMesure.js, src/adaptateurs/adaptateurPostgres.js, src/bus/abonnements/consigneActiviteMesure.js, src/bus/cablage.js, src/bus/evenementMesureServiceModifiee.js, src/depotDonnees.js, src/depots/depotDonneesActivitesMesure.js, src/depots/depotDonneesServices.js, src/modeles/activiteMesure.js, test/bus/abonnements/consigneActiviteMesure.spec.js, test/bus/evenementMesureServiceModifiee.spec.js, test/depots/depotDonneesActivitesMesure.spec.js, test/depots/depotDonneesServices.spec.js
Les activités liées aux changements de statut des mesures générales des services sont enregistrées dans une nouvelle table `activites_mesure`
=> [HISTORIQUE] Enregistre les changements de statut des mesures

src/bus/abonnements/consigneActiviteMesure.js, test/bus/abonnements/consigneActiviteMesure.spec.js
Les activités de mesure sont créées lorsque :
- une priorité est définie alors qu’il n’y en avait pas
- une priorité est modifiée
De plus, il est possible de changer un statut **ET** de définir/changer une priorité.
=> [HISTORIQUE] Enregistre les changements de priorité des mesures

src/bus/abonnements/consigneActiviteMesure.js, test/bus/abonnements/consigneActiviteMesure.spec.js
...sur une mesure qui a un statut `À définir`, suite à une décision métier
=> [HISTORIQUE] Gère le cas de l’ajout d’un statut

public/assets/images/icone_lien_externe.svg, public/assets/styles/homologation/indiceCyber.css, public/service/indiceCyber.js, src/modeles/mesures.js, src/modeles/service.js, src/vues/fragments/indiceCyber/radarIndiceCyber.pug, src/vues/service/indiceCyber.pug, svelte/lib/indiceCyberPersonnalise/IndiceCyberPersonnalise.svelte, svelte/lib/indiceCyberPersonnalise/indiceCyberPersonnalise.d.ts, svelte/lib/indiceCyberPersonnalise/indiceCyberPersonnalise.ts, test/modeles/mesures.spec.js, test/modeles/service.spec.js
On affiche désormais l'indice cyber personnalisé sur la page de l'indice cyber.
Le composant `Svelte` sera réutilisé sur la page SÉCURISER.
=> [INDICE CYBER PERSONNALISÉ] Ajout de l'indice cyber sur la page dédiée

public/assets/styles/homologation/mesures.css, public/service/indiceCyber.js, src/vues/service/indiceCyber.pug, src/vues/service/mesures.pug
Au menu dans cette PR :
- On supprime le cartouche de recommandation ANSSI dans le cas de l'indice cyber personnalisé, sur la page Indice Cyber
- On permet de naviguer directement sur un onglet de la page Indice Cyber via un `query param`
- On réduit l'espacement entre les indices cybers sur la page SÉCURISER afin de les afficher correctement sur des petits écrans
=> [INDICE CYBER PERSONNALISÉ] Derniers correctifs UI/UX

migrations/20240829064157_supprimeActivitesMesureSuiteChangementModele.js, src/bus/abonnements/consigneActiviteMesure.js, src/modeles/mesureGenerale.js, test/bus/abonnements/consigneActiviteMesure.spec.js, test/constructeurs/constructeurMesureGenerale.js, test/modeles/mesureGenerale.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
La date d’échéance des mesures peut être :
- ajoutée
- modifiée
- supprimée
Un refactoring au niveau de la comparaison des mesures a également été fait.
=> [HISTORIQUE] Ajoute les activités pour les changements d’échéance

public/assets/styles/dossiers.css, src/modeles/dossier.js, src/modeles/dossiers.js, src/modeles/service.js, src/vues/service/dossiers.pug, test/modeles/dossier.spec.js, test/modeles/dossiers.spec.js
On affiche désormais l'indice cyber personnalisé sur la page de résumé des dossiers d'homologation.
On doit enregistrer cet indice cyber au moment de la finalisation d'un dossier afin de garder une trace de sa valeur "à l'instant T".
=> [INDICE CYBER PERSONNALISÉ] Affichage sur la page des dossiers d'homologation

.github/workflows/node.js.yml
... car cela prend du temps pour rien, car la CI n'utilise pas de génération de PDF.
=> [CI/CD] N'installe pas Chromium dans la CI de github

src/bus/abonnements/consigneActiviteMesure.js, test/bus/abonnements/consigneActiviteMesure.spec.js, test/constructeurs/constructeurMesureGenerale.js
On sauvegarde les "ajouts" et les "suppressions" unitaires et pas des "modifications" (de la liste) avec ancienne/nouvelle valeur.
=> [HISTORIQUE] Ajoute les activités pour les ajouts/suppressions de responsables

src/pdf/modeles/indiceCyberPersonnalise/scoreIndiceCyberPersonnalise.pug
En environnement Scalingo, le `foreignObject` ne fonctionne pas correctement avec un `mask`.
On l'encapsule donc dans un `group` pour appliquer le masquage.
=> [CORRECTION] Affiche correctement l'indice cyber personnalisé

svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
...en passant par un display flex. 
Le problème se manifestait par un centrage peu esthétique sur certains navigateurs (par exemple sous Chromium).
Avant :
Après :
=> [CORRECTION] Répare le problème d’alignement pour les libellés longs dans les filtres

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/bus/abonnements/consigneActiviteMesure.js, src/depotDonnees.js, src/depots/depotDonneesActivitesMesure.js, src/modeles/activiteMesure.js, src/routes/connecte/routesConnecteApiService.js, src/routes/connecte/routesConnecteApiServiceActivitesMesure.js, svelte/lib/mesure/Mesure.svelte, svelte/lib/mesure/contenus/ContenuOngletActivite.svelte, svelte/lib/mesure/mesure.api.ts, test/bus/abonnements/consigneActiviteMesure.spec.js, test/constructeurs/constructeurAdaptateurPersistanceMemoire.js, test/constructeurs/constructeurMesureGenerale.js, test/depots/depotDonneesActivitesMesure.spec.js, test/routes/connecte/routesConnecteApiServiceActivitesMesure.spec.js
Lis les activités de mesure en base de données et les retourne dans une nouvelle route d'API dans un nouveau routeur dédié aux activités de mesure.
=> [HISTORIQUE] Lis les activités de mesure

src/adaptateurs/adaptateurCsv.js
… pour que le CSV s'ouvre correctement dans les Excel de nos utilisateurs qui sont a priori configurés en français.
Après la correction, un CSV exporté s'ouvre directement avec les colonnes « propres » dans Excel 👇
=> Utilise un séparateur ";" dans les CSV

migrations/20240904080913_ajouteIdentifiantMesuresSpecifiques.js, src/depots/depotDonneesServices.js, src/modeles/mesureSpecifique.js, test/depots/depotDonneesServices.spec.js, test/modeles/mesureSpecifique.spec.js, test/modeles/mesures.spec.js
... dans le dépôt de données.
Cela permet de pouvoir ensuite brancher une par une les méthodes PATCH, POST, DELETE tout en conservant le fonctionnement actuel.
On ajoute un `id` à toutes les mesures spécifiques existantes via une migration.
=> Ajoute un identifiant aux mesures spécifiques qui n'en ont pas

.env.template, public/assets/styles/mss.css, src/adaptateurs/adaptateurEnvironnement.js, src/http/middleware.js, src/vues/mss.pug, test/http/middleware.spec.js
... afin de signaler aux utilisateurs d'une maintenance proche.
> Afin de signaler la maintenance du jour, il faut rajouter la variable d'environnement `PREPARATION_MODE_MAINTENANCE=Jeudi 5 septembre 2024 - 17h à 19h`
=> Ajout d'un bandeau d'avertissement de maintenance

src/adaptateurs/adaptateurGestionErreurSentry.js, src/adaptateurs/adaptateurProtection.js, src/http/middleware.js, src/http/requeteHttp.js, test/http/requeteHttp.spec.js
Passer par ce header bas-niveau est plus fiable : il fonctionne de la même façon chez Scalingo et chez Clever.
Alors que `X-Real-Ip` était du spécifique Scalingo.
=> Manipule directement `X-Forwarded-For` pour extraire les adresses IP

src/adaptateurs/adaptateurPostgres.js, src/routes/connecte/routesConnecteApiServiceActivitesMesure.js, svelte/lib/mesure/contenus/ContenuOngletActivite.svelte, svelte/lib/mesure/contenus/activites/ActiviteAjoutEcheance.svelte, svelte/lib/mesure/contenus/activites/ActiviteAjoutPriorite.svelte, svelte/lib/mesure/contenus/activites/ActiviteAjoutResponsable.svelte, svelte/lib/mesure/contenus/activites/ActiviteAjoutStatut.svelte, svelte/lib/mesure/contenus/activites/ActiviteMiseAJourEcheance.svelte, svelte/lib/mesure/contenus/activites/ActiviteMiseAJourPriorite.svelte, svelte/lib/mesure/contenus/activites/ActiviteMiseAJourStatut.svelte, svelte/lib/mesure/contenus/activites/ActiviteSuppressionEcheance.svelte, svelte/lib/mesure/contenus/activites/ActiviteSuppressionResponsable.svelte, svelte/lib/mesure/contenus/activites/DesignationMesureActivite.svelte, test/routes/connecte/routesConnecteApiServiceActivitesMesure.spec.js
Le bon identifiant est envoyé depuis le front au back qui, de son côté, sait construire un identifiant numérique pour les mesures spécifiques. 
Pour l’instant, le (mon) choix est de prendre les 6 premiers caractères de l’UUID de la mesure spécifique.
=> [HISTORIQUE] Recupère les activités des mesures spécifiques

src/bus/cablage.js, src/bus/evenementMesureServiceSupprimee.js, src/depotDonnees.js, src/depots/depotDonneesServices.js, src/routes/connecte/routesConnecteApiService.js, test/depots/depotDonneesServices.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
L’événement est un nouvel événement car on ne veut pas consigner d’activité de suppression d’échéance et de responsables lorsqu’on supprime une mesure spécifique.
=> [HISTORIQUE] Envoi un événement au bus lorsqu’une mesure spécifique est supprimée

svelte/lib/blog/Blog.svelte
... car on a maintenant plus que 2 "catégories" il faut donc faire en sorte que les filtres s'étendent sur toute la ligne.
=> [BLOG] Affiche les filtres de catégories sur l'intégralité de la ligne

consoleAdministration.js
Il faut pour cela que l’utilisateur existe dans MSS et qu’il n’ait aucune autorisation sur le service. Après l’exécution de cette procédure, l’utilisateur sera propriétaire du service.
=> Permet d’ajouter un nouveau propriétaire à un service

public/modules/tableauDeBord/actions/ActionMesure.mjs, public/service/mesures.js, svelte/lib/mesure/Mesure.svelte, svelte/lib/mesure/contenus/ContenuOngletActivite.svelte, svelte/lib/mesure/mesure.api.ts, svelte/lib/mesure/mesure.d.ts, svelte/lib/mesure/suppression/SuppressionMesureSpecifique.svelte, svelte/lib/tableauDesMesures/actionsTiroir.ts
Ce n’est plus nécessaire depuis qu’on travaille avec des méthodes unitaires pour les mesures générales et les mesures spécifiques. 
Au passage, on supprime une erreur 404 qui se produisait en mode création quand on essayait de charger les activités d’une mesure.
=> [SOIN] Supprime le passage des mesures existantes au tiroir

src/bus/evenementNouvelleConnexionUtilisateur.js, src/depots/depotDonneesParcoursUtilisateur.js, src/routes/nonConnecte/routesNonConnecteApi.js, src/routes/nonConnecte/routesNonConnecteOidc.js, test/depots/depotDonneesParcoursUtilisateur.spec.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js
Afin de distinguer les utilisateurs MSS (email/mdp) et Agent Connect
=> [JOURNAL] Ajoute la source de connexion aux évènements CONNEXION_UTILISATEUR

public/modules/tableauDeBord/actions/ActionTelechargement.mjs
Sans cette query string dynamique, nos PDF sont mis en cache.
Ce qui empêche les utilisateurs d'avoir des PDF tout le temps à jour.
Par exemple :
- je génère un PDF
- je change le statut de 4 mesures
- je re-génère le PDF. Ici je récupère le PDF mis en cache à l'étape 1.
On passe par une query string plutôt que par une configuration du cache, car c'est beaucoup plus explicite et visible.
Le code modifié est évalué à chaque ouverture du tiroir. 
Donc ça fait bien des liens uniques à chaque ouverture 👇
=> [CORRECTION] Télécharge les PDF avec une query string empêchant la mise en cache

public/modules/tableauDeBord/actions/ActionExport.mjs, public/modules/tableauDeBord/actions/ActionExportMesures.mjs
... des services et des mesures, pour éviter d'avoir du cache.
=> [CORRECTION] Ajoute un `timestamp` sur les exports 

public/entete.js, src/routes/connecte/routesConnecteApi.js, test/routes/connecte/routesConnecteApi.spec.js
pour les utilisateurs non connectés avec mot de passe (par exemple, via Agent Connect)
=> Cache le lien du menu vers la page de changement de mot de passe

migrations/20240916143748_creationTableActivitesIndiceCyber.js, src/adaptateurs/adaptateurPostgres.js, src/bus/abonnements/sauvegardeEvolutionIndiceCyber.js, src/bus/cablage.js, src/depotDonnees.js, src/depots/depotDonneesEvolutionsIndiceCyber.js, src/modeles/mesures.js, src/modeles/service.js, src/modeles/statistiquesMesures.js, src/modeles/statistiquesMesuresGenerales.js, test/bus/abonnements/sauvegardeEvolutionIndiceCyber.spec.js, test/constructeurs/constructeurStatistiquesMesures.js, test/depots/depotDonneesEvolutionsIndiceCyber.spec.js, test/modeles/completudeMesures.spec.js, test/modeles/indiceCyber.spec.js, test/modeles/statistiquesMesuresGenerales.spec.js
Afin de préparer l'ajout d'un graphique du suivi de l'évolution de l'indice cyber, on souhaite commencer à historiser les modifications.
Ces modifications interviennent sur l'**indice cyber** et l'**indice cyber personnalisé**.
La comparaison est faite "2 chiffres après la virgule"
=> [HISTORISATION] Enregistre les modifications d'indice cyber

public/entete.js, src/adaptateurs/adaptateurEnvironnement.js, src/adaptateurs/adaptateurOidc.js, src/mss.js, src/routes/connecte/routesConnecteOidc.js, src/routes/connecte/routesConnectePage.js, src/routes/nonConnecte/routesNonConnecteOidc.js, test/aides/http.js, test/mocks/middleware.js, test/routes/connecte/routesConnecteOidc.spec.js, test/routes/connecte/routesConnectePage.spec.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js
La déconnexion de MSS pour une personne connectée via Agent Connect doit invalider le jeton Agent Connect avant de l'oublier.
=> [AGENT CONNECT] Déconnexion

src/mss.js, src/routes/nonConnecte/routesNonConnecteOidc.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js
pour éviter de se retrouver à s'inscrire avec un utilisateur Agent Connect en étant connecté avec un autre utilisateur (cas rare, mais possible pour plusieurs utilisateurs sur un même ordinateur).
=> [AGENT CONNECT] Supprime l'utilisateur authentifié au début du parcours de connexion

public/apresAuthentification.js, src/routes/nonConnecte/routesNonConnecteOidc.js, src/vues/apresAuthentification.pug, test/routes/nonConnecte/routesNonConnecteOidc.spec.js
En ajoutant cette information dans le cookie temporaire d'Agent Connect.
Il faudra penser à mettre l'url demandée en query sur le bouton Agent Connect (elle sera dans l'url de /connexion)
=> [AGENT CONNECT] Redirige vers l'url demandée intialement après connexion

src/vues/aPropos.pug, src/vues/cgu.pug, src/vues/mss.pug
… au lieu de `ssi.gouv.fr` qui ne répond plus.
=> [CORRECTION] Fais pointer vers `cyber.gouv.fr`

.github/workflows/deploiement-dev.yml
Plutôt que de créer un workflow par PR
=> Limite la création de workflow "déploiement en env de DEV" au déclenchement manuel

svelte/lib/mesure/commentaire/CommentaireMesure.svelte
(commit oublié sur la précédente branche)
=> Empêche que l'appui sur `Entrée` dans la sélection de mention publie le commentaire

src/routes/connecte/routesConnectePage.js
... car la librairie `tiptap` permettant de faire les commentaires à besoin d'un nonce pour fonctionner.
=> [CORRECTION] Ajoute un `nonce` sur la visite guidée de la page SÉCURISER

knexfile.js
... pour éviter les `stales connexions`, suite à la migration vers CleverCloud.
=> [INFRASTRUTURE] Utilise un `pool` minimum de 0

src/adaptateurs/adaptateurJournalMSSPostgres.js
... pour éviter les `stales connexions`, suite à la migration vers CleverCloud.
Le journal avait été oublié lors de la précédente PR.
=> [CORRECTION] Utilise un `pool` minimum de 0 pour le journal

src/pdf/modeles/ressources/styles.css
Il a été rajouté par faute d'inattention, on l'enlève.
Avec le bug, l'encart a un fond transparent. Par exemple ça peut ressembler à 👇 
L'attendu est 👇
=> [CORRECTION] Supprime le sélecteur CSS superflu

src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesUtilisateurs.spec.js
… si l'utilisateur se connectant via AgentConnect n'a pas de siret.
=> [CORRECTION] N'effectue pas d'appel API pour compléter les informations de l'entité

migrations/20240930142255_migreChampsRisquesSpecifiques.js, public/modules/elementsDom/saisieRisqueSpecifique.js, src/modeles/risqueGeneral.js, src/modeles/risqueSpecifique.js, src/pdf/modeles/annexeRisques.pug, src/routes/connecte/routesConnecteApiService.js, test/modeles/objetsPDF/objetPDFAnnexeRisques.spec.js, test/modeles/risqueGeneral.spec.js, test/modeles/risqueSpecifique.spec.js, test/modeles/risques.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
en gardant la route actuelle iso (elle disparaîtra au profit de la nouvelle page)
=> Renomme le champ `description` des risques en `intitulé`

svelte/lib/inscription/SelectionDomaineSpecialite.svelte
... car elle avait disparu lorsque nous avons transformé le bouton en champ texte. Un input ne peut en effet pas avoir de `::after` en CSS.
=> Corrige l’affichage de la flèche sur la sélection du domaine

svelte/lib/inscription/Inscription.svelte
Il n’est plus utile de demander une activation du compte, ni une saisie de mot de passe. On arrive donc directement sur le tableau de bord.
=> Redirige vers le tableau de bord après la création du compte

src/routes/nonConnecte/routesNonConnecteOidc.js
...car il s'agit probablement juste d'un utilisateur qui a mis trop de temps à finir de s'authentifier
=> Ne loggue pas d'erreur si le cookie AgentConnectInfo n'est pas défini

src/routes/nonConnecte/routesNonConnecteApi.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js
... car sinon le robot de contrôle de santé reçoit des codes '302'.
=> [CORRECTION] Empêche le cache sur la route `/api/sante`

src/vues/home.pug
Cette modification ajoute l'ID "video-presentation" à la balise <video> dans le fichier home.pug. Cela permet de créer un lien qui dirige directement les utilisateurs vers la vidéo de présentation sur la page d'accueil.
=> Ajout d'un ID à la balise vidéo pour un lien direct

src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesUtilisateurs.spec.js
... afin de la provisionner au modèle `Utilisateur`.
Cet oubli date sûrement de la mise en place du chiffrement.
=> [CORRECTION] Extrais correctement la `dateCreation` de l'adaptateur Persistance

public/mssConnecte.js
Cette modification permet d’afficher la modale de reconnexion lorsque le DOM est remonté suite à un redémarrage du navigateur. La requête "dureeSession" retournait la page de connexion, ce qui était ignoré jusqu’à présent et la modale n’était pas affichée.
=> Règle un problème des erreurs CSRF

svelte/lib/risques/LigneRisque.svelte, svelte/lib/risques/Risques.svelte, svelte/lib/risques/risques.ts, svelte/lib/ui/Avertissement.svelte
S’il y a des risques spécifiques qui n’ont pas de catégorie, on affiche une alerte au dessus du tableau des risques :
Chaque risque est affiché avec une alerte :
=> Affiche une alerte pour les risques specifiques à mettre à jour

svelte/lib/connexion/Connexion.svelte
On n'était plus redirigé, la fonctionnalité n'ayant pas été reprise dans la nouvelle page de connexion
=> Corrige la redirection quand on se connecte avec ProConnect

src/depots/depotDonneesServices.js, src/depots/depotDonneesUtilisateurs.js, src/modeles/contributeur.js, src/modeles/identite.js, src/modeles/objetsApi/objetGetService.js, src/modeles/service.js, src/modeles/utilisateur.js, src/routes/connecte/routesConnectePageService.js, test/depots/depotDonneesServices.spec.js, test/modeles/contributeur.spec.js, test/modeles/identite.spec.js, test/modeles/service.spec.js, test/modeles/utilisateur.spec.js
Cette PR vise à casser la dépendance entre `Service` et `Utilisateur`.
Pour le chantier de versionning des CGU acceptées par chaque `Utilisateur`, on va devoir modifier la classe `Utilisateur`.
La dépendance entre `Service` et `Utilisateur` nous gêne… car elle nous forcerait à modifier `Service` si on touche `Utilisateur`.
Pour résoudre le problème, cette PR extrait `Contributeur` qui est une version allégée d'un `Utilisateur`.
Par composition on évite la duplication de code en utilisant `Identite`.
=> Création de la classe `Contributeur`

svelte/lib/risques/MatriceRisques.svelte
... pour n'afficher que les premiers risques de la case sans débordement
=> Ajoute une ellipse et un tooltip sur les cases de la cartographie

svelte/lib/risques/Risques.svelte, svelte/lib/risques/TiroirLegende.svelte, svelte/lib/risques/TiroirRisque.svelte
... comme le javascript des anciens tiroirs se basait sur la classe "tiroir" pour ouvrir le tiroir contributeurs/téléchargements, et que les nouveaux tiroirs Svelte avaient aussi cette classe, quatre tiroirs s'ouvraient en même temps sur la page Risques
=> [CORRECTION] N'ouvre que le tiroir demandé sur la page Risques

src/modeles/objetsApi/objetGetService.js
...qui ne fonctionnait plus suite au renommage `id` vers `idUtilisateur`.
Cela avait pour impact de casser le filtre "Mes mesures"
=> [CORRECTION] Corrige la valeur de `estUtilisateurCourant`

src/depots/depotDonneesServices.js, test/depots/depotDonneesServices.spec.js
Si on publie avant, le service embarqué dans l'événement ne contient pas le nouveau risque.
=> [CORRECTION] Publie sur le bus *après* la mise à jour du service

src/modeles/inscriptionUtilisateur.js, test/modeles/inscriptionUtilisateur.spec.js
... car sinon on persiste la valeur "true", au lieu de la remplacer par la "dernière version" des CGU. 
On en profite pour ajouter un test unitaire spécifique au service d'inscription d'utilisateur, sinon tous les tests sont réalisés au niveau de l'API.
=> [CORRECTION] Valide l'acceptation des CGU lors de l'inscription d'un utilisateur

migrations/20241105100212_creationTableSuperviseurs.js, server.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/adaptateurs/adaptateurSupervision.js, src/adaptateurs/fabriqueAdaptateurSupervision.js, src/bus/abonnements/relieServiceEtSuperviseurs.js, src/bus/cablage.js, src/depotDonnees.js, src/depots/depotDonneesSuperviseurs.js, src/modeles/service.js, test/bus/abonnements/relieServiceEtSuperviseurs.spec.js, test/depots/depotDonneesSuperviseurs.spec.js
Afin de proposer un dashboard de "Supervision" aux utilisateurs concernés, MonServiceSécurisé va tenir dans son Journal une liste à jour des liens entre superviseur et service.
Cette PR permet de relier un service à un superviseur lors de sa création.
=> [SUPERVISION] Liaison entre superviseur et service à la création d'un service

src/bus/abonnements/delieServiceEtSuperviseurs.js, src/bus/abonnements/modifieLienServiceEtSuperviseurs.js, src/bus/abonnements/relieServiceEtSuperviseurs.js, src/bus/cablage.js, src/bus/evenementDescriptionServiceModifiee.js, src/depots/depotDonneesServices.js, src/supervision/serviceSupervision.js, test/bus/abonnements/delieServiceEtSuperviseurs.spec.js, test/bus/abonnements/modifieLienServiceEtSuperviseurs.spec.js, test/bus/abonnements/relieServiceEtSuperviseurs.spec.js, test/bus/evenementDescriptionServiceModifiee.spec.js, test/constructeurs/constructeurDescriptionService.js, test/supervision/serviceSupervision.spec.js
Cet abonné ne fait finalement qu'une suppression suivi d'un ajout dans le cas d'une modification de SIRET.
On en profite pour extraire un `ServiceSupervision` qui permet d'orchestrer ces actions.
=> [SUPERVISION] Modification du lien des superviseurs lors d'un changement de SIRET

migrations/20241107084938_remplaceMajusculeDansEmailUtilisateur.js, src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesUtilisateurs.spec.js
Suite à une erreur en PROD, on remarque que Agent Connect nous envoi parfois des informations utilisateur contenant des emails avec des majuscules.
Si le compte existe déjà dans MSS en version "minuscule", on ne trouve pas le compte, donc on essaye de le créer, ce qui provoque une erreur côté Brevo.
=> [CORRECTION] Considère uniquement des `email` en minuscule

migrations/20241107100038_ajouteColonneSiretHash.js, migrations/20241107100049_insereSiretHash.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesServices.js, test/depots/depotDonneesServices.spec.js
... en base de données, afin de pouvoir plus facilement rechercher tous les services d'un SIRET.
On sort cette données dans une colonne dédiée afin de garantir le fonctionnement de nos méthodes lorsque les données seront chiffrées.
=> [SUPERVISION] Ajoute le `hash` des SIRETs de service

src/modeles/service.js, test/modeles/service.spec.js
Ce bug provient de la séparation des contributeurs et utilisateurs et du renommage de id vers idUtilisateur de l'identifiant de l'utilisateur
=> [CORRECTION] Corrige un bug sur mise à jour d'une mesure spécifique avec responsable

svelte/lib/ui/ListeDeroulante.svelte
... car par défaut, le `select` ne prend pas la police du `body`
=> [CORRECTION] Applique la police "Marianne" sur la liste déroulante

src/bus/abonnements/metAJourParrainage.js, test/bus/abonnements/metAJourParrainage.spec.js, test/constructeurs/constructeurUtilisateur.js, test/notifications/centreNotifications.spec.js
... car sinon, le parrainage était validé avant même que l'utilisateur ne termine le parcours d'inscription.
=> [CORRECTION] Vérifie la finalisation de l'inscription pour le parrainage

src/vues/home.pug
Modification du texte sur la page d’accueil de MonServiceSécurisé pour indiquer le nouveau cap de 6 000 utilisateurs au lieu des 5 000 précédemment affichés. Ajustement éventuel de la mise en page pour assurer la cohérence. Cette mise à jour garantit l’exactitude des chiffres affichés.
=> Mise à jour de home.pug pour refléter le passage à 6 000 utilisateurs

public/assets/images/icone_etoile.svg, public/tableauDeBord-v2.js, src/routes/connecte/routesConnectePage.js, src/vues/tableauDeBordv2.pug, svelte/lib/tableauDeBord/TableauDeBord.svelte, svelte/lib/tableauDeBord/elementsDeService/EtiquetteContributeurs.svelte, svelte/lib/tableauDeBord/elementsDeService/EtiquetteIndiceCyber.svelte, svelte/lib/tableauDeBord/elementsDeService/EtiquetteProprietaire.svelte, svelte/lib/tableauDeBord/tableauDeBord.d.ts, svelte/lib/tableauDeBord/tableauDeBord.ts, svelte/lib/ui/IconeChargementEnCours.svelte, test/routes/connecte/routesConnectePage.spec.js
... en Svelte.
On crée donc un composant Svelte simple qui va permettre d'afficher le tableau des services "iso-prod" en terme de feature, mais avec le "nouveau look" de la V2 du tableau de bord.
=> [TABLEAU DE BORD V2] Ajout du tableau "simple" des services

src/vues/mss.pug
Changement mineur du lien de prise de rendez-vous pour la présentation de MonServiceSécurisé. Le lien de Calendly de Henri a été remplacé par celui de Fabien
=> Mise à jour du lien Calendly pour les rendez-vous de présentation

svelte/lib/uiKit/UiKit.svelte
... qui avait été introduit par un sélécteur `:global` avec l'UI Kit
=> [CORRECTION] Corrige l'alignement du texte sur tout MonServiceSécurisé

svelte/lib/tableauDeBord/TableauDeBord.svelte
... car l'intégralité de MSS est centré par défaut.
Un `text-align: left` avait été introduit par mégarde, et corrigé dans la #1941.
=> [CORRECTION] Aligne tout le contenu du tableau de bord à gauche

server.js, src/mss.js, src/routes/connecte/routesConnecteApi.js, src/routes/connecte/routesConnecteApiService.js, src/routes/nonConnecte/routesNonConnecteApi.js, test/routes/testeurMSS.js
... plutôt que de se reposer sur des paramètres positionnels. Cela permet de s'affranchir des problèmes d'ordre de passage des dépendances.
=> [SOIN] Utilise un 'objet' pour instancier le serveur

svelte/lib/ui/FilAriane.svelte
... et ajoute un `offset` entre le texte et la ligne soulignée.
=> [CORRECTION] Ajoute un `hover` sur les liens du fil d'ariane

src/mss.ts
...une erreur est lancée au démarrage du middleware mais l’application fonctionnait quand même
=> [CORRECTION] Corrige le controlleur d'erreur utilisé par MSS

public/scripts/csrf.mjs
...certaines erreurs sont renvoyées depuis l’API dans un objet et l’intercepteur CSRF doit prendre en charge ce cas afin d’éviter une erreur (`includes non trouvé`)
=> [CORRECTION] Corrige l'interception des erreurs

svelte/lib/tiroir/Tiroir.svelte
... afin d'éviter d'ouvrir le tiroir Svelte par dessus l'ancien tiroir jQuery.
Comme les deux portent la même classe, lorsque le jQuery fait `$('.tiroir').addClass('ouvert')`, il ouvre aussi le tiroir Svelte, or ce n'est pas le comportement voulu
=> [CORRECTION] Utilise un id 'tiroir' pour séparer le Legacy du Svelte

svelte/lib/tableauDeBord/TableauDeBord.svelte
afin de ne pas voir clignoter le tableau de bord v2 à chaque modification
=> [SOIN] N'affiche le loader qu'au premier affichage de la page

public/assets/styles/formulaire.css, public/assets/styles/tiroir.css, public/modules/tableauDeBord/actions/ActionSuppressionService.mjs, src/routes/connecte/routesConnecteApiService.js, src/vues/tiroirs/tiroirSuppressionService.pug, test/routes/connecte/routesConnecteApiService.spec.js
Demande confirmation à la suppression de services via un message de confirmation à taper plutôt qu'un challenge mot de passe. En effet, les utilisateurs ProConnect n'ont pas de mot de passe dans MSS.
On demande à l'utilisateur de copier une chaîne pour confirmer qu'il comprend l'action qu'il est en train de faire.
=> [CORRECTION] Ajoute une confirmation de suppression service

public/modules/tableauDeBord/actions/ActionSuppressionDossierCourant.mjs, src/vues/tiroirs/tiroirSuppressionDossierCourant.pug
...via un message de confirmation à taper plutôt qu'un challenge mot de passe. En effet, les utilisateurs ProConnect n'ont pas de mot de passe dans MSS. On demande à l'utilisateur de copier une chaîne pour confirmer qu'il comprend l'action qu'il est en train de faire.
=> [CORRECTION] Demande confirmation à la suppression d'un projet d'homologation

src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesUtilisateurs.spec.js
Lors de la création de compte utilisateur, on ne doit pas envoyer les invités à MPA.
Lors de la mise à jour d'un compte utilisateur, on ne doit envoyer que les invités confirmant leur inscription MSS.
=> [MonProfilAnssi] Inscris les invités à MonProfilAnssi

README.md
Les scripts de migration de la base de données sont appliqués automatiquement au démarrage. Plus besoin de les lancer manuellement.
=> Corrige le README pour l'installation initiale

svelte/lib/tableauDesMesures/stores/rechercheTextuelle.store.ts
… d'une mesure, appelé "modalités" au sein de l'objet métier.
Cette demande provient de @pgrange qui en aurait besoin dans son utilisation de MSS.
=> [SÉCURISER] Permet d'appliquer la recherche textuelle sur les "précisions" 

server.ts, src/adaptateurs/adaptateurGestionErreurSentry.js, src/adaptateurs/adaptateurGestionErreurVide.js, src/http/middleware.js, test/http/middleware.spec.js
Pour augmenter nos compréhensions des erreurs, cette PR [utilise le `setUser` de Sentry](https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/) dans notre middleware de vérification de JWT.
Ça commence par une PR de soin, pour faciliter l'ajout de `adaptateurGestionErreur` dans le middleware.
Côté Sentry, le résultat est 👇 
Dans ce qu'on log chez Sentry, si on met `token` ou `JWT`  le nom de dans le clé, la donnée se fait `[Filtered]`.
Donc j'ai choisi `Connexion UTC`.
Cette PR met l'ID de l'utilisateur… et pas l'email.
À voir si on veut l'email… car le dépôt, pour vérifier si l'utilisateur existe, le récupère en BDD. Donc ça ne serait pas plus cher…
=> Augmentation des infos transmises à Sentry

src/bus/busEvenements.js, src/erreurs.js, test/bus/busEvenements.spec.js
… pour avoir davantage d'infos sur le contexte lorsqu'une erreur part vers Sentry.
En renseignant la propriété `cause` de `Error`, Sentry est capable de faire un affichage 👇 
- _En (1) on voit que le `bus` logue maintenant le type d'événement ayant causé un crash dans l'abonné_
- _En (2) on voit l'imbrication des exceptions 🎉_ 
Cette PR pourrait être le début d'une gestion réfléchie des erreurs au niveau du bus : les abonnés `throw` et le bus logue en prenant soin de renseigner la propriété `cause` de l'erreur.
⚠️ Là… on ne sait pas encore précisément QUEL abonné a crashé. Réfléchissons à comment on s'y prend…
On pourrait imaginer un `try catch` dans chaque abonné, qui `throw new ErreurDansAbonne("Impossible de xyz", {cause: e})`, comme ça on aurait tout le temps 3 étages dans Sentry : …
=> [SOIN] Enrichis les erreurs loguées par le bus

svelte/lib/mesure/mesure.api.ts
... suite à un bug remonté en prod par @pgrange.
Il semblerait que ce bug proviennent si la session est terminé, auquel cas la requêtre renverrait un objet dans `data`.
=> [CORRECTION] Corrige l'enregistrement des mesures dans le cas où un problème survient lors de la récupération des activités

src/vues/statistiques.pug
… car on ne sait pas la calculer sur les 12 derniers mois 👇 
Nous sommes au début de l'année, et comme l'évolution est calculée à partir de la fin de l'année dernière, on a des chiffres comme « + 1% » qui sont affichés en PROD.
Autrement dit : on masque le chiffre, car il ne reflète pas la réalité.
Le chantier plus conséquent sera d'afficher de nouveau les statistiques sous forme de courbes.
=> [STATISTIQUES] Cesse d'afficher l'évolution

svelte/lib/inscription/SelectionDepartement.svelte, svelte/lib/profil/Profil.svelte
On utilise ici une mécanique d'export de fonction, pour contourner les problèmes de "race condition" entre la mise à jour des valeurs "bindés" et la mise à jour du DOM.
Cette feature fonctionnait lorsque nous utilisions `selectize`.
=> [CORRECTION] Remplace le département lors de la sélection d'une organisation

src/adaptateurs/adaptateurRechercheEntrepriseAPI.js, test/adaptateurs/adaptateurRechercheEntrepriseAPI.spec.js
Suite à une remontée des utilisateurs, certains établissement "secondaires" ne figuraient pas dans la liste de proposition des organisations.
C'est dû au fait que ces SIRET ne sont pas les sièges, mais des établissements annexes.
Grâce à l'aide de l'équipe technique responsable de l'API recherche entreprise, nous avons pu correctement extraire les données.
Nous testons EXCEPTIONNELEMENT un adaptateur dans cette Pull Request, car obligatoire pour s'assure que l'on couvre tous les cas d'usage.
=> [CORRECTION] Renvoi correctement les établissements "secondaires" lors d'une recherche par SIRET

src/adaptateurs/adaptateurRechercheEntrepriseAPI.js, test/adaptateurs/adaptateurRechercheEntrepriseAPI.spec.js
Apparemment, on peut avoir un siège mais une liste d'établissements vide.
=> [CORRECTION] Retourne les infos du siège si le matching établissements est vide

src/routes/connecte/routesConnecteApi.js, test/routes/connecte/routesConnecteApi.spec.js
Le cookie de session n'est mis à jour qu'une fois toutes les minutes.
La date d'affichage de la modale de déconnexion est mis à jour à chaque requête.
Il peut exister un battement de presque une minute pendant lequel l'utilisateur ne voit pas la modale mais le cookie est expiré. Dans ce cas, toute action provoque une erreur CSRF sur le serveur. Exmple :
* Bob se connecte à 12:00:00
* le cookie expire à 13:00:00
* la modale s'affichera à 13:00:00
* Bob effectue une action à 12:00:59
* le cookie expire à 13:00:00 (pas mis à jour car moins d'une minute)
* la modale s'affichera à 13:00:59
* Bob prend une pause et effectue une action à 13:00:01 (elle échoue)
* le cookie est expiré depuis 13:00:00 et donc n'est pas envoyé au serveur
* la modale ne s'est pas encore affiché car il n'est pas …
=> Vérifie une hypothèse sur les erreurs CSRF

src/routes/connecte/routesConnectePage.js, svelte/lib/tableauDeBord/BandeauFiltres.svelte, svelte/lib/tableauDeBord/TableauDeBord.svelte, svelte/lib/tableauDeBord/TableauDesServices.svelte, svelte/lib/ui/Bouton.svelte, svelte/lib/ui/Lien.svelte, svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte, svelte/lib/visiteGuidee/kit/ModaleSousEtape.d.ts, svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte, test/routes/connecte/routesConnectePage.spec.js
Corrige les deux petits retours de recette.
Ajoute un encart quand l'utilisateur n'a aucun service.
Active le tableau de bord v2 sur l'url `/tableauDeBord`. 
Corrige la visite guidée pour qu'elle s'affiche correctement avec le nouveau tableau de bord.
=> Active le tableau de bord v2

donneesReferentiel.js, public/assets/styles/carteInformations.css, public/assets/styles/dossiers.css, public/assets/styles/tableauDeBord.css, src/modeles/dossier.js, src/modeles/dossiers.js, src/modeles/objetsApi/objetGetService.js, src/vues/service/dossiers.pug, svelte/lib/tableauDeBord/TableauDesServices.svelte, svelte/lib/tableauDeBord/elementsDeService/EtiquetteHomologation.svelte, svelte/lib/tableauDeBord/tableauDeBord.d.ts, test/modeles/dossier.spec.js, test/modeles/objetsApi/objetGetService.spec.js
Expirée : ancien et nouveau statut iso
Non réalisée devient Aucune
BIentôt expiré devient le "expire + date"
Active devient "realisée"
Bientôt activée disparait, toute homologation qui n'est pas expirée est "réalisée"
=> Mets à jours les statuts d'homologation

svelte/lib/tableauDeBord/elementsDeService/EtiquetteHomologation.svelte
… afin d'éviter un affichage incorrect.
=> [CORRECTION] Empêche l'etiquette du statut d'homologation de se propager sur plusieurs lignes

svelte/lib/tableauDeBord/stores/affichageParStatutHomologation.ts, svelte/lib/tableauDeBord/stores/affichageTableauVide.ts, svelte/lib/tableauDeBord/tableauDeBord.d.ts
... afin de ne pas faire crasher le tableau de bord
=> [CORRECTION] Ne prend pas en compte les services dont le statut d'homologation est masqué pour un utilisateur dans l'affichage des onglets

package.json
En développement local, la création de l'utilisateur a besoin que le code ait déjà été compilé or on compilait après la création de cet utilisateur et donc cela échouait sur un environnement vierge sur lequel on n'avait jamais compilé.
On corrige l'ordre de ces instructions pour compiler avant de créer l'utilisateur.
=> Corrige la création de l'utilisateur démo en local

svelte/lib/tableauDeBord/TableauDesServices.svelte
...suite à une erreur dans les maquettes.
=> [CORRECTION] Passe les labels de besoins de sécurité au pluriel

src/modeles/autorisations/autorisation.js, src/modeles/objetsApi/objetGetService.js, src/modeles/service.js, svelte/lib/tableauDeBord/TableauDesServices.svelte, svelte/lib/tableauDeBord/elementsDeService/ActionRecommandee.svelte, svelte/lib/tableauDeBord/tableauDeBord.d.ts, svelte/lib/ui/Bouton.svelte, svelte/lib/ui/Lien.svelte, test/modeles/autorisations/autorisation.spec.js, test/modeles/objetsApi/objetGetService.spec.js, test/modeles/service.spec.js
L'action recommandée dépend du service et non de l'utilisateur qui navigue. C'est pourquoi parfois l'utilisateur n'a pas le droit d'exécuter l'action recommandée. Dans ce cas, on désactive le bouton.
=> [TDB V2] Désactive les actions recommandées si elles ne sont pas autorisées

svelte/lib/ui/tiroirs/TiroirSuppression.svelte
…car sinon, les caractères spéciaux RegEx sont mal interprétés.
Possible de tester avec ce nom de service : `Mon [](){}*\/^$.|?*+ Service`
=> [CORRECTION] "Échappe" le nom du service pour le `pattern` de confirmation de suppression

svelte/lib/tableauDeBord/ActionsDesServices.svelte, svelte/lib/tableauDeBord/TableauDesServices.svelte, svelte/lib/tableauDeBord/elementsDeService/ActionRecommandee.svelte, svelte/lib/tiroir/Tiroir.svelte, svelte/lib/ui/stores/tiroir.store.ts, svelte/lib/ui/tiroirs/TiroirDuplication.svelte, svelte/lib/ui/tiroirs/TiroirExportServices.svelte, svelte/lib/ui/tiroirs/TiroirGestionContributeurs.svelte, svelte/lib/ui/tiroirs/TiroirSuppression.svelte, svelte/lib/ui/tiroirs/TiroirTelechargementDocumentsService.svelte
... afin de rendre le code plus propre.
Aujourd'hui, chaque appel d'affichage d'un contenu de tiroir devait configurer le titre et le sous-titre à afficher. Or, cette configuration est liée au contenu de tiroir lui-même.
On créer donc des `props` : `titre`, `sous-titre` dans chaque tiroir, et on assigne un type de "ConfigurationTiroir" au store `tiroir.store`.
On utilise le [ComponentType](https://svelte.dev/docs/svelte/typescript#The-Component-type) de Svelte pour typer correctement ce store et ces composants.
=> [SOIN] Extrais la configuration du tiroir dans les composant

svelte/lib/tableauDeBord/BandeauFiltres.svelte
... qui était sous l'entête de tableau depuis que celui-ci était devenu sticky
=> [CORRECTION] Corrige l'affichage du menu filtres

migrations/20250121162039_enleveIdsDateCreationDeDonneesUtilisateur.js, src/depots/depotDonneesUtilisateurs.js, test/constructeurs/constructeurAdaptateurPersistanceMemoire.js, test/depots/depotDonneesUtilisateurs.spec.js
...ces éléments étant stockés dans des colonnes séparées. Depuis la modification sur le chiffrement, ils ont été par erreur re-sauvegardés dans la payload de données utilisateur.
=> [SOIN] Ne sauvegarde pas les identifiants et date de création dans les données utilisateur

src/adaptateurs/adaptateurJWT.js
... en cas de signature JWT invalide
=> Attrape l'erreur lancée par `jwt.verify` afin d'être redirigé vers la page de login

svelte/lib/tableauDeBord/TableauDesServices.svelte
Elle doit avoir une taille fixe pour ne pas "bouger" au survol.
Utiliser `width` ne fonctionne pas.
=> [CORRECTION] Corrige l'affichage de la cellule nom du TDB

src/mss.ts, test/aides/cookie.js, test/routes/connecte/routesConnecteApi.spec.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js, test/routes/nonConnecte/routesNonConnectePage.spec.js, test/routes/testeurMSS.js
... plutôt que `token`. 
Ce nommage est très confusant, car le cookie contient lui même un champ `token` qui est le JWT d'authentification. 
On préfère donc `session`.
> Le `merge` de cette PR entrainera une invalidation de toute les sessions actives :
> - Un clic de navigation renverra vers la page de connexion
> - Un appel API affichera la modale de reconnexion.
> [!WARNING]  
> Il est tout de même préférable de merger cette PR dans un "creu" d'utilisation de la plateforme. Une modification du `secret` n'est pas nécessaire.
=> Renomme le cookie de session en `session`

.env.template, src/adaptateurs/adaptateurChiffrementChaCha20.js, src/adaptateurs/adaptateurEnvironnement.js, test/adaptateurs/adaptateurChiffrementChaCha20.spec.js
En tant qu'attaquant,
Si j'arrive à mettre la main sur un dump de la base de données
Et seulement ce dump
Alors, me voilà bien embêté car je découvre que ces données sont chiffrées et que je ne peux pas les lire.
On utilise l'algorithme ChaCha20 pour le chiffrement dans un nouvel adaptateur. Celui n'est pas activé par cette PR.
=> Chiffrer en mémoire avec ChaCha20 les données stockées en base

src/http/middleware.js, src/mss.ts, test/http/middleware.spec.js, test/mocks/middleware.js
Par défaut, on interdit la mise en cache de toutes les réponses. On n'autorise qu'au cas par cas.
=> Interdis la mise en cache par défaut

migrationHash.js, migrations/20250211144528_creationTableVersioningSelHachage.js, migrations/20250218150831_modifieEmailHashUtilisateurEnTexte.js, src/adaptateurs/adaptateurChiffrement.js, test/adaptateurs/adaptateurChiffrement.spec.js
Stocke avec le hash la version 1 avec lequel il a été salé
> [!CAUTION]
> **⚠️ Mettre en prod avec le mode MAINTENANCE activé**
> **⚠️ Faire un backup des db MSS et MSSJournal**
=> [HACHAGE] Ajoute la première version du sel

.env.template, migrationHash.js, migrations/20240813070846_insereEmailHashUtilisateurs.js, migrations/20240819091430_insereNomServiceHash.js, migrations/20241107084938_remplaceMajusculeDansEmailUtilisateur.js, migrations/20241107100049_insereSiretHash.js, server.ts, src/adaptateurs/adaptateurChiffrement.js, src/adaptateurs/adaptateurChiffrementChaCha20.js, src/adaptateurs/adaptateurEnvironnement.js, src/adaptateurs/adaptateurPostgres.js, src/adaptateurs/fabriqueAdaptateurChiffrement.js, src/depotDonnees.js, src/depots/depotDonneesSelsDeHachage.js, src/erreurs.js, src/http/middleware.js, src/sel/serviceVerificationCoherenceSels.js, test/adaptateurs/adaptateurChiffrement.spec.js, test/adaptateurs/adaptateurEnvironnement.spec.js, test/depots/depotDonneesSelsDeHachage.spec.js, test/http/middleware.spec.js, test/sel/serviceVerificationCoherenceSels.spec.js
- Vérifie la cohérence des sels au démarrage (tous les sels en base sont dans la config, tous les sels de la config sont en base, l'empreinte en base correspond au sel de la config)
- Utilise tous les sels de la config pour hacher
> [!IMPORTANT]
>  Vous devez ajouter à votre .env la clé `CHIFFREMENT_SEL_DE_HASHAGE_1=` avec la valeur de sel correspondant à votre v1
> [!IMPORTANT]
>  Si vous n'avez jamais joué la migration des hash v1, vous devez la jouer pour que l'application démarre (vous pouvez démarrer en mode maintenance pour faire la migration)
> [!CAUTION]
> - Il faut ajouter la variable  `CHIFFREMENT_SEL_DE_HASHAGE_1` pour mettre en prod
=> [SEL] Vérifie la cohérence au démarrage et utilise les sels configurés

src/adaptateurs/adaptateurMailSendinblue.js
... car sans le "spread", on ne prend que le premier paramètre.
=> [CORRECTION] Corrige les paramètres de l'envoi de notification d'expiration

.env.template, knexfile.js, migrationHash.js, src/adaptateurs/adaptateurEnvironnement.js, src/adaptateurs/adaptateurJournalMSSPostgres.js, src/adaptateurs/adaptateurSupervisionMetabase.js
... afin de pouvoir le modifier en fonction de la taille de l'instance déployée.
> [!CAUTION]
> La variable `BASE_DONNEES_POOL_CONNEXION_MAX` doit être valorisée avant de merger 
> La variable `BASE_DONNEES_JOURNAL_POOL_CONNEXION_MAX` doit être valorisée avant de merger
=> [SOIN] Variabilise le pool de connexion maximum pour Postgres

migrationHash.js, migrationHash.spec.js, src/adaptateurs/adaptateurChiffrement.js, src/depots/depotDonneesSelsDeHachage.js, src/erreurs.js, src/sel/serviceVerificationCoherenceSels.js, test/depots/depotDonneesSelsDeHachage.spec.js, test/sel/serviceVerificationCoherenceSels.spec.js
..avec les fusibles associés, afin de ne pas migrer les hashs
- sans être en mode maintenance
- si plusieurs hashs sont nouveaux
- si les hashs appliqués ne correspondent pas à la config
- si la chaine est déjà hachée avec ce hash
- si la chaine n'est pas hachée avec tous les hash précédents
=> Ajoute la possibilité de migrer vers le dernier sel de la config

src/http/configurationServeur.js
Certaines pages sont publiques et ne nécessitent aucune authentification donc elles ne sont pas sujettes à une attaque CSRF. Donc on désactive la protection CSRF sur ces pages.
Le but de ce changement est de clarifier ce point pour le lecteur.
=> Clarifie l'explication sur CSRF

src/vues/erreur.pug
... afin de pouvoir l'utiliser directement dans un message. On utilise du code Javascript "custom" côté Crisp pour détecter ce `queryParams` et l'ajouter dans un message par défaut.
=> Passe l'identifiant d'erreur Sentry dans l'URL du support utilisateur

src/erreurs.js, src/modeles/service.js, src/routes/connecte/routesConnecteApiService.js, svelte/lib/ui/SelectionResponsables.svelte, test/modeles/service.spec.js, test/routes/connecte/routesConnecteApiService.spec.js
Aujourd'hui, un service dupliqué conserve ses mesures.
Il peut donc y avoir des responsables de mesures.
Or, ce service dupliqué ne conserve pas les contributeurs.
On veut donc éviter ces erreurs, en omettant les responsables de mesures inutiles au niveau de l'API.
=> [CORRECTION] Corrige les responsables manquants lors de la duplication d'un service

.env.template, server.ts, src/adaptateurs/adaptateurEnvironnement.js, src/http/middleware.js, src/mss.ts, test/http/middleware.spec.js, test/mocks/middleware.js
... dans `reponse.locals.featureFlags`, afin d'y avoir accès dans le `pug`
=> Charge les features flags depuis le Middleware

README.md, scripts/start.sh
On recommande l'utilisation de --build a chaque run docker compose pour s'assurer qu'on fait bien trouver la dernière version. S'il n'y a pas de changements, le cache docker permet au build de s'exécuter très rapidement.
On abstrait la commande derrière scripts/start.sh
=> Simplifie la lecture du README

admin/duplicationEnMasseDeServices.js, package-lock.json, package.json, src/depots/depotDonneesServices.js, src/modeles/service.js, test/depots/depotDonneesServices.spec.js, test/modeles/service.spec.js
... en permettant la duplication d'un service avec un nom prédéfini.
On augmente la fonction `dupliqueService` du dépôt données actuel, afin de pouvoir modifier le nom et le siret du service dupliqué à la demande. On utilise la `procedure` déjà en place pour l'invitation des contributeurs, afin de bénéficier de la logique métier d'envoie de mail.
[Screencast from 02-04-2025 11:12:24.webm](https://github.com/user-attachments/assets/9276ede7-b22a-4947-add8-3c96a5fb927e)
=> [ADMIN] Ajoute la possiblité de cloner "en masse"

src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesUtilisateurs.spec.js
... en ne persistant pas d'`idResetMdp`, et en n'envoyant pas d'email. 
On sait qu'un utilisateur est ProConnecté s'il n'a pas de mot de passe dans ses données persistées.
=> [CORRECTION] Ne permet pas de réinitialiser un mot de passe pour les utilisateurs "Pro Connecté"

src/pdf/modeles/ressources/styles.css
... car sinon, un nom de service comme "MonServiceSécurisé" ne tient pas sur une ligne et déborde.
=> [CORRECTION] Coupe le nom du service s'il ne tient pas sur une ligne

src/pdf/modeles/tamponHomologation.pug
... afin de pouvoir "couper" proprement les noms de service trop long.
=> Ajoute un "ZeroWidthSpace" sur le nom du service

src/routes/nonConnecte/routesNonConnecteOidc.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js
... suite à un bug lors de la MEP.
On ne tente plus de mettre à jour le profil d'un utilisateur invité avant qu'il ai fini le processus complet de création de compte. 
:point_right:  Cela pose problème car les utilisateurs invités n'ont pas encore de profil "complet". 
:star2:  On choisit donc à ce moment là de ne faire que "rafraichir" les données en faisant un GET sur MPA. 
:recycle:  Ensuite, l'utilisateur invité va passer par le processus de finalisation d'inscription, qui retombera sur une MAJ côté MPA.
=> [CORRECTION] Gère correctement les invités avec MPA

src/routes/connecte/routesConnectePage.js, src/routes/nonConnecte/routesNonConnecteOidc.js, test/routes/connecte/routesConnectePage.spec.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js
... lors de l'affichage du profil.
On en profite pour corrige un bug ou, un utilisateur qui n'a pas d'informations MonProfilAnssi se retrouve avec une création de compte avec des champs "undefined".
=> [CORRECTION] Reste robuste si l'utilisateur n'a pas de postes

src/modeles/utilisateur.js, src/routes/connecte/routesConnectePage.js, test/modeles/utilisateur.spec.js
... suite à un bug en prod.
On veut que cette propriété soit toujours exploitables.
C'était une erreur lors de l'ajoute de cette propriété, de la mettre en tant que "propriété atomique".
=> [CORRECTION] Utilise une valeur par défaut pour les `postes` des Utilisateurs

src/depots/depotDonneesUtilisateurs.js, src/utilisateur/serviceApresAuthentification.js, test/constructeurs/constructeurUtilisateur.js, test/depots/depotDonneesUtilisateurs.spec.js, test/utilisateur/serviceApresAuthentification.spec.js
Nous rencontrons des problèmes de compréhension et de lourdeur sur la route responsable de l'authentification d'un utilisateur après ProConnect. Cela est dû au fait que nous essayons désormais d'intégrer MonProfilANSSI. Nous avons donc 3 sources de données potentielles pour un utilisateur : MonProfilANSSI, ProConnect et MonServiceSécurisé.
Cette PR à pour but de sortir la logique de cette route dans un `service` permettant de simplifier la compréhension et les tests associés.
=> Création d'un service "ApresAuthentification"

src/mss.ts, src/routes/nonConnecte/routesNonConnecteOidc.js, src/routes/nonConnecte/routesNonConnectePage.js, src/utilisateur/serviceApresAuthentification.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js, test/routes/nonConnecte/routesNonConnectePage.spec.js, test/utilisateur/serviceApresAuthentification.spec.js
Le `serviceApresAuthentification` retourne un "ordre" qui est exécuté et qui remplace le mécanisme de la route OIDC existante.
=> Branche le service après authentification

src/adaptateurs/adaptateurGestionErreurSentry.js
Lorsqu'on accède à l'application directement sans passer par le waf
Dans le but de le court-circuiter
Alors on doit recevoir une erreur HTTP/401
Pourtant, on observe un code retour HTTP/200
C'était pas catastrophique parce que la réponse était quand même vide et le filtrage IP fonctionnel mais on retournait 200 au lieu de 401.
Comment vérifier, en démo :
```bash
#> curl -k https://domain.scw.clever-cloud.com -H 'Host: demo.monservicesecurise.cyber.gouv.fr' -I
HTTP/1.1 200 OK
```
Alors qu'on attendrait : 
```bash
#> curl -k https://domain.scw.clever-cloud.com -H 'Host: demo.monservicesecurise.cyber.gouv.fr' -I
HTTP/1.1 401 OK
```
=> Rejette les requêtes depuis des IPs invalides avec 401

src/routes/nonConnecte/routesNonConnecteOidc.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js
Lorsqu'on accédait à l'url de deconnexion et qu'il manquait le cookie, le service levait une exception et ne répondait pas, provoquant une erreur 503. On préfère retourner 401 dans ce cas.
=> Répond 401 si une déconnexion est tentée alors qu'il manque le cookie

src/modeles/mesureGenerale.js, src/moteurRegles.js, src/referentiel.js, src/routes/connecte/routesConnecteApiServiceActivitesMesure.js
Dans l'objectif d'optimiser le chargement du tableau de bord, on se penche sur les performances.
Pour créer un objet métier `Service`, MSS construit la liste des mesures de ce service.
Cette construction est très lente. On optimise donc de la manière suivante :
- Les `reduce` sont remplacés par des `Map` si possible, car plus performant
- La lecture des mesures du référentiel n'utilise plus `JSON.parse(JSON.stringify(...))`, au profit de `structuredClone`
- On s'attache à appeler la méthode `mesure(id)` plutot que `mesures()[id]` si nécessaire
- On réécrit le code qui rend les mesures indispensable, car il était trop complexe à comprendre
=> Optimise les performances de chargement des mesures

.env.template, src/adaptateurs/adaptateurEnvironnement.js, src/adaptateurs/adaptateurProtection.js, src/mss.ts, test/routes/testeurMSS.js
C'est la première IP dans la liste des IPs pour lesquelles on a forwardé qui était prise en compte pour le rate limit alors qu'on doit parcourir la liste de droite à gauche et prendre la première qui n'est pas un proxy.
On utilise trust proxy qui gère cela mieux que nous.
Il faut positionner la variable d'environnement `NB_REQUETES_TRUST_PROXY` avec le nombre de proxy sur le chemin.
=> Corrige rate-limit

src/moteurRegles.js, test/moteurRegles.spec.js
… s'il est déjà défini dans la mesure de base.
=> [CORRECTION] Conserve le statut "indispensable" d'une mesure

src/depots/depotDonneesUtilisateurs.js, test/depots/depotDonneesUtilisateurs.spec.js
... afin de ne pas créer d'erreur côté MPA, car les champs suivants sont obligatoires : nom, prenom, organisation, postes
=> [CORRECTION] Ne tente pas de mettre à jour MPA si le profil de l'utilisateur n'est pas complet

public/assets/styles/tiroir.css, svelte/lib/ui/Toaster.svelte
... afin d'éviter le chevauchement.
Le centre d'aide, qui provient de l'UI Kit, a un `z-index` de 1000.
Cela corrige l'issue #2149
=> [CORRECTION] Affiche le tiroir au-dessus du Centre d'aide

svelte/lib/tiroir/Tiroir.svelte
... car cela n'avait été fait que pour le tiroir "legacy".
=> Remonte le tiroir `Svelte` au-dessus du centre d'aide

src/bus/evenementServicesImportes.js, src/depotDonnees.js, src/depots/depotDonneesSuggestionsActions.js, src/erreurs.js, src/modeles/dossier.js, src/modeles/televersement/televersementServices.js, test/bus/evenementServicesImportes.spec.js, test/depots/depotDonneesSuggestionsActions.spec.js, test/modeles/dossier.spec.js, test/modeles/televersement/televersementServices.spec.js
... depuis un objet métier `TeleversementMetier`.
On ré-utilise toutes les méthodes métier qui existe actuellement, afin de garantir le fonctionnement standard de MSS.
=> [TÉLÉVERSEMENT] Ajoute la méthode qui créé les services

server.ts, src/mss.ts, src/routes/connecte/routesConnecteApi.js, src/routes/connecte/routesConnecteApiTeleversement.js, test/routes/connecte/routesConnecteApiTeleversement.spec.js, test/routes/testeurMSS.js
... afin d'importer "réellement" un service.
Cette route permet de convertir des objets de type `ServiceTeleverse` en vraies données de service, et de les persister.
=> [TÉLÉVERSEMENT] Ajoute la route de confirmation de téléversement

admin/consoleAdministration.js, src/adaptateurs/adaptateurPostgres.js, src/bus/abonnements/supprimeSuggestionsActions.js, src/bus/cablage.js, src/depotDonnees.js, src/depots/depotDonneesSuggestionsActions.js, test/bus/abonnements/supprimeSuggestionsActions.spec.js, test/depots/depotDonneesSuggestionsActions.spec.js
... en se câblant sur l'évènement dédié dans le bus.
> [!IMPORTANT]
> Il faut jouer la méthode "rattrapageSuppressionSuggestionsActions" dans la console admin au moment du déploiement.
=> [CORRECTION] Supprime les suggestions d'actions des services supprimés

src/adaptateurs/adaptateurEnvironnement.js
Lorsque la variable d'environnement NB_REQUETES_TRUST_PROXY est mal positionné alors on observe certains environnements qui disfonctionnent. Par exemple, impossible de s'authentifier sur l'env. de PR.
Afin de faciliter la détection d'erreur lorsqu'on a oublié de positionner cette variable, le service refuse de démarrer avec un message d'erreur explicite plutôt que d'utiliser une valeur par défaut.
=> Pas de valeur par défaut pour trust proxy

src/depots/depotDonneesServices.js, src/utilitaires/pMap.js
... car, pour chaque service, on effectue :
- une requête pour lire les contributeurs
- une requête pour lire les suggestions d'actions
Or, comme tous les services sont enrichis en même temps, toutes ces requêtes utilisent le pool de connexion de la base de données.
=> [CORRECTION] Utilise `pmap` pour limiter les promesses concurrentes lors de l'enrichissement d'un service

svelte/lib/rapportTeleversement/composants/LigneService.svelte
… dans le rapport de téléversement.
Cela permet de ne pas afficher un message "Invalid date".
=> [CORRECTION] Ne tente pas de créer un objet de Date si la chaine de caractère est vide

docker-compose.yml, src/bus/abonnements/consigneModificationMesureEnMasseDansJournal.js, src/bus/busEvenements.js, src/bus/cablage.js, src/bus/evenementMesureModifieeEnMasse.js, src/depots/depotDonneesServices.js, src/modeles/journalMSS/evenementMesureModifieeEnMasse.js, test/bus/abonnements/consigneModificationMesureEnMasseDansJournal.spec.js, test/bus/aides/busPourLesTests.js, test/depots/depotDonneesServices.spec.js, test/modeles/journalMSS/evenementMesureModifieeEnMasse.spec.js
Afin de pouvoir comptabiliser les utilisations de cette fonctionnalité dans metabase
=> Publie un évènement sur le bus lors de la modification en masse d'une mesure générale

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesServices.js, test/depots/depotDonneesServices.spec.js
... afin d'optimiser les performances. On préfère déléguer la jointure, pour un utilisateur, de ses autorisations de propriétaires, avec chaque contributeur et chaque suggestion d'action, pour chaque service.
... en faisant ainsi, on divise par 3 le temps de récupération des services.
=> [OPTIMISATION] Implémente une méthode spécifique pour lire tous les services d'un utilisateur

src/erreurs.js, src/modeles/mesureSpecifique.js, src/modeles/mesuresSpecifiques.js, src/modeles/service.js, tdd-todo/import_mesures_specifiques.md, test/modeles/mesureSpecifique.spec.js, test/modeles/mesuresSpecifiques.spec.js
Grâce à la manière dont sont construites les mesures spécifiques, il suffit juste de supprimer la propriété `idModele`.
De ce fait, les détails de la mesure spécifique sont déjà présents dans l'objet et la persistance suivant enregistrera donc cette mesure spécifique comme une mesure "autonome".
=> [MODELE MESURE SPÉCIFIQUE] Permet de détacher une mesure spécifique de son modèle

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depotDonnees.js, src/depots/depotDonneesModelesMesureSpecifique.js, src/depots/depotDonneesServices.js, src/erreurs.js, src/modeles/mesures.js, src/modeles/mesuresSpecifiques.js, src/modeles/service.js, tdd-todo/import_mesures_specifiques.md, test/depots/depotDonneesModelesMesureSpecifique.spec.js, test/modeles/mesureSpecifique.spec.js, test/modeles/mesuresSpecifiques.spec.js, test/modeles/service.spec.js
Afin de pouvoir correctement associer un modèle à des services, nous augmentons les capacités du dépôt de données.
Ce dernier est maintenant responsable de :
- vérifier la propriété du modèle
- vérifier les permissions de l'utilisateur sur ces services
- muter les services
- presister les services à jour
=> [MODÈLES MESURE SPECIFIQUE] Associe les mesures à leur modèle

docker-compose.yml, scripts/start.sh, scripts/tests.sh
Les scripts `scripts/start.sh` et `scripts/tests.sh` sont cassés (très probablement depuis [ce commit](https://github.com/betagouv/mon-service-securise/pull/2255/commits/cf6bb8fa015d373b19ce9684eed22cdebe63ba9b)).
Il semblerait que l'option `--build-arg` ne soit pas (plus ?) utilisable, et [qu'il faille spécifier les arguments via `build.args` dans le `docker-compose.yaml`](https://docs.docker.com/reference/compose-file/build/#args).
=> [SOIN] Répare les scripts de démarrage et de test

src/routes/connecte/routesConnecteApi.js, svelte/lib/listeMesures/ListeMesures.svelte, svelte/lib/listeMesures/kit/DescriptionCompleteMesure.svelte, svelte/lib/listeMesures/kit/ModaleDetailsMesure.svelte, svelte/lib/listeMesures/kit/tiroir/TiroirConfigurationMesure.svelte, svelte/lib/listeMesures/kit/tiroir/etapes/TroisiemeEtape.svelte, svelte/lib/listeMesures/listeMesures.api.ts, svelte/lib/listeMesures/listeMesures.d.ts, svelte/lib/modeles/modeleMesure.ts, svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte, svelte/lib/tableauDesMesures/stores/mesures.store.ts, svelte/lib/ui/SelectionStatut.svelte, svelte/lib/ui/types.d.ts, svelte/test/listeMesures/mesuresAvecServicesAssocies.store.spec.ts, svelte/test/tableauDesMesures/stores/volumetrieMesures.store.spec.ts, test/routes/connecte/routesConnecteApi.spec.js
... de la même manière que pour les mesures générales.
> [!TIP]
>  On voit émerger une forte ressemblance entre `MesureReferentiel` et `ModeleMesureSpecifique`.
> 
> Les `MesureReferentiel` sont en fait les mesures générales provenant du référentiel, qui peuvent donc être considérées comme des "Modèles" de mesure personnalisée.
> Nous cherchons donc à mutualiser et génériser l'utilisation de ces deux entités métier au sein de notre front, à suivre dans les prochaines PR.
=> [MODÈLES MESURE SPÉCIFIQUE] Affiche les services associés dans la modale

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/depots/depotDonneesModelesMesureSpecifique.js, src/depots/modelesMesureSpecifique/VerificationsUtilisateurPeutMuterModele.js, src/erreurs.js, src/modeles/mesuresSpecifiques.js, src/modeles/service.js, tdd-todo/import_mesures_specifiques.md, test/adaptateurs/adaptateurPostgres.spec.js, test/depots/depotDonneesModelesMesureSpecifique.spec.js, test/modeles/mesuresSpecifiques.spec.js
Dans ce cas de figure, on souhaite supprimer un modèle ainsi que toutes les mesures spécifiques associées.
Cette PR ajoute les méthodes nécessaires.
On ajoutera, dans la PR suivante, la route ainsi que le front.
=> Supprime un modèle de mesure et toutes les mesures associées

src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/adaptateurs/adaptateurTeleversementModelesMesureSpecifique.xls.js, src/depotDonnees.js, src/depots/depotDonneesTeleversementModelesMesureSpecifique.js, src/modeles/televersement/serviceTeleverse.js, src/modeles/televersement/televersementModelesMesureSpecifique.js, src/referentiel.js, src/routes/connecte/routesConnecteApiTeleversement.modelesMesureSpecifique.js, tdd-todo/televersement_mesures_specifiques.md, test/modeles/televersement/televersementModelesMesureSpecifique.spec.js, test/routes/connecte/routesConnecteApiTeleversement.modelesMesureSpecifique.spec.js
Cette PR pose les bases pour que `GET /api/televersement/modelesMesureSpecifique` renvoie une payload exploitable par le front pour montrer le rapport de téléversement.
On s'inspire de l'architecture du téléversement de Service, mais en plus simple : `TeleversementModelesMesureSpecifique` n'a pas du tout d'héritage, et pour le moment fait la validation elle-même. Ça tient.
Il manque le contrôle sur les noms de mesure non doublonnés : c'est tracé dans le `.md` de TDD.
Pour tester au runtime :
- téléverser un fichier de mesures
- visiter la page `/api/televersement/modelesMesureSpecifique` pour récupérer le `rapportDetaille()` en `JSON` 👇
=> [Téléversement] Début du calcul du rapport de téléversement

svelte/lib/tableauDeBord/televersementServices/RapportTeleversementServices.svelte
Depuis un refacto précédent, la carte « 1 service valide » était toujours affichée même avec un fichier téléversé ne contenant que des erreurs..
Exemple du bug en PROD où un fichier avec seulement 2 lignes donne cet affichage 👇 
Après correction 👇
=> [CORRECTION] Cesse d'afficher systématiquement « 1 service valide »

src/modeles/journalMSS/erreurs.js, src/modeles/journalMSS/evenement.js, src/modeles/journalMSS/evenementCollaboratifServiceModifie.js, src/modeles/journalMSS/evenementCompletudeServiceModifiee.js, src/modeles/journalMSS/evenementConnexionUtilisateur.js, src/modeles/journalMSS/evenementModelesMesureSpecifiqueImportes.js, src/modeles/journalMSS/evenementNouveauServiceCree.js, src/modeles/journalMSS/evenementNouvelUtilisateurInscrit.js, src/modeles/journalMSS/evenementNouvelleHomologationCreee.js, src/modeles/journalMSS/evenementRetourUtilisateurMesure.js, src/modeles/journalMSS/evenementServiceSupprime.js, src/modeles/journalMSS/evenementServicesImportes.js, test/modeles/journalMSS/evenementCollaboratifServiceModifie.spec.js, test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js, test/modeles/journalMSS/evenementConnexionUtilisateur.spec.js, test/modeles/journalMSS/evenementNouveauServiceCree.spec.js, test/modeles/journalMSS/evenementNouvelUtilisateurInscrit.spec.js, test/modeles/journalMSS/evenementNouvelleHomologationCreee.spec.js, test/modeles/journalMSS/evenementRetourUtilisateurMesure.spec.js, test/modeles/journalMSS/evenementServiceSupprime.spec.js, test/modeles/journalMSS/evenementServicesImportes.spec.js
On veut que chaque événement de journal puisse écrire quelque chose comme :
```js
Evenement.valide(donnees, ['idService', 'autorisations']);
```
=> [SOIN] Factorise la validation de données dans les événement du journal

src/routes/connecte/routesConnecteApi.js, src/routes/connecte/routesConnecteApiTeleversement.modelesMesureSpecifique.js, svelte/lib/listeMesures/kit/TableauSelectionServices.svelte, svelte/lib/listeMesures/mesureSpecifique/ServicesAssociesModeleMesureSpecifique.svelte, svelte/lib/listeMesures/mesureSpecifique/modification/ConfirmationModificationModeleMesureSpecifique.svelte, svelte/lib/listeMesures/servicesAssocies/TableauServicesAssocies.svelte, svelte/lib/listeMesures/televersement/LigneDeRapport.svelte, svelte/lib/tableauDesMesures/tableauDesMesures.api.ts, svelte/lib/tableauDesMesures/tableauDesMesures.d.ts, test/routes/connecte/routesConnecteApi.spec.js, test/routes/connecte/routesConnecteApiTeleversement.modelesMesureSpecifique.spec.js
Décode les données de mesure spécifique côté API pour éviter de dupliquer le décode partout côté front
=> Corrige l'encodage des modèles de mesure spécifique

src/adaptateurs/adaptateurPostgres.js
Dans le cas où on arrive dans `associeModelesMesureSpecifiqueAuService()` par une duplication de service qui pointe un service n'ayant aucune mesure spécifique associée à un modèle… on déclenchait `associeModelesMesureSpecifiqueAuService()` avec un tableau vide en entrée.
Ce tableau vide, côté Postgres cause une erreur "Error: The query is empty".
On protège, pour ne pas crasher.
=> [CORRECTION] N'essaie pas d'insérer si aucun modèle n'est passé

svelte/lib/listeMesures/ListeMesures.svelte
...sur les lignes de mesures générales non associées. En effet, on ne peut ouvrir le tiroir de configuration que si au moins un service est associé à cette mesure
=> [CORRECTION] Désactive le clic

src/mss.ts, src/routes/connecte/routesConnecteApi.js, src/routes/connecte/routesConnectePage.js, svelte/lib/inscription/Inscription.svelte, svelte/lib/inscription/inscription.api.ts, svelte/lib/inscription/inscription.d.ts, test/routes/connecte/routesConnecteApi.spec.js
On souhaite que la finalisation d'inscription d'un utilisateur (via PUT /utilisateur) continue de prendre en compte le nom/prénom et n'utilise pas de token passé dans le corps de la requête (il est de toute façon présent dans la session, car c'est une route connectée).
Avant cette PR, la mise à jour de profil utilisateur ne fonctionne plus car le endpoint `PUT /utilisateur` s'attend, à tord, de recevoir un token dans le corps de la requête suite à https://github.com/betagouv/mon-service-securise/pull/2269 et https://github.com/betagouv/mon-service-securise/pull/2276
Bonus : j'ai remarqué que des propriétés comme "proprietesAtomiquesRequises" étaient présentes dans la payload de mise à jour de profil, car elles étaient présentes dans l'objet `donnees-profil` sur la page profil, j'ai donc …
=> [CORRECTION] Permet la mise à jour de nom/prénom de l'utilisateur connecté

package-lock.json, package.json, src/mss.ts, test/aides/verifieFichierServi.js, test/mocks/middleware.js, test/mss.spec.js, test/routes/connecte/routesConnecteApi.spec.js, test/routes/connecte/routesConnecteApiNotifications.spec.js, test/routes/connecte/routesConnecteApiService.spec.js, test/routes/connecte/routesConnecteApiServiceActivitesMesure.spec.js, test/routes/connecte/routesConnecteApiServicePdf.spec.js, test/routes/connecte/routesConnecteApiTeleversement.modelesMesureSpecifique.spec.js, test/routes/connecte/routesConnecteApiTeleversement.services.spec.js, test/routes/connecte/routesConnecteApiVisiteGuidee.spec.js, test/routes/connecte/routesConnecteOidc.spec.js, test/routes/connecte/routesConnectePage.spec.js, test/routes/connecte/routesConnectePageService.spec.js, test/routes/nonConnecte/routesNonConnecteApi.spec.js, test/routes/nonConnecte/routesNonConnecteApiBibliotheques.spec.js, test/routes/nonConnecte/routesNonConnecteApiStyles.spec.js, test/routes/nonConnecte/routesNonConnecteOidc.spec.js, test/routes/nonConnecte/routesNonConnectePage.spec.js, test/routes/testeurMSS.js
... afin de tester nos routes dans une configuration "in memory".
Cela permet de faciliter la transition vers Typescript, Vitest, etc...
=> [TESTS] Ajout de `supertest`

src/http/middleware.js, test/depotDonnees.spec.js, test/depots/depotDonneesServices.spec.js, test/depots/depotDonneesUtilisateurs.spec.js, test/http/middleware.spec.js, test/modeles/descriptionService.spec.js, test/modeles/etapes/decision.spec.js, test/modeles/journalMSS/evenementCguAcceptees.spec.js, test/modeles/journalMSS/evenementCollaboratifServiceModifie.spec.js, test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js, test/modeles/journalMSS/evenementConnexionUtilisateur.spec.js, test/modeles/journalMSS/evenementNouveauServiceCree.spec.js, test/modeles/journalMSS/evenementNouvelUtilisateurInscrit.spec.js, test/modeles/journalMSS/evenementProfilUtilisateurModifie.spec.js, test/modeles/journalMSS/evenementRetourUtilisateurMesure.spec.js, test/modeles/journalMSS/evenementServiceRattacheAPrestataire.spec.js, test/modeles/journalMSS/evenementServiceSupprime.spec.js, test/modeles/mesure.spec.js, test/modeles/mesureGenerale.spec.js, test/modeles/mesureSpecifique.spec.js, test/modeles/risque.spec.js, test/modeles/risqueGeneral.spec.js, test/modeles/risqueSpecifique.spec.js, test/modeles/utilisateur.spec.js
On prépare l'arrivée de `Vitest`, qui ne supporte pas `done()`.
Cette PR supprime toutes les utilisations.
=> Suppression de toutes les utilisations de `done()`

donneesReferentiel.js, migrations/20250902085307_ajoutColonneVersionService.js, src/adaptateurs/adaptateurPersistanceMemoire.js, src/adaptateurs/adaptateurPostgres.js, src/bus/abonnements/consigneNouveauServiceDansJournal.js, src/depots/depotDonneesServices.js, src/modeles/journalMSS/evenementNouveauServiceCree.js, src/modeles/service.js, src/referentiel.js, tdd/les_services_actuels_sont_des_v1.md, test/adaptateurs/adaptateurPostgres.spec.js, test/constructeurs/constructeurService.js, test/depots/depotDonneesServices.spec.js, test/modeles/journalMSS/evenementNouveauServiceCree.spec.js, test/modeles/service.spec.js
... afin de préparer le terrain pour l'apparition de la version V2.
Cette PR permet de fixer la version à "v1" sur tous les services existants, et les nouveaux services créés.
=> Ajoute la version "v1" par défaut sur les Services

src/http/validePayloads.ts, src/routes/connecte/routesConnecteApiBrouillonService.ts
… pour que `requete.body` soit typé dans la route qui utilise `valideBody()`. 
Inspiration : https://jakerobins.com/blog/using-zod-to-provide-typesafe-express-requests
Cette PR permet d'avoir une `requete` typée sans dupliquer l'appel à `zod` 👇
=> Type la `Request` renvoyée par `valideBody`

src/modeles/base.ts, src/modeles/descriptionServiceV2.ts, src/modeles/informationsService.ts, src/referentiel.interface.ts, test/modeles/base.spec.ts
Afin de commencer à convertir notre code en Typescript, on isole les classes les plus importantes, qui nous permettront d'obtenir du typage plus précis.
=> Conversion de la classe "Base" en Typescript

svelte/lib/creationV2/etapes/etape1/QuestionStatutDeploiement.svelte
=> [CORRECTION] Assigne `estComplete` en mode "réactif", afin de l'évaluer au montage

svelte/lib/creationV2/etapes/etape1/QuestionPointsAcces.svelte, svelte/lib/creationV2/etapes/etape3/QuestionCategoriesDonneesTraitees.svelte
...après test utilisateur, les utilisateurs ont été perturbés de ne pas pouvoir passer au suivant si un champ est vide. On filtre les champs vides avant d'envoyer la donnée au back
=> Enlève l'obligation de remplissage pour les listes de champs texte côté front

svelte/lib/creationV2/CreationV2.svelte
On a constaté que sur une question dont la maj est envoyée au blur du champ et que ce blur est entraîné par le click sur le bouton "suivant", l'exécution de la fonction `suivant()` pouvait finir avant la ligne qui suit, et donc l'évaluation de "est-ce que l'étape courante est une étape avec avance rapide ?" porte dans ce cas sur la question suivante et non la question courante. Cela exécutait alors deux fois la fonction `suivant()`.
ex : Q1 a un champ texte et un bouton suivant, et pas d'avance rapide Q2 a une avance rapide
Q3 existe
-> remplir le champ texte de Q1 et sortir du champ en cliquant sur le bouton suivant entraîne une race condition entre `suivant` et `metsAJourBrouillonService`, les deux ayant lieu en même temps dans un ordre indéterminé.
-> Q1 est rempli, Q2 n'est pas rempli …
=> Evite de sauter une question à cause d'une race condition
