- Dockerfile
Problème de compatibilité entre Sqlite3 et node 17.
(note : dans une modification future, retirer Sqlite3 car non utilisé)
> Force la version de node à 16

- server.js
- src/adaptateurs/adaptateurChiffrement.js
- src/middleware.js
- src/mss.js
- src/vues/homologation/decision.pug
- test/middleware.spec.js
- test/mss.spec.js
[CORRECTION] Affiche correctement  barres de statistiques mesures
Le header Content-Security-Policy forçait la directive `style-src` à `'self'` (héritée de `default-src`), ce qui empêchait la prise en compte du style créé à la volée pour les barres de statistiques. L'utilisation d'un nonce permet de régler ce problème.
⚠️  LIMITATION : pour une raison inconnue, la génération du PDF sous Firefox continue de ne pas prendre en compte le style créé à la volée. Cela fonctionne correctement avec Safari et Chrome. L'ajout d'une directive `script-src 'strict-dynamic'` ne semble pas aider. [Un ticket d'incident a été ouvert](https://github.com/niklasvh/html2canvas/issues/2760).
> Import pdf

- donneesReferentiel.js
- src/vues/fragments/formulaireInformationsGenerales.pug
- Renommer le titre du block
- Renommer les choix selon les nouveaux textes
- Ajouter Signature électronique qui n'est pas présent
J'ai laissé intentionnellement _Autres fonctionnalités permettant des échanges de données_ car la possibilité d'ajout manuellement n'est pas encore là
Le seuil critique de Signature électronique reste à définir
> Renommer le choix des principales fonctionnalités de service

- package-lock.json
Dans package-lock npm était à 7 alors qu'il est à 8 dans package.json
> Montée de version de npm

- donneesReferentiel.js
- jeuDonnees.js
- migrations/20211209094517_renommageColonneNatureService.js
- src/modeles/homologation.js
- src/modeles/informationsGenerales.js
- src/mss.js
- src/referentiel.js
- src/vues/fragments/formulaireInformationsGenerales.pug
- src/vues/homologation/decision.pug
- test/modeles/homologation.spec.js
- test/modeles/informationsGenerales.spec.js
- test/mss.spec.js
- test/referentiel.spec.js
Dans la page informations générales, la question _Quelle est la nature du service numérique_ devient _Type de service numérique_
~~Je n'ai pas changé volontairement les types persistés~~
> Renommer nature du service en type de service dans la page informations générales

- donneesReferentiel.js
- src/vues/fragments/formulaireInformationsGenerales.pug
Dans la page Informations générales
Dans la question relative à la provenance du service
-> le titre est reformulé
-> les choix sont reformulés
-> les exemples illustrants les choix sont supprimés
> Renommage provenance du service

- migrations/20211206151020_copieColonnePresentationDansInformationsGenerales.js
- src/depotDonnees.js
- src/modeles/informationsGenerales.js
- src/mss.js
- test/depotDonnees.spec.js
- test/modeles/informationsGenerales.spec.js
- test/mss.spec.js
Dans la page _Caractéristiques complémentaires_ 
quand on saisit une **présentation**
Les données sont persistées avec Informations générales
-> migration de données pour les anciennes présentations
-> ~nouvel aiguillage des présentations~
> Déplacement de la présentation du service dans les propriétés d'informations générales

- donneesReferentiel.js
- migrations/20211210164225_modifieValeurDelaiAvantImpactCritique.js
- src/vues/fragments/formulaireInformationsGenerales.pug
Dans la page Informations générales,
La question _Au bout de combien de temps le dysfonctionnement grave de votre service aura-t-il un impact critique pour votre organisation ou pour les usagers ?_ évolue 
- il y a seulement 3 choix
- le texte est différent
-> ce dev entraine une migration de données incluse
> Modification question temps dysfonctionnement

- donneesReferentiel.js
- migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
Dans la page Informations générales,
nous avons mis à disposition une possibilité pour renseigner les _autres fonctionnalités_
Le choix _Autres fonctionnalités permettant des échanges de données_ va disparaitre
À la place il y aura un champ dans _autres fonctionnalités_ avec la valeur _Autres fonctionnalités permettant des échanges de données_
> Suppression de l'ancienne fonctionnalité Autres

- src/depotDonnees.js
- src/modeles/caracteristiquesComplementaires.js
- src/modeles/informationsGenerales.js
- src/mss.js
- src/vues/fragments/formulaireInformationsGenerales.pug
- src/vues/homologation/caracteristiquesComplementaires.pug
- test/depotDonnees.spec.js
- test/modeles/caracteristiquesComplementaires.spec.js
- test/modeles/informationsGenerales.spec.js
- test/mss.spec.js
La présentation du service passe de la page **Caractéristiques complémentaires** à **Informations générales**
-> La persistance s'effectue toujours dans les 2 objets **informationsGenerales** et **caracteristiquesComplementaires**
> Déplacement de la présentation dans la page informations génerales

- migrations/20211229123645_creationTableAcces.js
- migrations/20211229141624_renommeTableAccesEnAutorisations.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/modeles/autorisationCreateur.js
- src/modeles/autorisations/autorisationCreateur.js
- src/modeles/autorisations/fabriqueAutorisation.js
- test/depotDonnees.spec.js
- test/mss.spec.js
Cette PR est essentiellement une préparation de l'implémentation du mode collaboratif. Pour l'instant, à chaque création d'homologation, en plus de rattacher l'utilisateur à l'homologation, on crée un enregistrement dans la table `autorisations`.
La suite sera :
- migration : ajouter une autorisation de type `'createur'` pour chaque homologation existante en base
- transfert du code exploitant la relation directe entre une homologation et un utilisateur
- suppression de la colonne `Homologation.idUtilisateur`
… Puis :
- ajouter un collaborateur existant
- accéder à des homologations avec le rôle « collaborateur »
- interdire aux collaborateurs d'inviter d'autres collaborateurs
> Introduction notion métier d'« autorisation »

- migrations/20220103141419_dupliqueLienHomologationUtilisateurDansAutorisation.js
Cette PR fait suite à #40
La suite sera :
- transfert du code exploitant la relation directe entre une homologation et un utilisateur
- suppression de la colonne Homologation.idUtilisateur
… Puis :
- ajouter un collaborateur existant
- accéder à des homologations avec le rôle « collaborateur »
- interdire aux collaborateurs d'inviter d'autres collaborateurs
> [MIGRATION] Ajout autorisation de type `createur` pour chaque homologation existante en base

- src/depotDonnees.js
- src/modeles/informationsGenerales.js
- src/mss.js
- test/depotDonnees.spec.js
- test/modeles/informationsGenerales.spec.js
- test/mss.spec.js
Etape 1 du déplacement de **Localisation des données** dans Informations générales
Dans la page Caractéristiques complémentaires
Quand on sélectionne une localisation pour les données
Celle ci est persistée dans `caracteristiquesComplementaires` et dans `informationsGenerales`
> Ecriture de la localisation des données dans les informations générales

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/middleware.js
- test/depotDonnees.spec.js
- test/middleware.spec.js
Cette PR fait suite à #50
La suite sera :
- suppression de la colonne Homologation.idUtilisateur
… Puis :
- ajouter un collaborateur existant
- accéder à des homologations avec le rôle « collaborateur »
- interdire aux collaborateurs d'inviter d'autres collaborateurs
> Utilise les autorisations, plutôt que `homologation.idUtilisateur`

- migrations/20220111092352_conversionEmailsEnMinuscules.js
- src/mss.js
- test/mss.spec.js
Cela permet de ne pas avoir à tenir compte de la casse dans les adresses mail qui sont saisies pour les inscription.
> Convertis login en minuscules

- src/vues/fragments/formulaireInformationsGenerales.pug
Dans la page informations générales,
le titre et les textes autour subissent un renommage
> Renommer le titre d'informations générales et le texte autour

- src/vues/fragments/formulaireInformationsGenerales.pug
Dans la page description du service,
le bouton **Enregistrer** devient **Enregistrer et revenir à l'espace personnel**
> Renommer le bouton enregistrer de description du service

- src/depotDonnees.js
- src/modeles/descriptionService.js
- src/modeles/homologation.js
- test/depotDonnees.spec.js
Quand on crée ou modifie une homologation,
Les données dites informations générales sont persistées dans `informationsGenerales` ainsi que dans `descriptionService`
> Réplication de la persistance des données de description du service

- migrations/20220110160004_dupliqueInformationsGeneralesDansDescriptionService.js
Note : ce dev ce trouvera après https://github.com/betagouv/mon-service-securise/pull/62
Dans la persistance nous souhaitons que la colonne `descriptionService` soit la copie de `informationsGenerales`
> Duplications des informations générales en description du service

- src/middleware.js
- src/mss.js
- test/middleware.spec.js
- test/mss.spec.js
dans les appels de créations d'homologations et de mises à jours des informations générales des homologations,
on devait aseptiser plusieurs listes.
Ce dev rassemble les appels en un unique middleware
> Factorisation de l'aseptisation des listes en un seul middleware

- src/modeles/homologation.js
- src/modeles/informationsGenerales.js
- src/vues/homologation/decision.pug
- test/modeles/homologation.spec.js
- test/modeles/informationsGenerales.spec.js
Cette partie du code est devenue obsolète suite au changement de l'algorithme de criticité
> [CORRECTION] Supprime avertissement seuil criticité trop élevé dans dossier homologation

- src/depotDonnees.js
- src/mss.js
- test/depotDonnees.spec.js
- test/mss.spec.js
La présentation du service ne se trouve plus dans la page caractéristiques complémentaires et la persistance se fait en double dans `infonrmationsGenerales` et 'caracteristiquesComplementaires`
Ce dev propose de stopper la persistance dans `caracrteristiquesComplementaires` qui n'est plus utilisée
> Arrêt de la persistance de la présentation dans les caractéristiques complémentaire

- src/depotDonnees.js
- src/mss.js
- test/depotDonnees.spec.js
- test/mss.spec.js
La localisation des données ne se trouve plus dans la page caractéristiques complémentaires et la persistance se fait en double dans `informationsGenerales` et `caracteristiquesComplementaires`. Ce dev propose de stopper la persistance dans `caracteristiquesComplementaires` qui n'est plus utilisée.
> Arrêt de la persistance de la localisation dans les caractéristiques complémentaire

- public/homologation/formulaireInformationsGenerales.js
- src/modeles/donneesSensiblesSpecifiques.js
- src/modeles/informationsGenerales.js
- src/mss.js
- src/vues/fragments/formulaireInformationsGenerales.pug
- test/modeles/donneesSensiblesSpecifiques.spec.js
- test/modeles/informationsGenerales.spec.js
- test/mss.spec.js
Dans la page Informations générales
En dessous de la sélection des _Données à caractère personnel et autres données sensibles stockées par le service_
Ajout d'une possibilité de renseigner manuellement d'autres données sensibles
> Ajout manuel des données sensibles

- src/depotDonnees.js
- src/modeles/homologation.js
- src/mss.js
- src/vues/fragments/formulaireInformationsGenerales.pug
- test/depotDonnees.spec.js
- test/modeles/homologation.spec.js
- test/mss.spec.js
Remplacement dans le modèle de `informationsGenerales` et `InformationsGenerales` par `descriptionService` et `DescriptionService`
Il reste des _informationsGenerales_ dans 
- les vues et les scripts publiques (prochaine PR)
- l'adaptateur de persistance et l'adaptateur postgres
- dans les scripts de migrations (c'est normal)
- partout où c'est utilisé pour la double persistance (pour après)
> Changement informations générales pour description service dans le modèle

- src/modeles/avisExpertCyber.js
- test/modeles/avisExpertCyber.spec.js
- Rends le commentaire facultatif
- N'exige pas de date de renouvellement d'homologation si avis défavorable
> Revoie calcul statut saisie avis expert cyber

- migrations/20220118162341_suppressionColonneHomologationsIdUtilisateur.js
- src/depotDonnees.js
- src/modeles/homologation.js
- src/mss.js
- test/depotDonnees.spec.js
- test/mss.spec.js
… Dans le code et en base.
Cette PR fait suite à la #68 
La suite sera :
- ajouter un collaborateur existant
- accéder à des homologations avec le rôle « collaborateur »
- interdire aux collaborateurs d'inviter d'autres collaborateurs
> Suppression attribut `homologation.idUtilisateur`

- src/modeles/homologation.js
- src/vues/fragments/diagnostics.pug
Actuellement, si aucune information sur les mesures n'est saisie, la pastille
rouge ou verte ne s'affiche pas dans le document d'homologation.
Ce commit corrige le problème.
> [CORRECTION] Affiche correctement avis expert dans document homologation

- public/assets/styles/espacePersonnel.css
- public/espacePersonnel.js
- public/modules/elementsDom/homologations.js
- src/vues/espacePersonnel.pug
Jusqu'à présent, la carte « nouvelle homologation » s'affichait avant que les cartes homologation soient peuplées avec les données récupérées du serveur.
Cette PR assure qu'on n'affiche la carte « nouvelle homologation » qu'une fois les autres cartes affichées.
> Affichage carte « nouvelle homologation »

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- test/depotDonnees.spec.js
Quand on souhaite récupérer des homologations avec un nom d'homologation (cas : quand on crée une homologation pour vérifier si le nom existe déjà) on utilise `descriptionService` à la place de `informationsGenerales`
> Changement pour description service dans l'appel pour récupérer les homologations

- src/modeles/caracteristiquesComplementaires.js
- src/modeles/homologation.js
- test/modeles/caracteristiquesComplementaires.spec.js
- test/modeles/homologation.spec.js
Après le déplacement de la présentation et de la localisation des données dans description du service,
il était bon de retirer les propriétés non utilisées dans les caractéristiques complémentaires
Note : correction de la récupération de la présentation dans homologation
> Nettoyage des propriétés non utilisées des caractéristiques complémentaires

- consoleAdministration.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/erreurs.js
- test/depotDonnees.spec.js
Note :
- quand on aura introduit le rôle « collaborateur », il ne faudra transférer que
les autorisations de type « créateur »
> Permets le transfert d'autorisations depuis une console d'administration

- public/assets/styles/homologation/descriptionService.css
- src/vues/fragments/elementsAjoutables.pug
- src/vues/fragments/formulaireDescriptionService.pug
Dans la page description du service, au niveau des points d'accès
nous souhaitons qu'une zone de saisie vide apparaisse quand il n'y a pas de points d'accès
- j'ai corrigé une erreur sur l'affichage du label du lien `ajouter`
- j'ai arrangé le style car la zone de saisie était collé au titre _Accès au service numérique_
> Visibilité de la zone de saisie vide des points d'accès

- migrations/20220118145349_supprimeColonnePresentationDeCaracteristiques.js
Dans la persistance, 
On supprime la présentation des caractéristiques complémentaires car elle n'est plus utilisée
> Suppression la présentation des caractéristiques complémentaires

- migrations/20220119083758_supprimeColonneLocalisationDonneesDeCaracteristiques.js
Dans la persistance,
On supprime la localisation des données des caractéristiques complémentaires car elle n'est plus utilisée
> Suppression la localisation des données des caractéristiques complémentaires

- donneesReferentiel.js
Dans la page de synthèse à la place de **Avis de l'expert cyber** on voit **Avis sur le dossier**
NOTE IMPORTANTE : l'url reste `/avisExpertCyber` et tout le modèle de données vit avec `avisExpertCyber`
> Modification du texte du lien Avis sur le dossier dans la synthèse

- public/assets/styles/homologation/partiesPrenantes.css
- src/modeles/homologation.js
- src/modeles/partiesPrenantes.js
- src/vues/fragments/inputIdentite.pug
- src/vues/homologation/partiesPrenantes.pug
- test/modeles/homologation.spec.js
- test/modeles/partiesPrenantes.spec.js
Dans la page _Parties prenantes_
- Les acteurs qui étaient en 2 groupes sont dans un seul
- Les descriptions et les _je suis cette personne_ disparaissent
- Quelques textes sont changés
- On ajoute un nouvel acteur **le(a) délégué(e) à la protection des données**
_Note Bonus : comment intègre-t-on ce nouvel acteur dans la Décision ?_
> Modification des acteurs de l'homologations

- public/assets/styles/homologation/partiesPrenantes.css
Dans la page parties prenantes
le cadre n'était pas conforme aux autres
> Correction du style du cadre des saisies d'identités

- donneesReferentiel.js
- migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
Dans la page description du service,
dans la partie _Données à caractère personnel et autres données sensibles stockées par le service_,
la case à cocher **Autre données sensibles** est supprimé et à la place on intègre **Autre données sensibles** dans une zone de saisie de données sensibles
> Suppression du choix autres données sensibles

- public/assets/styles/homologation/descriptionService.css
- public/assets/styles/homologation/formulaire.css
- public/homologation/partiesPrenantes.js
- public/modules/brancheElementsAjoutables.js
- src/modeles/acteurHomologation.js
- src/modeles/acteursHomologation.js
- src/modeles/partiesPrenantes.js
- src/routes/routesApiHomologation.js
- src/vues/fragments/elementsAjoutables/elementsAjoutables.pug
- src/vues/fragments/elementsAjoutables/elementsAjoutablesActeurHomologation.pug
- src/vues/homologation/partiesPrenantes.pug
- test/modeles/acteurHomologation.spec.js
- test/modeles/acteursHomologation.spec.js
- test/modeles/partiesPrenantes.spec.js
- test/mss.spec.js
Dans la page parties prenantes,
en bas de la liste des acteurs de l'homologation,
nous souhaitons avoir une possibilité d'ajouter des acteurs supplémentaires
MISE À JOUR avec des labels
> Nouvel acteur homologation

- public/assets/styles/formulaire.css
Dans le navigateur internet au renard flamboyant,
les zones de saisies libres (text area) ont une taille de font plus grande que sur le navigateur chrome.
Après modification :
> Ajuste la taille du texte dans les zones de saisies libres pour firefox

- migrations/20220121103422_copieColonneHebergeurDansPartiesPrenantes.js
Dans les caractéristiques complémentaires, il y a le nom de l'hébergeur.
Nous voulons dans l'avenir que ce nom ainsi que d'autre informations concernant l'hébergement se trouve dans les parties prenantes
-> étape n°2 : duplication des données persistées
> Migration de l'hébergeur vers l'hébergement des parties prenantes

- src/vues/fragments/formulaireDescriptionService.pug
Dans la page Description du service on pouvait voir dans la console des outils du développeur une erreur
La raison est l'oublie de retrait de l'importation d'une feuille de style après la suppression de cette dernière
> Retrait de la déclaration d'une feuille de style supprimée

- src/depotDonnees.js
- src/modeles/partiesPrenantes/developpementFourniture.js
- src/modeles/partiesPrenantes/fabriquePartiePrenante.js
- src/routes/routesApiHomologation.js
- test/depotDonnees.spec.js
- test/modeles/partiesPrenantes/developpementFourniture.spec.js
- test/modeles/partiesPrenantes/fabriquePartiePrenante.spec.js
- test/mss.spec.js
Dans la page caractéristiques complémentaires,
Quand on enregistre une **structure ayant développé le service numérique**
Les données doivent aussi être sauvegardées dans les parties prenantes
> Persistance du développement / fourniture dans les parties prenantes

- src/vues/fragments/formulaireDescriptionService.pug
Dans la page Description du service,
nous souhaitons modifier le texte de la description apparaissant en dessous du titre
> Modification du texte de la description dans la page description du service

- public/assets/styles/homologation/partiesPrenantes.css
- public/homologation/avisExpertCyber.js
- public/homologation/caracteristiquesComplementaires.js
- public/homologation/mesures.js
- public/homologation/partiesPrenantes.js
- public/homologation/risques.js
- public/modules/manipulationTexte.mjs
- public/modules/parametres.js
- public/modules/parametres.mjs
- public/modules/soumetsHomologation.js
- public/utilisateur/edition.js
- src/depotDonnees.js
- src/modeles/caracteristiquesComplementaires.js
- src/modeles/partiesPrenantes/partiesPrenantes.js
- src/modeles/partiesPrenantes/typePartiePrenante.js
- src/routes/routesApiHomologation.js
- src/vues/fragments/inputIdentite.pug
- src/vues/fragments/inputPartiePrenante.pug
- src/vues/homologation/caracteristiquesComplementaires.pug
- src/vues/homologation/partiesPrenantes.pug
- test/depotDonnees.spec.js
- test/modeles/caracteristiquesComplementaires.spec.js
- test/modeles/partiesPrenantes/partiesPrenantes.spec.js
- test/modeles/partiesPrenantes/typePartiePrenante.spec.js
- test/mss.spec.js
Dans la page parties prenantes nous pouvons ajouter les informations d'hébergement.
Dans la page Caractéristique complémentaires, il n'y a plus la possibilité de voir ou modifier le nom de l'hébergeur.
Note : les données de l'hébergeur restent sauvegarder dans les caractéristiques complémentaires
> Déplacement de la saisie de l'hébergement

- src/depotDonnees.js
- test/depotDonnees.spec.js
Quand ont enregistre les caractéristique complémentaires vide,
dans la page de synthèse les parties prenantes (vide) apparaissent _à compléter_
> Correction de la mise à jour du développement fourniture vide

- src/depotDonnees.js
- src/modeles/homologation.js
- src/modeles/rolesResponsabilites.js
- test/depotDonnees.spec.js
Dans l'objectif de renommer **parties prenantes** en **rôles et responsabilités**,
La 1° étape est de dupliquer la persistance
> Double enregistrement des parties prenantes en rôles et responsabilités

- public/assets/images/pastille_bleu_anssi.svg
- public/assets/styles/espacePersonnel.css
- public/espacePersonnel.js
- public/modules/elementsDom/homologations.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/modeles/homologation.js
- src/modeles/utilisateur.js
- test/depotDonnees.spec.js
- test/modeles/homologation.spec.js
- test/modeles/utilisateur.spec.js
- Récupération des contributeurs en base
- Affichage des initiales dans une pastille bleue
- Affichage d'un tooltip avec prénom et nom complets
- Ajout dans le tooltip d'une mention « (vous) » quand il s'agit de l'utilisateur courant
Note : pour tester l'affichage, il faut actuellement ajouter directement en base de données une autorisation sur le format suivant :
```javascript
{
id: [uuid],
donnees: {
idUtilisateur: [identifiant de l'utilisateur contributeur],
idHomologation: [identifiant de l'homologation à partager],
type: 'contributeur',
},
}
```
> Affichage initiales contributeurs

- public/assets/styles/espacePersonnel.css
- Pour l'instant on ne peut pas ajouter de contributeurs, donc on n'affiche pas le texte « contributeurs » (pour l'instant)
- On centre les éléments de la carte « nouvelle homologation »
> Affiche correctement les cartes homologation dans Espace Personnel

- migrations/20220216134942_dupliquePartiesPrenantesDansRolesResponsabilites.js
2ieme étape pour passer de parties prenantes à rôles et responsabilités : la copie des données en base
> Migration des parties prenantes dans les rôles et responsabilités

- public/homologation/partiesPrenantes.js
- public/modules/parametres.mjs
- src/depotDonnees.js
- src/modeles/caracteristiquesComplementaires.js
- src/modeles/partiesPrenantes/partiesPrenantes.js
- src/modeles/partiesPrenantes/typePartiePrenante.js
- src/routes/routesApiHomologation.js
- src/vues/homologation/caracteristiquesComplementaires.pug
- src/vues/homologation/partiesPrenantes.pug
- test/depotDonnees.spec.js
- test/modeles/caracteristiquesComplementaires.spec.js
- test/modeles/partiesPrenantes/partiesPrenantes.spec.js
- test/modeles/partiesPrenantes/typePartiePrenante.spec.js
- test/routes/routesApiHomologation.spec.js
La « saisie du développement / fourniture de service » anciennement appelée « structure ayant développé le service » se fait dans la page parties prenantes et plus dans caractéristiques complémentaires
note : les noms des structures ayant développé sont toujours persistés avec les caractéristiques complémentaires
> Déplacement du développement / fourniture de service dans les parties prenantes

- src/depotDonnees.js
- src/modeles/listeItems.js
- src/modeles/partiesPrenantes/fabriquePartiePrenante.js
- src/modeles/partiesPrenantes/partiePrenanteSpecifique.js
- src/modeles/partiesPrenantes/partiesPrenantes.js
- src/modeles/partiesPrenantes/typePartiePrenante.js
- src/routes/routesApiHomologation.js
- test/depotDonnees.spec.js
- test/modeles/partiesPrenantes/fabriquePartiePrenante.spec.js
- test/modeles/partiesPrenantes/partiePrenanteSpecifique.spec.js
- test/modeles/partiesPrenantes/partiesPrenantes.spec.js
- test/modeles/partiesPrenantes/typePartiePrenante.spec.js
- test/routes/routesApiHomologation.spec.js
Dans l'aventure du déplacement des entités externes dans les rôles et responsabilités,
La première étape est d'enregistrer l'information dans les caractéristiques complémentaires et dans les parties prenantes.
> Déplacement entités externes Partie 1

- src/modeles/utilisateur.js
- test/modeles/utilisateur.spec.js
Dans l'optique où l'on va bientôt pouvoir inviter des contributeurs qui ne sont pas des utilisateurs existants en base, on doit gérer les cas où des utilisateurs seront créés uniquement avec leur email, et éviter que l'information « prénom / nom » de l'utilisateur dans l'entête, ou dans les pastilles contributeurs n'affiche pas de `undefined`.
> Affichage « prénom / nom » quand le prénom ou le nom n'ont pas été saisis

- public/assets/images/pastille_grise.svg
- public/assets/styles/espacePersonnel.css
- public/modules/elementsDom/homologations.js
Dans l'optique où on veut pouvoir inviter des contributeurs encore non inscrits dans MSS, on affiche en gris les pastilles des contributeurs invités qui n'ont pas encore finalisé leur inscription.
> Affiche en gris les contributeurs qui n'ont pas encore finalisé leur inscription

- migrations/20220221142354_copieEntitesExternesDansPartiesPrenantes.js
Dans l'aventure du déplacement des entités externes dans les rôles et responsabilités,
La deuxième étape est de migrer les entités externes des caractéristiques complémentaires dans les parties prenantes.
> Déplacement entités externes Partie 2

- public/homologation/partiesPrenantes.js
- src/modeles/partiesPrenantes/fabriquePartiePrenante.js
- src/modeles/partiesPrenantes/maintenanceService.js
- src/modeles/partiesPrenantes/partiesPrenantes.js
- src/vues/homologation/partiesPrenantes.pug
- test/modeles/partiesPrenantes/fabriquePartiePrenante.spec.js
- test/modeles/partiesPrenantes/maintenanceService.spec.js
- test/modeles/partiesPrenantes/partiesPrenantes.spec.js
Dans la page partie prenante nous pouvons renseigner une nouvelle partie prenante **Maintenance du service**
qui correspond au maintien en conditions opérationnelles
> Nouvelle partie prenante : maintenance du service

- public/homologation/partiesPrenantes.js
- src/modeles/partiesPrenantes/fabriquePartiePrenante.js
- src/modeles/partiesPrenantes/partiesPrenantes.js
- src/modeles/partiesPrenantes/securiteService.js
- src/vues/homologation/partiesPrenantes.pug
- test/modeles/partiesPrenantes/fabriquePartiePrenante.spec.js
- test/modeles/partiesPrenantes/partiesPrenantes.spec.js
- test/modeles/partiesPrenantes/securiteService.spec.js
Dans la page partie prenante nous pouvons renseigner une nouvelle partie prenante Sécurité du service
qui correspond au maintien en conditions de sécurité
> Nouvelle partie prenante : sécurité du service

- public/assets/styles/homologation/partiesPrenantes.css
- public/homologation/partiesPrenantes.js
- public/modules/interactions/brancheOnglets.mjs
- src/vues/homologation/partiesPrenantes.pug
- test_public/modules/interactions/brancheOnglets.spec.mjs
Dans la page parties prenantes,
Nous utilisons des onglets pour afficher soit les _acteurs de l'homologation_ soit les _parties prenantes_
NOTE : j'ai retiré les titres de section **Acteurs de l'homologations** et **Parties prenantes** car je trouvais que cela faisait doublon
> Onglets pour les rôles et responsabilités

- public/homologation/partiesPrenantes.js
Dans la page parties prenantes onglet parties prenantes,
Quand on renseigne la sécurité du service
L'information n'est pas prise en compte
- les paramètres ne sont pas bien ajustés avant la requête
- surement causé par un rebase trop rapide
> Erreur dans la récupération des paramètres de la sécurité du service

- src/depotDonnees.js
- src/modeles/caracteristiquesComplementaires.js
- src/modeles/homologation.js
- src/modeles/partiesPrenantes.js
- src/routes/routesApiHomologation.js
- test/depotDonnees.spec.js
- test/modeles/caracteristiquesComplementaires.spec.js
- test/modeles/homologation.spec.js
- test/modeles/partiesPrenantes.spec.js
- test/routes/routesApiHomologation.spec.js
Comme l'hébergeur n'est plus affiché dans la page caractéristiques complémentaires,
il peut être supprimé dans le modèle
- changement de l'appel pour l'affichage dans le document de synthèse
> Suppression de l'hébergeur dans le modèle

- src/depotDonnees.js
- src/modeles/caracteristiquesComplementaires.js
- src/modeles/homologation.js
- src/modeles/partiesPrenantes.js
- src/routes/routesApiHomologation.js
- test/depotDonnees.spec.js
- test/modeles/caracteristiquesComplementaires.spec.js
- test/modeles/homologation.spec.js
- test/modeles/partiesPrenantes.spec.js
- test/routes/routesApiHomologation.spec.js
La structure du développement qui se trouvait dans les caractéristiques complémentaires est maintenant disponible dans la partie prenante développement / fourniture
Donc le code dans les caractéristiques complémentaires est devenu inutile
> Suppression dans le modèle de la structure de développement

- migrations/20220309143836_suppressionColonneStructureDeveloppement.js
La structure du développement a été déplacée des caractéristiques complémentaires et est sortie du modèle, nous pouvons effacer les données des caractéristiques complémentaires persistées
> Suppression des données de la structure du développement dans les caractéristiques complémentaires

- migrations/20220315083635_ecraseRolesResponsabilitesAvecPartiesPrenantes.js
Les parties prenantes spécifiques n'ont pas été copiées lors de la première migration et n'étaient pas écrites dans les rôles et responsabilités du temps des caractéristiques complémentaires.
Une nouvelle copie remettra tout à jour
> Copie des parties prenantes en roles et responsabilités

- src/depotDonnees.js
- src/modeles/caracteristiquesComplementaires.js
- src/modeles/partiesPrenantes.js
- src/routes/routesApiHomologation.js
- test/depotDonnees.spec.js
- test/modeles/caracteristiquesComplementaires.spec.js
- test/modeles/homologation.spec.js
- test/modeles/partiesPrenantes.spec.js
- test/routes/routesApiHomologation.spec.js
Comme les entités externes on été déplacé en parties prenantes spécifiques dans la page rôles et responsabilités, nous pouvons les supprimer du modèle
> Suppression des entités externes dans le modèle

- .eslintrc.js
- migrations/20211013203941_ajoutColonneRisquesGenerauxAHomologations.js
- migrations/20211021200444_supprimeColonneRisquesDeHomologations.js
- migrations/20211022131727_ajoutColonneMesuresGeneralesAHomologations.js.js
- migrations/20211031201722_supprimeColonneMesuresDeHomologations.js
- migrations/20220110160004_dupliqueInformationsGeneralesDansDescriptionService.js
- migrations/20220118162341_suppressionColonneHomologationsIdUtilisateur.js
- migrations/20220204145444_supprimeInformationsGenerales.js
- migrations/20220216134942_dupliquePartiesPrenantesDansRolesResponsabilites.js
- migrations/20220315083635_ecraseRolesResponsabilitesAvecPartiesPrenantes.js
- src/middleware.js
- src/mss.js
- src/routes/routesHomologation.js
- test/middleware.spec.js
- test/mocks/middleware.js
L'intention de ce commit est de pouvoir détecter en amont ces paramètres inutilisés, plutôt que [pendant une relecture de PR](https://github.com/betagouv/mon-service-securise/pull/190#discussion_r827111096) 😉
Afin de permettre malgré tout l'utilisation de paramètres déclarés plus loin dans la liste des paramètres, on peut spécifier les paramètres nécessaires pour l'ordre d'appel, mais inutilisés dans la fonction, en les faisant précéder du caractère `_`.
Peut-être que c'est un peu plus lourd à utiliser, et que la déclaration explicite des paramètres inutilisés n'est pas vraiment dans l'esprit JavaScript. Malgré tout, cette vérification aura au moins permis de mettre en évidence une erreur ligne 35 dans le test `test/middleware.spec.js`.
> Détecte les paramètres de fonction déclarés et inutilisés

- migrations/20220316133022_supprimeColonneEntitesExternes.js
Après le déplacement des entités externes dans les parties prenantes et la suppression dans le modèle,
nous pouvons supprimer les entités externes des données
> Suppression des entités externes dans les données

- src/vues/homologation/decision.pug
Jusqu'à il y a peu, le document de décision d'homologation pouvait afficher en entête un encadré d'alerte, qui déplaçait les blocs vers le bas. On n'a plus besoin de provisionner cet espace en fin de première page et on peut maintenant couper plus loin.
> [CORRECTION] Déplace le saut de page

- src/modeles/homologation.js
- src/modeles/rolesResponsabilites.js
- src/vues/homologation/decision.pug
- test/modeles/rolesResponsabilites.spec.js
Dans le document d'homologation,
nous souhaitons voir apparaitre les intervenants listés dans la page rôles et responsabilités.
Dans le bloc Equipe j'ai ajouté après _Décision d'homologation préparée par ..._ tous les acteurs de l'homologation
> Les Intervenants dans le documents d'homologation

- src/depotDonnees.js
- src/modeles/homologation.js
- src/modeles/partiesPrenantes.js
- test/depotDonnees.spec.js
Après le changement des parties prenantes en rôles et responsabilités,
nous pouvons arrêter la double persistance.
note : la classe PartiesPrenantes n'ayant plus d'utilité peut être supprimé
> Arrêt double persistance des parties prenantes

- public/homologation/mesures.js
- public/modules/arrangeParametresMesures.mjs
- src/routes/routesApiHomologation.js
- test/routes/routesApiHomologation.spec.js
- test_public/modules/arrangeParametresMesures.spec.mjs
Quand on renseigne des modalités sans cocher de statut,
Les modalités sont bien prises en compte
> Correction de la sauvegarde des modalités des mesures

- migrations/20220331122356_suppressionPartiesPrenantes.js
Dans les données en base,
l'objet `partiesPrenantes` n'est plus utilisé et peut être supprimé.
> Suppression dans les données des parties prenantes

- src/depotDonnees.js
- src/depots/depotDonneesAutorisations.js
- src/depots/depotDonneesHomologations.js
- src/depots/depotDonneesUtilisateurs.js
Le fichier était devenu très gros, difficile à lire… et ne mettait pas en évidence les dépendances entre les différentes tables. Cette PR répond à ce problème.
PR à venir :
- Séparation des tests de `depotDonnees.spec.js` en plusieurs modules correspondants
- Voir si ça peut être pertinent de ne plus accéder à l'API des dépôts par `DepotDonnees.XXX()`, mais peut-être par quelque chose comme `DepotDonnees.utilisateurs.XXX()`
> [NETTOYAGE] Séparation du dépot de données en plusieurs sous-dépôts

- public/assets/styles/nouvellesFonctionnalites.css
Dans la page http://localhost:1917/nouvellesFonctionnalites le texte se situe à droite des puces
> Correction de l'alignement des puces dans nouvelles fonctionnalités

- public/assets/images/icone_plus_pastille_bleue.svg
Problème rencontré sur Firefox dans l'espace personnel :
> [CORRECTION] Alignement du 'plus' dans la pastille bleue

- src/vues/homologation/decision.pug
Dans le document d'homologation,
dans la première partie,
les caractères spéciaux étaient affichés en code html
> Affichage correct du texte échappé dans le document d'homologation

- public/assets/styles/decision.css
Dans le document d'homologation,
Quand une description de risque avait plus de quatre lignes
la première ligne n'apparaissait pas.
> Affichage correct des descriptions des risques

- public/assets/styles/espacePersonnel.css
- public/assets/styles/palette.css
- src/vues/espacePersonnel.pug
Dans la page espace personnel,
nous souhaitons avoir un bandeau permettant d'accéder à la page présentant les nouveautés
> Bandeau nouveautés dans l'espace personnel

- public/assets/styles/formulaire.css
- public/assets/styles/homologation/mesures.css
Dans les pages Description du service et Mesures nous utilisions les styles par défaut
- fonctionne sur Chrome Firefox et Safari (avec un ajustement spécifique)
- Le focus fonctionne sur Chrome quand on utilise TAB mais pas au moment du clic
> Style cible pour les boutons radio et les case à cocher

- src/vues/homologation/decision.pug
Dans le document d'homologation,
Dans la parties des risques principaux,
Le texte des risques spécifiques avec caractères spéciaux ne s'affichait pas correctement
> Correction de l'affichage des risques spécifiques échappés

- src/adaptateurs/adaptateurMail.js
… Conformément aux maquettes.
Note : à ce jour les messages sont envoyés en mode « texte » et la mise en forme est limitée. J'ai choisi de mettre le nom du service entre guillemet plutôt qu'en gras, et les éléments de liste sont précédés de tirets plutôt que de puces.
> Reformulation messages invitation à contribution

- public/assets/styles/homologation/risques.css
- public/homologation/risques.js
- src/vues/homologation/formulaire.pug
- src/vues/homologation/risques.pug
Dans la page des risques,
nous souhaitons avoir des cartes d'informations pour aider l'utilisateur.
Des maquettes sont disponibles dans Figma Version Cible
Note : 
- La largeur de la carte ainsi que les gouttières ne corespondent pas à la maquette Version Cible car cela entraine un dépassement des 1200px de largeur ou la réduction du formulaire.
- Pour les gouttières j'ai pris la valeur de 24px de la maquette UI kit
- Pour les cartes j'ai choisi la largeur de 270px qui est moins que les 282px prévu mais qui selon moi est un bon équilibre avec la taille diminué du formulaire
> Cartes d'informations dans la page des risques

- public/modules/arrangeParametresMesures.mjs
- test_public/modules/arrangeParametresMesures.spec.mjs
quand on enregistre les mesures générales,
actuellement toutes les mesures vide sont enregistrées ce qui donne le faux positif de page saisie
> Correction enregistrement des mesures vides

- public/homologation/mesures.js
- src/vues/homologation/mesures.pug
avec un service qui n'est pas une application mobile,
quand on filtre pour avoir uniquement les mesures de protections,
en bas de la page il y a un i qui vient s'ajouter et perturbe l'affichage
- la désactivation des affichages des mesures se faisaient sur les fieldset je l'ai déplacée sur les div.mesure parents
- j'ai changé le comportement d'identification des mesures en étant plus déclaratif dans le pug
boy-scout : j'ai transformer le .click() en .on('click', )
> Correction affichage parasite d'une icône d'information

- src/modeles/homologation.js
- src/modeles/mesures.js
- src/modeles/mesuresGenerales.js
- test/modeles/mesures.spec.js
- test/modeles/mesuresGenerales.spec.js
Dans la page de synthèse les mesures apparaissaient _à completer_
dû à la personnalisation et l'ajout d'une mesure spécifique application mobile.
Pour y remédier,
- j'ai modifié la condition de statut des mesures générales pour qu'elles regardent uniquement les statuts des mesures de la listes
- les mesures utilisent la listes des identifiants référentiel pour ajuster le statut des mesures générales
- l'homologation donne aux mesures les identifiants obtenu après le passage dans le moteur de règles
C'est un fix mais je trouve cela lourd
> Correction du statut de saisie des mesures générales

- donneesReferentiel.js
- src/moteurRegles.js
- test/moteurRegles.spec.js
Quand l'utilisateur achète l'application,
les mesures à retirer sont
- Disposer d'une liste à jour des équipements et des logiciels contribuant au fonctionnement du service numérique
- Effectuer un test d'intrusion et/ou réaliser un bug bounty
~- Réaliser un audit de configuration et de code source du service~
- Envoyer aux administrateurs et aux utilisateurs une notification en cas de connexion suspecte
Ce dev est l'occasion d'écrire la règle de retrait de mesures
~La mesure **Réaliser un audit de configuration et de code source du service** est nouvelle, elle n'a pas été pour le moment ajoutée aux mesures de base~
> Personnalisation des mesures achat sur étagère

- donneesReferentiel.js
Précédemment le profil création de comptes s'activait si on cochait la fonctionnalité création de compte
Maintenant nous souhaitons affiner les critères en ajoutant que la provenance du service est développement et pas achat
> Règles du profil création de comptes

- migrations/20220509153038_nettoyageMesuresGeneralesVides.js
Précédemment dans l'application (https://github.com/betagouv/mon-service-securise/pull/247) l'enregistrement des mesures enregistrait des mesures et de modalités vides.
Actuellement cela est visible dans le document d'homologation (dans le cas d'un enregistrement de la page mesures avant le correctif) où on a toutes les mesures qui s'affichent.
Ce code est une migration des données qui a pour but des supprimer les mesures générales qui ont un statut vide et des modalités vides.
Pour tester j'ai écrit dans node la commande qui suit avant et après la migration
```node
require('knex')(require('./knexfile').development).select('donnees').from('homologations').then((lines) => lines.map((line) => line.donnees).map((donnees) => donnees?.mesuresGenerales?.filter((mesure) => !mesure.statut && …
```
> Suppression dans les mesures des statuts et modalités vides

- src/vues/inscription.pug
- src/vues/mss.pug
Dans le footer de toutes les pages il y avait **Version béta** ce n'est plus le cas
Le texte de la page inscription à été changé pour ne plus faire apparaitre **phase alpha**
> Retrait des mentions alpha et béta

- donneesReferentiel.js
Dans la description du service,
quand l'utilisateur renseigne le statut de déploiement du service numérique,
il souhaite avoir la possibilité de choisir En projet
> Nouveau statut de déploiement en projet

- donneesReferentiel.js
- migrations/20220517130637_modificationClesStatutDeploiement.js
Dans la page Description du service,
les statuts de déploiement accessible et non accessible sont renommés en en ligne et en cours
Note : ce dev comporte une migration de données
> Renmmage des statuts de déploiement

- src/vues/fragments/formulaireDescriptionService.pug
Dans la page Description du service,
Le label de la question sur les fonctionnalités du service est renommé
> Renommage du label de la question des fonctionnalités

- src/vues/homologation/decision.pug
Ces informations étant aseptisées, les apostrophes étaient affichées sous forme de code d'échappement.
Ce commit règle le problème.
> [CORRECTION] Affiche correctement les descriptions de mesure dans le document d'homologation

- src/vues/connexion.pug
Ajout du placeholder " ex: jean.dupont@domaine.fr" dans le champs de saisie "Email".
> Création placeholder dans le champs E-mail

- src/vues/connexion.pug
Le sous-titre "Vous n'avez pas encore de compte ? Créez-en un !" est remplacé par "ou créez votre compte".
La phrase "J'ai oublié mon mot de passe" est remplacée par "mot de passe oublié".
> Renommage sous-titre et phrase du mot de passe

- .eslintrc.js
- public/modules/statistiques/construis.mjs
- public/modules/statistiques/donnees.mjs
- public/statistiques.js
- src/middleware.js
- src/mss.js
- src/vues/mss.pug
- src/vues/statistiques.pug
- test/middleware.spec.js
- test_public/modules/statistiques/construis.spec.mjs
Dans un premier temps, les données statistiques sont remplies à la main dans le fichier `public/modules/statistiques/donnees.mjs`. À terme, on utilisera plutôt une requête en base de données.
> Publie page statistiques d'usage

- public/assets/styles/mss.css
Dans certaines pages (exemple : /reinitialisationMotDePasse) le footer apparait légèrement surélevé
NOTE : j'ai essayé pleins de choses : position absolute fixe flexbox et cette solution fonctionne sans trop chambouler le site
> Le pied de page en bas de la page

- public/assets/styles/homologation/rolesResponsabilites.css
- public/assets/styles/mss.css
- public/homologation/mesures.js
- public/modules/interactions/brancheFiltresMesures.mjs
- src/vues/homologation/mesures.pug
- test_public/modules/interactions/brancheFiltresMesures.spec.mjs
- test_public/modules/interactions/brancheOnglets.spec.mjs
Lorsqu'on cliquait sur le filtre « Tout », les mesures spécifiques ne s'affichaient plus. Cette PR corrige l'anomalie.
Au passage, j'ai extrait le code des interactions de la barre de filtre dans un module à part et j'ai ajouté des tests pour valider le comportement attendu.
> Correction filtre mesures specifiques

- public/assets/styles/formulaire.css
- src/vues/admin/inscription.pug
- src/vues/connexion.pug
- src/vues/reinitialisationMotDePasse.pug
Dans la page de connexion,
le style à changé : 
- plus de séparateurs
- bouton à droite
- _mot de passe oublié_ en non gras
- ajustement des espaces blancs
Le label du bouton a changé
Les pages Inscription et Réinitialisation du mot de passe ont aussi changé
> Style de la page de connexion

- public/assets/styles/index.css
Dans la page d'accueil,
l'image d'introduction avait rétréci après un changement du texte d'introduction.
> Corrige la taille de l'image d'introduction

- src/vues/homologation/decision.pug
Dans la page de la décision d'homologation,
il manquait un c à affecter
> [CORRECTION] Typo dans les notes finales de la décision

- src/modeles/homologation.js
- src/modeles/rolesResponsabilites.js
- src/vues/homologation/decision.pug
- src/vues/homologation/rolesResponsabilites.pug
- test/modeles/rolesResponsabilites.spec.js
- test_public/modules/interactions/brancheOnglets.spec.mjs
Dans la page rôles et responsabilités,
les acteurs de l'homologation deviennent la gouvernance
> Renommage des acteurs de l'homologation en gouvernance

- src/modeles/mesure.js
- src/modeles/mesureGenerale.js
- test/modeles/homologation.spec.js
- test/modeles/mesureGenerale.spec.js
- test/modeles/mesureSpecifique.spec.js
- test/modeles/mesuresGenerales.spec.js
En préparation au calcul du cyberscore, on introduit la notion de mesures recommandées par l'ANSSI (notion qui varie suivant que la mesure est spécifique ou générique).
… Et on en profite pour nettoyer quelques tests.
> Introduis la notion de mesures recommandées par l'ANSSI

- public/modules/statistiques/donnees.mjs
… On remarque tout de même qu'il y a un problème… quand on ne met pas à jour
une semaine donnée, les pourcentages depuis la précédente mesure sont
artificiellement gonflés. Peut-être qu'il faudra revoir ça.
> Mise à jour des statistiques

- donneesReferentiel.js
- migrations/20220614074541_changementStatutsMesuresPlanifies.js
- public/assets/styles/decision.css
- src/modeles/mesure.js
- src/modeles/mesuresGenerales.js
- src/vues/homologation/decision.pug
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/mesure.spec.js
- test/modeles/mesuresGenerales.spec.js
Il était possible d'avoir en statut Fait Planifié Non fait ou Non concerné
maintenant le statut Planifié est retiré et le statut En cours prend sa place
Les mesures avec un statut Planifié auront un statut Non fait
Notes : 
- ce dev contient une migration de données
- la page Décision et le document d'homologation sont impactés
> Changement des statuts de mesure

- src/middleware.js
- src/routes/routesBibliotheques.js
- src/vues/homologation/decision.pug
- src/vues/mss.pug
- src/vues/statistiques.pug
- test/middleware.spec.js
- test/routes/routesBibliotheques.spec.js
Cette PR fait suite à la #302 
Dorénavant, on ne fait plus d'appels directs à des URL en dehors du serveur MSS.
> Chargement des bibliothèques tierces depuis MSS

- public/modules/deconnexion.js
Quand un utilisateur est connecté sur plusieurs onglets / fenêtres,
les modales notifiant la déconnexions doivent être synchronisées
NOTE : utilisation d'une variable dans le localStorage coté client
> Modale de déconnexion multi fenêtres

- src/vues/homologation/decision.pug
Dans la page de décision de l'homologation + PDF, dans le bloc _Principaux risques de sécurité identifiés_
les risques spécifiques qui comportent dans leurs descriptions des caractères spéciaux sont affiché avec des codes
> Correction Affichage sans échappement des risques dans la décision

- src/vues/mssInscription.pug
Dans la page inscription le titre du département et l'exemple du poste ne convenaient pas.
> Changement de textes dans la page inscription

- src/vues/index.pug
Dans la page d'accueil,
le bouton `S'inscrire` invite à envoyer un e-mail,
nous souhaitons qu'il nous emmène directement vers la page inscription.
> Changement cible pour le bouton S'inscrire 

- donneesReferentiel.js
- public/assets/styles/carteInformations.css
- public/assets/styles/homologation/risques.css
- public/homologation/risques.js
- public/modules/elementsDom/saisieRisqueSpecifique.js
- public/modules/interactions/saisieNiveauGravite.js
- src/referentiel.js
- src/vues/carteInformations.pug
- src/vues/homologation/risques.pug
- test/referentiel.spec.js
Cette PR vient en préparation de l'affichage du score dans un composant « carte ». On commence par extraire ce composant de la page risques, là où il était utilisé uniquement jusqu'à présent.
(Note : on profite de cette PR pour supprimer la duplication concernant la gestion des couleurs pour les risques.)
> [PREMANIEMENT] extraction composant carte

- public/assets/styles/inscription.css
- src/vues/mssInscription.pug
Dans la page d'inscription,
nous souhaitons voir un message de prévention pour l'utilisateur
Nouvelle proposition
> Message de prévention dans inscription

- public/assets/styles/inscription.css
- public/inscription.js
Dans la page d'inscription,
Quand un champ texte est rempli ou un champ à liste de choix est sélectionné,
Le conteneur du champ doit apparaitre en bleu comme dans l'UI kit
> Mise en avant des champs saisis

- src/vues/activation.pug
Dans la page d'activation qui apparait après l'inscription d'un nouvel utilisateur `/activation`,
Le texte se voit modifié.
NOTE : Je me suis permis d'écrire un objet au mailto : `Non réception du lien d'activation`
> Nouveaux texte dans la page d'activation de compte

- .dockerignore
- docker-compose.yml
… plutôt que ceux de la machine hôte. Cela permet de pouvoir utiliser le code du projet depuis la machine hôte et depuis le conteneur, chaque contexte d'utilisation ayant ses propres dépendances de modules Node installées de manière cohérente.
En particulier : il devient possible d'exécuter les tests avec`./script/tests.sh` (dans le contexte du conteneur Docker sous Linux) _et_ depuis la machine hôte sous un OS différent, par exemple depuis l'IDE.
Il fallait faire deux modifications dans la configuration :
- d'une part ne pas copier les modules déjà installés sur la machine hôte lors de la construction de l'image
- d'autre part ne pas mapper les modules de la machine hôte lors de l'exécution de l'image
Cf. documentation :
- https://docs.docker.com/compose/compose-file/#volumes
- …
> Utilisation modules Node.js installés à la création de l'image

- src/adaptateurs/adaptateurChiffrement.js
- src/depotDonnees.js
- src/depots/depotDonneesUtilisateurs.js
- test/depotDonnees.spec.js
- test/depots/depotDonneesAutorisations.spec.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/depots/depotVide.js
- test/mocks/adaptateurChiffrement.js
- test/routes/testeurMSS.js
Pour ne plus dépendre de bcrypt dans les tests,
Nous mettons en place un adaptateur de chiffrement.
NOTE : il reste une dépendance à bcrypt dans les tests du fichier depotDonnees.spec.js qui utilisent `DepotDonnees.creeDepotVide()` qui 🤷🏻‍♂️ utilise bcrypt
> Utilisation d'un adaptateur chiffrement

- public/assets/styles/formulaire.css
- public/assets/styles/palette.css
Sur toutes les pages,
Les checkboxes et les bouton radio changent quand ils ne sont pas sélectionnés
Voir la maquette de la page description du service cible
> Nouveau style des cases à cocher non sélectionnées

- public/modules/interactions/champsRequis.mjs
Dans le fichier `champsRequis.mjs` on utilise un `=== undefined` pour tester si la valeur est de type non défini,
C'est une meilleur pratique d'utiliser `typeof … === 'undefined'`
> [CORRECTION] comparaison au type non défini

- package-lock.json
- package.json
- server.js
- src/middleware.js
- src/vues/aPropos.pug
- src/vues/cgu.pug
- src/vues/confidentialite.pug
- src/vues/homologation/decision.pug
- src/vues/index.pug
- src/vues/inscription.pug
- src/vues/mss.pug
- src/vues/questionsFrequentes.pug
- src/vues/utilisateur/edition.pug
- test/middleware.spec.js
Il restait encore à plusieurs endroits la mention historique « Mon Service Sécurisé ». Cette PR corrige ce problème
.
> [CORRECTION] Utilisation systématique du nom « MonServiceSécurisé »

- src/vues/fragments/formulaireUtilisateur.pug
Dans les formulaire d'inscription et d'édition,
le nom et le prénom acceptent tout les caractères non chiffre,
et un nouveau message renseigne cela
> Changement erreur nom et prénom

- src/vues/mentionsLegales.pug
Remplace les deux lignes concernant les adresses e-mails (lab ANSSI et Scalingo).
> Remplaces texte des e-mails page MentionsLegales

- public/assets/styles/activation.css
- public/assets/styles/bouton.css
- public/assets/styles/carteInformations.css
- public/assets/styles/deuxColonnes.css
- public/assets/styles/formulaire.css
- public/assets/styles/homologation/formulaire.css
- public/assets/styles/homologation/risques.css
- public/assets/styles/mss.css
- src/vues/accesRefuse.pug
- src/vues/activation.pug
- src/vues/deuxColonnes.pug
- src/vues/homologation.pug
- src/vues/homologation/formulaire.pug
Cette PR introduit le template `deuxColonnes.pug` utilisé par la page de synthèse (et dans le futur par la page listant les homologations pour un service donné) et spécialisé par le template `homologation/formulaire.pug`. Ce template sur deux colonnes offre un place holder dans lequel on peut injecter le nom du service depuis les pages filles.
Elle met en évidence le besoin d'homogénéiser la structure de la « zone principale » des divers templates, et de ce fait résout quelques duplications dans les feuilles de style.
Cette PR embarque enfin une homogénéisation de présentation des cartes d'information.
> Affichage du nom du service en haut des formulaires

- public/assets/styles/modules/validation.css
Dans la pages Inscription et Édition de profil,
L'icône danger et le texte des messages d'erreurs étaient trop collés
> Un espace supplémentaire entre l'icône et le message d'erreur

- src/adaptateurs/adaptateurMail.js
- src/depots/depotDonneesUtilisateurs.js
- src/erreurs.js
- src/routes/routesApi.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/routes/routesApi.spec.js
Dans la page d'inscription,
Quand un utilisateur utilise une adresse e-mail déjà lié à un compte
L'inscription n'apparait plus en erreur et un e-mail de notification de tentative de réinscription est envoyé à l'adresse renseignée
L'e-mail envoyé a pour objet **Tentative de réinscription** et le contenu :
```text
Bonjour,
Lors de la création de votre compte utilisateur sur MonServiceSécurisé, l'e-mail que vous avez renseigné est déjà associé à un compte existant.
Si vous souhaitez en créer un nouveau, cliquez sur ce lien :  
http://www.monservicesecurise.beta.gouv.fr/inscription
Si vous souhaitez réinitialiser votre mot de passe, cliquez sur ce lien :  
http://www.monservicesecurise.beta.gouv.fr/reinitialisationMotDePasse
Si vous n'êtes pas l'origine de cette demande, votre compte est …
```
> Comportement en cas de réinscription

- src/vues/homologation/mesures.pug
- Titre « mesures de sécurité » devient « Sécuriser »
- MAJ de la légende.
> Mise à jour du titre et de la légende de la page mesures de sécurité

- public/assets/styles/service/homologations.css
- src/mss.js
- src/routes/routesService.js
- src/vues/service/homologations.pug
- test/routes/routesService.spec.js
Première PR sur le parcours homologation.
> Ajoute une route `/service/:id/homologations`

- src/modeles/descriptionService.js
- src/modeles/homologation.js
- src/referentiel.js
- test/modeles/descriptionService.spec.js
- test/modeles/homologation.spec.js
- test/referentiel.spec.js
Afin de pouvoir produire le futur document de synthèse de sécurité,
Nous souhaitons avoir la possibilité d'afficher le statut de déploiement.
> Accessibilité de la description du statut de déploiement dans l'homologation

- src/routes/routesHomologation.js
- src/vues/homologation/syntheseSecurite.pug
- test/routes/routesHomologation.spec.js
Dans la perspective de créer une synthèse de sécurité,
Une étape est de créer une nouvelle route `/syntheseSecurite`
> Nouvelle route pour la synthèse de sécurité

- public/assets/styles/mss.css
Dans la page de synthèse,
Quand le nom du service est trop long,
L'affichage du nom doit être tronqué pour tenir dans le bloc
> Correction de l'affichage tronqué de nom de service long

- src/modeles/homologation.js
- src/vues/homologation/decision.pug
- test/modeles/homologation.spec.js
Afin de pouvoir produire le futur document de synthèse de sécurité,
Nous souhaitons avoir la possibilité d'utiliser la clé de localisation des données.
> Clé de localisation des données disponible dans l'homologation

- public/assets/styles/cartes/indiceCyber.css
- public/assets/styles/homologation.css
- public/assets/styles/homologation/synthese.css
- src/routes/routesHomologation.js
- src/vues/cartes/indiceCyber.pug
- src/vues/homologation.pug
- src/vues/homologation/synthese.pug
- test/routes/routesHomologation.spec.js
Cette page est accessible par l'URL orpheline `/homologation/:id/synthese`. On choisit de dupliquer la page `/homologation/:id` tant que la page de synthèse « nouvelle UX » n'est pas utilisable. 
Au passage, on en a profité pour extraire une carte `indiceCyber` qui permet de résoudre une duplication entre les 2 vues touchées par cette PR.
On a inséré une `div` de classe `outils-complementaires` qui permettra de travailler en parallèle sur l'intégration des outils complémentaires.
> Ajout nouvelle page synthèse

- public/assets/styles/syntheseSecurite.css
- src/vues/homologation/decision.pug
- src/vues/homologation/syntheseSecurite.pug
Dans la quête du PDF de synthèse de sécurité,
La page doit avoir un header avec les logos
La page est à l'adresse `/homologation/[id]/syntheseSecurite`
NOTE : sur ma machine avec google chrome quand je télécharge le document le logo de l'ANSSI est flou 😢
> Entête de la page de synthèse de sécurité

- public/assets/images/vignette_drapeau_france.svg
- public/assets/styles/palette.css
- public/assets/styles/syntheseSecurite.css
- src/vues/homologation/syntheseSecurite.pug
Dans la page de synthèse de sécurité nous ajoutons le bloc de résumé du service
> Page synthèse de sécurité - Bloc Résumé

- src/routes/routesBibliotheques.js
- src/vues/mss.pug
Axios a introduit une régression en livrant la version v1.1.0. Comme on chargeait toujours la version la plus récente, on s'est retrouvé avec une version qui ne marche pas.
(cf. https://github.com/axios/axios/issues/5038, et le patch proposé https://github.com/axios/axios/issues/5038#issuecomment-1270717223)
> Utilisation explicite de la v1.0.0 d'Axios

- donneesReferentiel.js
- src/erreurs.js
- src/modeles/actionSaisie.js
- src/modeles/actionsSaisie.js
- src/referentiel.js
- src/routes/routesHomologation.js
- test/modeles/actionSaisie.spec.js
- test/modeles/actionsSaisie.spec.js
- test/referentiel.spec.js
- La page « Synthèse » fait peau neuve.
- On souhaite garder en PROD la page « Synthèse » actuelle tout en déployant la nouvelle.
- La page actuelle sera remplacée seulement lorsque la nouvelle sera finalisée.
- Tant qu'il n'y a pas de remplacement, les 2 pages doivent fonctionner en parallèle.
☝️ C'est ce dernier point qui motive cette PR.
Pour permettre la coexistence des 2 versions de « Synthèse », l'abstraction `ActionsSaisie` se voit enrichie d'une notion de `version`. 
Les `Actions` actuelles deviennent des actions `"v1"`.  
Les `Actions` de la nouvelle « Synthèse » seront des `"v2"`.
Cette PR n'apporte aucune fonctionnalité apparente. Elle ajoute simplement l'abstraction de `version` à l'existant.
La page actuelle utilise les `ActionsSaisie` (au pluriel) pour nourrir les liens …
> Versionnage des actions de saisie

- src/routes/routesHomologation.js
- test/routes/routesHomologation.spec.js
On affiche maintenant la nouvelle page de synthèse sur la route `GET /homologation/:id` – si la variable d'environnement `AVEC_SYNTHESE_V2` est présente.
> Page Synthèse nouvelle formule

- public/modules/interactions/saisieContributeur.js
Suite au renommage des variables homologation en service nous ne renseignons plus l'identifiant à passer pour la requête d'ajout d'un contributeur. (Une erreur 500 généré car l'autorisation entre l'utilisateur et l'id de l'homologation (non renseigné) n'était pas trouvée.) Ce commit corrige ce problème.
> Correction - Répare l'ajout d'un contributeur

- public/scripts/statistiquesMesures.js
Si jamais la valeur vaut `0`, on n'affiche pas le label.
> Camembert – Traitement du cas où la valeur vaut `0`

- src/routes/routesApi.js
- test/routes/routesApi.spec.js
**Bug remonté en PROD :**
Si Rémi Martin crée son compte utilisateur avec son adresse mail…  
… et que Sophie Dubois invite Rémi Martin à contribuer sur un dossier qu'elle a créé avec une adresse mail où il y a des majuscules (ex. Remi.MARTIN@example.com)
…alors MSS ne reconnaît pas qu'il existe déjà un compte associé à cette adresse, crée un deuxième compte, et n'associe pas le dossier au bon compte. Rémi peut se connecter un premier coup avec ce nouveau compte (parcours de finalisation), accéder au dossier qu'on lui a partagé  
… mais ensuite il ne peut plus se connecter à ce deuxième compte et a l'impression d'avoir perdu ses données.  
En fait, non, il n'a rien perdu, c'est juste qu'il n'a pas accès à ce deuxième compte avec des majuscules.
**Explication :**
Si on invite un …
> [CORRECTION] Convertis l'email en minuscules pour éviter les comptes en doublon

- public/assets/images/forme_fleche_bleue.svg
- public/assets/styles/syntheseSecurite.css
- src/vues/fragments/statistiquesMesures.pug
- src/vues/homologation/syntheseSecurite.pug
Cette PR ajoute la flèche et l'encart blanc indiquant le nombre de mesures restantes.
:warning: Le nombre de mesures restantes est codé en dur pour l'exemple, pour l'instant.
Une simulation d'intégration du camembert avec un `div` factice :
> Affiche les mesures restantes dans le PDF de synthèse

- public/assets/styles/palette.css
- public/assets/styles/syntheseSecurite.css
- src/vues/homologation/syntheseSecurite.pug
Cette PR ajoute la légende sous les camemberts.
On note qu'en version PDF imprimable, le *gap* entre chaque élément de légende est agrandi… mais la légende continue de tenir en une ligne.
> Affiche la légende

- donneesReferentiel.js
C'était dans le backlog. C'est la seule donnée pour laquelle il y avait ".etc" après l'exemple.
> Retrait de etc.

- donneesReferentiel.js
C'est la seule donnée pour laquelle il y avait « etc. » après un exemple.
> Retrait de « etc. »

- src/vues/index.pug
Dans la page d'accueil,
Le bouton renvoyant vers la page d'inscription reprend son ancien libellé **S'inscrire**
> Libellé du lien vers la page d'inscription

- public/assets/styles/homologation/synthese.css
- src/vues/homologation/synthese.pug
Cette PR affiche le titre tronqué suivi de `…` lorsqu'il est trop long.
**Sans** la PR :
**Avec** la PR :
Pour rappel, un titre qui n'a pas besoin de troncature s'affiche comme suit (avec et sans la PR) :
Le PDF n'est pas soumis à la troncature. J'ai trouvé l'affichage satisfaisant sans l'appliquer :
Aucune troncature non plus dans le pied de page du PDF, qui mentionne le nom du service :
Si vous pensez qu'il faut soumettre la question à l'équipe d'UX, faites-moi signe.
> Troncature du titre du service si nécessaire

- public/assets/styles/syntheseSecurite.css
- public/homologation/syntheseSecurite.js
- src/modeles/statistiquesMesures.js
- src/vues/homologation/syntheseSecurite.pug
- test/modeles/statistiquesMesures.spec.js
Cette PR ajoute les segments de mesure par catégorie :
L'impression PDF fonctionne :
Un exemple qui offre davantage de couleurs :
- On dimensionne les segments avec des `flex` dont la valeur est le nombre de mesures.
- 24 mesures faites donne `flex: 24`.
- Les statistiques sont calculées dans les statistiques des mesures.
> Affichage des mesures par catégorie sur le PDF

- public/assets/styles/syntheseSecurite.css
- src/modeles/homologation.js
- src/modeles/mesures.js
- src/vues/fragments/totalMesures.pug
- src/vues/homologation/syntheseSecurite.pug
- test/modeles/homologation.spec.js
- test/modeles/mesures.spec.js
- test/modeles/mesuresSpecifiques.spec.js
Dans la page de synthèse de sécurité,
nous souhaitons voir apparaitre le nombre de mesures ajoutés par l'utilisateur (mesures spécifiques)
> Nombre de mesures spécifiques dans le Pdf de synthèse

- migrations/20220911174845_creationTableServices.js
- migrations/20220911180114_duplicationHomologationsDansServices.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesHomologations.js
- src/depots/depotDonneesServices.js
- src/depots/depotDonneesUtilisateurs.js
- src/modeles/service.js
- src/utilitaires/copie.js
- test/depots/depotDonneesHomologations.spec.js
- test/depots/depotDonneesServices.spec.js
- test/depots/depotDonneesUtilisateurs.spec.js
Grosse PR – pas sûr de savoir comment la découper en plusieurs morceaux… Suggestions bienvenues.
Cette PR fait suite à #366 et s'inscrit de manière plus large dans l'ajout d'un parcours homologation.
> Duplication des homologations en services

- public/assets/styles/homologation/synthese.css
Suite à notre livraison de la troncature, on nous a demandé d'espacer un peu les "…" et le bouton.
> Espace la fin du titre et le bouton de téléchargement

- donneesReferentiel.js
- src/modeles/homologation.js
- src/modeles/mesureGenerale.js
- src/modeles/mesures.js
- src/modeles/mesuresGenerales.js
- src/modeles/profils/mesures.js
- src/modeles/profils/profil.js
- src/moteurRegles.js
- src/referentiel.js
- test/modeles/mesureGenerale.spec.js
- test/modeles/mesures.spec.js
- test/modeles/mesuresGenerales.spec.js
- test/moteurRegles.spec.js
- test/referentiel.spec.js
Le moteur de règles peut maintenant rendre indispensable une liste de mesures pour un profil donné.
La pastille "indispensable" est mise à jour dans la page des mesures.
Les statistiques sont mises à jour dans la page de synthèse du PDF.
> La règle "sauvegarde des données" est rendue indispensable pour le profil MSS+

- donneesReferentielDepartements.js
- test/modeles/utilisateur.spec.js
- test/referentiel.spec.js
Dans le référentiel des département,
nous n'avons pas l'utilité d'avoir les codes de région.
> Nettoyage des codes de région non utilisés

- src/vues/mssConnexionEnCours.pug
Nouveau lien dans l'en-tête au moment de se connecter :
> Ajout de « Questions fréquentes » à la page de connexion

- src/vues/mssInscription.pug
En accord avec les dernières maquettes, l'entête pendant l'inscription n'est plus…
…mais devient :
J'ai choisi de réutiliser le template `mssConnexionEnCours` depuis l'inscription.
Une alternative serait de déclarer `block navigation` dans `vues/inscription.pug`. Mais bon…pour minimiser les cas différents de `navigation`, j'ai préféré réutiliser `mssConnexionEnCours`.
Ça justifie peut-être un renommage du template `mssConnexionEnCours` : `mssAccesEnCours` peut-être ?
> Utilisation de l'entête de « Connexion » pour l'inscription

- public/assets/styles/entete.css
Pour corriger ce problème de logo carré sous Chrome :
> [CORRECTION] Affiche correctement logo sous Chrome

- src/modeles/mesuresGenerales.js
- test/modeles/mesuresGenerales.spec.js
Corrige le bug qui affichait des nombres négatif dans les camemberts
Avant
Après
> Correction des statistiques en tenant compte des mesures rendues indispensables

- public/assets/styles/mss.css
Sur la page Espace personnel,
Le bandeau des nouvelles fonctionnalités est détaché du header
> Correction de la position du bandeau des nouvelles fonctionnalités

- public/assets/styles/entete.css
Cette PR corrige l'alignement de la Marianne avec les autres logos. 
C'est un retour qu'on a eu via le recettage de l'entête.
> Alignement de la Marianne avec le logo ANSSI

- public/assets/images/forme_point_bleu.svg
- public/assets/styles/annexes/mesures.css
- public/assets/styles/palette.css
- public/assets/styles/syntheseSecurite.css
- src/modeles/homologation.js
- src/modeles/mesure.js
- src/modeles/mesureGenerale.js
- src/modeles/mesureSpecifique.js
- src/modeles/mesures.js
- src/modeles/mesuresGenerales.js
- src/modeles/mesuresSpecifiques.js
- src/vues/homologation/annexes/mesures.pug
- test/modeles/homologation.spec.js
- test/modeles/mesure.spec.js
- test/modeles/mesureGenerale.spec.js
- test/modeles/mesureSpecifique.spec.js
- test/modeles/mesures.spec.js
- test/modeles/mesuresGenerales.spec.js
- test/modeles/mesuresSpecifiques.spec.js
dans l'objectif de réaliser une annexe avec les mesures,
J'ai ajouté les mesures en cours à la page `/:id/syntheseSecurite/annexes/mesures`
- Il n'y a pas de saut de page
- Les modalités (commentaires) des mesures n'est pas affiché
- La capture des données inclue les mesures faites et non faites pour un affichage futur
NOTE : les mesures spécifiques sont présentes
> L'annexe avec les mesures en cours

- public/assets/styles/annexes/mesures.css
- src/modeles/mesuresGenerales.js
- src/modeles/mesuresSpecifiques.js
- src/vues/homologation/annexes/mesures.pug
- test/modeles/mesuresGenerales.spec.js
- test/modeles/mesuresSpecifiques.spec.js
Dans la page des annexes des mesures `:id/syntheseSecurite/annexes/mesures`
Les modalités sont affichées quand elles sont renseignées
NOTE : valable pour les mesures générales et spécifiques
> Annexe des mesures ajout des modalités

- donneesReferentiel.js
La provenance du service peut être un outil existant.
NOTE : Mise à jour du profil Application Achetée
> Le service peut avoir pour provenance un outil existant

- donneesReferentiel.js
- migrations/20221102134033_changeProvenanceService.js
- public/assets/styles/homologation/formulaire.css
- src/modeles/descriptionService.js
- src/vues/fragments/formulaireDescriptionService.pug
- test/modeles/descriptionService.spec.js
- test_migrations/20221102134033_changeProvenanceService.spec.js
La provenance du service deviens une question à choix simple, les textes sont renommés
NOTE : ce dev comporte une migration
> Choix simple pour la provenance du service

- docker-compose.yml
On veut éviter une situation où un membre de l'équipe a un schéma de BDD qui n'est pas le dernier, sans pour autant que l'application ne plante. Ce serait le pire : avoir un modèle de données non conforme au reste de l'équipe, mais pas de plantage.
En forçant les migrations knex, on évite ce problème.
Exemple : #459 contient une migration. Si cette migration n'est pas exécutée, l'application en plante pas. Elle enregistre une chaîne de caractères dans un champs de `donnees` qui est normalement devenu un tableau.
⚠️ ~~Cette PR utilise la syntaxe `sh -c` pour donner plusieurs commandes au conteneur qui se lance.
En utilisant cette syntaxe, l'arrêt *graceful* du conteneur semble devenu impossible.  
Le conteneur affiche `Gracefully stopping... (press Ctrl+C again to force)` pendant 10 …
> Exécution des migrations knex au lancement de l'application en local

- public/assets/styles/entete.css
Sans cette PR, les icônes ne suivent pas la taille du texte.
Par exemple avec une règle `html { font-size: 40px; }`
> Icônes qui suivent la taille de police

- .env.template
- src/adaptateurs/adaptateurMailSendinblue.js
Cette PR ajoute un adaptateur qui repose sur Sendinblue pour envoyer les emails.
Cet adaptateur n'est pas encore branché au reste du code.
La PR a pour but de présenter une implémentation possible pour support de discussion.
Les textes sont copiés / collés depuis l'adaptateur précédent.  
Des `<br />` sont ajoutés car on passe en HTML.  
[La documentation](https://developers.sendinblue.com/docs/send-a-transactional-email) utilise HTML. Je n'ai rien trouvé pour envoyer en texte brut…ce qui ne me dérange pas.
En local, l'e-mail arrive très bien, et la police fait un peu moins « brute » que précédemment : 
- Ajouter une gestion d'erreur
- Brancher l'adaptateur
- Décommissionner l'adaptateur précédent (et les variables d'environnement associées)
> Nouvel adaptateur Sendinblue pour envoi d'e-mails

- src/adaptateurs/adaptateurPostgres.js
L'erreur a été détectée en lisant dans les logs d'un environnement de DEMO :
> error: delete from "utilisaateurs" where "id" = $1 - relation "utilisaateurs" does not exist
Pendant les tests en DEMO autour de l'utilisation de Sendinblue pour l'envoi d'e-mails.
> Correction de la suppression d'utilisateur

- donneesReferentiel.js
- migrations/20221115150500_suppressionDiffusionRestreinte.js
Cette PR fait disparaître le choix « Diffusion restreinte » du référentiel.
Il apparaissait à la place du cadre rouge :
> Supprime « Diffusion restreinte » des données à caractère personnel

- .env.template
- src/vues/homologation.pug
- src/vues/homologation/synthese.pug
L'indice cyber est activé jusqu'en Production. L'interrupteur n'est plus nécessaire.
> Supprime interrupteur AVEC_INDICE_CYBER

- server.js
- src/adaptateurs/adaptateurPdfStatique.js
- src/mss.js
- src/routes/routesPdf.js
- test/routes/routesPdf.spec.js
- test/routes/testeurMSS.js
Une 1ère étape est la création d'une route et d'un adaptateur de pdf
La route est `/pdf/:id/annexeMesures.pdf` et le pdf est un pdf statique
> Pdf vide de l'annexe des mesures

- package-lock.json
- package.json
- src/adaptateurs/adaptateurPdfLatex.js
- src/latex/fabriquantGabarit.js
- src/routes/routesPdf.js
- src/vuesTex/annexeMesures.template.tex
- test/latex/fabriquantGabarit.spec.js
Une 3ème étape est l'utilisation d'un moteur de modèle pour générer le latex
La route est `/pdf/:id/annexeMesures.pdf` et le pdf est un pdf statique obtenu à partir de latex avec le texte GOUVERNANCE injecté
- Utilisation de la bibliothèque DoT https://olado.github.io/doT/
> Moteur de modèle pour générer le latex

- package-lock.json
- package.json
- src/adaptateurs/adaptateurPdfLatex.js
- src/latex/miseEnFormeDonnees.js
- src/routes/routesPdf.js
- src/vuesTex/annexeMesures.template.tex
- test/latex/miseEnFormeDonnees.spec.js
Une 4ème étape est le décodage des caractères html issue de l'aseptisation avant l'interpolation dans le latex
La route est /pdf/:id/annexeMesures.pdf et le pdf est un pdf statique obtenu à partir de latex avec un échantillon de données injecté contenant un caractère html
- Ajout de la bibliothèque html-entities https://github.com/mdevils/html-entities#readme
> Décodage des caractères html pour le latex

- src/mss.js
- src/routes/routesPdf.js
- src/vuesTex/annexeMesures.template.tex
- test/routes/routesPdf.spec.js
Ceci est la dernière étape pour avoir les mesures sans style et sans pagination
La route est /pdf/:id/annexeMesures.pdf et le pdf affiche toutes les mesures mais non ordonnées et avec les catégories mal écrites
> Toutes les mesures dans le pdf

- .env.template
- src/mss.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
- test/routes/testeurMSS.js
Description du bug : 
Quand un utilisateur possède un mot de passe avec des caractères aseptisables (ex : &), la connexion ne se fait pas
Dans api/utilisateur on aseptise le mot de passe donc les caractères mais pas dans /api/token ce bug vient d'une modification sur la route PUT /api/utilisateur https://github.com/betagouv/mon-service-securise/commit/33b716e2164c22f7e322f480cffc83fbb8266bac#diff-bb9fee1edd1c7cc853a1c85ca33c152f511b18687e9955c3fba901c174bdea44
Qui est en prod depuis le 26 aout https://github.com/betagouv/mon-service-securise/pull/324
> [CORRECTION] Le mot de passe est aseptisé par erreur

- src/depots/depotDonneesHomologations.js
- src/modeles/journalMSS/evenements.js
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/journalMSS/evenements.spec.js
Suite à notre décision commune de parler de _« Service »_ dès le départ dans les Événements.
> Parle de « Service » plutôt que « d'Homologation »

- src/vues/fragments/formulaireUtilisateur.pug
Jusqu'à présent, lors que l'utilisateur a un prénom, un nom, un poste ou une entité de rattachement qui contient une apostrophe, ces données ne sont pas affichées correctement dans le formulaire d'édition du profil utilisateur.
Cette PR corrige le problème.
> [CORRECTION] Affichage correct des données du profil utilisateur

- migrations/20221021094600_suppressionMesuresGeneralesObsoletes.js
- migrations/20221102134033_changeProvenanceService.js
- migrations/20221115150500_suppressionDiffusionRestreinte.js
Jusqu'ici, ces trois (dernières) migrations ne mettaient pas à jour les données dans la table `services`, ce qui entraînait une divergence entre les deux tables.
Cette PR corrige le problème (et nécessite de rejouer ces trois migrations dans les environnements de déploiement).
> [CORRECTION] Jeu des migrations sur les tables `homologations` _et_ `services`

- public/espacePersonnel.js
- public/modules/interactions/pastilles.js
Jusqu'à présent, lorsqu'on cliquait sur une pastille créateur ou contributeur, l'événement était propagé à la carte service et redirigeait vers la page synthèse de ce service.
La PR corrige ce problème.
(Note : plus tard, le clic sur une pastille déclenchera l'ouverture d'une modale de gestion des contributeurs.)
> [CORRECTION] Désactivation de l'action quand clic sur une pastille créateur / contributeur

- src/modeles/homologation.js
- src/modeles/statistiquesMesures.js
- src/routes/routesPdf.js
- src/vuesTex/annexeMesures.template.tex
- test/modeles/homologation.spec.js
- test/modeles/statistiquesMesures.spec.js
Sur la dernière page, on veut afficher le nombre de mesures personnalisées qui n'ont pas de statut.
Si toutes les mesures sont remplies : pas de page en plus dans l'annexe 
Sinon, une page supplémentaire qui fait attention au nombre de mesures :
> [Annexe Mesures] Affiche le nombre des mesures « À remplir »

- .env.template
- README.md
- docker-compose.yml
Dans le cadre de la cohabitation avec mss-journal, on veut un network nommé et 'external'. 
Pour que les conteneurs de mss-journal utilisent le même.
[La PR côté mss-journal](https://github.com/betagouv/mon-service-securise-journal/pull/3)
> Crée et utilise network Docker « mss-network »

- src/modeles/homologation.js
- src/modeles/objetsVues/vueAnnexePDFRisques.js
- src/routes/routesPdf.js
- src/vuesTex/annexeRisques.template.tex
- test/modeles/homologation.spec.js
- test/modeles/objetsVues/vueAnnexePDFRisques.spec.js
- test/routes/routesPdf.spec.js
Une 3ème étape est l'ajout d'un style comme l'annexe des mesures
> Annexe risques - Style comme les mesures

- src/modeles/mesuresGenerales.js
- src/modeles/statistiquesMesures.js
- test/modeles/statistiquesMesures.spec.js
Pour rendre le code plus simple à comprendre.
On peut ajouter un test explicite autour de la fonction déplacée, pour documenter le comportement.
On réduit la taille de `MesuresGenerales.statistiques()` qui est déjà très grosse.
On réduit le couplage avec la structure interne des statistiques.
💡  J'aimerais que le déplacement du
```js
  this.items.forEach((mesure) => { … }
```
suive.
Ce qui va mettre une grosse pression sur notre possible défaut de design qui est :
```js
this.items.forEach((mesure) => {
const { id, statut } = mesure;
const { categorie } = this.referentiel.mesure(id);
mesure.rendueIndispensable = mesuresPersonnalisees[id].indispensable; // <--- CETTE LIGNE
```
Je n'ai pas envie d'y passer trop de temps. Je me donne la soirée.
> [REMANIEMENT] Déplace la création des statistiques

- .env.template
- src/adaptateurs/adaptateurJournalMSSMemoire.js
- src/adaptateurs/adaptateurJournalMSSPostgres.js
- src/adaptateurs/fabriqueAdaptateurJournalMSS.js
- src/depotDonnees.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
- test/depots/depotVide.js
Les tests continuent d'utiliser l'adaptateur mémoire par souci d'isolation et de rapidité. 
L'utilisation de l'adaptateur mémoire peut être forcée via `.env` pour s'économiser le besoin de lancer MSS-Journal lors du développement en local.
-----------------
📋  Pour rappel, la feuille de route que nous avions estimé ensemble :
créations de compte utilisateur, permettant de croiser les données entre Service et Utilisateur.
> Crée adaptateur Postgres du « Journal MSS »

- src/modeles/risques.js
- test/modeles/risques.spec.js
Une 5ème étape est la mise à disposition des risques par niveau de gravité
NOTE : l'insertion dans l'objet de pdf annexe risques et l'utilisation dans le pdf suivent
> Annexe risques - risques spécifiques par niveau

- src/vuesTex/annexeRisques.template.tex
Les commentaires n'était pas alignés avec les descriptions des risques
Avant
Maintenant
> Annexe risques - les commentaires alignés

- donneesReferentiel.js
- migrations/20221130100733_suppressionStatutMesureNonConcerne.js
- public/assets/styles/decision.css
- src/modeles/mesure.js
- src/modeles/mesureGenerale.js
- src/modeles/mesures.js
- src/modeles/mesuresGenerales.js
- test/modeles/homologation.spec.js
- test/modeles/mesure.spec.js
- test/modeles/mesuresGenerales.spec.js
- test_migrations/20221130100733_suppressionStatutMesureNonConcerne.spec.js
Dans la section « sécuriser », le choix « non concerné » disparaît (56d6f6e8a3600a3500de2f37c991c9879b3ffd5d).
Les mesures déjà enregistrées comme « non concerné » deviennent « non fait » (e5fa99858eb5a764e95798f1c9d2aafe851d6c63).
> Suppression du choix « non concerné »

- src/latex/miseEnFormeDonnees.js
- test/latex/miseEnFormeDonnees.spec.js
À l'heure actuelle, s'il y a un double saut de ligne dans les modalités décrites pour une mesure, ce saut est interprété par LaTeX comme le début d'un nouveau paragraphe, ce qui ne peut pas avoir lieu dans une balise `\textcolor`.
Le présent commit corrige ce problème.
> [CORRECTION]Échappement des sauts de ligne pour génération des fichiers LaTeX

- src/modeles/mesure.js
- src/modeles/mesuresGenerales.js
- src/modeles/mesuresSpecifiques.js
- test/modeles/mesure.spec.js
- test/modeles/mesuresGenerales.spec.js
- test/modeles/mesuresSpecifiques.spec.js
Dans l'annexe des mesures en PDF, nous voulons que soient listées les mesures en cours, puis à faire, puis faites.
> Ordonne les statuts dans l'ordre attendu

- consoleAdministration.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
Cette PR ajoute la possibilité de supprimer les services créés par des utilisateurs, via leur identifiant.
L'objectif est de supprimer les services existants à tort en PROD.
⚠️ Pour ne pas supprimer le service « MSS », il est possible de spécifier des identifiants de service à toujours conserver.
La suppression se déclenche par `ConsoleAdministration` chez Scalingo :
```js
ConsoleAdministration = require('./consoleAdministration')
admin = new ConsoleAdministration();
utilisateur = 'uuid-utilisateur';
monServiceSecurise = 'uuid-mss';
admin.supprimeHomologationsDeUtilisateur(utilisateur, [monServiceSecurise])
.then(() => console.log('OK'))
```
ℹ️  Les discussion avec @egaillot ont permis d'identifier 9 comptes utilisateurs à nettoyer via la console.
--------------------
📋  Pour rappel, la …
> 🧹 Nettoie services créés pour les tests

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
Car `autorisations` est un meilleur socle pour répondre à la question « qui sont les créateurs des homologations ? ».
> [REMANIEMENT] Utilise autorisations pour trouver homologations d'un créateur

- consoleAdministration.js
- src/depots/depotDonneesHomologations.js
- src/modeles/journalMSS/erreurs.js
- src/modeles/journalMSS/evenements.js
- test/modeles/journalMSS/evenements.spec.js
Désormais les événements de création de service embarquent un SHA-1 de l'identifiant du service.
Ça nous laisse la porte grande ouverte pour l'exploitation des données.
Ce serait très compliqué à rattraper plus tard, sur les événements déjà enregistrés.
> Exige présence identifiant service

- public/scripts/statistiquesMesures.js
Dans l'annexe de synthèse,
Quand toutes les mesures sont faites,
Les camemberts ne sont pas pleins.
- Les camemberts sont pleins
- Pendant que j'y étais j'ai centré le label au centre du camembert
> Correction des camemberts des mesures non pleins

- src/modeles/homologation.js
- src/modeles/mesures.js
- src/modeles/mesuresGenerales.js
- src/modeles/mesuresSpecifiques.js
- src/modeles/statistiquesMesures.js
- test/modeles/homologation.spec.js
- test/modeles/statistiquesMesures.spec.js
Nous voulons mesurer dans Metabase le nombre de services ayant été « complétés à plus de 50 % ».
Cette PR ajoute le calcul de cette complétude à notre modèle.
C'est `StatistiquesMesures` qui porte l'intelligence
🧹 Sur Mattermost j'avais évoqué l'idée de supprimer du code mort. En fait ce code est supprimé par #496 donc je ne le fais pas ici.
------------------
📋  Pour rappel, la feuille de route que nous avions estimé ensemble :
- #511
- #520 
-   ☝️  **La présente PR contribue à ce point.**
> Calcul de la complétude des mesures

- public/assets/styles/index.css
- src/vues/index.pug
Cette PR ajoute le bouton « Voir l’actu sur le site de l’ANSSI » à la page d'accueil.
Le wording sur Figma est « Voir le communiqué de presse » mais – vu avec @jbdemaison – on le change car le lien référence désormais le site de l'ANSSI.
ℹ️ Le code de cette PR faisait partie à l'origine de #535. Mais le bouton avait été enlevé car nous n'avions pas l'URL associée au bouton. @egaillot avait validé le code de la PR **avant** suppression du bouton.
> 🎨 Ajoute lien vers actu ANSSI sur la page d'accueil

- src/modeles/homologation.js
- src/modeles/mesureGenerale.js
- src/modeles/mesuresGenerales.js
- test/modeles/homologation.spec.js
- test/modeles/mesureGenerale.spec.js
- test/modeles/mesuresGenerales.spec.js
Dans les annexes,
Les mesures rendues indispensables apparaissent comme recommandées (sans l'étoile)
La cause est l'instanciation dans les listeItems des objets MesureGenerale sans le paramètre `renduIndispensable`
> Correction du bug des mesures générales indispensables

- public/assets/styles/formulaire.css
- public/assets/styles/homologation/mesures.css
- public/assets/styles/utilisateur.css
- public/homologation/mesures.js
- public/modules/interactions/validation.js
- public/modules/saisieListeItems.js
- src/vues/fragments/formulaireUtilisateur.pug
- src/vues/homologation/mesures.pug
Dans la page des mesures
les mesures spécifiques sont munies de système de validation pour les champs description, statut et catégorie
- Style des select commun à tous les formulaires
- Branchement des validateur sur un conteneur
- Nouveau style du bloc
> Champs requis pour les mesures spécifiques

- .eslintrc.js
- migrations/20221129194103_duplicationAutorisationsHomologationsEnAutorisationsServices.js
- package-lock.json
- package.json
- src/depots/depotDonneesAutorisations.js
- src/depots/depotDonneesHomologations.js
- src/modeles/autorisations/autorisationBase.js
- test/depots/depotDonneesAutorisations.spec.js
- test/depots/depotDonneesHomologations.spec.js
Cette PR fait suite à #388 et s'inscrit de manière plus large dans l'ajout d'un parcours homologation.
Note : on profite de cette PR pour explorer un chemin sans `Promise.all` dans les migrations, en s'appuyant sur [p-map](https://github.com/sindresorhus/p-map). Si ça convient comme tel, je m'occuperai de nettoyer les autres `Promise.all` gênants dans notre code de cette manière.
> Duplication des autorisations homologations services

- public/assets/styles/bouton.css
- src/vues/fragments/modaleNouveauService.pug
Avant :
Après correction :
(Au passage, on en a profité pour supprimer une inclusion CSS en doublon.)
> Correction bords bouton inactif

- public/assets/styles/modules/validation.css
- public/homologation/etapesDossier.js
- public/homologation/mesures.js
- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
- public/modules/interactions/validation.mjs
Dans la grande aventure qui est la validation des formulaires coté client,
je propose d'ajouter aux systèmes de validation déjà en place la validation des checkbox et textarea
Notes :
- Pages concernées :
- /inscription
- /utilisateur/edition
- /homologation/:id/mesures
- /homologation/:id/dossier/edition/etape/*
- /espacePersonnel -> popin de création
- J'ai renommé le fichier avec mjs en extension pour l'utiliser plus tard dans les fichiers de description du service
- Les textarea apparaissent avec une bordure bleue au moment du submit ou de la modification
> Ajoute la validation des cases à cocher et zone de texte

- public/assets/styles/homologation/descriptionService.css
- public/modules/soumetsHomologation.mjs
- src/vues/fragments/formulaireDescriptionService.pug
- src/vues/fragments/inputChoix.pug
- src/vues/homologation/creation.pug
- src/vues/homologation/decrire.pug
- src/vues/homologation/descriptionService.pug
- test_public/modules/soumetsHomologation.spec.mjs
Il y a des validateurs de présence sur les champs voulus obligatoires.
Notes :
- La maquette est disponible dans Figma
- ~~J'ai pour le moment inventé les messages d'erreurs (à valider / ré-écrire)~~
- Il n'y a pas de validateurs pour `Données à caractère personnel et autres données sensibles stockées par le service` et `Fonctionnalité(s) offerte(s)` à la place il y a une phrase indiquant qu'il est bon de remplir
> Champs requis dan la page Décrire

- src/vues/cartes/indiceCyber.pug
Vu avec Mari, il faut supprimer le terme "Évalué par l'Anssi", sous titre de l'indice cyber
> Suppression du sous titre

- src/modeles/mesureSpecifique.js
- src/routes/routesApiHomologation.js
- test/modeles/mesureSpecifique.spec.js
- test/routes/routesApiHomologation.spec.js
On ne sauvegarde pas les mesures spécifiques qui n'ont pas tous les champs requis
> Champs requis pour les mesures spécifiques coté serveur

- src/modeles/base.js
- test/modeles/base.spec.js
Tous les objets du modèle fils de Base auront la possibilité de savoir si toutes les propriétés obligatoires sont renseignées
> Propriétés obligatoires

- src/routes/routesApiHomologation.js
- test/routes/routesApiHomologation.spec.js
Actuellement, si on forge une requête `POST` ou `PUT` sur homologation avec des données incohérentes avec le référentiel pour la description du service, `DescriptionService.valide` lève une exception qui n'est pas récupérée et qui génère un crash du serveur.
Ce commit corrige le problème.
> [CORRECTION] Gestion exceptions levées à instanciation `DescriptionService`

- consoleAdministration.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesUtilisateurs.js
- src/erreurs.js
- test/depots/depotDonneesUtilisateurs.spec.js
On peut supprimer uniquement les utilisateurs qui ne sont pas créateurs.
Les utilisateurs contributeurs sont supprimés avec leurs autorisations de contribution.
À utiliser avec la console Admin.
> Suppression utilisateur depuis console administrateur

- public/assets/styles/modules/validation.css
- src/vues/fragments/modaleNouveauService.pug
On ne souhaite plus afficher l'étoile avant la case à cocher, contrairement aux autres formulaires.
> Suppression étoile dans la modale de création de nouveau service

- consoleAdministration.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
L'objectif est d'alimenter le journal MSS en événements de complétude afin d'avoir une vision sur tous les services référencés.
Note pour le relecteur : `toutesHomologations()` est une duplication assumée et non élégante de `homologations(idUtilisateur)`. Ce code est voué à être utilisé une seule fois via la consoleAdministration pour nourrir la PROD. Il sera ensuite « git reverted ». Ce ne devrait pas être une source d'inspiration.
Un chemin de design plus souhaitable serait de réutiliser `homologations(idUtilisateur)` qui saurait gérer le cas où on ne lui passe aucun id en retournant toutes les homologations.
> Génère un événement de complétude pour chaque service

- public/assets/styles/homologation/descriptionService.css
- public/assets/styles/modules/validation.css
- public/assets/styles/utilisateur.css
- src/vues/homologation/mesures.pug
Dans la page des mesures, nous souhaitons avoir la mention champ obligatoire
NOTE : pendant que je passais par là, j'en ai profité pour mettre les propriétés de styles de `.mention` uniquement dans validation.css
Les pages impactées par cela sont :
- Décrire
- Profil / Inscription
- Homologation - étape 2
> Mention champ obligatoire dans les mesures

- public/modules/interactions/brancheFiltresMesures.mjs
- test_public/modules/interactions/brancheFiltresMesures.spec.mjs
les mesures spécifiques disparaissent quand on utilise les onglets.
Le comportement attendu est :
- Une mesure spécifique apparait quand l'onglet toutes est sélectionné
- Une mesure spécifique n'ayant pas encore de catégorie apparait dans tous les onglets
- Une mesure spécifique avec une catégorie apparait dans l'onglet de sa catégorie et pas dans les onglets des autres catégories
NOTE : bug causé par le passage du bouton select à des boutons radio
> Affichage des mesures spécifiques dans les onglets

- creeUtilisateurDemo.js
a8a7074d4dc8e40b4c8224c585851119c4f12f99 a ajouté une `DescriptionService` au service de Démo, car celle-ci est désormais obligatoire.
Par contre le `typeService` doit être un tableau (et non une chaîne) car il peut être multiple. Il est d'ailleurs rendu par des checkboxes sur la page `Décrire`.
> [CORRECTION] Utilise un tableau pour le type du service « Démo »

- public/assets/styles/index.responsive.css
- src/vues/base.pug
- src/vues/index.pug
Nouveau style responsif pour la page d'accueil,
Les points de rupture sont 768px et 1247px.
Les maquettes sont sur Figma
Pour ce dev j'ai utilisé un fichier css supplémentaire qui surcharge les propriétés
NOTE : les prochains devs seront pour le footer et le header
> Corps de la page d'accueil responsive

- public/assets/styles/filAriane.css
- public/assets/styles/homologation/synthese.css
- public/assets/styles/lien.css
- src/vues/deuxColonnes.pug
- src/vues/fragments/texteTronque.pug
- src/vues/homologation/avisExpertCyber.pug
- src/vues/homologation/decrire.pug
- src/vues/homologation/formulaireEtapier.pug
- src/vues/homologation/mesures.pug
- src/vues/homologation/risques.pug
- src/vues/homologation/rolesResponsabilites.pug
- src/vues/homologation/synthese.pug
- src/vues/mss.pug
J'ai fait quelques choix qui nous écartent potentiellement de la maquette – à valider avec l'équipe design :
- Quand on crée un nouveau service, on affiche dans le fil d'Ariane `Espace personnel > Décrire`
- Quand on est dans la page de synthèse, on affiche dans le fil d'Ariane `Espace personnel > Service XXX > Synthèse`
> Affiche un fil d'Ariane pour les pages privées

- src/depots/depotDonneesHomologations.js
- src/modeles/journalMSS/evenementServiceSupprime.js
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/journalMSS/evenementServiceSupprime.spec.js
Maintenant qu'on génère nos statistiques sur la base d'événements de création / modification de service, il est important de consigner aussi les événements de suppression – sinon, on continue de comptabiliser des services supprimés, ce qui fausse les métriques.
Ainsi, avec cette PR, on consigne un événement de suppression de service quand on supprime un service.
> Journalisation événement suppression service

- public/assets/styles/index.responsive.css
- public/assets/styles/piedPage.responsive.css
- src/vues/index.pug
Afin de rendre le site plus responsif,
le pied de page prends en charge 3 niveaux de taille d'écran
NOTES : 
- J'ai volontairement importé la feuille de style dans index.pug pour que seul la landing page reçoive le changement
- J'ai mis un commit de retrait de bouchonnage
- J'ai pas un bon résultat quand il y a le mélange liens, texte et ponctuation en mobile
> Bas de page accueil responsif

- .env.template
- public/scripts/matomo.js
- src/vues/base.pug
… pour nous permettre d'avoir un Matomo de DEMO et un de PROD.
Ou bien de débrancher totalement Matomo en omettant la variable d'environnement.
🔔 Il faudra penser à créer les variables sur nos environnements Scalingo DEMO et PROD.
> Paramètrage du « Site ID » de Matomo

- public/assets/images/icone_sandwich.svg
- public/assets/styles/entete.css
- public/assets/styles/entete.responsive.css
- public/assets/styles/index.responsive.css
- public/entete.js
- public/modules/interactions/brancheMenuSandwich.js
- src/vues/index.pug
- src/vues/mss.pug
Afin de rendre le site plus responsif,
L'entête a des styles différents pour 3 niveaux d'écran et un menu sandwich 🍔
Notes :
- Cette PR contient un commit de débouchonnage du style de l'entête
- Pour le sandwich j'ai du faire des modifications dans l'entête desktop
- La version connecté n'est pas optimale
> Entête de l'accueil responsif

- public/scripts/statistiquesMesures.js
Dans la synthèse de sécurité,
Dans les camemberts,
Quand on a qu'un seul type présent (en cours OU non fait OU fait OU à remplir),
L'affichage du label doit être centré
> Affichage centré du label dans les camemberts

- src/routes/routesApi.js
- test/mocks/middleware.js
- test/routes/routesApi.spec.js
Il s'agit d'une première étape sur le chemin vers une page à part pour changer le mot de passe.
Tâches à venir par la suite :
> Ajout route `PUT /api/motDePasse`

- src/erreurs.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
Cette PR fait suite à #614. Il s'agit d'une étape suivante sur le chemin vers une page à part pour changer le mot de passe.
Tâches à venir par la suite :
> Factorisation appels changements mot de passe

- src/adaptateurs/adaptateurPdfLatex.js
- src/routes/routesPdf.js
- src/vuesTex/annexeDescription.template.tex
- test/routes/routesPdf.spec.js
J'ai créé une route provisoire `/pdf/:id/annexeDescription.pdf` avec une page quasi vide
> Route annexe description

- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
- public/modules/interactions/brancheValidationMotDePasse.js
- src/vues/fragments/utilisateur/nouveauMotDePasse.pug
Cette PR met en place une double saisie du mot de passe côté client.
Le champ de confirmation [est invalide](https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation#complex_constraints_using_the_constraint_validation_api) si les 2 saisies diffèrent.
J'ai bien aimé pouvoir faire porter le JS de validation directement dans le mixin de mot de passe.
J'ai l'intuition que ça nous facilitera la tâche au moment de transition où on aura la saisie de mot de passe sur 2 pages distinctes.
> Double saisie du mot de passe

- src/adaptateurs/adaptateurPdfLatex.js
- src/modeles/homologation.js
- src/modeles/objetsVues/vueAnnexePDFDescription.js
- src/routes/routesPdf.js
- src/vuesTex/annexeDescription.template.tex
- test/modeles/homologation.spec.js
- test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
- test/routes/routesPdf.spec.js
J'ai ajouté les entête et pied de page au pdf `/pdf/:id/annexeDescription.pdf`
> Annexe description - entête et pied de page

- public/utilisateur/edition.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
Pour assurer une transition douce vers la création d'une page dédiée au changement du MDP.
**[EDIT après être de nouveau en non-Draft]**
Ça aurait été un sacré bug d'oublier `cguAcceptees` dans le payload qui part vers `PUT /api/motDePasse`.
Je m'en suis rendu compte en supprimant la gestion du mot de passe dans `PUT /api/utilisateur` : en lisant les tests que je supprimais j'ai compris qu'il manquait quelque chose côté front avec les CGU…
La PR est grosse car j'ai supprimé tous les tests devenus obsolètes sur `PUT /api/utilisateur`.
**[/EDIT]**
🗺️  Feuille de route :
> Utilisation de la route `/api/motDePasse` pour MAJ du mot de passe

- public/motDePasse/edition.js
- src/mss.js
- src/vues/fragments/utilisateur/nouveauMotDePasse.pug
- src/vues/motDePasse/edition.pug
- src/vues/utilisateur/edition.pug
- test/mss.spec.js
Sur l'URL `/motDePasse/edition` on affiche le formulaire qui est – pour le moment – également présent sur la page d'édition du profil utilisateur.
🗺️  Feuille de route :
> Ajout de la page dédiée au changement de mot de passe

- src/modeles/homologation.js
- src/modeles/itemsAvecDescription.js
- src/modeles/objetsVues/vueAnnexePDFDescription.js
- src/referentiel.js
- src/vuesTex/annexeDescription.template.tex
- src/vuesTex/fragments/couleurs.tex
- test/modeles/itemsAvecDescriptions.spec.js
- test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
- test/referentiel.spec.js
J'ai ajouté le bloc Fonctionnalités au pdf `/pdf/:id/annexeDescription.pdf`
Notes :
- Les fonctionnalités spécifiques sont ajoutées à la suite des fonctionnalités
- Le bloc disparait quand il n'y a pas de fonctionnalité
> Ajoute les fonctionnalités à l'annexe description

- public/assets/styles/homologation/synthese.css
L'icône s'affichait en blanc sur fond blanc, ce qui la rendait invisible.
> [CORRECTION] Affichage icône nouvel onglet en bleu

- public/assets/styles/mss.css
- src/vues/connexion.pug
a20b37a16351e8003cc2abb4e4f1fb232733e4c4 a changé les espaces verticaux de règles très larges de `mss.css`. Cela cause des régressions sur la page « Décrire » où les labels « Ajouter une fonctionnalité » et « Ajouter des données » se retrouvent collés aux sections inférieures.
Ce commit conserve le placement correct de `.mention champ obligatoire` dans la page de connexion en modifiant la structure de `connexion.pug` plutôt que le CSS de `mss.css`.
La correction du bug :
> [CORRECTION] Retourne à espacement vertical connu

- src/modeles/objetsVues/vueAnnexePDFDescription.js
- src/referentiel.js
- src/vuesTex/annexeDescription.template.tex
- test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
- test/referentiel.spec.js
J'ai ajouté le bloc Données stockées au pdf `/pdf/:id/annexeDescription.pdf`
Notes :
- Les données stockées spécifiques sont ajoutées à la suite des données stockées
- Le bloc disparait quand il n'y a pas d'élément
> Données stockées à l'annexe description

- src/modeles/objetsVues/vueAnnexePDFDescription.js
- src/referentiel.js
- src/vuesTex/annexeDescription.template.tex
- src/vuesTex/macros/boiteGrise.tex
- test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
- test/referentiel.spec.js
J'ai ajouté le bloc Durée maximale acceptable de dysfonctionnement grave du service au pdf `/pdf/:id/annexeDescription.pdf`
Notes :
- Le texte `Non renseignée` apparait si la durée n'est pas définie
> Durée maximale acceptable dans l'annexe description

- src/modeles/autorisations/autorisationBase.js
- src/modeles/autorisations/autorisationCreateur.js
- src/routes/routesApiService.js
- test/modeles/autorisations/autorisationBase.spec.js
- test/modeles/autorisations/autorisationCreateur.spec.js
- test/routes/routesApiService.spec.js
Dans la feature de suppression de service,
Je propose d'ajouter une nouvelle route DELETE qui permet de supprimer un service quand on est connecté, cgu acceptées et créateur du service.
La suppression utilise les mécanismes déjà implémentés et utilisés dans la console admin.
> Nouvelle route de suppression de service

- public/assets/styles/modaleSuppressionService.css
- public/assets/styles/palette.css
- public/espacePersonnel.js
- src/vues/espacePersonnel.pug
- src/vues/fragments/modales/modaleSuppressionService.pug
Dans la feature de suppression de service,
dans la page espace personnel
Création d'une modale qui permettra d'appeler la suppression d'un service.
Note : Il n'y a aucun lien ou bouton pour afficher la modale, si vous voulez la voir et la tester une technique est de le faire depuis la console du navigateur
```js
$('.services').trigger('modaleSuppression', {nomService: 'Nom du service à supprimer', idService: '123-ou-un-id-a-supprimer'});
```
> Modale de suppression de service

- src/middleware.js
- test/middleware.spec.js
… car désormais c'est sur cette page que se fait l'acceptation des CGU.
Le formulaire de changement de MDP + acceptation des CGU va disparaître de la page « Profil utilisateur ».
> Redirige vers page « Mot de passe » pour accepter les CGU

- public/assets/styles/espacePersonnel.css
- public/espacePersonnel.js
- src/modeles/utilisateur.js
- src/vues/espacePersonnel.pug
- src/vues/utilisateur/edition.pug
- test/modeles/homologation.spec.js
- test/modeles/utilisateur.spec.js
Désormais le changement de MDP se fait sur une page dédiée.
Cette page dédiée sera également utilisée comme page d'arrivée pour les utilisateurs invités à s'inscrire.
Autrement dit :
* A est inscrit
* Il invite B à contribuer
* B clique sur le lien d'inscription qu'il reçoit par e-mail
* B arrivera sur la page « Changer votre mot de passe »
Avant, B arrivait sur la page « Profil » où il était obligé de saisir à la fois son mot de passe **ET** ses informations de profil.
Désormais il faut donc inciter le nouvel inscrit à aller remplir ses infos de profil. 
C'est ce que fait ce bandeau.
Le scenario est :
- partir d'un compte complet
- inviter un collaborateur
- regarder dans la console l'ID de reset MDP du collaborateur
- naviguer sur `http://mss-local/initialisationMotDePasse/:uuid` pour …
> Affiche un bandeau « Mettez à jour vos informations » si le nom n'est pas renseigné

- src/mss.js
Cette PR modifie la page utilisée pour l'initialisation du mot de passe.
Avant c'était la page de profil, désormais c'est la page dédiée au changement de mot de passe.
> Utilisation de la page de changement de MDP pour l'initialisation du mot de passe

- src/adaptateurs/adaptateurPersistanceMemoire.js
- test/depots/depotDonneesUtilisateurs.spec.js
Actuellement, l'adaptateur en mémoire supprime toutes les contributions, ce qui n'est pas le comportement souhaité.
(Note : l'adaptateur PostgreSQL fonctionne déjà correctement.)
> [CORRECTION] Ne supprime que les contributions d'un utilisateur donné

- donneesReferentiel.js
Ajout de "à" dans le titre de la mesure Autoriser uniquement la création de comptes d'accès nominatifs associés chacun une personne
> Modification d'une coquille

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesAutorisations.js
- src/erreurs.js
- test/depots/depotDonneesAutorisations.spec.js
Cette PR corrige le comportement du transfert de tous les dossiers d'un utilisateur source vers un utilisateur cible. Spéciquement :
- Si l'utilisateur cible est déjà contributeur sur un service dont l'utilisateur source est aussi contributeur, on ne doit pas dupliquer les droits de contribution sur ce service.
- Si l'utilisateur cible est contributeur sur un service dont l'utilisateur source est le créateur, on doit mettre à jour les droits pour l'utilisateur cible.
> [CORRECTION] gestion des transferts

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesAutorisations.js
Note : le mécanisme de transaction existe seulement pour l'adaptateur Postgres. Peut-être que si on voulait réutiliser un jour l'adaptateur mémoire en prod, il faudrait l'y implémenter ? Le débat semble prématuré pour l'instant.
> Regroupe les différentes requêtes pour transfert dans une même transaction

- src/routes/routesApiService.js
Le paramètre `suite` avait été oublié alors qu'il est utilisé dans la fonction
> Correction d'un oubli de suite dans la route delete service

- src/modeles/mesures.js
- test/modeles/mesures.spec.js
… car on ne veut pas qu'elles polluent les statistiques calculées dans Metabase.
Sans cette correction, on se retrouve avec une visualisation Metabase qui montre des mesures sans statut 👇
> [CORRECTION] Ignore les mesures dont le statut n'est pas renseigné

- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesHomologations.js
- src/modeles/base.js
- src/modeles/homologation.js
- src/modeles/listeItems.js
- src/modeles/objetsDonnees/donneesPersistanceHomologation.js
- src/modeles/risqueGeneral.js
- test/modeles/homologation.spec.js
- test/modeles/risqueGeneral.spec.js
Nettoyage, aligne comportement postgres avec comportement adaptateur mémoire (créateur et collaborateurs toujours dans homologation depuis la base).
Pour éviter de sauvegarder créateur et collaborateurs dans les mises à jour des services,
on introduit un objet intermédiaire (donneesPersistanceHomologation) qui exclut explicitement ces données (créateur et collaborateurs) des données à sauvegarder.
Au passage, on corrige aussi une anomalie : on embarquait dans la base de données la description du risque général persisté, maintenant ce n'est plus le cas.
NOTE : Modifie l'adaptateur postgres
> Utilisation d'un objet de persistance homologation

- creeUtilisateurDemo.js
- migrations/20221129194103_duplicationAutorisationsHomologationsEnAutorisationsServices.js
- migrations/20230207141258_suppressionDonneesIdUtilisateurDansServices.js
- migrations/utilitaires/pourChaqueLigne.js
- src/depots/depotDonneesHomologations.js
- src/routes/routesApiService.js
- test/depots/depotDonneesHomologations.spec.js
- test/routes/routesApiService.spec.js
On utilise maintenant _toutes_ les données du service (y compris mesures, risques, etc.) pour créer la nouvelle homologation. Ceci en préparation de la fonctionnalité de duplication de service.
Au passage, on corrige le fait que la base de données persistait encore (à tort) `idUtilisateur` dans la table `homologations`. Et on fait une migration pour nettoyer les données existantes.
> Creation nouveau service complet

- src/routes/routesApiService.js
- test/routes/routesApiService.spec.js
- test/routes/testeurMSS.js
Afin de dupliquer un service, nous avons une route COPY `/api/service/:id` qui duplique le service
quand : 
- l'utilisateur connecté est créateur du service
- le nom cible (* - Copie) n'existe pas déjà
Pour tester : curl fetch postman et tout le rest
Si le code vous est familier, c'est normal c'est quasi le même que la suppression. Si vous avez un refacto il sera le bienvenu
> Route pour duplication de service

- src/depots/depotDonneesHomologations.js
- src/modeles/homologation.js
- src/routes/routesApiService.js
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/homologation.spec.js
- test/routes/routesApiService.spec.js
Cette PR permet de dupliquer plusieurs fois un même service, sans avoir d'erreur de « nom déjà pris ».
> Utilise nom d'homologation disponible pour la duplication

- public/espacePersonnel.js
- public/scripts/modaleDuplicationService.js
- src/vues/fragments/modales/modaleDuplicationService.pug
… qui arrivaient en « ouvrant » puis « fermant » plusieurs fois de suite une modale de duplication.
Le souci était que le handler `.on('submit')` était déclaré **dans** le handler `.on('modaleDuplication')`. Autrement dit : chaque ouverture de modale enregistrait un nouveau handler de soumission du formulaire.
Ce commit corrige le bug, et au passage introduit un fichier JS dédié à la modale pour mieux s'y retrouver.
Co-authored-by: Jacques Raguin <jacques.raguin@beta.gouv.fr>
> [CORRECTION] Évite les multiples duplications non désirées

- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
- On passe d'une compléxité O(n²) à une compléxité O(n)
-  On découple la création du nom de la recherche d'un index de copie pour dans un deuxième temps permettre de faire N copies sans faire N recherches
> [OPTIMISATION] Réduction de la compléxité algorithmique de duplication de service

- public/assets/styles/modaleSuppressionService.css
- public/espacePersonnel.js
- public/scripts/modaleDescriptionService.js
- public/scripts/modaleSuppressionService.js
- src/vues/fragments/modales/modaleSuppressionService.pug
Ce commit applique l'architecture utilisée par #671 à la suppression du service.
Au passage on supprime un fichier JS non utilisé, et on corrige une régression sur un nom de service qui doit être en gras 👇
> [REMANIEMENT] Organise la suppression de la même manière que la duplication

- Dockerfile
- package.json
On passe de node 16 - npm 8 à node 18 - npm 9 car node 18 est la version lts en cours
> Montée de version de node en 18

- src/vues/fragments/modales/modaleDuplicationService.pug
Comme il y a 1 seul champ, nous n'avons pas besoin de l'astérisque
> Retrait l'astérisque de la modale de duplication

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
Sans ce commit, les services avec contributeurs étaient ramenés « contributeurs + 1 » fois.
> [CORRECTION] Ramène seulement une fois chaque service à la récupération de tous les services

- package-lock.json
- package.json
La version 20 de jsdom comporte une vulnérabilité modérée qui se voit corrigée avec la dernière version 21
NOTE : jsdom est utilisé dans les tests js coté client qui utilise du jquery
> Montée version de jsdom qui corrige une vulnérabilité

- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
Pendant la duplication, si l'id de l'homologation ne correspond à rien en base l'application reste robuste
> Duplication test présence homologation

- public/assets/styles/espacePersonnel.css
- public/modules/interactions/brancheMenuContextuelService.js
Dans l'espace personnel,
quand le menu contextuel est ouvert,
le bouton … doit être gris clair
> Bouton du menu contextuel gris quand le menu est ouvert

- src/modeles/dossier.js
- src/modeles/etapeDate.js
- src/vues/homologation/etapeDossier/2.pug
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/dossier.spec.js
- test/routes/routesApiService.spec.js
Fait suite à la PR #689,
- Utilisation de EtapeDate pour persister
- Utilisation de EtapeDate dans les templates
> Utilisation l'objet étape date pour le dossier d'homologation

- public/assets/styles/etapesDossier.css
- public/assets/styles/palette.css
- src/vues/homologation/formulaireEtapier.pug
Dans le parcours homologuer,
les étapes complètes sont cliquables.
Ce dev ajoute des styles d'intéeactions et rend uniquement le rond cliquable
Normal
Survol
Clic
Focus
> Couleurs d'interactions pour l'étapier

- public/assets/styles/espacePersonnel.css
- public/homologation/avisExpertCyber.js
- public/homologation/etapesDossier.js
- public/homologation/mesures.js
- public/homologation/risques.js
- public/homologation/rolesResponsabilites.js
- public/modules/elementsDom/services.mjs
- public/modules/soumetsHomologation.mjs
- src/adaptateurs/adaptateurMailSendinblue.js
- src/mss.js
- src/routes/routesService.js
- src/vues/deuxColonnes.pug
- src/vues/documentImprimable.pug
- src/vues/fragments/modaleNouveauService.pug
- src/vues/homologation/dossiers.pug
- src/vues/homologation/etapeDossier/1.pug
- src/vues/homologation/formulaireEtapier.pug
- src/vues/homologation/synthese.pug
- test/mocks/middleware.js
- test/routes/routesApiService.spec.js
- test/routes/routesPdf.spec.js
- test/routes/routesService.spec.js
- test/routes/testeurMSS.js
- test_public/modules/soumetsHomologation.spec.mjs
Cette PR fait suite à #593 et démarre une série de renommage des routes `homologation` en `service`.
On s'intéresse ici au renommage des routes `/homologation/*` en `/service/*`. On en profite pour renommer les dénominations « homologation » en « service » dans les fichiers changés, en s'en tenant aux noms avec une portée locale.
> [NETTOYAGE] Renommage routes homologation

- test/mocks/middleware.js
- test/routes/routesApi.spec.js
- test/routes/routesApiService.spec.js
- test/routes/testeurMSS.js
On utilise désormais un objet dans la méthode `reinitialise` pour faciliter l'utilisation d'objet personnalisé.
Cela permet aussi d'utiliser une homologation personnalisée lorsqu'on appele la fonction `trouveHomologation` dans le middleware de test.
Prémaniement du travail de l'étape décision.
> Améliore le middleware de test

- public/espacePersonnel.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
Cette PR fait suite à #695 et poursuit une série de renommage des routes `homologation` en `service`.
On s'intéresse ici au renommage des routes `/homologation/*` en `/service/*`. On en profite pour renommer les dénominations « homologation » en « service » dans les fichiers changés, en s'en tenant aux noms avec une portée locale.
> Renommage route `/api/homologations`

- .github/workflows/codeql-analysis.yml
La v1 de CodeQL est dépréciée https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
> Version 2 de CodeQL

- .env.template
- src/adaptateurs/adaptateurEnvironnement.js
- src/adaptateurs/adaptateurJournalMSSMemoire.js
… afin de ne pas avoir de logs polluants quand l'adaptateur est utilisé par les tests automatisés.
🧹 Pour vérifier que c'est clean, on peut regarder [les logs de la build](https://github.com/betagouv/mon-service-securise/actions/runs/4284218469/jobs/7460865905) qui ne montrent plus de `console.log` des événements du journal.
> Conditionne les logs dans la console du « Journal MSS mémoire »

- src/modeles/dossier.js
- test/modeles/dossier.spec.js
Cette PR répare un oubli.
Il faut bien interroger `datesTelechargements` pour savoir si un dossier est complet.
Exemple de problème qui peut arriver sans cette PR :
- créer une homologation
- télécharger seulement **un** document sur les 3
- en changeant l'URL du navigateur, aller à l'étape `date` de l'homologation
- remplir cette étape
- arriver ensuite sur l'étape « Récapitulatif » et cliquer « Enregistrer la décision »
- sans cette PR : on peut finaliser le dossier sans avoir téléchargé les 3 PDF à la première étape.
> Interroge `datesTelechargements` pour savoir si dossier est complet

- src/modeles/etapes/decision.js
- test/constructeurs/constructeurDossier.js
- test/modeles/dossier.spec.js
- test/modeles/dossiers.spec.js
En introduisant le constructeur de dossier pour les tests, on s'est rendu compte d'un bug :
Les tests étaient faux car `new Date(2023, 1, 1)` *correspond à Février* : Les mois sont indéxés en base 0, alors que `new Date("2023-01-01")` correspond bien au 1er Janvier.
Cette PR corrige les tests et montre ainsi le défaut dans l'implémentation, en introduisant un constructeur de dossier.
> Correction date homologation

- public/assets/styles/homologation/mesures.css
- src/vues/service/mesures.pug
Dans la page Sécurisé,
Le bouton Enregistrer et le footer deviennent sticky.
> Enregistrement sticky des mesures

- public/assets/styles/homologation/mesures.css
Dans la page Sécurisé,
le bouton collant n'était pas bien positionné.
> Correction position bouton collant des mesures

- src/modeles/dossier.js
- test/modeles/dossier.spec.js
On a trouvé un bug, lors de l'ajout de l'étape Autorité, les homologations qui étaient finalisées n'ont plus la coche verte car le dossier n'est plus `estComplet()`
> [CORRECTION] Vérifie que le dossier est finalisé pour être actif

- public/assets/styles/utilisateur.css
- src/vues/fragments/formulaireUtilisateur.pug
Dans les page /utilisateur/edition et /inscription,
nous ajoutons une information au champ téléphone
> Sous-titre informatif au champ téléphone

- test/routes/routesApiService.spec.js
C'est [ce log](https://github.com/betagouv/mon-service-securise/actions/runs/4314569761/jobs/7527775395#step:5:1123) que cette PR vient supprimer.
Avoir une stack trace dans les logs de nos tests : 👎👎👎  
Le prix à payer pour ne pas loguer l'exception semble trop élevé : bouchonner la console le temps du test, puis la remettre en place après le test.
Il faudrait plutôt que nos routes soient, par construction, robustes aux erreurs inattendues. Pourquoi pas un wrapper qui ajouterait lui-même ce `.catch()` qui devrait être systématique sur les routes d'API.
> Supprime un test qui logue une exception dans la console

- public/assets/styles/bouton.css
- public/assets/styles/homologation/mesures.css
- src/vues/service/mesures.pug
Cette PR pousse un cran plus loin l'intégration du footer d'enregistrement.
🎨 C'est seulement du CSS. Aucun JS modifié.
**AVANT**
**APRÈS**
L'inspiration vient des Figma existants où le footer est plus étoffé :
> Déplace le bouton « Ajouter une mesure spécifique » à côté de « Enregistrer »

- src/modeles/avis.js
- src/routes/routesApiService.js
- test/constructeurs/constructeurDossier.js
- test/modeles/avis.spec.js
- test/modeles/dossier.spec.js
- test/modeles/etapes/etapeAvis.spec.js
- test/modeles/homologation.spec.js
- test/routes/routesApiService.spec.js
Le champ `prenomNom` d'un avis de dossier n'est pas une chaine de caractères, mais un tableau de nom de collaborateurs.
> Remplace le champ `prenomNom` par une collection

- src/pdf/modeles/annexeMesures.pug
Dans l'annexe HTML des mesures, les caractères spéciaux venants de l'utilisateurs (modalités et description mesure spécifique) ont des caractères spéciaux échappés coté back.
> Affichage des caractères spéciaux dans l'annexe html des mesures

- src/pdf/modeles/annexeDescription.pug
Dans l'annexe HTML de description, les caractères spéciaux venants de l'utilisateurs (fonctionnalités supplémentaires et données supplémentaires) ont des caractères spéciaux échappés coté back.
> Affichage des caractères spéciaux dans l'annexe html de description

- src/pdf/modeles/annexeMesures.pug
- src/pdf/modeles/annexeRisques.pug
Dans le pdf HTML les sauts de page évite de diviser les descriptions des commentaires
> Mesures et risques avec commentaires indivisible

- src/vues/fragments/modaleNouveauService.pug
Cette PR supprime un `s` en trop 👇
> [CORRECTION] Supprime le « s » en trop

- src/adaptateurs/adaptateurPdf.js
… pour éviter une erreur de type :
```
mon-service-securise-web-1  | ProtocolError: Protocol error (Page.printToPDF): Printing failed
mon-service-securise-web-1  |     at /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
mon-service-securise-web-1  |     at new Promise (<anonymous>)
mon-service-securise-web-1  |     at CDPSessionImpl.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
mon-service-securise-web-1  |     at CDPPage.createPDFStream (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:746:88)
mon-service-securise-web-1  |     at CDPPage.pdf (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:772:37)
mon-service-securise-web-1  |     at generePdf …
```
> [CONTOURNEMENT] Ne génère pas d'annexe « risques » s'il n'y a aucun risque

- public/assets/styles/modale.css
Ce comportement n'est reproductible que sur Chrome.
Lors de l'affichage d'une modale, si la page comporte un slider de défilement, il disparait, entrainant un saut d'affichage de toute la page.
> Enlève le saut d'affichage lors de l'apparition d'une modale

- src/mss.js
En local, on ne souhaite pas rendre une "belle" page d'erreur en dernier recours, pour 2 raisons :
- Les erreurs remontées nous permettent souvent dans les phases de développement de comprendre où sont les problèmes
- Certains tests se basent sur le fait que le serveur crash
> Conditionne le rendu de la page d'erreur

- public/modules/elementsDom/services.mjs
- public/modules/interactions/saisieContributeur.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
… plutôt que de laisser l'utilisateur sans information.
On affiche un message : 
Cette PR trace une ébauche de gestion d'erreur où l'API renvoie un objet `{ erreur: { code: '…' } }`
> Affiche une erreur en cas d'invitation déjà envoyée

- donneesReferentiel.js
- src/referentiel.js
- test/modeles/avis.spec.js
- test/modeles/dossier.spec.js
- test/modeles/dossiers.spec.js
- test/modeles/etapes/etapeAvis.spec.js
- test/modeles/homologation.spec.js
- test/referentiel.spec.js
- test/routes/routesApiService.spec.js
Dans le référentiel, dans la clé `statutAvisDossierHomologation` il manquait un s à statut
> Erreur typographique au mot statuts

- public/assets/styles/etapesDossier/avis.css
- src/referentiel.js
- src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
- src/vues/service/etapeDossier/avis.pug
- test/referentiel.spec.js
Dans le parcours d'homologation,
La future étape 2 est pas encore accessible,
Ce dev est le corps d'une page non liée au parcours
Notes : 
- pour voir la page il faut modifier les donneesReferentiel en ajoutant `{ numero: 2, libelle: 'Avis', id: 'avis' },` à l'objet etapesParcoursHomologation
- Il ne se passe rien quand on clique sur ajouter un élément car les éléments ajoutables coté clients ne sont pas encore présent
- L'enregistrement à la soumission du formulaire n'est pas présent non plus
> Page étape avis sans possibilité d'ajouter des éléments

- public/homologation/etapesDossier.js
- public/modules/soumissionEtapeAvis.mjs
- test_public/modules/soumissionEtapeAvis.spec.mjs
Dans le parcours d'homologation,
La future étape 2 est pas encore accessible,
Ici on permet l'enregistrement des avis
NOTES :
pour voir la page il faut modifier les donneesReferentiel en ajoutant { numero: 2, libelle: 'Avis', id: 'avis' }, à l'objet etapesParcoursHomologation
> Permets la soumissions du formulaire des avis

- src/modeles/etapes/etapeAvis.js
- test/modeles/etapes/etapeAvis.spec.js
… pour respecter une demande métier.
La partie « UI » de cette évolution arrivera dans un second temps.
On peut dores et déjà supprimer l'avis ajouté par défaut, mais ce n'est pas l'UX finale.
> Considère que l'étape « Avis » est complète s'il n'y a aucun avis

- src/vues/mssConnexionEnCours.pug
- src/vues/mssDeconnecte.pug
Le lien est maintenant disponible dans le BOM.
Il y'a toujours une redirection dans `mss.js`, doit on l'enlever ?
```js
// Pour que les utilisateurs ayant cette page en favoris ne soient pas perdus.
app.get('/questionsFrequentes', (_requete, reponse) => {
reponse.redirect('https://aide.monservicesecurise.beta.gouv.fr');
});
```
> Supprime le lien vers `Questions fréquentes`

- public/assets/styles/homologation/formulaire.css
Dans la page avis du parcours d'homologation,
Les étiquettes et le menu contextuel des collaborateurs passe au dessus de la barre collant d'enregistrement
Avant :
Après :
NOTE : j'ai mis un z-index 10 comme le BOM car moins le menu contextuel passe au dessus et plus le BOM est en dessous
> Affichage des étiquettes collaborateurs au dessus de la barre collante

- public/homologation/etapes/avis.js
- src/modeles/dossier.js
- src/modeles/etapes/etapeAvis.js
- src/routes/routesApi.js
- src/routes/routesApiService.js
- src/utilitaires/aseptisation.js
- test/constructeurs/constructeurDossier.js
- test/modeles/dossier.spec.js
- test/modeles/etapes/etapeAvis.spec.js
- test/modeles/homologation.spec.js
- test/routes/routesApiService.spec.js
Cette propriété sera utile prochainement afin de sélectionner "avec avis" ou sans.
Cela permet d'avoir une relation 1:1 entre les données du domaine et ce qu'affiche le Front.
> Ajoute une propriété `avecAvis` à l'étape "Avis"

- migrations/20230327122127_ajouteOrganisationsResponsables.js
- public/modules/parametresDescriptionService.mjs
- src/modeles/descriptionService.js
- src/routes/routesApiService.js
- src/vues/fragments/formulaireDescriptionService.pug
- test/modeles/descriptionService.spec.js
- test/modeles/homologation.spec.js
- test/routes/routesApiService.spec.js
nous souhaitons pouvoir donner la possibilité d'ajouter l'organisation responsable.
Pour alimenter ce champ nous récupérerons le champ Nom de votre organisation de l'utilisateur si il existe.
NOTE : ce dev comporte une migration de données
> Organisations responsables

- src/modeles/dossier.js
- src/modeles/etapes/documents.js
- src/routes/routesApiService.js
- src/vues/service/etapeDossier/decision.pug
- test/constructeurs/constructeurDossier.js
- test/modeles/dossier.spec.js
- test/modeles/etapes/documents.spec.js
- test/modeles/homologation.spec.js
- test/routes/routesApiService.spec.js
On rajoute une étape dans le parcours d'homologation (back).
Cette étape a un comportement proche de l'étape "Avis" :
- On peut choisir de renseigner des documents, ou non
- Si oui, on doit fournir au moins un nom de document
Cette PR se concentre uniquement sur le back-end
> Etape document - Back

- public/homologation/etapes/avis.js
- public/modules/saisieListeItems.js
Cette PR ajoute et utilise un événement nouvellement lancé par la mécanique des éléments ajoutables.
> Coche le bouton radio « Aucun avis » lors de la suppression du dernier avis

- src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
Sans cette PR, les caractères spéciaux s'affichent mal 👇 
Cette PR répare l'affichage 👇
> [CORRECTION] Affiche l'identité des contributeurs sans caractères encodés

- donneesReferentiel.js
- src/modeles/dossier.js
- test/modeles/dossier.spec.js
On active maintenant l'étape "Documents" dans le parcours d'homologation.
On la rend obligatoire pour pouvoir terminer le parcours.
> :warning: [ETAPE DOCUMENTS] Activation - A merger en dernier

- public/homologation/etapes/documents.js
Il est actuellement possible de passer a l'étape suivante avec aucun documents :
- On enregistre un document
- On clique sur "aucun document"
- On clique de nouveau sur "un ou plusieurs document"
- On fait suivant
Cette PR corrige ce bug
> [CORRECTION] Force le vidage de l'input caché

- Dockerfile
Certaines dépendences de chromium ne s'installe pas correctement sur Docker Linux, on force donc le `--fix-missing`.
> [CORRECTION] Dockerfile linux - Chromium

- src/routes/routesService.js
- test/routes/routesService.spec.js
Dans l'espace personnel,
quand on crée un nouveau service,
le champ **Organisations responsables** est prérempli avec l'organisation de l'utilisateur créateur
> Organisation responsable d'un nouveau service préremplie

- public/homologation/mesures.js
Dans la page Sécuriser,
Quand on clique sur Ajouter une mesure spécifique,
Nous souhaitons être positionnés sur la nouvelle mesure
NOTE : J'ai mis ~~le focus sur~~ un scroll vers le champ Intitulé de la nouvelle mesure
> Focus après ajout d'une nouvelle mesure spécifique

- public/assets/styles/modale.css
La modale s'affiche désormais par dessus tout le reste.
> [CORRECTION] Affiche la modale par dessus tout le reste

- src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
Un utilisateur a fait remonter un bug :
> Problème d'encodage des caractères
Bonjour,
Dans l'avis formulé dans une homologation, les caractères «'» sont mal encodés.
Quand on revient sur le formulaire, ils sont remplacés par le code HTML.
Exemple :/    Les conditions d&#x27;hygiène informatique sont conformes aux attentes./
Serait-il possible d'y remédier car cela affecte ensuite les rapports ?
Cordialement.
On échappe donc désormais le champ correctement.
> [CORRECTION] Échappe correctement les commentaires d'avis

- public/assets/styles/homologation/descriptionService.css
- public/assets/styles/modules/validation.css
- public/homologation/descriptionService.js
- public/modules/soumetsHomologation.mjs
- src/routes/routesApiService.js
- src/vues/fragments/formulaireDescriptionService.pug
- test/routes/routesApiService.spec.js
- test_public/modules/soumetsHomologation.spec.mjs
Dans le cas ou le nom du service existe déjà, on affiche désormais un message d'erreur.
On passe désormais une callback d'erreur à l'adaptateur Ajax.
Le comportement `scrollIntoView` pourrait être utilisé à d'autres endroits pour indiquer quels champs de formulaire sont invalides.
> [NOUVEAU SERVICE] Message d'erreur "Nom de service déjà utilisé"

- public/assets/images/icone_ko_pastille_rose.svg
- public/assets/images/icone_ok_pastille_verte.svg
- public/assets/styles/carteInformations.css
Dans la page de synthèse,
Quand le service n'est pas / plus homologué,
La carte d'information adopte un nouveau style avec une croix.
> Carte non homologué

- src/vues/service/etapeDossier/date.pug
On ne doit la voir apparaître que sur la première étape
> Supprime la mention obligatoire sur l'étape date

- src/pdf/modeles/syntheseSecurite.pug
Cette PR règle un problème dans le cas ou certains chiffres sont à 0.
Ils étaient affichés tout de même, les uns sur les autres :
> [CORRECTION] Affiche les chiffres uniquement si ils existent

- src/vues/base.pug
Il y a de maigre chance que grace à cela google affiche MonServiceSécurisé à la place de Béta.gouv.
Pour info les balises open graph sont utilisées pour les réseaux sociaux (https://www.referenseo.com/guide-seo/open-graph/)
> Balise open graph avec le nom du site

- public/service/homologation/etapes/autorite.js
- public/service/homologation/etapes/avis.js
- public/service/homologation/etapes/documents.js
- public/service/homologation/etapes/etapeDate.js
- public/service/homologation/etapes/recapitulatif.js
- public/service/homologation/formulaireEtape.js
- src/routes/routesApiService.js
- src/routes/routesService.js
- src/vues/service/dossiers.pug
- src/vues/service/etapeDossier/decision.pug
- src/vues/service/formulaireEtapier.pug
- test/routes/routesApiService.spec.js
- test/routes/routesService.spec.js
Dans l'entreprise Homologations -> services ; dossiers -> homologations,
Cette PR correspond à la tache Routes `/service/:id/dossier/*` -> `/service/:id/homologation/*` de la checklist
PR précédente #822
Les routes concernées sont les routes des étapes du parcours homologuer et les routes api de ce parcours
> Changement des routes `dossier` en routes `homologation`

- public/assets/images/icone_ok_pastille_bleue.svg
- public/assets/styles/formulaire.css
- public/assets/styles/modules/selectize.css
- public/plugins/selectize.aucun-resultat.js
- public/utilisateur/suggestionEntite.js
- server.js
- src/adaptateurs/adaptateurAnnuaire.js
- src/mss.js
- src/referentiel.js
- src/routes/routesApi.js
- src/vues/fragments/formulaireUtilisateur.pug
- test/referentiel.spec.js
- test/routes/routesApi.spec.js
- test/routes/testeurMSS.js
Cette PR passe les champs « département » et « nom de l'organisation » de mode « Selectize ».
~~De plus, le champ « département de l'organisation » disparaît car cette information est désormais récupérée via l'API qui suggère les noms.~~
~~Donc lorsque l'utilisateur sélectionne son organisation dans la liste des suggestions, MSS récupère le département associé.~~
Pour « département » on utilise nos données de référentiel pour nourrir le `Selectize`.
Pour « organisation » on fait appel à l'API `https://recherche-entreprises.api.gouv.fr/search` via un adaptateur.
> Aide à la saisie pour l'organisation et son département

- src/pdf/graphiques/camembert.js
- test/pdf/graphiques/camembert.spec.js
Pour que la dernière section du camembert ne soit pas tronquée, il faut veiller à répartir les angles entre 0 et 360 degrés 👇 
De plus pour améliorer la lisibilité on passe à un angle minimum de 20 degrés.
> [CORRECTION] Angles de 360 degré maximum pour les camemberts

- src/pdf/graphiques/camembert.js
- src/pdf/modeles/ressources/styles.css
- src/pdf/modeles/syntheseSecurite.pug
- test/pdf/graphiques/camembert.spec.js
Dans cette PR, on ajuste la synthèse de sécurité :
- Limitation de la taille de la présentation
- Affichage du nombre au milieu du camembert en cas de mesure unique présente
- Correction du padding des camemberts
> [CORRECTION] Derniers ajustement pour la synthèse de sécurité

- src/vues/service/etapeDossier/documents.pug
Car le bouton précédent portait à confusion (sentiment de pouvoir upload un document)
> Remplace le bouton "Ajouter" de l'étape document

- src/adaptateurs/adaptateurMailSendinblue.js
- src/adaptateurs/adaptateurMailSurConsole.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
Nous nous sommes rendu compte que les contacts dans SendinBlue sont crées uniquement lorsque le premier email est **ouvert**.
Afin de préparer le comportement de l'infolettre, on souhaite créer systématiquement ce contact au moment de l'inscription.
De plus, cela nous permet de remplir les champs `PRENOM` et `NOM`.
> Création du contact dans SendinBlue à l'inscription

- migrations/20230426144428_ajoutChampInfolettreAcceptee.js
- public/assets/styles/formulaire.css
- public/assets/styles/modules/validation.css
- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
- src/adaptateurs/adaptateurMailSendinblue.js
- src/adaptateurs/adaptateurMailSurConsole.js
- src/modeles/utilisateur.js
- src/routes/routesApi.js
- src/vues/fragments/formulaireUtilisateur.pug
- test/modeles/homologation.spec.js
- test/modeles/utilisateur.spec.js
- test/routes/routesApi.spec.js
On s'interface avec SendinBlue pour gérer l'abonnement ou non à notre infolettre.
On souhaite mettre le champ `emailBlacklisted` à `true` ou `false` au moment de la création du contact.
Lors de la mise à jour du profil, si l'abonnement à l'infolettre change, on met à jour le contact chez SendinBlue via la route `PUT https://api.sendinblue.com/v3/contacts/{identifier}`
Le désabonnement depuis le mail vers MSS se fera dans une deuxième PR.
> [Newsletter] Acceptation infolettre

- src/routes/routesApi.js
- test/routes/routesApi.spec.js
La valeur était évaluée à `true` car `!undefined = true`.
On fixe la valeur à `false` pour éviter la confusion.
> [CORRECTION] Force l'acceptation de l'infolettre à `false` lors d'une invitation

- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
… en cas de caractère spécial dans le nom de service à dupliquer.
Exemple de scénario :
- Avoir un service nommé avec des parenthèses : « Service A (mairie) ».
- Dupliquer ce service : ça fonctionne et MSS trouve un nom « Service A (mairie) - Copie 1 ».
- Dupliquer à nouveau le service original.
Comportement attendu : que MSS trouve le nom « Service A (mairie) - Copie 2 ». Comportement observé : MSS trouve le nom « Service A (mairie) - Copie 1 - Copie 1 ». Montrant ainsi qu'il échoue à extraire l'index disponible dans ce cas-là.
Ce commit corrige le problème.
> [CORRECTION] Corrige un problème d'extraction d'index disponible

- creeUtilisateurDemo.js
- package-lock.json
- package.json
- src/adaptateurs/adaptateurPdf.js
- src/routes/routesApiService.js
- src/routes/routesApiServicePdf.js
- src/utilitaires/date.js
- test/routes/routesApiServicePdf.spec.js
On souhaite pouvoir télécharger tous les documents d'homologation dans un seul fichier au format `zip`.
Cette route n'est pas encore utilisée par le front.
> Route de téléchargement des documents d'homologation au format `zip` 

- src/routes/routesApi.js
- test/routes/routesApi.spec.js
… pour éviter les promesses concurrentes d'une part et d'autre part la sortie en erreur dans les tests :
```
✔ jette une erreur si l'utilisateur n'existe pas
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at new NodeError (node:internal/errors:399:5)
at ServerResponse.setHeader (node:_http_outgoing:663:11)
…
```
On en profite pour supprimer le test et le code de vérification de l'existence de l'utilisateur, car c'est déjà assuré par le middleware `verificationJWT`.
> [CORRECTION] Chaîne proprement les promesses de mise à jour de l'utilisateur

- src/vues/service/dossiers.pug
Les étapes "Décision" et "DateTéléchargement" sont inversées entre notre front et notre back. Il y a donc un problème de redirection lorsque l'étape 4 `estComplete`.
> Pointe vers l'étape courante si un dossier d'homologation existe déjà

- donneesReferentiel.js
- src/vues/service/etapeDossier/dateTelechargement.pug
- src/vues/service/etapeDossier/decision.pug
- test/routes/routesService.spec.js
Avant ce commit, les étapes `decision` et `dateTelechargement` étaient inversées dans notre modèle.
Une explication est l'influence du wording utilisé par le front : l'étape de téléchargement utilise le libellé « Décision » et l'étape d'enregistrement de la décision utilise le libellé « Date ».
> [CORRECTION] Enchaîne correctement les étapes du parcours d'homologation

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/gestionnaireTiroir.mjs
- public/modules/tableauDeBord/tableauDesServices.mjs
- src/modeles/homologation.js
- src/modeles/objetsApi/objetGetServices.js
- src/vues/tableauDeBord.pug
- test/modeles/homologation.spec.js
- test/modeles/objetsApi/objetGetServices.spec.js
Dans le tiroir de téléchargement des PDFs, cette PR explicite le cas où le dossier de décision d'homologation est indisponible.
Conteneur grisé & nombre de documents qui passe à « 2 »👇
> [TDB] Adaptation des documents disponibles au téléchargement

- public/assets/styles/formulaire.css
… pour éviter d'avoir 👇 
Le résultat 👇
> [CORRECTION] Conserve toujours la pleine largeur des checkboxes

- server.js
- src/adaptateurs/adaptateurPdf.js
- src/adaptateurs/adaptateurZip.js
- src/mss.js
- src/routes/routesApi.js
- src/routes/routesApiService.js
- src/routes/routesApiServicePdf.js
- test/routes/routesApiServicePdf.spec.js
- test/routes/testeurMSS.js
… pour les services qui n'ont pas de dossier d'homologation en cours.
Car pour ces services, les données nécessaires au dossier de décision sont indisponibles.
> Exclure le dossier de décision de l'archive « Tous les documents »

- public/assets/styles/bom.css
- public/assets/styles/mss.css
- public/modules/tableauDeBord/gestionnaireActionsTiroir.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- public/modules/tableauDeBord/gestionnaireTiroir.mjs
- public/scripts/bom.js
On souhaite cacher le BOM à l'ouvreture du tiroir d'actions afin de ne pas les afficher l'un sur l'autre.
> Cache bom lorsque le tiroir est ouvert

- public/modules/tableauDeBord/tableauDesServices.mjs
... car le tri faisait une comparaison à `null` au lieu de `AUCUNE`, donc le tri ne revenait plus jamais en position initiale.
> [CORRECTION] Tri correctement en fonction de la direction AUCUNE

- public/assets/styles/entete.css
- public/assets/styles/modale.css
On supprime la possibilité de fermer la modale de déconnexion afin de forcer les utilisateurs à se reconnecter.
On en profite pour styliser proprement le bouton de reconnexion.
> [CORRECTION] Fermeture modale deconnexion

- public/assets/styles/formulaire.css
- public/assets/styles/mss.css
- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/tableauDesServices.mjs
- src/modeles/objetsApi/objetGetIndicesCyber.js
- src/modeles/objetsApi/objetGetServices.js
- src/routes/routesApi.js
- src/vues/tableauDeBord.pug
- test/modeles/objetsApi/objetGetIndicesCyber.spec.js
- test/modeles/objetsApi/objetGetServices.spec.js
- test/routes/routesApi.spec.js
Après investiguation, on se rends compte que le calcul de l’indice cyber est très lent, ce qui rend la récupération des services très longues.
On déplace donc l’obtention des informations d'indice cyber sur une deuxième route.
On afficher un "loader" en attendant que l'info soit récupérée.
> Perfomance get services

- public/assets/styles/tableauDeBord.css
Actuellement, il est possible de `focus` le tiroir même si il n'est pas ouvert.
- Aller sur la page du tableau de bord
- Focus sur le champ de recherche
- Appuyer sur tab plusieurs fois jusqu’à arriver au focus du tiroir qui n’est pourtant pas visible
On intercepte donc l'event de scroll et on le conditionne en fonction de l'état d'ouverture du tirroir.
> Empêche le focus dans le tiroir si il n'est pas ouvert

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- public/modules/tableauDeBord/gestionnaireTiroir.mjs
- public/modules/tableauDeBord/tableauDesServices.mjs
- src/vues/tableauDeBord.pug
Nous remettons en forme les actions de service pour coller avec les nouvelles maquettes Figma, suite aux retours UX.
Les actions s'affichent désormais dans un format "barre d'outils".
> [TDB] Barre d'outils des actions de service

- public/modules/tableauDeBord/tableauDesServices.mjs
Afin de montrer que la recherche ne donne aucun résultat et ne pas cacher tout le tableau.
> [TDB] Affichage en cas de recherche sans résultats

- donneesReferentiel.js
- src/modeles/homologation.js
- src/referentiel.js
- test/modeles/homologation.spec.js
- test/modeles/objetsApi/objetGetServices.spec.js
- test/referentiel.spec.js
- test/routes/routesApiServicePdf.spec.js
On souhaite maintenant rendre le dossier de décision disponible uniquement si :
- Il y a un `dossierCourant`
- Ce `dossierCourant` est au moins à une étape précise (dans notre cas, étape `décision`)
On ajoute donc cette indication d'étape au données du référentiel.
> Disponibilité du dossier de décision

- public/assets/styles/tableauDeBord.css
- src/vues/tableauDeBord.pug
… qui n'est pas pertinent tant que les statuts d'homologations ne sont pas plus détaillés.
L'indicateur de tri disparaît donc sur la colonne 👇
> Enlève le tri sur la colonne « Homologation »

- public/assets/styles/formulaire.css
- public/assets/styles/tableauDeBord.css
Les checkbox sont stylisées afin de coller à notre UI Kit.
On doit donc forcer le `cursor: pointer` qui n'est pas le comportement par défaut.
> [CORRECTION] Ajoute le curseur 'pointer' sur toutes les checkbox

- public/modules/tableauDeBord/gestionnaireEvenements.mjs
Afin de ne pas faire une requête GET par défaut.
> [CORRECTION] Empêche la soumission des formulaires dans le tiroir des actions

- src/adaptateurs/adaptateurCsv.js
- src/routes/routesApi.js
- src/utilitaires/tableau.js
- test/routes/routesApi.spec.js
- test/utilitaires/tableau.spec.js
L'indice cyber avait disparu suite au changement visant à séparer le chargement de l'indice cyber de toutes les autres données, pour favoriser le _time to pixel_ du tableau de bord.
> [CORRECTION] Réintégration de l'indice cyber dans l'export CSV

- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- src/modeles/utilisateur.js
- test/modeles/utilisateur.spec.js
Suite aux démo, on enlève les `…` utilisés lorsque les infos sont manquantes 👇 
On laisse chaîne vide.
> Correction dans l'affichage des postes sur le tableau de bord

- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- public/modules/tableauDeBord/tableauDesServices.mjs
Avec ce fix, quand on est dans un cas de filtre + sélection 👇 
Cliquer sur la checkbox désélectionne tous les services, comme il se doit.
Avant ce commit, rien ne se passait dans ce cas.
> Correction du comportement de la checkbox « sélection tous service »

- donneesReferentiel.js
- src/modeles/dossier.js
- src/modeles/dossiers.js
- src/referentiel.js
- test/constructeurs/constructeurDossier.js
- test/modeles/dossier.spec.js
- test/modeles/dossiers.spec.js
Afin de pouvoir utiliser les nouveaux statuts d'homologation dans le tableau de bord et la synthèse, on met en place de nouvelles règles métier. :point_down:
> Ajoute les statuts d'homologations

- .env.template
- server.js
- src/adaptateurs/adaptateurEnvironnement.js
- src/adaptateurs/adaptateurMailSendinblue.js
- src/adaptateurs/adaptateurTrackingMemoire.js
- src/adaptateurs/adaptateurTrackingSendinblue.js
- src/mss.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
- test/routes/testeurMSS.js
On ajoute maintenant un adaptateur pour envoyer à SendinBlue des événements de cycle de vie utilisateur, afin d'envoyer des emails transactionnels.
La documentation de l'API est [ici](https://tracker-doc.brevo.com/reference/trackevent-3).
:warning: Mettre les variables d'env Scalingo à jour :
- Ajouter `SENDINBLUE_TRACKING_CLEF_API`
- Renommer `SENDINBLUE_CLEF_API` en `SENDINBLUE_EMAIL_CLEF_API`
> [Tracking SendinBlue] Événement de connexion

- src/adaptateurs/adaptateurTrackingSendinblue.js
Le champ `properties` permet d'agir sur les workflows d'envoie de mail, donc c'est ce que l'on cherche à faire.
Le champ `eventdata` est en fait réservé pour les données servant à 'customiser' le contenu d'un mail. Nous pourrons nous en servir par la suite.
> [CORRECTION] Utilise le champs `properties` au lieu du champ `eventdata`

- src/adaptateurs/adaptateurTrackingMemoire.js
- src/adaptateurs/adaptateurTrackingSendinblue.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
- test/routes/testeurMSS.js
On souhaite tracker les events d'inscription pour pouvoir relancer les personnes qui ne reviennent pas sur la plateforme.
On ne prend pas en compte les personnes qui sont invitées à collaborer (uniquement inscription 'volontaire')
> [Tracking SendinBlue] Événement d'inscription

- src/modeles/dossier.js
- src/modeles/dossiers.js
- test/constructeurs/constructeurDossier.js
- test/modeles/dossier.spec.js
- test/modeles/dossiers.spec.js
En attendant d'explorer tous les cas aux limites, on accepte le fait que le cas par défaut pour un statut d'homologation soit 'À réaliser'.
Cela implique de vérifier explicitement si un dossier est expiré ou non.
> [CORRECTION] Cas par défaut des statuts d'homologation

- donneesReferentiel.js
- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/tableauDesServices.mjs
- src/modeles/objetsApi/objetGetServices.js
- src/referentiel.js
- src/routes/routesApi.js
- src/vues/tableauDeBord.pug
- test/modeles/objetsApi/objetGetServices.spec.js
- test/referentiel.spec.js
- test/routes/routesApi.spec.js
On intègre les nouveaux status d'homologation 'Bientôt expirée' et 'Expirée' à l'affichage du tabeau de bord.
Le tri est maintenant possible sur cette colonne, en suivant la règle :
> Le classement des homologations par ordre croissant (niveau plus urgent au moins urgent) est : expiré, bientôt expiré, à finaliser, réalisée, à réaliser.
> [TDB] Statuts d'homologation

- src/modeles/parcoursUtilisateur.js
- src/referentiel.js
- test/modeles/parcoursUtilisateur.spec.js
- test/referentiel.spec.js
On introduit un nouveau modèle permettant d'historiser le parcours d'un utilisateur.
Dans ce cas, on souhaite pouvoir connaître la dernière date de connexion, afin de savoir si de nouvelles fonctionnalités ont étés déployées depuis.
___
> [Carrousel] Modèle parcours utilisateur

- .env.template
- server.js
- src/adaptateurs/adaptateurEnvironnement.js
- src/adaptateurs/adaptateurTrackingMemoire.js
- src/adaptateurs/adaptateurTrackingSendinblue.js
- src/adaptateurs/fabriqueAdaptateurTracking.js
- src/depotDonnees.js
- src/depots/depotDonneesHomologations.js
- test/constructeurs/constructeurService.js
- test/depots/depotDonneesHomologations.spec.js
- test/routes/testeurMSS.js
On souhaite tracer les événements de création / duplication de nouveaux services.
L'envoi s'opère lors d'une nouvelle homologation au même moment où on consigne les événements.
> [Tracking Sendingblue] Événement nouveau service créé

- .env.template
- test/constructeurs/constructeurAdaptateurPersistanceMemoire.js
- test/constructeurs/constructeurDepotDonneesServices.js
- test/depots/depotDonneesHomologations.spec.js
Facilite l'initialisation des tests afin de masquer certains détails d'implémentations qui suivant les contextes embrouillent la compréhension et l'intention.
> [REMANIEMENT] Extraction constructeurs test

- src/adaptateurs/adaptateurChiffrement.js
- src/depots/depotDonneesUtilisateurs.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/mocks/adaptateurChiffrement.js
… car il s'agit bel et bien de hachage et non de chiffrement – puisque le déchiffrement est impossible.
Si on laisse `chiffre` comme nom, alors ça va compliquer l'arrivée du code qui chiffrera réellement les données métier puisqu'il va vouloir créer une fonction `chiffre()`.
> Renomme les fonctions de hachage utilisant `bcrypt`

- src/referentiel.js
- src/routes/routesApi.js
- src/vues/nouvellesFonctionnalites/tableauDeBord.pug
- test/referentiel.spec.js
- test/routes/routesApi.spec.js
On ajoute la route qui sert le contenu HTML d'une nouvelle fonctionnalité.
On ajoute aussi le premier PUG concernant le tableau de bord, afin de faciliter les tests et préparer l'affichage.
Cependant, cette nouvelle fonctionnalité n'est pas encore ajouté au référentiel car non disponible.
> [Carrousel] Route `/nouvelleFonctionalite`

- src/adaptateurs/adaptateurChiffrement.js
- src/depotDonnees.js
- src/depots/depotDonneesHomologations.js
- test/constructeurs/constructeurDescriptionService.js
- test/depots/depotDonneesHomologations.spec.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/depots/depotVide.js
- test/mocks/adaptateurChiffrement.js
- test/modeles/homologation.spec.js
Cette PR pose les tuyaux qui permettent de chiffrer toutes les données voulues dans _« Description Service »_.
L'implémentation PROD du chiffrement est la fonction identité.
➡️ Donc à l'exécution rien n'est encore chiffré.
📋  La suite du plan : 
- PR pour poser les tuyaux pour déchiffrer la description du service (en faisant attention aux fonctions de recherche par nom)
- PR pour implémentation réelle du chiffrement/déchiffrement + migration
> Branchement du chiffrement des données de « Description Service »

- donneesReferentiel.js
On ajoute une entrée dans `donneesReferentiel` afin d'afficher dès demain le carrousel de nouveautés.
> [Carrousel] Déploie la nouvelle fonctionnalité du tableau de bord

- public/assets/styles/nouvellesFonctionnalites.css
- public/nouvellesFonctionnalites.js
- src/vues/nouvellesFonctionnalites.pug
On peut désormais afficher le carrousel 'à la demande' depuis la page `/nouvellesFonctionnalites`.
:point_down:
> [Carrousel] Ajoute un bouton pour afficher une nouvelle fonctionnalité dans la page dédiée

- public/modules/tableauDeBord/gestionnaireEvenements.mjs
... si on clique n'importe ou à l'extérieur du menu.
On utilise `$(document)` pour intercepter tous les événements de click, et on s'assure qu'on ne soit ni sur l'entête, ni dans le contenu du menu grâce à la méthode `parents()`.
> [CORRECTION] Ferme le menu flottant de tri de contributeurs

- test/modeles/parcoursUtilisateur.spec.js
… pour que l'adaptateur horloge passé soit bel et bien utilisé.
Exemple de test fail : https://github.com/betagouv/mon-service-securise/actions/runs/5320676346/jobs/9634768769?pr=943
> [CORRECTION] Corrige l'appel au constructeur de `ParcoursUtilisateur`

- src/referentiel.js
- test/constructeurs/constructeurDepotDonneesServices.js
- test/constructeurs/constructeurDescriptionService.js
- test/depots/depotDonneesHomologations.spec.js
Lors de l'appel au constructeur de service, la fonction `uneDescriptionValide` force la recharge du référentiel en le modifiant avec les données du référentiel à vide ce qui avait un effet de bord dans les tests.
Le but est de pouvoir bénéficier d'un référentiel cohérent de bout en bout dans les tests.
> [Remaniement] Ajoute une fonction enrichis au constructeur de service

- src/adaptateurs/adaptateurTrackingMemoire.js
- src/adaptateurs/adaptateurTrackingSendinblue.js
- src/depots/depotDonneesHomologations.js
- src/tracking/serviceTracking.js
- test/constructeurs/constructeurDepotDonneesServices.js
- test/depots/depotDonneesHomologations.spec.js
- test/tracking/serviceTracking.spec.js
Permet d'envoyer la complétude des services vers Sendingblue lorsqu'un nouveau service est créé
> [Tracking Sendingblue] Envoie la completude vers Sendingblue lors de la création d'un nouveau service

- src/depots/depotDonneesHomologations.js
- test/constructeurs/constructeurUtilisateur.js
- test/depots/depotDonneesHomologations.spec.js
- test/tracking/constructeurServiceTracking.js
Permet d'envoyer la complétude vers Sendingblue lorsque la description du service est mise à jour
> [Tracking Sendingblue] Envoie évenement tracking complétude ajout description service

- src/modeles/objetsApi/objetGetServices.js
- test/modeles/objetsApi/objetGetServices.spec.js
On chercher à exposer un objet générique de permissions afin que le front puisse être conditionné sur des actions.
Ceci à pour but de faciliter le travail futur qui sera effectué sur les rôles (lecture/écriture).
Pour l'instant, on se base uniquement sur l'utilisateur qui fait la demande, si il est créateur ou non.
> Enrichis l'objet get services avec des permissions

- .env.template
- src/vues/cgu.pug
… au lieu de la version `.beta.gouv.fr` que nous abandonnons petit à petit.
Note :
- Pour l'instant `aide.monservicesecurise.beta.gouv.fr` n'est **pas** remplacée. Ça va nécessiter de synchroniser (A) la modifications des entrées DNS avec (B) le changement et déploiement de notre code source et (C) le changement de configuration côté Crisp.
- L'email `contact@mss.beta.gouv.fr` reste inchangé. Le sujet des emails en `@monservicesecurise.ssi.gouv.fr` est en discussion.
> Référence l'URL en `.ssi.gouv.fr`

- src/adaptateurs/adaptateurMailSendinblue.js
- src/adaptateurs/adaptateurTrackingSendinblue.js
On fait apparaître les `response.data` des erreurs remontées par Brevo afin d'avoir une meilleur visibilité coté Sentry.
> [SENTRY] Loggue les erreurs Brevo vers Sentry

- public/assets/images/icone_contributeurs_actifs.svg
- public/assets/images/icone_contributeurs_attente_activation.svg
- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- src/vues/tableauDeBord.pug
On sépare les contributeurs en 2 listes :
- les contributeurs qui ont un compte 'actif'
- les contributeurs qui ne se sont jamais connectés sur MSS
On utilise le champ `cguAcceptee` comme vu précédemment ensemble.
> [TDB] Contributeurs en attente d'activation

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- src/vues/tableauDeBord.pug
À la suite d'une faute d'orthographe propagée pour le menu flottant.
> [CORRECTION] Corrige 'flotant' en 'flottant'

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- src/vues/tableauDeBord.pug
À la suite d'une faute d'orthographe propagée pour le menu flottant.
>  [CORRECTION] Corrige 'flotant' en 'flottant'

- migrations/20230627141030_archivageDossiersHomologations.js
- test_migrations/20230627141030_archivageDossiersHomologations.spec.js
On rajoute la propriété `archive` à tous les dossiers existants en suivant ces règles : 
- Les dossiers non `finalise` ne sont par archivés (dossier en cours)
- On archive tous les dossiers `finalise` sauf le plus récent (en se basant sur `decision.dateHomologation`)
- On archive systématiquement tout dossier dont la structure est compromise (`finalise` sans `decision` ou sans `dateHomologation`)
Afin de garantir l'exactitude de cette migration, on pourra utiliser la méthode `archiveDossiers` sur des données brutes en démo.
> [MIGRATION] Archive les anciens dossiers d'homologations

- src/modeles/objetsApi/objetGetServices.js
- test/modeles/objetsApi/objetGetServices.spec.js
Le compteur de services homologués ne fonctionnait plus à cause du changement des statuts d'homologations.
> [CORRECTION] Compteur de services homologués

- src/modeles/objetsApi/objetApiStatutHomologation.js
- src/routes/routesService.js
- test/modeles/objetsApi/objetApiStatutHomologation.spec.js
Il avait été créé dans `objetsVue` par erreur.
> Déplace un objet API dans le bon répertoire

- src/modeles/homologation.js
- src/modeles/objetsApi/objetApiUtilisateur.js
- src/modeles/utilisateur.js
- src/mss.js
- src/routes/routesApi.js
- src/vues/motDePasse/edition.pug
- test/constructeurs/constructeurUtilisateur.js
- test/modeles/homologation.spec.js
- test/modeles/objetsApi/objetApiUtilisateur.spec.js
- test/modeles/utilisateur.spec.js
- test/mss.spec.js
- test/routes/routesApi.spec.js
On cherche à découpler les objets qui transite par l'API, les modèles et les objets de persistance.
Dans cette PR, on créer une représentation `API` pour le modèle `Utilisateur` afin de pouvoir modifier le modèle sans casser les contrats d'API (pour la feature `Fonction/poste`).
> [REMANIEMENT] Objet API pour le modèle `Utilisateur`

- migrations/20230704144300_ajouteChampPostes.js
- src/modeles/utilisateur.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
On ajoute le champ `postes` pour préparer la modification du front.
On 'craft' ce champ en fonction de l'existant sur l'API.
On réalise une migration pour ajouter ce champ chez tous nos utilisateurs.
> Ajout du champ `postes` dans le modèle `Utilisateur`

- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
Il était possible de soumettre le formulaire sans valeur de 'Fonction/poste'
> [CORRECTION] Le champ postes ne doit pas accepter de valeur vide

- src/http/configurationServeur.js
Afin de garantir que Brevo ai le droit de nous contacter sur cette route.
> Ajoute la route `/api/desinscriptionInfolettre` dans la liste des endpoints sans CSRF

- src/mss.js
- src/routes/privees/routesApiPrivee.js
- src/routes/publiques/routesApiPublique.js
- test/mocks/middleware.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/publiques/routesApiPublique.spec.js
Plutôt que de demander à chaque route privée de penser à positionner le middleware `verifieJWT`, on passe à une sécurité par construction où le middleware est positionné devant le routeur privé au global.
Faite en binôme cc @ThibaudMZN
> [REMANIEMENT] Utilisation d'une vérification JWT unifiée sur les routes privées

- src/mss.js
- src/routes/privees/routesApiPrivee.js
- src/routes/privees/routesApiService.js
- src/routes/privees/routesApiServicePdf.js
- src/routes/privees/routesService.js
- test/routes/privees/routesApiService.spec.js
- test/routes/privees/routesApiServicePdf.spec.js
- test/routes/privees/routesService.spec.js
Pour assurer la cohérence de la base de code, on déplace ces routes.
> [REMANIEMENT] Regroupe toutes les routes privée dans `routes/privees`

- src/routes/mappeur/utilisateur.js
- src/routes/privees/routesApiPrivee.js
- src/routes/publiques/routesApiPublique.js
Le code avait été dupliqué lorsque nous avons séparé les routes publiques et privées dans des fichiers distincts.
> [REMANIEMENT] Supprime la duplication de code de mapping

- public/motDePasse/validationMotDePasse.mjs
- src/http/validationMotDePasse.js
- src/routes/privees/routesApiPrivee.js
- test/http/validationMotDePasse.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test_public/motDePasse/validationMotDePasse.spec.mjs
La logique qui était pertinente lorsqu'on était en transition vers une page dédiée au changement de mot de passe n'est plus utile. Pendant cette période le code devait gérer des appels depuis la page « Profil utilisateur » (qui avait les champs de changement de MDP) et depuis la nouvelle page « Mot de passe ».
Maintenant : tout passe par la page « Mot de passe ».
Donc on fait les nettoyages suivants :
- Le mot de passe chaîne vide n'est plus valide.
- Appeler l'API sans valeur pour `motDePasse` n'est plus un 204.
- La vérification du type « chaîne » est faite par la fonction de validation, plus par l'API. Par contre, côté front on ne fait pas cette vérification, car le mot de passe est obtenu par ``` const motDePasse = $champMdp.val(); ``` qui renvoie forcément une chaîne.
> [NETTOYAGE] Nettoie la validation de mot de passe

- src/modeles/statistiquesMesures.js
- src/pdf/graphiques/camembert.js
- src/pdf/modeles/ressources/styles.css
- src/pdf/modeles/syntheseSecurite.pug
- test/modeles/statistiquesMesures.spec.js
- test/pdf/graphiques/camembert.spec.js
- Créer un service
- Afficher sa synthèse PDF
- Voir qu'on a (pour cet exemple) 25 mesures « À remplir » dans la section blanche du Camembert « Indispensable »
- Retourner sur « Sécuriser » et cocher à « Faite » 1 mesure indispensable
- Ré-afficher la synthèse PDF
Attendu : le chiffre dans le camembert blanc est maintenant 24, puisqu'on a coché 1 mesure.
Observé : le chiffre est toujours à 25, alors qu'on voit apparaître la section « Faites » qui a le chiffre 1.
Une régression est apparue au moment où on a passé la synthèse PDF en Puppeteer.
Dans la version avant Puppeteer, le calcul des `aRemplir` était fait dans un `.js` côté client.
Et ce calcul n'a pas été porté dans la version Puppeteer.
On peut voir ce calcul dans le commit …
> [CORRECTION] Le chiffre dans le camembert « À remplir »

- src/vues/base.pug
Cet attribut est nécessaire pour l'accéssibilité de la page.
> Ajoute l'attribut `lang` dans l'HTML de base

- src/http/middleware.js
- src/routes/privees/routesApiPrivee.js
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/routes/privees/routesApiPrivee.spec.js
On ajoute une route pour modifier son mot de passe lorsqu'on est connecté.
Cette route reprend le fonctionnement de la route `POST /motDePasse`, sans vérification des CGUs mais avec vérification du mot de passe actuel via le middleware `challengeMotDePasse`
> Ajoute la route `PATCH /motDePasse`

- src/vues/motDePasse/edition.pug
Afin d'être plus cohérent en cas de création de mot de passe :point_down:
> Conditionne l'affichage du titre de la page d'édition de mot de passe

- docker-compose.yml
- scripts/init-mss-crypto.sh
On ajoute un conteneur [Hashicorp Vault](https://www.vaultproject.io/) pour gérer le chiffrement/déchiffrement des données de MSS en local.
On utilise une clé d'encryption 'statique' afin qu'elle soit la même à chaque redémarrage du conteneur, mais aussi qu'elle soit partagé entre le pôle dev pour une meilleur facilité à chiffrer/déchiffrer les données de la même manière.
> Ajoute un conteneur docker 'Vault' pour gérer le chiffrement

- src/routes/privees/routesApiServicePdf.js
- test/routes/privees/routesApiServicePdf.spec.js
Le fichier dans l'archive ZIP avait une typo: `DossierDecison` -> `DossierDecision`
> [CORRECTION] Wording du nom de fichier

- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- src/modeles/objetsApi/objetGetServices.js
- src/vues/tableauDeBord.pug
- test/modeles/objetsApi/objetGetServices.spec.js
Afin de ne pas donner d'information sur le statut des comptes sur MSS, on supprime cette distinction dans le tiroir contributeur.
_La partie En attente d'activation du compte MonServiceSécurisé n'est plus présente_
> Retire l'info 'En attente de création de compte MSS'

- public/assets/styles/formulaire.css
- src/vues/fragments/formulaireUtilisateur.pug
Afin de mieux séparer la case infolettre du bloc `Fonction/poste` :point_down:
> Ajoute un fond et un titre sur la case infolettre

- migrations/20230719132333_ajouteChampTransactionnelAccepte.js
- src/modeles/utilisateur.js
- src/routes/privees/routesApiPrivee.js
- src/routes/publiques/routesApiPublique.js
- test/modeles/homologation.spec.js
- test/modeles/utilisateur.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/publiques/routesApiPublique.spec.js
On ajoute le champ `transactionnelAccepte` sur `Utilisateur`.
Ce champ est à `true` par défaut.
Il est forcé à `true` sur les routes d'inscription et de modification de profil.
Il n'est pas possible de le modifier pour l'instant.
> Ajoute champ mailing transactionnel - Utilisateur

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/actions/Action.mjs
- public/modules/tableauDeBord/actions/ActionDuplication.mjs
- public/modules/tableauDeBord/actions/ActionInvitation.mjs
- public/modules/tableauDeBord/actions/ActionSuppression.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- public/motDePasse/edition.js
- public/tableauDeBord.js
- src/routes/privees/routesApiService.js
- src/vues/tableauDeBord.pug
- test/mocks/middleware.js
- test/routes/privees/routesApiService.spec.js
On vérifie maintenant l'action de suppression grâce à une 'ré-authentification' : on re-demande le mot de passe de l'utilisateur.
On utilise le middleware `challengeMotDePasse` mit en place précédemment.
> Verification du mot de passe sur action critique - Suppression de service

- package-lock.json
- package.json
Les dépendances avec vulnérabilités qui sont changées par ce commit :
```
semver  <=5.7.1 || 6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install nodemon@3.0.1, which is a breaking change
node_modules/eslint-config-airbnb-base/node_modules/semver
node_modules/eslint-plugin-react/node_modules/semver
node_modules/make-dir/node_modules/semver
node_modules/nodemon/node_modules/semver
node_modules/semver …
```
> Exécute `npm audit fix --force` pour rester à jour

- .env.template
- src/adaptateurs/adaptateurMailSendinblue.js
De cette façon, nous pourrons utiliser Sendinblue pour inviter les utilisateurs à revenir sur MSS pour finir leur travail démarré.
L'attribut `listIds` est détaillé [sur la page de doc de l'API `createContact`](https://developers.brevo.com/reference/createcontact#form-body-createContact)
💻  Il faut créer la variable d'env. `SENDINBLUE_ID_LISTE_POUR_MAILS_TRANSACTIONNELS_DE_RELANCE ` chez Scalingo
> Ajoute les inscrits MSS aux destinataires des emails transactionnels de relance

- test/routes/privees/routesApiPrivee.spec.js
Et au passage on améliore `convertit l'infolettre acceptée en valeur booléenne` qui n'échouait pas si l'API cessait d'appeler le dépôt de données.
> Passe les tests en `async/await`

- server.js
- src/adaptateurs/adaptateurMailMemoire.js
- src/modeles/utilisateur.js
- src/routes/privees/routesApiPrivee.js
- test/constructeurs/constructeurUtilisateur.js
- test/modeles/utilisateur.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/testeurMSS.js
Ça recentre la responsabilité. Et ça va faciliter l'arrivée de la MAJ du canal « email transactionnel ».
Le code de l'API devient trivial, et sera facilement extensible :
```js
depotDonnees
.utilisateur(idUtilisateur)
.then((utilisateur) =>
utilisateur.changePreferencesCommunication(
{ infolettreAcceptee: donnees.infolettreAcceptee },
adaptateurMail
)
)
.then(() => depotDonnees.metsAJourUtilisateur(idUtilisateur, donnees))
```
> Déplace la MAJ des préférences de communication dans `Utilisateur`

- consoleAdministration.js
On est obligé d'appeler plusieurs fois le détail de la liste, pour obtenir tous les contacts.
Exemple d'output si on fixe la taille des paquets à 10 👇 
Dans le code, la taille est à 500 : le max autorisé par Brevo.
> Prends en compte la pagination imposée par l'API Brevo

- test/depots/depotDonneesHomologations.spec.js
Sans ce commit, si les tests sont exécutés alors que `process.env.SENDINBLUE_TRACKING_CLEF_API` est valorisée alors les tests utilisent une implémentation concrète de l'adaptateur de Tracking.
On évite ce problème en fournissant explicitement une implémentation mémoire.
> [CORRECTION] Utilise explicitement l'adaptateur Tracking mémoire dans les tests

- src/routes/privees/routesService.js
- src/vues/cartes/statutHomologation.pug
- src/vues/service/mesures.pug
- src/vues/service/synthese.pug
- test/routes/privees/routesService.spec.js
On veut les mêmes cartes que sur la page d'accueil du service.
Le résultat 👇 
La carte `statutHomologation` était la seule qui n'était pas un mixin indépendant.
C'est chose faite dans cette PR.
> Ajoute des cartes sur la page « Sécuriser »

- src/adaptateurs/adaptateurTrackingMemoire.js
- src/adaptateurs/fabriqueAdaptateurTracking.js
- test/constructeurs/constructeurDepotDonneesServices.js
Afin que les tests puissent redéfinir certaines fonctions sans toucher à l'implémentation d'origine.
> Crée une méthode de fabrication de l'adaptateur Tracking Mémoire

- server.js
- src/adaptateurs/adaptateurTrackingMemoire.js
- src/mss.js
- src/routes/privees/routesApiPrivee.js
- src/routes/procedures.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/testeurMSS.js
L'objectif est de déporter certaines logiques portées par les routes d'API dans des procédures isolées de la couche HTTP.
En créant un conteneur de procédures, on pourra bouchonner les procédures appelées dans les tests.
Dans l'immédiat c'est #1038 qui va être le premier utilisateur de ce conteneur.
> Création d'un conteneur de procédures

- src/depots/depotDonneesUtilisateurs.js
- test/depots/depotDonneesUtilisateurs.spec.js
De cette façon, tous les nouveaux inscrits ont forcément `transactionnelAccepte = true`. 
Ce qui est le comportement voulu.
Avant ce commit, les utilisateurs ajoutés par une invitation à collaborer (donc qui ne s'inscrivent pas eux-même) n'avaient pas ce booléen.
On met la logique dans le dépôt pour éviter que de futures façons d'inscrire les utilisateurs souffrent à nouveau de ce bug.
> Force l'acceptation des emails transactionnels au niveau du dépôt

- public/modules/modaleNouvellesFonctionnalites.mjs
… avant de populer de nouveau.
Sans ça, cliquer plusieurs fois sur « Nouveautés » sans recharger la page résulte dans une modale qui contient de plus en plus de paginations. Par exemple après 3 clics, l'utilisateur se retrouve avec 3 blocs de pagination adjacents.
Le problème en image 👇
> [CORRECTION] Effacer l'éventuelle pagination existante

- public/modules/tableauDeBord/actions/ActionInvitation.mjs
- src/routes/privees/routesApiPrivee.js
- test/routes/privees/routesApiPrivee.spec.js
Cette PR ajoute l'invitation sur plusieurs services côté front 👇 
C'est la fin de la séquence sur l'invitation multiple : le front et le back supportent désormais l'invitation sur plusieurs services simultanément.
> Rends disponible l'action « Inviter » lorsque plusieurs services sont sélectionnés

- src/modeles/autorisations/ajoutContributeurSurServices.js
- test/modeles/autorisations/ajoutContributeurSurServices.spec.js
Un bug a été remonté lors d'une démo :
L'évenement de tracking `INVITATION_CONTRIBUTEUR` est envoyé avec le contributeur en tant que destinataire, au lieu de l'utilisateur qui invite.
> [FIX] Destinataire du tracking INVITATION_CONTRIBUTEUR

- server.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/annuaire/serviceAnnuaire.js
- src/mss.js
- src/routes/privees/routesApiPrivee.js
- test/annuaire/serviceAnnuaire.spec.js
- test/constructeurs/constructeurUtilisateur.js
- test/routes/privees/routesApiPrivee.spec.js
On ajoute une route qui permet de rechercher un contributeur dans tous les services dont je suis propriétaire, en fonction d'un chaine de recherche.
On se base sur les champs `email`, `prenom` et `nom`.
> Route d'annuaire de suggestions des contributeurs

- public/utilisateur/suggestionEntite.js
- src/adaptateurs/adaptateurRechercheEntrepriseAPI.js
- src/annuaire/serviceAnnuaire.js
- src/routes/publiques/routesApiPublique.js
- test/routes/publiques/routesApiPublique.spec.js
Après ajout d'une nouvelle route d'annuaire (`/annuaire/contributeurs`), on harmonise les deux routes pour être cohérent.
- Les méthodes du `serviceAnnuaire` sont accordés au pluriel: `rechercheOrganisation` -> `rechercheOrganisations`
- La route de recherche d'organisation hérite du nom de la ressource recherchée: `/annuaire/suggestions` -> `/annuaire/organisations`
- On en profite pour aseptiser les paramètres de la route `/annuaire/organisations` car cela n'avait pas été fait avant.
> [NETTOYAGE] Harmonisation des routes d'annuaire

- public/modules/modaleNouvellesFonctionnalites.mjs
Nous avons détecté un bug en démo, réalisable comme cela :
- ouvrir le carrousel via le bouton 'Nouveautés'
- cliquer sur suivant pour aller à la deuxième page
- fermer le carrousel
- réouvrir le carrousel via le bouton 'Nouveautés'
- aller à la deuxième page, elle ne s'affiche pas
Il s'agissait d'un bug où, à la fermeture, le compteur `data-page-actuelle` n'était pas réinitialisé à `1`, donc le compteur continuait d'incrémenter au delà du nombre de slide.
> [CORRECTION] Affichage de modale sans contenu

- .eslintrc.js
- .gitignore
- README.md
- docker-compose.yml
- package-lock.json
- package.json
- svelte/lib/Preuve.svelte
- svelte/lib/preuve.ts
- svelte/lib/vite-env.d.ts
- svelte/svelte.config.js
- svelte/tsconfig.json
- svelte/vite.config.mts
... parce que le tiroir `Contributeurs` devient trop complexe pour être géré en jQuery, on introduit [Svelte](https://svelte.dev/) pour coder du front complexe en raisonnant en composants.
Cette PR introduit uniquement les outils de compilation de `vite` et `Svelte`.
Afin de tester le bon fonctionnement de la CI, on pourra vérifier que le fichier `/statique/composants-svelte/preuve.js` est bien présent.
> Ajoute la technologie `Svelte`

- svelte/lib/gestionContributeurs.store.ts
- svelte/lib/gestionContributeurs.ts
On remarque que même si le composant `Svelte` est détruit puis ré-instancié à chaque demande depuis le tableau de bord, le `store` garde son état.
Ceci est visible lorsque l'on change d'étape dans le composant (Suppression d'un contributeur), si le tiroir est fermé puis ré-ouvert, le composant reste à l'étape `Suppression`.
On rajoute donc une méthode pour le réinitialiser.
> [CORRECTION] Réinitialise le store au montage du composant

- svelte/.eslintrc.js
- svelte/lib/LigneContributeur.svelte
- svelte/lib/SuppressionContributeur.svelte
Les données stockées en base de données sont au format `HTML`.
Avant, on utilisait le rendu natif de jQuery qui convertit cette données.
Maintenant, nous devons utiliser l'instruction `@html` [de Svelte](https://learn.svelte.dev/tutorial/html-tags).
> [HOTFIX] Utilise l'instruction `@html` pour décoder les données

- svelte/lib/LigneContributeur.svelte
- svelte/lib/gestionContributeurs.store.ts
- svelte/lib/ui/MenuFlottant.svelte
Cette PR touche à ce menu flottant 👇 
Le menu ouvert se ferme lorsqu'on clic ailleurs que sur les «…».
De plus, on cesse de gérer l'état d'affichage dans un store : c'est local au composant.
> Réparation de la fermeture du menu quand on clic en dehors de celui-ci

- svelte/lib/GestionContributeurs.svelte
- svelte/lib/InvitationContributeur.svelte
- svelte/lib/LigneContributeur.svelte
- svelte/lib/SuppressionContributeur.svelte
- svelte/lib/gestionContributeurs.d.ts
- svelte/lib/gestionContributeurs.store.ts
- svelte/lib/gestionContributeurs.ts
… au lieu d'utiliser le composant racine `<GestionContributeurs>`.
Ça allège le code.
Au passage on corrige un bug où on affichait l'invitation pour les services dont l'utilisateur n'est pas propriétaire.
> Stockage des `services` dans le store Svelte

- svelte/lib/ChampAvecSuggestions.svelte
C'est un utilisateur qui nous a remonté le problème.
> [CORRECTION] Autorise `-` et `.` dans les adresses emails à inviter

- .env.template
- src/adaptateurs/adaptateurMailSendinblue.js
... afin de pouvoir le modifier facilement, suite à l'incident avec le DNS Brevo / Sendinblue.
> Utilise une variable d'environnement pour l'URL de l'API Brevo

- src/modeles/objetsApi/objetGetService.js
- src/modeles/objetsApi/objetGetServices.js
- src/routes/privees/routesApiService.js
- test/modeles/objetsApi/objetGetService.spec.js
- test/modeles/objetsApi/objetGetServices.spec.js
- test/routes/privees/routesApiService.spec.js
On ajoute une route `GET /api/service/:id` afin de pouvoir, à tout moment, récupérer les informations d'un service, sous le même format qu'elles sont renvoyées pour le tableau de bord.
Ceci nous permet d'injecter à la demande les données nécessaires pour le bon fonctionnement du compostant `Svelte` du tiroir des contributeurs.
Cela va nous permettre d'afficher simplement le tiroir des contributeurs dans le parcours d'un service.
> Route `GET /api/service/:id` 

- migrations/20230912144944_ajouteDroitsEnEcriture.js
- src/depots/depotDonneesAutorisations.js
- src/depots/depotDonneesHomologations.js
- src/modeles/autorisations/autorisationBase.js
- src/modeles/autorisations/gestionDroits.js
- test/depots/depotDonneesAutorisations.spec.js
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/autorisations/autorisationBase.spec.js
En vue de préparer l'intégration des droits de contributions, on ajoute au modèle `autorisation` une donnée permettant de gérer les niveaux des droits pour chacune des 5 rubriques de MSS (Décrire, Sécuriser, Homologuer, Risques et Contacts utiles).
Par la suite, ces droits seront challengés sur chaque opération portant sur un service (GET, PUT et POST) afin de savoir si l'action est permise.
Ils permettront aussi de conditionner l'affichage du front.
> Ajout des droits lecture/écriture/invisible dans le modèle `Autorisation`

- src/depots/depotDonneesAutorisations.js
- src/erreurs.js
- src/http/middleware.js
- src/modeles/autorisations/autorisationBase.js
- src/modeles/autorisations/gestionDroits.js
- src/routes/privees/routesApiPrivee.js
- src/routes/privees/routesApiService.js
- src/routes/privees/routesApiServicePdf.js
- src/routes/privees/routesService.js
- src/routes/publiques/routesApiPublique.js
- test/depots/depotDonneesAutorisations.spec.js
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/routes/privees/routesApiService.spec.js
- test/routes/privees/routesApiServicePdf.spec.js
- test/routes/privees/routesService.spec.js
On utilise maintenant les droits contenu dans `autorisation` pour autoriser ou non l'accès à toute les routes existantes.
> Sécurisation de certaines routes d'API

- svelte/lib/ChampAvecSuggestions.svelte
Le REGEX `^$` permet de contraindre l'intégralité d'une chaine pour la fonction `String.test()`
> [CORRECTION] REGEX pour l'invitation par email des contributeurs

- src/erreurs.js
- src/http/middleware.js
- src/routes/privees/routesService.js
- test/constructeurs/constructeurAutorisation.js
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/routes/privees/routesService.spec.js
Pour chaque routes front du parcours service (Décrire, Sécuriser, Homologuer, Risques, Contacts), on enrichit la réponse du serveur avec `autorisationsService`.
Cela est fait dans le middleware.
Cela nous permet de masqué et/ou passer certaines composants du DOM en lecture seule.
> Enrichissement de la réponse du serveur pour les routes du parcours du service

- public/modules/tableauDeBord/tableauDesServices.mjs
- src/adaptateurs/adaptateurCsv.js
- src/modeles/objetsApi/objetGetService.js
- src/modeles/objetsApi/objetGetServices.js
- src/routes/privees/routesApiPrivee.js
- src/routes/privees/routesApiService.js
- test/modeles/objetsApi/objetGetService.spec.js
- test/modeles/objetsApi/objetGetServices.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/privees/routesApiService.spec.js
On conditionne l'affichage du statut d'homologation sur le front en fonction de la permission sur la rubrique HOMOLOGUER.
Les statuts sont masqués si l'utilisateur n'a pas les droits suffisants.
Ils ne sont aussi pas prit en compte pour le calcul du nombre total de services homologués.
> Masquage des statuts d'homologation en fonction des droits

- .eslintrc.js
- public/modules/tableauDeBord/actions/ActionTelechargement.mjs
- src/modeles/autorisations/autorisationBase.js
- src/modeles/homologation.js
- src/modeles/objetsApi/objetGetService.js
- src/routes/privees/routesApiService.js
- src/routes/privees/routesApiServicePdf.js
- src/vues/tiroirs/tiroirTelechargement.pug
- test/modeles/homologation.spec.js
- test/modeles/objetsApi/objetGetService.spec.js
- test/modeles/objetsApi/objetGetServices.spec.js
- test/routes/privees/routesApiService.spec.js
- test/routes/privees/routesApiServicePdf.spec.js
:warning: Il faut modifier le wording pour l'archive zip avec une phrase statique : 'Ce fichier .ZIP contient tous les PDF'
On conditionne la disponibilité des PDF en fonction des permissions sur les diiférentes rubriques.
Les documents indispnibles sont affichés comme cela dans le tiroir :point_down:
> Conditionnement des disponibilités des PDF en fonction des droits

- public/assets/styles/formulaire.css
- public/assets/styles/homologation/risques.css
- public/assets/styles/modules/validation.css
- public/modules/elementsDom/saisieRisqueSpecifique.js
- public/modules/saisieListeItems.js
- public/service/mesures.js
- public/service/risques.js
- src/vues/fragments/elementsAjoutables/elementsAjoutables.pug
- src/vues/fragments/elementsAjoutables/elementsAjoutablesActeurHomologation.pug
- src/vues/fragments/elementsAjoutables/elementsAjoutablesDescription.pug
- src/vues/fragments/elementsAjoutables/elementsAjoutablesPartiePrenante.pug
- src/vues/fragments/formulaireDescriptionService.pug
- src/vues/fragments/inputChoix.pug
- src/vues/fragments/inputIdentite.pug
- src/vues/fragments/inputPartiePrenante.pug
- src/vues/service/mesures.pug
- src/vues/service/risques.pug
- src/vues/service/rolesResponsabilites.pug
On conditionne en lecture seule tous les champs à remplir dans les rubriques `DECRIRE`, `SECURISER`, `RISQUES` et `CONTACTS UTILES`.
L'étape `HOMOLOGUER` sera gérée dans une deuxième PR car plus complexe.
Le conditionnement est fait :
- Avec l'attribut `readonly` sur les `input[type="text"]` et `textarea`
- Avec l'attribut `disabled` sur les `checkbox`, `radio` et autre
> Conditionne le parcours `Service` en lecture seule (sauf `HOMOLOGUER`)

- src/adaptateurs/adaptateurMailSendinblue.js
- src/modeles/autorisations/ajoutContributeurSurServices.js
- src/routes/privees/routesApiPrivee.js
- src/routes/publiques/routesApiPublique.js
- svelte/lib/gestionContributeurs/ChampAvecSuggestions.svelte
- test/modeles/autorisations/ajoutContributeurSurServices.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/publiques/routesApiPublique.spec.js
Pour ne pas abonner les personnes seulement sur la base d'une invitation, cette PR corrige le workflow déclenchant un abonnement Brevo.
- A invite B
- B se retrouve immédiatement abonné aux emails marketing Brevo
- A invite B
- Brevo n'est pas sollicité
- C'est seulement lorsque B se connecte (le lien de connexion est dans le mail d'invitation) et accepte les CGU que Brevo est sollicité
> [CORRECTION] Abonnement aux emails marketing

- public/assets/images/icone_deconnecter.svg
- public/assets/styles/entete.css
- public/assets/styles/entete.responsive.css
- public/assets/styles/menuNavigation.css
- public/entete.js
- src/vues/mss.pug
Cette PR change le header du mode **connecté** de MSS.
Le bouton de déconnexion devient toujours visible. Il n'apparaît plus dans le sous-menu de l'utilisateur 👇 
----
Sur la page d'accueil, le mode responsive est également impacté 👇 
Il y a un impact sur l'icône de déconnexion, qui reste présente dans le menu de navigation 👇 
Pour rappel : l'existant sur la page d'accueil et les pages « Services » 👇
> [UI] Nouvelle version du header

- donneesReferentiel.js
- public/assets/images/actionsSaisie/descriptionService.svg
- public/assets/images/actionsSaisie/dossiers.svg
- public/assets/images/actionsSaisie/mesures.svg
- public/assets/images/fleche_retour.svg
- public/assets/images/icone_retour.svg
- public/assets/styles/deuxColonnes.css
- public/assets/styles/entete.css
- public/assets/styles/entete.responsive.css
- public/assets/styles/index.css
- public/assets/styles/menuNavigation.css
- public/assets/styles/mss.css
- public/assets/styles/tableauDeBord.css
- public/assets/styles/tiroir.css
- src/vues/deuxColonnes.pug
- src/vues/fragments/menuNavigation.pug
- src/vues/motDePasse/edition.pug
- src/vues/mss.pug
- src/vues/mssConnecte.pug
- src/vues/service/descriptionService.pug
- src/vues/service/dossiers.pug
- src/vues/service/mesures.pug
- src/vues/service/risques.pug
- src/vues/service/rolesResponsabilites.pug
- src/vues/tableauDeBord.pug
- src/vues/utilisateur/edition.pug
Cette PR relooke le menu pour qu'il soit en v2 👇
> Implémente la version 2 du menu de navigation

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesAutorisations.js
- src/modeles/autorisations/autorisationBase.js
- src/routes/privees/routesApiService.js
- test/constructeurs/constructeurAutorisation.js
- test/constructeurs/constructeurService.js
- test/constructeurs/constructeurUtilisateur.js
- test/depots/depotDonneesAutorisations.spec.js
- test/modeles/autorisations/autorisationBase.spec.js
- test/routes/privees/routesApiService.spec.js
On ajoute la route `/service/:id/autorisation` pour pouvoir alimenter par la suite le tiroir contributeurs.
Cette route retourne soit :
- Tout les statuts de droit de tous les utilisateurs du service, si j'en suis créateur
- Uniquement mon statut et celui du propriétaire, si j'en suis contributeur
> Ajout de la route `/service/:id/autorisations`

- src/vues/service/dossiers.pug
- src/vues/service/formulaireEtapier.pug
… afin qu'il soit affiché sur toutes les étapes du parcours d'homologation, et pas seulement sur l'étape qui liste tous les dossiers.
> [CORRECTION] Déplace le titre dans `formulaireEtapier`

- donneesReferentiel.js
- public/assets/styles/etapesDossier.css
- public/assets/styles/modules/selectize.css
- public/service/homologation/formulaireEtape.js
- src/http/middleware.js
- src/modeles/autorisations/autorisationBase.js
- src/referentiel.js
- src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
- src/vues/service/dossiers.pug
- src/vues/service/etapeDossier/autorite.pug
- src/vues/service/etapeDossier/avis.pug
- src/vues/service/etapeDossier/dateTelechargement.pug
- src/vues/service/etapeDossier/documents.pug
- src/vues/service/formulaireEtapier.pug
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/referentiel.spec.js
La rubrique `HOMOLOGUER` est différente des autres rubrique dans le cas de la lecture seule.
- D'une part, les champs de saisie sont passés en lecture seule, comme les autres rubriques
- D'autre part, l'étape 4 est modifiée dans le cas où un utilisateur n'a pas la permission `peutHomologuer`
Les boutons `Suivant` n'effectue plus l'action de `POST` en cas de lecture seule.
On en profite pour supprimer le bouton `Revenir à la synthèse` qui n'a plus lieu d'être.
Le résumé des dossiers d'homologation n'indique plus l'étape actuelle en cas de lecture seule.
> Rubrique `HOMOLOGUER` en lecture seule

- public/assets/images/icone_contributeurs_actifs.svg
- public/assets/images/icone_contributeurs_attente_activation.svg
- public/assets/styles/tiroir.css
- src/modeles/autorisations/autorisationBase.js
- src/modeles/autorisations/autorisationCreateur.js
- svelte/lib/gestionContributeurs/ChampAvecSuggestions.svelte
- svelte/lib/gestionContributeurs/GestionContributeurs.svelte
- svelte/lib/gestionContributeurs/Initiales.svelte
- svelte/lib/gestionContributeurs/InvitationContributeur.svelte
- svelte/lib/gestionContributeurs/LigneContributeur.svelte
- svelte/lib/gestionContributeurs/TagNiveauDroit.svelte
- svelte/lib/gestionContributeurs/gestionContributeurs.d.ts
- test/modeles/autorisations/autorisationBase.spec.js
- test/modeles/autorisations/autorisationCreateur.spec.js
- test/routes/privees/routesApiService.spec.js
On affiche désormais, quand ils sont disponibles, les résumé de niveau de droit de chaque utilisateur dans le tiroir contributeurs.
Dans une PR suivante, cela deviendrait le `trigger` pour un Menu flottant.
> Composant « Vue seulement » des résumés de niveau de droit par contributeur

- public/assets/styles/tableauDeBord.css
Avant ce commit, le bandeau et le corps de page n'étaient pas en mode colonne 👇 
Après correction 👇
> [CORRECTION] Répare l'affichage en cas de bandeau présent
