betagouv/mon-service-securise

- src/mss.js
- test/mss.spec.js
confère https://scotthelme.co.uk/content-security-policy-an-introduction/
> Ajout le Header Content-Security-Policy

- TODO.txt
- public/homologation/formulaireInformationsGenerales.js
- public/modules/soumetsHomologation.js
- src/middleware.js
- src/modeles/informationsGenerales.js
- src/modeles/pointAcces.js
- src/modeles/pointsAcces.js
- src/mss.js
- src/vues/fragments/formulaireInformationsGenerales.pug
- test/middleware.spec.js
- test/modeles/informationsGenerales.spec.js
- test/modeles/pointAcces.spec.js
- test/modeles/pointsAcces.spec.js
- test/mss.spec.js
Dans une Homologation nouvelle ou existante, on peut ajouter, modifier ou supprimer des points d'accès
> Ajout de la saisie des points d'accès dans la page informations générales

- donneesReferentiel.js
- src/vues/fragments/formulaireInformationsGenerales.pug
Dans la page Informations générales
- modification du titre de la question du bloc données à caractère personnel
- modification du texte des choix
- ajout de 3 nouveaux choix
> Modifier le bloc données à caractère personnel

- donneesReferentiel.js
- public/assets/styles/homologation/risques.css
- public/assets/styles/palette.css
- public/homologation/risques.js
- src/erreurs.js
- src/modeles/risqueGeneral.js
- src/mss.js
- src/referentiel.js
- src/vues/homologation/risques.pug
- test/modeles/risqueGeneral.spec.js
- test/mss.spec.js
- test/referentiel.spec.js
J'ai découpé la fonctionnalité en plusieurs PR pour rendre la lecture plus digeste 😅 
Les PR qui viendront ensuite :
- Saisie du niveau de gravité pour un risque spécifique
- Affichage dans le document PDF
> Saisie du niveau de gravité d'un risque

- donneesReferentiel.js
- public/assets/styles/modale.css
- src/vues/fragments/modaleInformationsGenerales.pug
- src/vues/homologation/risques.pug
L'intitulé des risques est modifié, les identifiants restent les mêmes, 1 nouveau risque ajouté (`donneesModifiees`), des liens externes ajoutés dans les descriptions longues.
> Mise à jour du référentiel des risques

- .eslintrc.js
- public/assets/styles/homologation/risques.css
- public/homologation/risques.js
- public/modules/elementsDom/saisieRisqueSpecifique.js
- public/modules/interactions/saisieNiveauGravite.js
- public/modules/saisieListeItems.js
- src/modeles/risque.js
- src/modeles/risqueGeneral.js
- src/modeles/risqueSpecifique.js
- src/modeles/risquesSpecifiques.js
- src/mss.js
- src/vues/homologation/risques.pug
- test/modeles/risqueSpecifique.spec.js
- test/mss.spec.js
Cette PR propose d'étendre le comportement défini pour les risques généraux aux risques spécifiques.
> Niveau de gravité des risques spécifiques

- src/vues/fragments/modaleInformationsGenerales.pug
La pop-in de criticité proposait un lien vers le guide en 9 étape de l'ANSSI. Maintenant, le lien est vers la page des questions fréquentes du site.
> Redirige vers les questions fréquentes du site

- public/homologation/formulaireInformationsGenerales.js
- public/modules/soumetsHomologation.js
Une première pierre pour désencombrer `soumetsHomologation` https://github.com/betagouv/mon-service-securise/issues/43
> Modification la récupération des paramètres de listes avec items

- public/homologation/formulaireInformationsGenerales.js
- public/modules/elementsAjoutables.js
- src/vues/fragments/elementsAjoutables.pug
- src/vues/fragments/formulaireInformationsGenerales.pug
- J'ai utilisé un template pug pour peupler directement les données
-> fin du script jsn en bas de page
-> moins de traitement en JS
- j'ai transformé la classe ElementsAjoutables en une fonction
-> l'appel n'utilise plus de new
> Amélioration du code des items à éléments ajoutables

- public/modules/elementsAjoutables.js
Erreur quand on ajoute le premier élément
> Corrige une erreur dans les éléments ajoutables

- package-lock.json
(cf. https://github.com/betagouv/mon-service-securise/security/dependabot/package-lock.json/follow-redirects/open)
> Bump version package follow-redirects

- public/homologation/formulaireInformationsGenerales.js
- public/modules/brancheElementsAjoutables.js
- public/modules/elementsAjoutables.js
- public/modules/saisieListeItems.js
- src/vues/fragments/elementsAjoutables.pug
Quand on a des éléments déjà présents au chargement, on ne peut pas les supprimer car le script de suppression n'a pas été activé :(
> Correction d'une erreur dans la suppression des éléments ajoutables

- src/modeles/homologation.js
Finalement, il n'y a pas d'anomalie… Il faut juste penser à jouer les migrations avant 😓
> Revert "[CORRECTION] Affiche correctement statut saisie description service"

- public/assets/styles/decision.css
- src/vues/homologation/decision.pug
> Ajoute lien retour dans vue dossier homologation

- src/adaptateurs/adaptateurMail.js
… Et modifie le mail de réinitialisation de mot de passe pour des questions de cohérence.
> Reformule le mail de finalisation d'inscription

- src/mss.js
- src/routes/routesApi.js
Déplacement dans un autre fichier des routes commençant par /api
> Déplacement des routes commençant par api

- migrations/20220204145444_supprimeInformationsGenerales.js
Il n'y a plus d'utilisation de `informationsGenerales` il est temps de les supprimer en base
> Suppression des données les informations générales

- creeUtilisateurDemo.js
- docker-compose.yml
- server.js
- src/adaptateurs/fabriqueAdaptateurPersistance.js
- src/depotDonnees.js
- src/referentiel.js
La création du dépôt de données prenait beaucoup de paramètres qui pouvaient dans bien des cas avoir des valeurs par défaut. Cette PR corrige ce problème.
> Simplifie instanciation par défaut du dépôt de données

- public/assets/styles/entete.css
Réduction de la taille du texte de 
1. Questions fréquentes
2. Nous contacter
3. Bouton inscription
4. Bouton connexion
> Réduction de la taille du texte du header et des boutons

- public/assets/styles/homologation/mesures.css
- public/assets/styles/homologation/risques.css
- public/assets/styles/modale.css
- public/homologation/mesures.js
- public/homologation/risques.js
- public/modules/interactions/modale.mjs
- src/vues/homologation/mesures.pug
- src/vues/homologation/risques.pug
Merci Jacques d'avoir réagi à mes idées pour faire ça et de m'avoir donné la solution !
> Ajout modale description des mesures de sécurité

- src/adaptateurs/adaptateurMail.js
> Mets à jour texte mail réinitialisation mot de passe

- src/vues/aPropos.pug
- src/vues/questionsFrequentes.pug
Reprend sans modification le code de la PR https://github.com/betagouv/mon-service-securise/pull/150
> Mise à jour de la page à propos

- src/vues/aPropos.pug
changement de "mail" pour "e-mail"
> MAJ A propos

- public/assets/styles/questionsFrequentes.css
- src/vues/questionsFrequentes.pug
> QuestionsFrequentes.pug

- .eslintrc.js
- public/modules/interactions/brancheOnglets.mjs
- public/modules/soumetsHomologation.mjs
- test_public/modules/interactions/brancheOnglets.spec.mjs
- test_public/modules/parametres.spec.mjs
Le linter ne passait pas dans les fichiers mjs, j'ai corrigé les erreurs après l'activation
> Linter dans les fichiers .mjs

- public/assets/styles/formulaire.css
- public/entete.js
- src/depotDonnees.js
- src/routes/routesApi.js
- src/vues/utilisateur/edition.pug
- test/depotDonnees.spec.js
- test/routes/routesApi.spec.js
> L'utilisateur peut mettre à jour son profil (prénom et nom)

- .eslintrc.js
- package-lock.json
- package.json
L'intention est de pouvoir vérifier que les tests n'ont pas été commités avec un `.only` oublié par mégarde.
> Détection par ESLint de la présence de tests exclusifs 

- public/assets/images/pastille_foncee.svg
- public/assets/styles/espacePersonnel.css
- public/modules/elementsDom/homologations.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/modeles/homologation.js
- test/depotDonnees.spec.js
- test/modeles/homologation.spec.js
> Affichage du propriétaire de l'homologation

- src/vues/nouvellesFonctionnalites.pug
Dans la page nouvelle fonctionnalités,
- Changement de l'ordre des nouveautés
- Ajout d'une nouveauté
- Changement de la date
> Mise à jour la liste des nouvelles fonctionnalités

- public/homologation.js
- public/homologation/descriptionService.js
- public/modules/adaptateurAjaxAxios.mjs
- public/modules/erreurs.mjs
- public/modules/parametresDescriptionService.mjs
- public/modules/soumetsHomologation.mjs
- src/vues/fragments/formulaireDescriptionService.pug
- src/vues/homologation/creation.pug
- src/vues/homologation/descriptionService.pug
- test_public/modules/soumetsHomologation.spec.mjs
J'ai 
- regroupé les scripts dans descriptionService
- testé soumetsHomologation 😵‍💫
- arrangé un peu le fichier en sortant la partie spécifique à description du service
Lié à l'issue https://github.com/betagouv/mon-service-securise/issues/43
> Refacto du fichier soumetsHomologation

- src/vues/base.pug
- src/vues/homologation/decision.pug
- src/vues/mss.pug
Dans la page du document d'homologation,
la favicon n'apparaissait pas
> Favicon dans la page document d'homologation

- src/routes/routesApi.js
- test/routes/routesApi.spec.js
Jusqu'à présent, si on tentait de ré-inviter un contributeur déjà invité, on lui renvoyait un nouveau mail. Cette PR corrige le problème.
> [CORRECTION] Ne pas envoyer de mail à un contributeur déjà invité

- donneesReferentiel.js
Quand on sélectionne **création de comptes** dans les fonctionnalités de la description du service,
on ajoute les mesures : 
~1. Lister et mettre en oeuvre les mesures de sécurité nécessaires découlant de l'analyse de risque et de l'audit~
2. Organiser au moins un atelier d'analyse des risques du service numérique
3. Héberger le service numérique et les données au sein d'un Cloud qualifié SecNumCloud
4. Fixer les modalités du suivi de la sécurité du service entre les parties prenantes
5. Formaliser les modalités de mise en œuvre des mécanismes de sécurité importants pour le service
6. Dissocier les accès, les comptes et les privilèges des agents à la fois utilisateurs et administrateurs
7. Effectuer un test d'intrusion et/ou réaliser un bug bounty
~8. Prévoir l'authentification …
> Mesures à ajouter pour la création de comptes

- donneesReferentiel.js
- src/modeles/profils/profil.js
- src/modeles/profils/regle.js
- src/modeles/profils/regles.js
- test/modeles/profils/profil.spec.js
- test/modeles/profils/regles.spec.js
- test/moteurRegles.spec.js
Quand un utilisateur sélectionne une ou plusieurs de ces possibilités :
- Application NON achetée + Application Développée + Fonctionnalité Réseau Social
- Application NON achetée + Application Développée + Fonctionnalité Visio Conférence
- Application NON achetée + Application Développée + Fonctionnalité Messagerie
- Application NON achetée + Application Développée + Fonctionnalité Edition
- Application NON achetée + Application Développée + Fonctionnalité Paiement
- Données d'identité
- Données relatives à la situation familiale, économique et financière
- Données concernant des personnes mineures
Les mesures suivantes sont ajoutées :
- Héberger le service numérique et les données au sein d'un Cloud qualifié SecNumCloud
- Fixer les modalités du suivi de la sécurité du service entre les …
> Règles de personnalisation pour mss +

- public/assets/styles/homologation/mesures.css
- public/homologation/mesures.js
- public/modules/saisieListeItems.js
- src/vues/homologation/mesures.pug
Le bouton d'ajout des mesures ainsi que les mesures spécifiques seront affichés avant les mesures générales
> Les mesures spécifiques en haut et en ordre inverse

- .env.template
- donneesReferentiel.js
- src/erreurs.js
- src/modeles/homologation.js
- src/modeles/mesures.js
- src/modeles/mesuresGenerales.js
- src/modeles/statistiquesMesures.js
- src/referentiel.js
- src/routes/routesHomologation.js
- src/vues/homologation.pug
- test/modeles/homologation.spec.js
- test/modeles/mesures.spec.js
- test/modeles/mesuresGenerales.spec.js
- test/modeles/statistiquesMesures.spec.js
- test/referentiel.spec.js
Note : si aucune mesure générale n'a été renseignée, le cyberscore vaut 0 mais n'est pas affiché.
> Calcul du cyberscore

- src/middleware.js
- src/mss.js
- src/routes/routesBibliotheques.js
- src/vues/homologation/decision.pug
- src/vues/mss.pug
- test/middleware.spec.js
Création d'une route `/bibliotheques/jquery-*` pour ne plus à avoir à mettre le domaine dans les csp
> Suppression de jquery des headers du csp

- public/entete.js
- public/modules/deconnexion.js
- public/mssConnecte.js
- src/configurationServeur.js
- src/mss.js
- src/routes/routesApi.js
- src/vues/mss.pug
- test/mss.spec.js
- test/routes/routesApi.spec.js
Dans les pages connectées,
le navigateur obtient le délai de session en appellant le serveur
> Récupération du délai depuis le serveur

- donneesReferentiel.js
- public/assets/styles/decision.css
- src/modeles/mesure.js
- src/modeles/mesuresGenerales.js
- src/vues/homologation/decision.pug
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/mesure.spec.js
- test/modeles/mesuresGenerales.spec.js
This reverts commit 8556e68cf2ed208eefd08a1a797910c1d63a57a5.
> Revert "Remplace le choix statut de mesure planifié par en cours"

- migrations/20220706130321_ajoutColonneDateUtilisateurs.js
- src/adaptateurs/adaptateurHorloge.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/modeles/utilisateur.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/modeles/utilisateur.spec.js
Quand on ajoute un nouvel utilisateur,
une date de création lui est associée
- ce dev contient une migration sur la table utilisateurs
> Date creation pour les nouveaux utilisateurs

- donneesReferentiel.js
- donneesReferentielDepartements.js
- public/assets/styles/admin/inscription.css
- src/mss.js
- src/referentiel.js
- src/vues/admin/inscription.pug
- test/referentiel.spec.js
Dans la page administrateur de création de compte,
nous souhaitons avoir la possibilité de sélectionner les départements dans une liste finie
> Création utilisateur avec liste des départements

- public/assets/styles/admin/inscription.css
- public/inscription.js
- public/modules/interactions/champsRequis.mjs
- src/erreurs.js
- src/modeles/utilisateur.js
- src/routes/routesApi.js
- src/vues/admin/inscription.pug
- src/vues/fragments/inputChoix.pug
- test/modeles/utilisateur.spec.js
- test/routes/routesApi.spec.js
- test_public/modules/interactions/champsRequis.spec.mjs
Dans la page de création de compte pour administrateur (/admin/inscription)
Les champs Nom, Prénom, E-mail, RSSI, Délégué protection données, nom de l'entité et département sont requis
Ils apparaitront en rouge quand ils ne seront pas complétés et la requête sera bloquée.
Une vérification supplémentaire aura lieu avant l'inscription en base.
> Validation des champs pour la création d'utilisateur

- public/assets/styles/admin/inscription.css
Le fichier inscription.css est mal indenté
> Correction indentation du style inscription

- src/vues/fragments/modaleDescriptionService.pug
- src/vues/homologation/avisExpertCyber.pug
- src/vues/index.pug
- src/vues/mssInscription.pug
- src/vues/nouvellesFonctionnalites.pug
Remplacement dans tout le projet des **’** par des **'**
> Remplacement des apostrophes obliques par des droites

- README.md
(Note : cette PR s'appuie sur la correction dans #333 , qui doit être mergée d'abord.)
> Ajoute fichier `README.md`

- public/assets/styles/utilisateur.css
- public/inscription.js
- public/modules/interactions/brancheMiseEnAvantSaisie.js
- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
- public/utilisateur/edition.js
- src/erreurs.js
- src/modeles/utilisateur.js
- src/mss.js
- src/routes/routesApi.js
- src/vues/fragments/formulaireUtilisateur.pug
- src/vues/fragments/inputChoix.pug
- src/vues/fragments/utilisateur/nouveauMotDePasse.pug
- src/vues/fragments/utilisateur/questionCgu.pug
- src/vues/inscription.pug
- src/vues/mssInscription.pug
- src/vues/utilisateur/edition.pug
- test/modeles/utilisateur.spec.js
- test/routes/routesApi.spec.js
Dans la page d'édition du profil utilisateur `/utilisateur/edition`,
Les informations demandées n'étaient pas suffisantes comparées aux informations demandées pour la création d'un utilisateur,
NOTE : cette PR contient énormément de code 😿
> Page édition avec les nouvelles propriétés

- public/assets/styles/carteInformations.css
- src/modeles/statistiquesMesures.js
- src/vues/homologation.pug
- test/modeles/statistiquesMesures.spec.js
> Affichage des indices de sécurité pour chaque catégorie

- src/vues/mentionsLegales.pug
MAJ pour corriger l'affichage sur Dashlord.
> MAJ des mentions légales

- src/vues/confidentialite.pug
Changement sous-traitance en "sous-traitants" pour essayer de passer le test dashlord.
> MAJ confidentialité

- README.md
> MAJ du para d'intro du Readme

- src/vues/aPropos.pug
Changement du corps de texte dans la page A Propos.
> Changes corps du texte page APropos

- public/assets/styles/bouton.css
> Affichage des boutons de validation en bas à droite de tous les formulaires

- src/vues/fragments/formulaireDescriptionService.pug
1. Le titre "description du service" devient "décrire"
2. Changement de la légende
> Changement titre et légende de la page

- public/assets/styles/decision.css
- public/assets/styles/documentImprimable.css
- public/assets/styles/syntheseSecurite.css
- public/homologation/decision.js
- public/homologation/syntheseSecurite.js
- public/modules/interactions/telechargementPdf.js
- src/vues/documentImprimable.pug
- src/vues/homologation/decision.pug
- src/vues/homologation/syntheseSecurite.pug
Dans la perspective de créer une synthèse de sécurité,
La page `/syntheseSecurite` doit pouvoir être téléchargée en PDF
> Téléchargement du PDF synthèse de sécurité

- public/assets/styles/bouton.css
- public/assets/styles/carteInformations.css
- public/assets/styles/espacePersonnel.css
- public/assets/styles/formulaire.css
- public/assets/styles/modale.css
- public/assets/styles/modules/lienNouvelOnglet.css
- public/assets/styles/palette.css
- public/assets/styles/utilisateur.css
- public/espacePersonnel.js
- public/modules/elementsDom/services.js
- public/modules/interactions/modale.mjs
- public/modules/modaleNouveauService.js
- src/vues/cartes/indiceCyber.pug
- src/vues/espacePersonnel.pug
- src/vues/fragments/lienNouvelOnglet.pug
- src/vues/fragments/modaleDescriptionService.pug
- src/vues/fragments/modaleNouveauService.pug
> Espace personnel modale d attestation

- public/assets/styles/palette.css
- public/assets/styles/syntheseSecurite.css
- src/modeles/homologation.js
- src/modeles/mesures.js
- src/vues/homologation/syntheseSecurite.pug
- test/modeles/homologation.spec.js
- test/modeles/mesures.spec.js
Dans la page de synthèse de sécurité,
Nous ajoutons le total de mesures générales
> PDF total mesures générales

- src/vues/homologation/synthese.pug
> Correction faute d'orthographe

- src/vues/questionsFrequentes.pug
Quelques modifs éditos importantes.
> Reformulation des textes dans la page des questions fréquentes

- .eslintrc.js
- public/assets/styles/syntheseSecurite.css
- public/scripts/statistiquesMesures.js
- src/routes/routesBibliotheques.js
- src/vues/documentImprimable.pug
- src/vues/fragments/statistiquesMesures.pug
- src/vues/homologation/syntheseSecurite.pug
Pour l'instant, ce sont des valeurs de démonstration, indiquées en dur. Dans une prochaine PR on injectera les valeurs depuis le serveur.
> Ajoute le camembert des mesures indispensables

- public/scripts/statistiquesMesures.js
- src/modeles/homologation.js
- src/modeles/mesuresGenerales.js
- src/modeles/statistiquesMesures.js
- src/vues/fragments/statistiquesMesures.pug
- src/vues/homologation/syntheseSecurite.pug
- test/modeles/homologation.spec.js
- test/modeles/mesuresGenerales.spec.js
- test/modeles/statistiquesMesures.spec.js
- on injecte maintenant les données depuis le serveur
- on affiche le camembert pour les mesures recommandées
> Statistiques mesures

- public/assets/styles/deuxColonnes.css
- public/assets/styles/homologation/synthese.css
- public/carteInformations.js
- src/vues/carteInformations.pug
- src/vues/homologation/synthese.pug
- src/vues/mss.pug
En (1) nous rajoutons l'encart avec les liens pour la rétro-compatibilité.
En (2) le lien de téléchargement de la synthèse pointe désormais sur la synthèse v2.
> Ajoute carte avec liens rétro-compatibilité

- donneesReferentiel.js
Reverts betagouv/mon-service-securise#407
Finalement, il ne fallait pas enlever le point final 😓
> Revert "Retrait de etc."

- src/vues/cartes/indiceCyber.pug
- src/vues/fragments/descriptionIndiceCyber.pug
- src/vues/homologation/syntheseSecurite.pug
- src/vues/questionsFrequentes.pug
Cette PR évite d'avoir 3 descriptions subtilement différentes pour l'indice cyber.
La description unique devient :
> L'indice cyber est calculé à partir des mesures de sécurité mises en œuvre, sur la base des déclarations de l'équipe, par rapport à l'ensemble des mesures proposées par l'ANSSI. Il fournit une évaluation indicative du niveau de sécurité du service.
> Homogénéisation de la description de l'indice cyber

- .env.template
introduite dans le commit 70a638c61ebb44141959f04b3cff2a96752ef9dd
> Documente la variable d'environnement AVEC_SYNTHESE_V2

- public/assets/images/icone_dossier.svg
- public/assets/styles/annexes/mesures.css
- public/assets/styles/pdfs.css
- public/assets/styles/syntheseSecurite.css
- public/homologation/annexes/mesures.js
- src/routes/routesHomologation.js
- src/vues/homologation/annexes/mesures.pug
- src/vues/homologation/syntheseSecurite.pug
- test/routes/routesHomologation.spec.js
Dans le travail de création de l'annexe des mesures,
la première étape est la création d'une nouvelle page accessible uniquement via l'url `/:id/syntheseSecurite/annexes/mesures`
Dans ce premier de il y a la route, la page avec le titre et le conteneur pour les mesures en cours.
> Annexe des mesures - Nouvelle page

- donneesReferentiel.js
- migrations/20221021094600_suppressionMesuresGeneralesObsoletes.js
Cette suppression demande une migration de données pour les dossiers qui contiendraient ces mesures.
> Suppression des mesures obsolètes du référentiel

- public/modules/convertisReponseOuiNon.mjs
- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
- public/modules/parametresDescriptionService.mjs
- src/modeles/descriptionService.js
- src/routes/routesApiHomologation.js
- src/vues/fragments/formulaireDescriptionService.pug
- test/modeles/descriptionService.spec.js
- test/routes/routesApiHomologation.spec.js
- test_public/modules/convertisReponseOuiNon.spec.mjs
Nous souhaitons avoir une question supplémentaire
NOTE : ~~la valeur persisté est `oui` ou `non`~~
> Question concernant les risques financiers juridiques et réputationnels

- src/vues/mssConnexionEnCours.pug
- src/vues/mssDeconnecte.pug
Reformulation de « Nous contacter » en « Contactez-nous » sur 2 écrans.
> Utilisation du vocabulaire du système de design de l'État

- public/assets/styles/entete.css
- public/assets/styles/palette.css
Cette PR apporte de la couleur au survol des logos ANSSI et MSS.
> Bloc marque de l'entête respectant le système de design de l'État

- public/assets/styles/mss.css
- public/assets/styles/palette.css
- public/assets/styles/piedPage.css
- src/vues/mss.pug
Cette PR modifie les liens du pied de page pour respecter [le système de design de l'État](https://www.systeme-de-design.gouv.fr/).
> [Pied de page] Liens

- public/assets/styles/nouvellesFonctionnalites.css
- src/vues/nouvellesFonctionnalites.pug
Je ne sais pas comment ajouter des puces et une nouvelle icone (cross). Tout est disponible sur Figma.
> Ajout textes et icones novembre

- donneesReferentiel.js
- migrations/20221115150500_suppressionDiffusionRestreinte.js
Corrige le problème de #472 qui a été identifié dans #475 : on ajoute une garde avec `?.`.
> Supprime « Diffusion restreinte » des données à caractère personnel

- src/latex/miseEnFormeDonnees.js
- src/routes/routesPdf.js
- src/vuesTex/annexeMesures.template.tex
- test/latex/miseEnFormeDonnees.spec.js
Une 5ème étape est l'échappement des caractères latex
La route est /pdf/:id/annexeMesures.pdf et le pdf est un pdf statique obtenu à partir de latex avec un échantillon de données injecté contenant les caractères spéciaux latex
- Source de la liste des caractères https://tex.stackexchange.com/questions/34580/escape-character-in-latex/34586#34586
> Échappement des caractères spéciaux latex

- src/mss.js
Dans mss.js un app.use(…) apparait 2x
> [CORRECTION] Déclaration en double d'une route

- src/adaptateurs/adaptateurPdfLatex.js
- src/routes/routesPdf.js
- src/vuesTex/annexeRisques.template.tex
- test/routes/routesPdf.spec.js
Une 1ère étape est la création d'une route et d'un pdf latex avec que le titre
> Route du Pdf de l'annexe des risques

- .env.template
- src/mss.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
- test/routes/testeurMSS.js
La correction est désormais appliquée dans tous les environnements.
> Supprime AVEC_CORRECTION_ASEPTISATION_MOT_DE_PASSE

- donneesReferentiel.js
Remonté par un utilisateur, via Antoine.
> [CORRECTION] Typo dans description

- public/assets/images/pastille_foncee.svg
- public/assets/images/pastille_transparente.svg
- public/assets/images/pastille_violette.svg
- public/assets/styles/espacePersonnel.css
- public/espacePersonnel.js
- public/modules/elementsDom/services.mjs
- test_public/modules/elementsDom/services.spec.mjs
- Une pastille détaillée pour le premier contributeur
- Une pastille commune pour tous les contributeurs supplémentaires
> Restriction de l'affichage des pastilles contributeur

- .eslintrc.js
- src/adaptateurs/adaptateurChiffrement.js
- src/depots/depotDonneesHomologations.js
- src/modeles/journalMSS/erreurs.js
- src/modeles/journalMSS/evenements.js
- test/modeles/journalMSS/evenements.spec.js
Chiffrement pour l'ID utilisateur stocké dans les événements.
> Chiffre l'identifiant utilisateur stocké dans les événements

- donneesReferentiel.js
- public/assets/styles/etapesDossier.css
- src/referentiel.js
- src/routes/routesHomologation.js
- src/vues/homologation/formulaireEtapier.pug
- test/routes/routesHomologation.spec.js
> Affiche la barre de progression

- src/vues/questionsFrequentes.pug
> Correction de coquilles

- src/modeles/listeRisques.js
- src/modeles/risqueGeneral.js
- src/modeles/risques.js
- test/modeles/listesRisques.spec.js
- test/modeles/risque.spec.js
- test/modeles/risqueGeneral.spec.js
- test/modeles/risques.spec.js
Une 4ème étape est la mise à disposition des risques généraux par niveau de gravité
NOTE : les risques spécifiques et l'utilisation dans le pdf suivent
> Annexe risques - risques généraux par niveau

- src/vues/homologation/rolesResponsabilites.pug
> Changement wording contacts utiles

- donneesReferentiel.js
- public/assets/styles/etapesDossier.css
- public/assets/styles/formulaire.css
- public/assets/styles/modules/validation.css
- public/assets/styles/utilisateur.css
- public/homologation/etapesDossier.js
- src/vues/fragments/formulaireUtilisateur.pug
- src/vues/homologation/dossiers.pug
- src/vues/homologation/etapeDossier/1.pug
- src/vues/homologation/etapeDossier/2.pug
- src/vues/homologation/etapeDossier/3.pug
Note : On a la validation des champs côté client, mais pas encore la persistence. Ça s'en vient 😉
> Étape 2 du parcours homologation (« Date »)

- src/referentiel.js
- src/vuesTex/annexeRisques.template.tex
- test/modeles/objetsVues/vueAnnexePDFRisques.spec.js
- test/referentiel.spec.js
Une 7ème étape est l'affichage dans le PDF des risques groupés par niveau de gravité
> Annexe risques - affichage des risques

- donneesReferentiel.js
> Ajoute option durée validité 3 ans

- public/assets/styles/homologation/descriptionService.css
- src/vues/fragments/formulaireDescriptionService.pug
- src/vues/fragments/inputChoix.pug
Dans la page **Décrire** 
- Nous souhaitons modifier le texte de la question _Une atteinte à la sécurité ou au bon fonctionnement du service pourrait entraîner des conséquences graves sur les plans juridique, financier ou réputationnel_
- Nous voulons aussi que quand **Oui** est coché un message apparaisse
> Question atteinte juridique, financier ou réputationnel

- src/vues/mssConnecte.pug
Changement d'adresse de contact --> support
> Changement d'adresse de contact

- donneesReferentiel.js
- public/assets/styles/etapesDossier.css
- src/modeles/dossier.js
- src/modeles/dossiers.js
- src/referentiel.js
- src/utilitaires/date.js
- src/vues/homologation/dossiers.pug
- src/vues/homologation/formulaireEtapier.pug
- test/modeles/dossier.spec.js
- test/modeles/dossiers.spec.js
- test/utilitaires/date.spec.js
> Affiche récapitulatif des dossiers dans parcours homologation

- donneesReferentiel.js
"Disposer d'une liste à jour des comptes disposant d'un D'accès privilégié au service" devient "Disposer d'une liste à jour des comptes disposant d'un accès privilégié au service"
> Correction coquille intitulé mesure

- src/adaptateurs/adaptateurPostgres.js
Dans le script d'export des événements de création des « anciennes » homologations, la requête utilisée n'associait pas explicitement les intervenants (créateur et collaborateurs) aux homologations, et la commande d'export retournait une erreur.
Ce commit corrige le problème.
> [CORRECTION] Ajout intervenants aux homologations dans script export événements

- public/scripts/statistiquesMesures.js
Reverts betagouv/mon-service-securise#564
> Revert "Correction des camemberts des mesures non pleins"

- src/vues/mssConnecte.pug
Ouvrir dans un nouvel onglet la FAQ
> Redirection du mailto pour la faq

- public/modules/interactions/brancheValidationCasesACocher.mjs
- test_public/modules/interactions/brancheValidationCasesACocher.spec.mjs
Dans la grande aventure qui est la validation des formulaires coté client,
je propose d'ajouter le mécanisme pour les checkbox quand au moins une réponse est requise.
Notes : 
- Ce code n'est utilisé que dans les tests et sera utilisé dans les futurs développement de la validation de la page décrire
- Les tests donne une description de l'utilisation de mécanisme
> Validation pour les cases à cocher

- public/connexion.js
- src/vues/connexion.pug
⌨️ Cette PR permet de se connecter en utilisant la touche « Entrée » du clavier.
> Soumettre le formulaire de connexion sur « Entrée »

- consoleAdministration.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
Reverts betagouv/mon-service-securise#599
Les événements de complétude ont été injectés dans le journal MSS de PROD. 
🧹  On peut se débarrasser du code ayant servi à les y mettre.
> Revert "Génère un événement de complétude pour chaque service"

- src/vues/nouvellesFonctionnalites.pug
Ajout de nouvelles fonctionnalités
> Ajout des nouvelles fonctionnalités

- src/vues/aPropos.pug
> Changement de wording

- public/assets/images/icone_sandwich.svg
- public/assets/styles/entete.css
- public/assets/styles/entete.responsive.css
- public/assets/styles/index.responsive.css
- public/assets/styles/piedPage.responsive.css
- public/entete.js
- public/modules/interactions/brancheMenuSandwich.js
- src/vues/base.pug
- src/vues/index.pug
- src/vues/mss.pug
Toute la page d'accueil est responsive
Dans cette branche il y a les commits des PRs #602 #603 #608 mais sans les commits de bouchonnage débouchonnage
3 gammes d'écrans
- mobile < 767px
- tablette 768px -> 1247px
- desktop > 1247px
> Responsive page d'accueil

- src/vuesTex/annexeMesures.template.tex
- src/vuesTex/annexeRisques.template.tex
- src/vuesTex/fragments/couleurs.tex
- src/vuesTex/fragments/definitionDocument.tex
- src/vuesTex/macros/boiteGrise.tex
- src/vuesTex/macros/entetePiedPage.tex
Dans les templates latex servant à générer les annexes pdf,
Il y avait beaucoup de code en commun,
Une factorisation s'imposait 🙂.
Aucun comportement n'a été changé
info sur les macros https://en.wikibooks.org/wiki/LaTeX/Macros#New_commands
> Macros dans les templates latex

- src/adaptateurs/adaptateurPdfLatex.js
- src/routes/routesPdf.js
J'ai inséré la ou les pages Description au début pdf `/pdf/:id/annexes.pdf`
> Annexe description dans les annexes

- src/adaptateurs/adaptateurPdfLatex.js
- src/routes/routesPdf.js
- test/routes/routesPdf.spec.js
J'ai retiré la route inutilisée `/pdf/:id/annexeDescription.pdf`
> Nettoyage route pdf annexe description

- public/assets/styles/entete.css
- public/entete.js
Cette PR ajoute un élément dans le menu utilisateur 👇
> Ajoute lien vers changement mot de passe

- src/vues/fragments/formulaireDescriptionService.pug
> Ajout de Risk Manager après Ebios

- .env.template
- donneesReferentiel.js
- public/assets/styles/homologation/synthese.css
- server.js
- src/adaptateurs/adaptateurEnvironnement.js
- src/modeles/actionSaisie.js
- src/modeles/dossiers.js
- src/mss.js
- src/referentiel.js
- src/routes/routesHomologation.js
- src/vues/homologation/synthese.pug
- test/modeles/actionSaisie.spec.js
- test/modeles/actionsSaisie.spec.js
- test/modeles/dossiers.spec.js
- test/routes/routesHomologation.spec.js
- test/routes/testeurMSS.js
Je profite de cette PR pour nettoyer du code mort :
- gestion des actions indisponibles
- gestion de la variable d'environnement `AVEC_ACCES_REFERENTIEL`
(Ça me semblait judicieux de ne pas faire de PR à part, mais si vous pensez le contraire on peut revoir ça.)
> Affichage de la coche « action terminée » sur la carte « Homologuer »

- consoleAdministration.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
… pour alimenter le journal MSS avec les données introduites par d3bab405a1b386783484ebf4477216669b5ddf33.
Ce commit reprend le code de 71dbae6dd8f9a071328d45775a43b6bcf382c387. Il a donc les mêmes défauts de duplication non élégante.
> Génère un événement de complétude pour chaque service

- public/assets/styles/espacePersonnel.css
Cette PR ajoute un fond blanc aux « … » ce qui donne 👇
> Affiche toujours les « … » sur fond blanc

- public/assets/styles/modaleDuplicationService.css
- public/espacePersonnel.js
- src/vues/fragments/modales/modaleDuplicationService.pug
Duplication multiple de service directement depuis le front
Note : J'ai ajouté un validateur de présence sur le nombre de service
> Duplication multiple de service

- public/assets/images/icone_coche_blanche.svg
- public/assets/styles/etapesDossier.css
- src/vues/homologation/formulaireEtapier.pug
Dans le parcours homologation,
l'étapier a un nouveau style
> Nouveau style pour l'étapier

- donneesReferentiel.js
- public/assets/styles/etapesDossier.css
- public/homologation/etapes/1.js
- server.js
- src/erreurs.js
- src/modeles/dossier.js
- src/modeles/etapes/datesTelechargements.js
- src/mss.js
- src/referentiel.js
- src/routes/routesApi.js
- src/routes/routesApiService.js
- src/vues/homologation/etapeDossier/1.pug
- src/vues/homologation/etapeDossier/2.pug
- src/vues/homologation/formulaireEtapier.pug
- test/modeles/dossier.spec.js
- test/modeles/etapes/datesTelechargements.spec.js
- test/modeles/homologation.spec.js
- test/referentiel.spec.js
- test/routes/routesApiService.spec.js
- test/routes/testeurMSS.js
On ajoute les dates de téléchargements dans l'étape de décision.
> Etape decision

- src/vues/fragments/descriptionIndiceCyber.pug
> [CORRECTION] Corrige typo

- public/assets/images/entete_fenetre_bom.svg
- public/assets/images/forme_chevron_blanc.svg
- public/assets/images/icone_croix_blanche.svg
- public/assets/images/icone_croix_bleue.svg
- public/assets/images/vignette_bom.svg
- public/assets/images/vignette_bom_survol.svg
- public/assets/styles/bom.css
- public/scripts/bom.js
- src/vues/mss.pug
- src/vues/mssDeconnecte.pug
Dans les pages publiques,
en bas à droite on peut y voir un BOM
Pages :
- `/`
- `/aPropos`
- `/cgu`
- `/confidentialite`
- `/mentionsLegales`
- `/nouvellesFonctionnalites`
- `/statistiques`
> BOM dans les pages publiques

- public/assets/styles/etapesDossier.css
- src/vues/homologation/etapeDossier/1.pug
… pour correspondre à ce que @marids demande 👇
> Sépare la date du document par un tiret

- donneesReferentiel.js
- public/homologation/etapesDossier.js
- src/adaptateurs/adaptateurPdfLatex.js
- src/modeles/dossier.js
- src/modeles/etapes/autorite.js
- src/routes/routesApiService.js
- src/routes/routesApiServicePdf.js
- src/vues/service/etapeDossier/autorite.pug
- src/vues/service/etapeDossier/decision.pug
- test/constructeurs/constructeurDossier.js
- test/modeles/dossier.spec.js
- test/routes/routesApiService.spec.js
- test/routes/routesApiServicePdf.spec.js
L'étape `Autorité` permet, dans le parcours d'homologation, d'enregistrer le Nom - Prénom et fonction de la personne en charge de l'homologation.
> Etape autorité

- public/assets/styles/etapesDossier.css
- src/vues/service/etapeDossier/autorite.pug
… et corrige au passage les espacements verticaux.
Le bug en PROD : 
La maquette :
L'UI avec cette PR :
> [CORRECTION] Masque une bordure inférieure qui ne doit pas être présente

- src/adaptateurs/adaptateurPdfLatex.js
- test/modeles/dossier.spec.js
> Correction de deux typos

- donneesReferentiel.js
- public/assets/styles/cartes/recommandationsANSSI.css
- src/referentiel.js
- src/routes/routesService.js
- src/vues/cartes/recommandationsANSSI.pug
- src/vues/service/etapeDossier/decision.pug
- test/referentiel.spec.js
Dans le parcours homologuer,
On souhaite avoir une carte qui indique l'indice cyber et les recommandations en fonction de celui ci
> Carte recommandation de l'ANSSI

- src/http/middleware.js
- src/modeles/avis.js
- src/modeles/dossier.js
- src/modeles/etapes/etapeAvis.js
- src/routes/routesApiService.js
- test/http/middleware.spec.js
- test/modeles/dossier.spec.js
- test/routes/routesApiService.spec.js
Cette PR ajoute la route permettant d'enregistrer les avis d'un dossier d'homologation.
> Nouvelle route `PUT /dossier/avis`

- donneesReferentiel.js
Cette PR change la formulation de la recommandation, qui devient 👇
> Raccourcis la phrase de recommandation ANSSI

- src/adaptateurs/adaptateurPdfHtml.js
- src/pdf/modeles/annexeDescription.pug
- src/pdf/modeles/annexes.pug
- src/pdf/modeles/dossierDecision.pug
- src/routes/routesApiServicePdf.js
- test/routes/routesApiServicePdf.spec.js
Le PDF d'annexe de description est généré via un template Pug (HTML seulement pour l'instant).
> Template Pug du PDF d'annexe de description

- donneesReferentiel.js
- src/adaptateurs/adaptateurPdfHtml.js
- src/pdf/modeles/annexeDescription.pug
- src/pdf/modeles/annexeMesures.pug
- src/pdf/modeles/annexeRisques.pug
- src/pdf/modeles/annexes.pug
- src/pdf/modeles/ressources/styles.css
- src/referentiel.js
- src/routes/routesApiServicePdf.js
- test/referentiel.spec.js
On ajoute la génération d'annexe des risques avec la nouvelle UI.
> Annexe risques

- src/pdf/modeles/annexeDescription.pug
- src/pdf/modeles/annexeMesures.pug
- src/pdf/modeles/annexeRisques.pug
- src/pdf/modeles/annexes.pug
- src/pdf/modeles/ressources/styles.css
Nous avons remplacer les fieldset par des tableaux pour réussir des saut de page de haut niveau.
> Modification des annexes html pour le saut de page

- src/adaptateurs/adaptateurPdf.js
- src/adaptateurs/adaptateurPdf.puppeteer.js
- src/routes/routesApiServicePdf.js
Le but est d'améliorer les performances de génération, et d'alléger la consommation de ressources.
Les benchmarks en local :
```
AVANT
mon-service-securise-web-1  | Execution time (hr): 1s 599.552418ms
mon-service-securise-web-1  | Execution time (hr): 1s 149.564667ms
mon-service-securise-web-1  | Execution time (hr): 1s 14.023041ms
mon-service-securise-web-1  | Execution time (hr): 1s 13.585ms
mon-service-securise-web-1  | Execution time (hr): 1s 71.815084ms
mon-service-securise-web-1  | Execution time (hr): 1s 180.533793ms
mon-service-securise-web-1  | Execution time (hr): 1s 74.471876ms
mon-service-securise-web-1  | Execution time (hr): 1s 112.358167ms
mon-service-securise-web-1  | Execution time (hr): 0s 999.13575ms
mon-service-securise-web-1  | Execution time (hr): 1s 86.553334ms …
```
> Remaniement Puppeteer

- .env.template
- package-lock.json
- package.json
- server.js
- src/adaptateurs/adaptateurEnvironnement.js
- src/adaptateurs/adaptateurGestionErreurSentry.js
- src/adaptateurs/adaptateurGestionErreurVide.js
- src/mss.js
- src/vues/erreur.pug
- test/routes/testeurMSS.js
Quand l'application a des erreurs, elles seront envoyer dans sentry
Nous ajoutons aussi une page qui s'affiche quand il y a des erreurs
> Monitoring via Sentry

- consoleAdministration.js
… pour faciliter leur filtrage côté Metabase.
> Marque les événements générés par un administrateur

- src/http/middleware.js
- src/routes/routesApiService.js
- src/routes/routesApiServicePdf.js
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/routes/routesApiService.spec.js
- test/routes/routesApiServicePdf.spec.js
Nous ajoutons une nouvelle méthode de middleware afin de diminuer la duplication de code et simplifier l'accés au dossier courant.
> Middleware trouve dossier courant

- src/vues/mssConnecte.pug
> [CORRECTION] Corrige l'url des nouvelles fonctionnalités

- public/assets/styles/etapesDossier/avis.selectize.css
- public/homologation/etapes/avis.js
- public/modules/arrangeParametresAvis.mjs
- public/modules/parametres.mjs
- src/mss.js
- src/routes/routesBibliotheques.js
- src/routes/routesStyles.js
- src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
- src/vues/service/etapeDossier/avis.pug
- test/routes/routesStyles.spec.js
- test_public/modules/arrangeParametresAvis.spec.mjs
Dans l'étape avis du parcours d'homologation,
nous souhaitons avoir plusieurs collaborateurs pour le même avis
NOTE : ajout de la lib Selectize https://selectize.dev/
> Multi collaborateurs pour les avis

- src/vues/service/etapeDossier/avis.pug
Dans la page avis du parcours homologation,
Nous souhaitons voir la recommandation de l'ANSSI et l'indice cyber du service
> Recommandation de l'ANSSI dans la page avis

- public/assets/styles/homologation/formulaire.css
- public/homologation/etapes/avis.js
- src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
- src/vues/service/etapeDossier/avis.pug
Cette PR ajoute des boutons radio pour afficher ou masquer la saisie d'avis 👇
> Boutons radio pour la saisie des avis

- donneesReferentiel.js
- src/modeles/dossier.js
- test/modeles/dossier.spec.js
Nous activons l'étape "Avis" dans le parcours d'homologation
> Activation etape avis

- creeUtilisateurDemo.js
Cela permet de rendre opérationnel, dès le départ, le filtre côté front sur les services.
> Ajoute une « organisation responsable » au service de test

- src/pdf/modeles/annexe.piedpage.pug
- src/pdf/modeles/annexeMesures.pug
- src/pdf/modeles/base.pug
- src/pdf/modeles/ressources/styles.css
- src/pdf/modeles/ressources/tourDePage.css
Liste des corrections :
- Mise en page des annexes via les retours de Mari
- Correction du wording sur les mesures restantes
> [CORRECTION] Met en page les PDF

- src/vues/service/etapeDossier/autorite.pug
- src/vues/service/etapeDossier/avis.pug
- src/vues/service/etapeDossier/decision.pug
- src/vues/service/etapeDossier/documents.pug
- src/vues/service/formulaireEtapierRecommandation.pug
Dans le parcours homologation,
nous souhaitons voir la recommandation de l'anssi dans les étapes 1 à 4
La carte était présente dans Avis Documents et Décision il manquait Autorité
> Recommandation de l'ANSSI dans l'étape autorité

- donneesReferentiel.js
- public/assets/styles/cartes/recommandationsANSSI.css
- public/assets/styles/palette.css
- src/pdf/modeles/annexeAvis.pug
- src/vues/cartes/indiceCyber.pug
- src/vues/cartes/recommandationsANSSI.pug
- src/vues/fragments/carteInformations.pug
- src/vues/fragments/cartesInformations.pug
- src/vues/service/formulaireEtapierRecommandation.pug
- src/vues/service/risques.pug
- src/vues/service/synthese.pug
Dans les pages du parcours homologuer qui contiennent la carte de recommandation (Autorité, Avis, Documents, Décision, Date)
La carte de recommandation a été mise à jour
La page d'annexe des Avis à été touchée par la modification
> Carte recommandation du parcours homologuer

- src/vues/mss.pug
- src/vues/mssConnecte.pug
Changement de l'url de tchat dans le BOM
> Changement de l'url de tchat dans le BOM

- public/assets/images/icone_ajout_pastille_bleue.svg
- public/assets/images/icone_supprimer_gris.svg
- public/assets/styles/modules/selectize.css
- public/utilisateur/suggestionEntite.js
- src/vues/fragments/formulaireUtilisateur.pug
Dans l'inscription et l'édition de profil, on donne la possibilité d'ajouter son organisation si elle n'existe pas dans la liste.
Le champ `département` redevient obligatoire.
> Recherche API - Ajout organisation libre

- consoleAdministration.js
On ajoute une fonction pour supprimer "proprement" un compte (l'utilisateur, ses autorisations et ses services).
> [Admin] Fonction de suppression de compte

- .env.template
- .eslintrc.js
- public/scripts/matomoGestionnaireTag.js
- src/adaptateurs/adaptateurEnvironnement.js
- src/http/middleware.js
- src/mss.js
- src/routes/routesBibliotheques.js
- src/vues/base.pug
- test/http/middleware.spec.js
Ceci nous permet de remonter vers Matomo des evénements spécifiques.
> Ajout du gestionnaire d'étiquette de Matomo

- src/adaptateurs/adaptateurMailSendinblue.js
… pour éviter d'envoyer des e-mails contenant des « `de l&#x27;étoile` »
> [CORRECTION] Décode les caractères HTML envoyés à Sendinblue

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/gestionnaireActionsTirroir.mjs
- public/tableauDeBord.js
- src/vues/tableauDeBord.pug
... pour nous permettre de réutiliser le comportement de validation
> Encapsule toutes les actions tiroir dans des formulaires

- src/adaptateurs/adaptateurMailSendinblue.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
… pour ne pas faire fuiter de logique d'infrastructure dans l'API.
> Déplace la détection de contact existant dans l'adaptateur

- public/assets/images/icone_croix_blanche.svg
- public/assets/images/icone_croix_bleue.svg
- public/assets/images/icone_croix_grise.svg
- public/assets/styles/bom.css
- src/vues/mss.pug
... afin d'être plus facilement accessible sur smartphone.
> Déplacement du bouton de fermeture du BOM

- server.js
- src/adaptateurs/adaptateurCsv.js
- src/mss.js
- src/routes/routesApi.js
- test/routes/routesApi.spec.js
- test/routes/testeurMSS.js
On souhaite exporter une liste de services séléctionnés en `CSV`.
Pour cela on ajoute un `adaptateurCsv` et on se base sur `objetGetServices` car il contient toutes les données nécessaires.
> [TDB] Route export des services CSV

- server.js
- src/adaptateurs/adaptateurAnnuaire.js
- src/adaptateurs/adaptateurCsv.js
- src/adaptateurs/adaptateurGestionErreurSentry.js
- src/adaptateurs/adaptateurGestionErreurVide.js
- src/adaptateurs/adaptateurMailSendinblue.js
- src/adaptateurs/adaptateurPdf.js
- src/adaptateurs/fabriqueAdaptateurGestionErreur.js
- src/routes/routesApiServicePdf.js
- test/routes/routesApiServicePdf.spec.js
…pour être tenu au courant des erreurs internes.
> Utilisation de Sentry dans les adaptateurs

- public/modules/tableauDeBord/tableauDesServices.mjs
- src/adaptateurs/adaptateurCsv.js
- src/modeles/objetsApi/objetGetServices.js
- test/modeles/objetsApi/objetGetServices.spec.js
... pour supprimer la duplication de code
> Déplace les statuts d'homologation

- src/routes/routesService.js
- test/routes/routesService.spec.js
... afin d'éviter qu'un utilisateur puisse accéder à une étape suivante sans avoir complété les précédentes.
> Ajoute une redirection vers l'étape courante

- public/assets/styles/tableauDeBord.css
- src/vues/tableauDeBord.pug
> Place la barre de recherche sous les informations résumées

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/tableauDesServices.mjs
On affiche désormais la note totale de l'indice cyber
> Ajoute la note totale dans l'indice cyber

- public/assets/styles/tableauDeBord.css
Pour que tout fonctionne bien, même sur les résolutions verticales pour qui il faut une scroll bar.
> Amélioration de la position et du scroll du tiroir

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/gestionnaireActionsTiroir.mjs
- src/vues/tableauDeBord.pug
Afin de montrer que l'action est en cours.
> [TDB] Affiche un loader pendant la duplication et la suppression

- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- public/modules/tableauDeBord/tableauDesServices.mjs
- src/vues/tableauDeBord.pug
... venant de la recherche textuelle ou du filtrage "Mes services"
> Efface la sélection des services au moment d'un filtrage

- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- public/modules/tableauDeBord/actions/ActionDuplication.mjs
- public/modules/tableauDeBord/actions/ActionExport.mjs
- public/modules/tableauDeBord/actions/ActionInvitation.mjs
- public/modules/tableauDeBord/actions/ActionInvitationConfirmation.mjs
- public/modules/tableauDeBord/actions/ActionSuppression.mjs
- public/modules/tableauDeBord/actions/ActionTelechargement.mjs
- public/modules/tableauDeBord/gestionnaireBarreOutils.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- public/modules/tableauDeBord/gestionnaireTiroir.mjs
- public/modules/tableauDeBord/registreActions.mjs
- public/modules/tableauDeBord/tableauDesServices.mjs
- src/vues/tableauDeBord.pug
On fait émerger un `gestionnaireBarreOutils` et on extrait le `registreDesActions`.
> Conditionne l'affichage des outils en fonction de la selection

- public/modules/tableauDeBord/actions/ActionInvitation.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- src/vues/tableauDeBord.pug
... Afin d'offrir la fonctionnalité telle qu'elle est prévue.
> [CORRECTION] Redirection vers liste des contributeurs dans le tiroir invitation

- public/modules/tableauDeBord/actions/ActionInvitation.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- src/vues/tableauDeBord.pug
Afin d'expliquer à l'utilisateur l'erreur.
> [CORRECTION] Affiche une erreur si la personne est déjà invitée

- src/vues/mssInscription.pug
Afin de coller avec le nouveau wording de la maquette Figma :point_down:
> Modifie le wording du bandeau d'inscription

- src/vues/tableauDeBord.pug
... afin de coller avec la nouvelle maquette Figma.
> Renomme le titre de la page tableau de bord

- migrations/20230615101630_creationTableParcoursUtilisateur.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesParcoursUtilisateur.js
- src/modeles/parcoursUtilisateur.js
- src/routes/routesApi.js
- test/depots/depotDonneesParcoursUtilisateur.spec.js
- test/modeles/parcoursUtilisateur.spec.js
- test/routes/routesApi.spec.js
On créer le dépôt des parcours utilisateur.
Au passage, on implémente la sauvegarde de la dernière date de connexion au moment de la récupération d'un token, afin de commencer à alimenter la base.
> [Carrousel] Dépôt & route `/token`

- donneesReferentiel.js
- src/depotDonnees.js
- src/depots/depotDonneesParcoursUtilisateur.js
- src/modeles/parcoursUtilisateur.js
- src/routes/routesApi.js
- test/modeles/parcoursUtilisateur.spec.js
- test/routes/routesApi.spec.js
On utilise désormais le modèle `ParcoursUtilisateur` pour connaitre la nouvelle fonctionnalité si disponible.
Cette dernière est ajouté à la payload de la réponse sur la route `GET /token`
> [Carrousel] Enrichissement du token avec la nouvelle fonctionnalité

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
Pour préparer l'arrivée à venir du chiffrement des données métier.
Pour rappel nous ciblons le design suivant 👇 
Un bout d'historique est disponible dans #923.
Cette PR implémente le design montré ci-dessus.
> [REMANIEMENT] Point d'entrée unique vers la sauvegarde d'homologation

- donneesReferentiel.js
... car il y avait un résidu de test local.
> Corrige les données réferentiel

- src/routes/routesApi.js
- test/routes/routesApi.spec.js
On prépare la possibilité de supprimer un contributeur d'un service, lorsqu'on en est propriétaire.
L'objectif est de pouvoir faire cette action depuis le tirroir 'contributeurs' du tableau de bord.
> Ajoute la route de suppression d'autorisation

- src/vues/mssConnecte.pug
Suppression du mailto:Faire une suggestion
> [BOM] Suppression de "Faire une suggestion'

- public/assets/images/icone_information_suppression.svg
- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- src/vues/tableauDeBord.pug
On ajoute un menu d'actions flotantes au tirroir des contributeurs pour pouvoir les retirer du service.
> [TDB] Suppression de contributeur unique

- public/modules/tableauDeBord/actions/ActionContributeurs.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- src/vues/tableauDeBord.pug
... et corrige au passage l'affichage des menus flottants en harmonisant les déclencheurs :point_down:
> [CORRECTION] Affichage de confirmation de suppression contributeur

- src/vues/nouvellesFonctionnalites/tableauDeBord.pug
> Utilise « Suivant » comme texte du premier bouton

- src/depots/depotDonneesUtilisateurs.js
- test/depots/depotDonneesUtilisateurs.spec.js
La review devient facile si on la fait commit par commit.
> [REMANIEMENT] Passage en `async/await` de `depotDonneesUtilisateurs`

- donneesReferentiel.js
- public/assets/styles/tableauDeBord.css
On en profites pour ré-aligner le crayon après un retour recette.
> [CORRECTION] Wording du statut 'Active'

- .env.template
- package-lock.json
- package.json
- server.js
- src/http/middleware.js
- src/mss.js
- src/vues/accesRefuse.pug
- src/vues/admin/inscription.pug
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/mss.spec.js
Cette route n'a plus aucune utilité.
On peut au passage supprimer des vues et un package inutile
> [NETTOYAGE] Suppression de la route admin/inscription

- .env.template
- package-lock.json
- package.json
- server.js
- src/adaptateurs/adaptateurProtection.js
- src/mss.js
- src/vues/erreurTropDeTrafic.pug
- test/routes/testeurMSS.js
C'est [codeQL](https://github.com/betagouv/mon-service-securise/security/code-scanning/97) qui nous a alerté aujourd'hui.
Cette PR corrige le problème.
> Ajout d'une protection `rate-limit`

- src/mss.js
- src/routes/privees/routesApiPrivee.js
- test/routes/privees/routesApiPrivee.spec.js
À la manière de #998 pour les routes d'API publique.
> [REMANIEMENT] Déplacement des routes de l'API privée dans un routeur dédié

- src/depotDonnees.js
- src/depots/depotDonneesUtilisateurs.js
- src/erreurs.js
- test/depots/depotDonneesUtilisateurs.spec.js
On ajoute une méthode pour pouvoir vérifier le mot de passe d'un utilisateur.
Cette méthode servira par la suite à valider l'identité d'un utilisateur au moment d'une action sensible.
On compare le mot de passe passé avec celui haché dans notre base de données.
> Depot données - Vérification du mot de passe

- public/motDePasse/edition.js
- src/mss.js
- src/vues/motDePasse/edition.pug
Cette PR ajoute ce champ, et la logique de vérification qui va avec 👇
> Ajout du challenge de mot de passe lors du changement de mot de passe

- src/modeles/objetsApi/objetGetServices.js
- test/modeles/objetsApi/objetGetServices.spec.js
Suite à une erreur remontée en Démo.
> [CORRECTION] Comptabilise les services bientôt expirés dans les services homologués

- public/assets/styles/formulaire.css
- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
- src/adaptateurs/adaptateurMailMemoire.js
- src/adaptateurs/adaptateurMailSendinblue.js
- src/modeles/utilisateur.js
- src/routes/mappeur/utilisateur.js
- src/routes/privees/routesApiPrivee.js
- src/routes/publiques/routesApiPublique.js
- src/vues/fragments/formulaireUtilisateur.pug
- src/vues/mssInscription.pug
- src/vues/utilisateur/edition.pug
- test/constructeurs/constructeurUtilisateur.js
- test/modeles/utilisateur.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/publiques/routesApiPublique.spec.js
Cette PR ajoute la case à cocher au profil, et la synchronisation avec Brevo.
> Affichage de « je souscris aux emails transactionnels » dans le profil

- test/depots/depotDonneesHomologations.spec.js
> Passage de tests en `async/await`

- src/depots/depotDonneesHomologations.js
- src/modeles/autorisations/ajoutContributeurSurService.js
- src/tracking/serviceTracking.js
- test/constructeurs/constructeurDepotDonneesServices.js
- test/tracking/serviceTracking.spec.js
> Renomme la fonction de fabrication du service de Tracking

- src/modeles/autorisations/ajoutContributeurSurServices.js
- src/routes/privees/routesApiPrivee.js
- src/routes/procedures.js
- test/modeles/autorisations/ajoutContributeurSurServices.spec.js
- test/routes/privees/routesApiPrivee.spec.js
Cette PR permet d'appeler l'ajout avec une collection de services sur lesquels ajouter un contributeur.
> Changement d'API métier pour l'ajout de contributeur

- src/modeles/autorisations/ajoutContributeurSurServices.js
- test/modeles/autorisations/ajoutContributeurSurServices.spec.js
La suite est que l'API appelle la logique en lui fournissant bel et bien plusieurs services.
Désormais le code ne jette plus d'erreur en cas de ré-invitation. Et ne traite que les services sur lesquels le contributeur n'existe pas déjà.
> Permets d'ajouter un contributeur sur plusieurs services à la fois

- src/vues/fragments/formulaireUtilisateur.pug
Suite à une demande juridique.
> Change la formulation du label

- public/modules/tableauDeBord/gestionnaireEvenements.mjs
La gestion des contributeurs se fait désormais en Svelte.
> Supprime du code mort

- public/scripts/menuNavigation.js
- src/vues/fragments/menuNavigation.pug
Le bug en image : on voit 1 contributeur sur le service en cours de création + une erreur `404` dans la console 👇 
Cette PR masque tout ce cadre bleu au moment de la création de service 👇 
Ce qui donne 👇
> [CORRECTION] N'affiche pas les contributeurs pendant la création du service

- public/assets/styles/tiroir.css
- public/modules/tableauDeBord/actions/ActionTelechargement.mjs
- public/modules/tableauDeBord/gestionnaireBarreOutils.mjs
- src/vues/service/etapeDossier/dateTelechargement.pug
- src/vues/tableauDeBord.pug
- src/vues/tiroirs/tiroirTelechargement.pug
Afin de ne pas montrer à l'utilisateur "ce qu'il ne peut pas faire".
> Masquage des PDF indisponibles

- public/modules/soumetsHomologation.mjs
- public/service/mesures.js
- public/service/risques.js
- public/service/rolesResponsabilites.js
- src/modeles/autorisations/gestionDroits.js
- src/routes/privees/routesService.js
- test/routes/privees/routesService.spec.js
- test_public/modules/soumetsHomologation.spec.mjs
Lors de l'accès à un service depuis le tableau de bord, on souhaite rediriger l'utilisateur vers la première rubrique à laquelle il peut accéder.
On en profite pour corriger l'ancienne redirection de chaque rubrique vers la synthèse qui n'existe plus.
> Redirection vers la première rubrique disponible

- public/assets/styles/deuxColonnes.css
Cette PR ajoute les effets `hover` et `active` sur le lien de retour vers le tableau de bord 👇
> Ajoute effets `hover` et `active` sur le lien de retour au tableau de bord

- public/assets/styles/deuxColonnes.css
Pour être conforme aux maquettes.
> Rétrécis le logo MSS sur les pages « Service »

- public/assets/styles/tiroir.css
- src/modeles/objetsApi/objetGetAutorisation.js
- src/modeles/objetsApi/objetGetService.js
- src/routes/privees/routesApiPrivee.js
- src/routes/privees/routesApiService.js
- svelte/lib/gestionContributeurs/GestionContributeurs.svelte
- svelte/lib/gestionContributeurs/InvitationContributeur.svelte
- svelte/lib/gestionContributeurs/LigneContributeur.svelte
- svelte/lib/gestionContributeurs/SuppressionContributeur.svelte
- svelte/lib/gestionContributeurs/TagNiveauDroit.svelte
- svelte/lib/gestionContributeurs/gestionContributeurs.d.ts
- svelte/lib/gestionContributeurs/gestionContributeurs.store.ts
- svelte/lib/ui/MenuFlottant.svelte
- test/modeles/objetsApi/objetGetService.spec.js
- test/modeles/objetsApi/objetGetServices.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/privees/routesApiService.spec.js
Cette PR ajoute la possibilité d'avoir la modification des droits depuis Svelte.
Modification des droits dans la liste des contributeurs 👇 
… et modification lors de l'invitation 👇
> Modification des droits depuis Svelte

- svelte/lib/gestionContributeurs/SuppressionContributeur.svelte
… sur le fait que la suppression est réversible 👇
> Supprime message d'information

- svelte/lib/gestionContributeurs/gestionContributeurs.d.ts
- svelte/lib/gestionContributeurs/invitation/BoutonsActions.svelte
- svelte/lib/gestionContributeurs/invitation/EnvoiEnCours.svelte
- svelte/lib/gestionContributeurs/invitation/InvitationContributeur.svelte
- svelte/lib/gestionContributeurs/invitation/ListeInvitations.svelte
- svelte/lib/gestionContributeurs/invitation/Rapport.svelte
- svelte/lib/gestionContributeurs/invitation/invitation.api.ts
- svelte/lib/gestionContributeurs/personnalisation/PersonnalisationDroits.svelte
Cette PR extrait des composants pour alléger `<InvitationContributeur />`.
Nouvelle organisation 👇
> ✂️ Découpage du Svelte `<InvitationContributeur />`

- svelte/lib/gestionContributeurs/personnalisation/PersonnalisationDroits.svelte
… lors de l'invitation, ou bien en gérant les contributeurs.
Décocher la case rend la rubrique invisible 👇
> Permets de masquer une rubrique

- src/modeles/autorisations/autorisationBase.js
- src/modeles/objetsApi/objetGetService.js
- src/modeles/objetsApi/objetGetServices.js
- src/routes/privees/routesService.js
- src/vues/service/mesures.pug
- test/routes/privees/routesService.spec.js
> Masque le statut homologation pour les utilisateurs ne pouvant pas le voir

- public/assets/images/icone_check.svg
- svelte/lib/gestionContributeurs/kit/OnOff.svelte
- svelte/lib/gestionContributeurs/personnalisation/PersonnalisationDroits.svelte
Cette PR change les checkbox en un composant plus proche de la maquette 👇
> Utilise un joli « on / off » à la place de la checkbox classique

- public/service/descriptionService.js
- src/vues/fragments/formulaireDescriptionService.pug
> Change un placeholder

- public/assets/styles/bouton.css
- public/assets/styles/formulaire.css
- public/modules/enregistreRubrique.mjs
- public/modules/soumetsHomologation.mjs
- public/service/homologation/formulaireEtape.js
- public/service/mesures.js
- public/service/risques.js
- public/service/rolesResponsabilites.js
- src/vues/service/risques.pug
- src/vues/service/rolesResponsabilites.pug
On souhaite faire apparaitre un `loader` au moment de l'enregistrement des rubriques du 'parcours service' afin de signaler à l'utilisateur que l'enregistrement est en cours coté serveur.
Ce loader remplace le texte du bouton et `disable` le bouton en attendant de rafraichir la page.
> Loader sur enregistrement des rubriques

- src/adaptateurs/adaptateurPersistanceMemoire.js
Afin de nettoyer tout MSS de la notion de `type` d'autorisation
> Supprime l'utilisation du type `createur` dans l'adaptateur mémoire

- svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte
Afin de coller avec la nouvelle maquette
> Modifie le wording de l'item de menu 'Personnalisé'

- .github/workflows/codeql-analysis.yml
- .github/workflows/node.js.yml
...puisque nous utilisons maintenant `Node v18`
> Met à jour les actions Github

- src/vues/deuxColonnes.pug
- src/vues/historiqueProduit.pug
- src/vues/motDePasse/edition.pug
- src/vues/nouvellesFonctionnalites/menuNavigation.pug
- src/vues/nouvellesFonctionnalites/tableauDeBord.pug
- src/vues/tableauDeBord.pug
- src/vues/utilisateur/edition.pug
… pour qu'il cesse de rediriger vers l'accueil.
On en profite pour ajouter des attributs `title`.
> Change le lien du logo MSS sur le tableau de bord

- src/adaptateurs/adaptateurPostgres.js
On recherche maintenant tout les 'autres' contributeurs sur tout les services dont l' utilisateur est propriétaire, et qui ne sont pas cet utilisateur
> Utilise `estProprietaire` dans la méthode `rechercheContributeurs`

- src/vues/fragments/formulaireUtilisateur.pug
... Afin de préciser aux utilisateurs de préféré leur email de travail
> Modifie 'Email' en 'Email professionnel' au moment de l'inscription

- public/assets/styles/menuNavigation.css
Le nombre de contributeurs était "coupé" si il était plus grand que 9.
> [CORRECTION] Corrige l'affichage du nombre de contributeurs quand ils sont > 9

- src/routes/privees/routesApiPrivee.js
> Passe en `async/await`

- public/assets/styles/menuNavigation.css
- public/scripts/menuNavigation.js
- src/vues/fragments/menuNavigation.pug
Après une demande du pôle bizDev : les utilisateurs ne trouve pas le bouton
> Ouvre le bouton "Inviter des contributeurs" pendant 3 secondes à l'ouverture du menu

- public/assets/images/forme_chevron_bleu_fonce.svg
- public/assets/styles/menuNavigation.css
- src/vues/fragments/menuNavigation.pug
> Ajoute le lien vers la page de l'indice cyber

- donneesReferentiel.js
Ces données étaient exploitées par la carte de recommandation de l'ANSSI.
> Suppression des données obsolètes du référentiel

- src/vues/service/etapeDossier/documents.pug
Corrrection d'une faute d'orthographe.
> Correction orthographique dans documents.pug

- src/vues/tiroirs/tiroirDuplication.pug
... Afin de rester cohérent avec le nouveau `rate-limit` en place
> Diminue le nombre maximum de copie à 10

- svelte/lib/ui/FermetureSurClicEnDehors.svelte
- svelte/lib/ui/MenuFlottant.svelte
... afin de pouvoir le réutiliser plus facilement dans le nouveau composant 'TableauDesMesures`
> [REMANIEMENT] Extrais le composant de 'Fermeture' d'un menu flottant

- svelte/lib/directives/validationChamp.ts
- svelte/lib/mesure/Mesure.svelte
… mais cette fois en spécifiant le nombre de lignes 👇
> Reviens au `textarea`

- public/service/mesures.js
> Utilise `Enregistré`

- public/assets/images/icone_danger_bleu.svg
- svelte/lib/mesure/Mesure.svelte
- svelte/lib/mesure/mesure.api.ts
- svelte/lib/mesure/mesure.store.ts
- svelte/lib/mesure/suppression/SuppressionMesureSpecifique.svelte
On ajoute le tiroir permettant de supprimer une mesure spécifique.
On réutilise le même sytème d'Étape que dans la `GestionContributeurs`.
> [SECURISER] Suppression d'une mesure spécifique

- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
> Renomme le bouton "Ajouter"

- svelte/lib/mesure/mesure.store.ts
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
... afin de n'utiliser qu'un "référentiel"
> Renomme les mesures "Ajoutée" et "Nouvelle" en "Spécifique"

- svelte/lib/ui/CartoucheReferentiel.svelte
... Suite à une décision Produit.
> [SECURISER] Modifie le wording de "Spécifique" en "Mesure ajoutées"

- src/routes/privees/routesService.js
... afin de mettre en production la nouvelle page de mesure.
La suppression de l'ancienne page et des fichiers annexes se fera dans une autre PR.
> [SECURISER] Remplace la vue `mesure` par `mesure-v2`

- svelte/lib/directives/surligneTexte.ts
- svelte/lib/mesure/Mesure.svelte
- svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
- svelte/lib/tableauDesMesures/tableauDesMesures.store.ts
... dans le cas d'une recherche textuelle.
> [SECURISER] Surligne la description longue

- svelte/lib/mesure/Mesure.svelte
- svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
... car il y'a avait encore un bug en cas de recherche vide
> [CORRECTION] Corrige la recherche dans les descriptions longue

- public/assets/styles/accessibilite.css
- public/assets/styles/piedPage.css
- src/mss.js
- src/vues/accessibilite.pug
- src/vues/mss.pug
On ajoute la page Accessibilité pour être conforme aux réglementations.
Le travail de mise à niveau de l'accessibilité globale sera fait au fur et à mesure, sur l'année 2024.
> Page accessibilité

- src/vues/aPropos.pug
- src/vues/accessibilite.pug
- src/vues/activation.pug
- src/vues/base.pug
- src/vues/cgu.pug
- src/vues/confidentialite.pug
- src/vues/connexion.pug
- src/vues/erreur.pug
- src/vues/erreurAccesRefuse.pug
- src/vues/erreurTropDeTrafic.pug
- src/vues/historiqueProduit.pug
- src/vues/inscription.pug
- src/vues/mentionsLegales.pug
- src/vues/motDePasse/edition.pug
- src/vues/reinitialisationMotDePasse.pug
- src/vues/service/decrire.pug
- src/vues/service/dossiers.pug
- src/vues/service/formulaireEtapier.pug
- src/vues/service/indiceCyber.pug
- src/vues/service/mesures.pug
- src/vues/service/risques.pug
- src/vues/service/rolesResponsabilites.pug
- src/vues/statistiques.pug
- src/vues/tableauDeBord.pug
- src/vues/utilisateur/edition.pug
... afin de savoir où on se situe dans MSS.
Cette donnée peut aussi être très utile sur Matomo.
> [ACCESSIBILITE] Ajoute un titre sur toutes les pages de MSS

- src/vues/service/creation.pug
...sinon le haut de page est vide.
> [DECRIRE] Ajoute un titre de page sur la création de service

- src/vues/service/dossiers.pug
- src/vues/service/etapeDossier/autorite.pug
- src/vues/service/etapeDossier/avis.pug
- src/vues/service/etapeDossier/dateTelechargement.pug
- src/vues/service/etapeDossier/decision.pug
- src/vues/service/etapeDossier/documents.pug
- src/vues/service/etapeDossier/recapitulatif.pug
- src/vues/service/formulaireEtapier.pug
... afin de mieux les identifier dans nos outils d'analyses, et pour l'accessibilité :point_down:
> Ajoute des titres de pages spécifiques pour les étapes de l'homologation

- svelte/lib/gestionContributeurs/kit/ChampAvecSuggestions.svelte
... afin de mieux indiquer comment fonctionne l'invitation par Nom/prénom
> Modifie le wording du placeholder d'invitation de contributeur

- src/vues/mss.pug
- src/vues/mssConnecte.pug
> Ouvre les liens du BOM dans un nouvel onglet

- public/assets/styles/entete.css
... pour que les espaces (optiques) entre les boutons restent les même
> [CORRECTION] Espacement du bouton de profil

- src/routes/publiques/routesApiPublique.js
> [SOIN] Route /token en `async/await`

- src/adaptateurs/adaptateurGestionErreurSentry.js
- src/mss.js
... avant de l'envoyer vers Sentry.
> [SENTRY] Modifie la requête pour supprimer les informations sensibles

- donneesReferentiel.js
Pour remplacer #1297 avec une PR qui ne contient qu'un seul commit.
> Ajoute des `<p>` pour aérer les descriptions

- public/assets/styles/entete.css
... en ne forçant pas la taille du bouton, mais uniquement du menu.
> Corrige l'affichage du menu

- test/routes/privees/routesApiService.spec.js
Cette PR se concentre sur des tests.
> [SOINS] Passe des tests en `async/await`

- public/modules/tableauDeBord/actions/ActionExport.mjs
- public/modules/tableauDeBord/gestionnaireEvenements.mjs
- src/vues/tiroirs/tiroirExport.pug
... pour améliorer l'accessibilité et permettre un tracking correct coté Matomo
> Convertis le `button` de téléchargement en lien pour l'export des services

- donneesReferentiel.js
Suppression d'un point dans le descriptif d'une mesure
> [WORDING] Suppression d'un point dans le descriptif d'une mesure

- donneesReferentiel.js
Suppression d'une coquille dans la description d'une mesure
> [WORDING] Suppression d'une coquille dans la description d'une mesure

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/tableauDesServices.mjs
... afin de suivre le nouveau design.
> [TDB] Ajoute un lien cliquable pour l'indice cyber

- public/assets/styles/formulaire.css
... afin que le 2 checkbox soit alignées "en haut"
> [CORRECTION] Aligne correctement la `checkbox` d'inscription

- public/assets/styles/tableauDeBord.css
- public/modules/tableauDeBord/tableauDesServices.mjs
- src/vues/tableauDeBord.pug
... afin de correspondre à ceux présent dans le tableau des mesures.
> [UI] Harmonisation des chevrons du tableau de bord

- src/vues/fragments/formulaireDescriptionService.pug
...pour être cohérent avec les pages Sécuriser et Homologuer
> [DECRIRE] Supprime le sous-titre de la page

- test/bus/busEvenements.spec.js
...après avoir identifié le problème dans un environnement de PR
> [SOIN] Ajoute un test pour vérifier que le bus ne crash pas s'il n'a pas de handlers

- public/assets/styles/formulaire.css
- src/vues/fragments/formulaireDescriptionService.pug
...afin d'être plus explicite pour les utilisateurs
> Ajoute un texte explicatif pour le nombre d'organisations

- public/assets/styles/bom.css
- public/assets/styles/bom.responsive.css
- src/vues/mss.pug
On ajoute une vue responsive au BOM pour un affichage correct sur téléphone :
> [BOM] Format responsif

- public/assets/styles/home.css
- public/assets/styles/home.desktop.css
- src/vues/home.pug
... afin de finaliser la `home` :
- ajout des comportements `hover` et `active` sur les liens et boutons
- correction de marges
> [HOME] Dernières retouches

- src/vues/service/dossiers.pug
...suite à une décision produit
> N'affiche plus le tampon d'homologation

- public/modules/tableauDeBord/tableauDesServices.mjs
...avec un autre texte si jamais une recherche textuelle est en cours.
> [TDB] Affiche un texte spécifique s'il n'y a pas de service

- public/assets/styles/dossiers.css
- public/assets/styles/etapesDossier.css
- public/assets/styles/homologation/formulaire.css
- public/service/homologation/dossiers.js
- src/modeles/dossiers.js
- src/routes/privees/routesService.js
- src/vues/service/dossiers.pug
- src/vues/service/formulaireEtapier.pug
- test/constructeurs/constructeurDossier.js
- test/modeles/dossiers.spec.js
On refait visuellement la page d'accueil.
Pour l'instant, aucune feature n'est ajoutée.
La suppression du dossier courant sera dans une PR suivante.
> [HOMOLOGUER] Refonte UI de la page d'accueil

- public/assets/styles/formulaire.css
- public/assets/styles/homologation/formulaire.css
- public/assets/styles/palette.css
- src/vues/fragments/elementsAjoutables/elementsAjoutables.pug
- src/vues/fragments/elementsAjoutables/elementsAjoutablesDescription.pug
- src/vues/fragments/formulaireDescriptionService.pug
- src/vues/fragments/inputChoix.pug
- src/vues/fragments/menuNavigation.pug
- src/vues/nouvellesFonctionnalites/modaleNouvellesFonctionnalites.pug
On actualise la page DÉCRIRE pour corriger les erreurs d'accessibilité.
Les erreurs restantes sont :
- des problèmes de contrastes (notamment avec le "rouge" de l'astérisque "champ obligatoire")
- des problèmes de liens redondant (présent sur toutes les pages du parcours service)
| ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/b0cbb9cc-8ae8-4066-8b81-f6971a7889e4) | ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/50672096-35da-439b-8ecc-91884cc1426d) |
> [ACCESSIBILITÉ] Rubrique DÉCRIRE

- public/assets/styles/dossiers.css
- src/modeles/dossier.js
- src/modeles/dossiers.js
- src/modeles/homologation.js
- src/vues/service/dossiers.pug
- test/depots/depotDonneesHomologations.spec.js
- test/modeles/dossier.spec.js
- test/modeles/dossiers.spec.js
- test/modeles/homologation.spec.js
> [!WARNING]  
> Cette PR dépend de #1374 
On affiche les indices cyber des dossiers en cours ou passés, uniquement lorsqu'ils sont disponibles.
> [HOMOLOGUER] Affiche l'indice cyber des dossier finalisés

- public/modules/tableauDeBord/tableauDesServices.mjs
- src/modeles/utilisateur.js
- src/routes/privees/routesApiPrivee.js
- src/routes/publiques/routesApiPublique.js
- test/modeles/utilisateur.spec.js
- test/routes/privees/routesApiPrivee.spec.js
- test/routes/publiques/routesApiPublique.spec.js
...Personne n'utilisait les données supplémentaires de toJSON(). Les données utilisateur n'étaient pas utilisées dans le retour de récupération du token.
> [SOIN] Supprime des données utilisateur inutiles

- public/assets/styles/dossiers.css
- src/adaptateurs/adaptateurPdf.js
- src/routes/privees/routesApiServicePdf.js
- src/vues/service/dossiers.pug
- test/routes/privees/routesApiServicePdf.spec.js
... pour le dossier d'homologation actif.
On avait masqué cette feature en attendant la commission d'homologation de MSS.
> Affiche le nouveau le tampon d'homologation

- public/assets/styles/piedPage.css
... afin de faire loger toutes les entrées.
| ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/c130f1aa-fdf0-4b5f-8d34-f093c43153bd) | ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/d6aa673d-3e84-4812-9f28-8871b252e09f) |
> [CORRECTION] Diminue la taille de police du footer

- src/vues/historiqueProduit.pug
Ajout des nouveautés sur l'homologation
> Ajout de fonctionnalités dans l'historique du produit

- public/assets/styles/mss.css
- public/assets/styles/tableauDeBord.css
- public/assets/styles/tiroir.css
- public/assets/styles/utilisateur.css
- public/tableauDeBord.js
- public/utilisateur/edition.js
- public/utilisateur/suggestionEntite.js
- src/modeles/utilisateur.js
- src/routes/privees/routesApiPrivee.js
- src/vues/fragments/formulaireUtilisateur.pug
- src/vues/tableauDeBord.pug
- src/vues/utilisateur/edition.pug
- test/modeles/utilisateur.spec.js
- test/routes/privees/routesApiPrivee.spec.js
ainsi qu'une bannière informative sur le formulaire utilisateur
> Affiche un bandeau à l'utilisateur lorsque le SIRET n'est pas renseigné

- public/assets/styles/homologation/indiceCyber.css
- src/vues/service/indiceCyber.pug
Afin de montrer les détails :point_down:
> Ouvre les détails de l'indice cyber par défaut

- svelte/lib/mesure/Mesure.svelte
... et utilise un conteneur `sticky` pour le conteneur des actions.
> Ouvre le tiroir de description des mesures par défaut

- src/vues/mss.pug
- src/vues/mssConnecte.pug
Modification du lien d'inscription à un webinaire de présentation de MonServiceSécurisé
> Liens d'inscriptions au webinaire MSS

- public/assets/styles/mss.css
- public/mssConnecte.js
- src/mss.js
- src/vues/mss.pug
- src/vues/mssConnecte.pug
- svelte/lib/visiteGuidee/VisiteGuidee.svelte
- svelte/lib/visiteGuidee/visiteGuidee.d.ts
- svelte/lib/visiteGuidee/visiteGuidee.ts
- test/mocks/middleware.js
- test/mss.spec.js
... en fonction d'une variable d'environnement.
Affiche un rideau uniquement sur le tableau de bord.
> [VISITE GUIDEE] Affiche la première modale

- src/adaptateurs/adaptateurEnvironnement.js
... après avoir vu un bug en démo
> [VISITE GUIDEE] Corrige l'assignation en cas de variable manquante

- public/scripts/menuNavigation.js
- src/mss.js
- svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
La modale devrait maintenant pouvoir accueillir facilement toutes les sous étapes des autres étapes.
La seule chose à ajouter sera les positionnement différents des modales.
> [VISITE GUIDEE] Ajoute la 2ème sous-étape de DÉCRIRE

- public/service/mesures.js
- src/mss.js
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
- svelte/lib/tableauDesMesures/modeVisiteGuidee/donneesVisiteGuidee.ts
- svelte/lib/tableauDesMesures/tableauDesMesures.d.ts
- svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte
- svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
- svelte/lib/visiteGuidee/visiteGuidee.d.ts
- svelte/lib/visiteGuidee/visiteGuidee.store.ts
On ajoute la première sous-étape, sur la page du tableau des mesures.
Pour cela, il faut pouvoir instancier le composant `TableauDesMesures` en mode "Visite guidée".
On rajoute la possibilité de pouvoir placer la modale à gauche d'un élément dans `ModaleSousEtape`.
> [VISITE GUIDEE] Ajout de la première sous-étape de l'étape SÉCURISER

- svelte/lib/gestionContributeurs/kit/ChampAvecSuggestions.svelte
...après avoir vu un bug en démo.
> [CORRECTION] Empêche l'ajout d'un contributeur en mode visite guidée

- src/mss.js
- svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
... afin de continuer l'implémentation des sous étapes.
Au passage, on corrige le repositionnement de la modale lorsque la fenêtre est `resize`.
> [VISITE GUIDÉE] Ajoute la sous-étape de l'indice cyber

- public/modules/tableauDeBord/actions/ActionTelechargement.mjs
- public/scripts/menuNavigation.js
- src/mss.js
- svelte/lib/visiteGuidee/etapes/homologuer/EtapeHomologuer.svelte
- svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
- svelte/lib/visiteGuidee/visiteGuidee.d.ts
- svelte/lib/visiteGuidee/visiteGuidee.store.ts
On ajoute l'étape HOMOLOGUER, avec ouverture du tiroir de téléchargement.
> [VISITE GUIDÉE] Ajoute l'étape HOMOLOGUER

- public/modules/tableauDeBord/actions/ActionTelechargement.mjs
- test/mss.spec.js
... afin de s'assurer qu'on ne casse pas, à l'avenir, un rendu de la visite guidée en modifiant le `pug` de cette route.
> [VISITE GUIDÉE] Ajoute un test sur la route `/visiteGuidee/:idEtape`

- svelte/lib/visiteGuidee/etapes/homologuer/EtapeHomologuer.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
Afin qu'elles s'affichent correctement sur un écran de portable 13 pouces
> [VISITE GUIDEE] Modifie la hauteur des modales 

- src/modeles/etatVisiteGuidee.js
- src/routes/privees/routesApiPrivee.js
- test/modeles/etatVisiteGuidee.spec.js
- test/routes/privees/routesApiPrivee.spec.js
... afin de pouvoir "ignorer" la visite guidée à n'importe quel moment.
> [VISITE GUIDEE] Ajoute la route de finalisation de la visite guidée

- src/mss.js
- svelte/lib/visiteGuidee/etapes/initiale/EtapeBienvenue.svelte
- svelte/lib/visiteGuidee/etapes/initiale/EtapePresentationMenuNavigation.svelte
- svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
- svelte/lib/visiteGuidee/visiteGuidee.api.ts
- svelte/lib/visiteGuidee/visiteGuidee.store.ts
Pour le changement d'étape et le fait de terminer la visite guidée
> [VISITE GUIDEE] Branche le front de la visite guidée

- public/mssConnecte.js
- src/http/middleware.js
- src/modeles/etatVisiteGuidee.js
- src/routes/privees/routesApiVisiteGuidee.js
- src/vues/mssConnecte.pug
- test/http/middleware.spec.js
- test/modeles/etatVisiteGuidee.spec.js
- test/routes/privees/routesApiVisiteGuidee.spec.js
> [VISITE GUIDEE] Affiche un lien pour réinitialiser la visite guidée

- public/modules/tableauDeBord/tableauDesServices.mjs
- src/http/middleware.js
- src/vues/mssConnecte.pug
- svelte/lib/visiteGuidee/etapes/initiale/EtapeBienvenue.svelte
- svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.d.ts
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
- svelte/lib/visiteGuidee/visiteGuidee.d.ts
- svelte/lib/visiteGuidee/visiteGuidee.store.ts
- svelte/lib/visiteGuidee/visiteGuidee.ts
- test/http/middleware.spec.js
Sur la première étape, personnalise le message de bienvenue avec le prénom de l'utilisateur si son profil est complet.
Sur la dernière modale, si l'utilisateur est un invité on l'invite à participer au service existant, sinon on propose de créer un nouveau service.
> [VISITE GUIDEE] Personnalise les étapes selon le fait que l'utilisateur soit invité ou non

- svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte
- svelte/lib/visiteGuidee/etapes/homologuer/EtapeHomologuer.svelte
- svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte
- svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.d.ts
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
…afin de pouvoir faire "respirer" certaines éléments, surtout ceux contenant des bords arrondis.
> [VISITE GUIDÉE] Ajoute la possibilité de modifier la marge autour de l'élément mis en avant

- donneesReferentiel.js
- src/referentiel.js
- src/routes/connecte/routesConnectePage.js
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
- svelte/lib/visiteGuidee/visiteGuidee.d.ts
- svelte/lib/visiteGuidee/visiteGuidee.store.ts
- svelte/lib/visiteGuidee/visiteGuidee.ts
- test/referentiel.spec.js
> [VISITE GUIDÉE] Ajoute le bouton "Précédent"

- svelte/lib/visiteGuidee/etapes/initiale/EtapePresentationMenuNavigation.svelte
- svelte/lib/visiteGuidee/kit/IndicateurEtape.svelte
... et l'étape active en bleu, pour les différencier
> [VISITE GUIDÉE] Affiche l'étape disponible en "noir"

- src/vues/service/etapeDossier/documents.pug
Changement du placeholder du champ de texte du titre de "2022" à "2023" pour correspondre à une temporalité normale
> Modification du champ de texte pour le titre du document

- public/assets/styles/tiroir.css
- src/vues/tableauDeBord.pug
- src/vues/tiroirs/tiroirSuppressionService.pug
On corrige ici :
- l'affichage des checkbox
- l'affichage de l'icone "voir" sur le champ "mot de passe" de la suppression de service
> [CORRECTION] Correctif UI du tableau de bord

- consoleAdministration.js
On ajoute une méthode à la console administration pour rattacher les utilisateurs existants à leur entreprise.
> [BREVO/ENTREPRISE] Rattrapage des utilisateurs existants

- creeUtilisateurDemo.js
... afin de corriger la dépendances manquantes.
> [CORRECTION] Passe l'adaptateur de recherche entreprise au dépôt de données

- src/vues/tableauDeBord.pug
> [WORDING] Remplace le wording du bouton par "Ajouter"

- src/adaptateurs/adaptateurMailMemoire.js
- src/adaptateurs/adaptateurMailSendinblue.js
- src/bus/abonnements/envoieNombreDeServicesDeLUtilisateurABrevo.js
- src/bus/cablage.js
- test/bus/abonnements/envoieNombreDeServicesDeLUtilisateurABrevo.spec.js
...pour le propriétaire.
On distingue le nombre de services dont l'utilisateur est propriétaire de celui dont il est contributeur.
> [Brevo] Envoie le nombre de services d'un utilisateur à la création d'un nouveau service

- src/modeles/journalMSS/evenementProfilUtilisateurModifie.js
- test/modeles/journalMSS/evenementProfilUtilisateurModifie.spec.js
... en enrichissant simplement l'événement `PROFIL_UTILISATEUR_MODIFIE` avec les données nécéssaires.
> Ajoute les informations d'estimation du nombre de services dans Metabase

- src/bus/abonnements/metAJourEstimationNombreServicesContactBrevo.js
- src/bus/cablage.js
- src/crm/crmBrevo.js
- test/bus/abonnements/metAJourEstimationNombreServicesContactBrevo.spec.js
- test/constructeurs/constructeurUtilisateur.js
- test/crm/crmBrevo.spec.js
...afin de rendre la données disponible pour le pôle BizDev.
> [BREVO] Ajout de l'estimation du nombre de services des utilisateurs

- consoleAdministration.js
... afin de mettre à jour les contacts dans Brevo.
> Ajoute une méthode dans la console d'administration pour rattraper les données d'estimation du nombre de services sur Brevo

- consoleAdministration.js
... pour filtrer uniquement sur les utilisateurs qui ont remplis le champ.
> [CORRECTION] Utilise des chaines de caractères plutôt que des nombres

- src/vues/home.pug
> [HOME] Ajoute Fabien dans la description du pôle

- donneesReferentiel.js
> Corrige une coquille sur "public"

- consoleAdministration.js
... des utilisateurs existants
> [Brevo] Rattrapage des numéros de téléphone

- consoleAdministration.js
Un utilisateur nous a demandé de récupérer la propriété d'un service dont le propriétaire actuel a quitté ses fonctions.
Il ne peut donc pas transférer la propriété via MSS.
Cette PR ajoute à `consoleAdministration` une fonction qui prend un paramètre un `idAutorisation` et transforme l'autorisation ciblée en autorisation de Propriétaire.
Le code est directement inspiré du code de la route `PATCH /service/:id/autorisations/:idAutorisation` qui est déclenché par l'IHM.
Au passage, on doit soigner l'injection de dépendances, en fournissant un `bus` au dépôt de données.
> [ADMIN] Permets de transformer une autorisation en « Propriétaire »

- consoleAdministration.js
- src/adaptateurs/adaptateurMailMemoire.js
- src/adaptateurs/adaptateurMailSendinblue.js
... lors de la suppression d'un utilisateur, afin de ne pas avoir à le faire à la main.
> [CONSOLE ADMINISTRATION] Suppression du contact dans brevo

- src/vues/connexion.pug
- src/vues/mssConnexionEnCours.pug
- src/vues/mssDeconnecte.pug
- src/vues/mssInscription.pug
- src/vues/reinitialisationMotDePasse.pug
> Suppression du lien "Contactez-nous"

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesNotifications.js
- src/notifications/centreNotifications.js
- src/routes/connecte/routesConnecteApiNotifications.js
- test/notifications/centreNotifications.spec.js
- test/routes/connecte/routesConnecteApiNotifications.spec.js
On en profite aussi pour ajouter, au moment de la lecture des notifications pour un utilisateur, celle qui sont "lue" ou non.
> [CENTRE DE NOTIFICATIONS] Ajout de la route pour marquer les nouveautés à "lue"

- public/assets/styles/tableauDeBord.css
- public/tableauDeBord.js
- src/routes/connecte/routesConnecteApi.js
- src/vues/tableauDeBord.pug
- test/routes/connecte/routesConnecteApi.spec.js
... car il a été remplacé par des "tâches" dans le centre de notifications.
> [NOTIFICATIONS] Supprime le bandeau de mise à jour de profil

- svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte
Le message lors de la visite guidée explique ce qu’est le centre de notification
> [VISITE GUIDEE] met à jour le message pour le centre de notifications

- public/assets/styles/bom.css
... afin de les rendre distinguables sur fond bleu
> [BOM] Modifie le liseré du bouton et de l'encart

- src/vues/service/modaleEncartHomologation.pug
... suite à une demande métier
> Modifie le titre de la modale d'encart homologation

- public/assets/styles/bom.css
...pour éviter un artefact visuel dans les coins supérieurs.
> [BOM] Égalise les arrondis de la modale et du bandeau de titre

- svelte/lib/visiteGuidee/etapes/homologuer/EtapeHomologuer.svelte
... car l'emplacement du bouton a changé
| ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/77861214-8cf2-4e51-8313-c8118ca3f95b) | ![image](https://github.com/betagouv/mon-service-securise/assets/1643465/a5f03dcf-1b55-4d52-a16e-1ad6855297cd) |
> [CORRECTION] Corrige l'affiche de la modale sur le bouton de nouvelle homologation

- public/assets/styles/homologation/descriptionService.css
- public/modules/soumetsHomologation.mjs
- src/vues/service/creation.pug
... pour suivre le nouveau design.
> Ajoute une modale avec une animation lors de la création d'un service

- public/assets/styles/bom.responsive.css
... en supprimant le `padding-left`
> [BOM] Aligne le titre du BOM à gauche en version mobile

- src/routes/connecte/routesConnectePageService.js
- test/routes/connecte/routesConnectePageService.spec.js
... pour éviter les problèmes d'envoi
> [CORRECTION] Supprime tous les caractères spéciaux dans le nom de fichier

- src/modeles/journalMSS/evenementCompletudeServiceModifiee.js
- test/constructeurs/constructeurDescriptionService.js
- test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js
...afin d'exploiter l'information dans Metabase
> Ajoute les niveaux de sécurité minimal et choisi à l'évènement de journal complétude service

- donneesReferentiel.js
... pour l’évaluation des mesures des profils MSS+ et MSS++
> Utilise le niveau de sécurité dans les règles de personnalisation

- package-lock.json
- package.json
... pour éviter les vulnérabilités
> Met à jour le package `express-ipfilter`

- package-lock.json
... pour éviter https://github.com/betagouv/mon-service-securise/security/dependabot/32
> Met à jour la version de `express`

- package-lock.json
... pour corriger la vulnérabilité sur `tar`
> Met à jour la version de `bcrypt`

- src/adaptateurs/adaptateurMailSendinblue.js
...afin d'avoir plus d'informations dans un premier temps sur les réponses de type 400, pour ensuite déterminer si l'erreur doit être traitée par MSS
> Logue la réponse de Brevo en cas d'erreur

- consoleAdministration.js
... plutôt que d'ajouter l'évènement directement au journal. Ceci afin d'exécuter également la logique d'ajout des détails de l'entité du service, logique qui n'était pas reportée dans la console admin.
Les évènements qui avaient été créés via cette méthode de consoleAdmin étaient donc sans détails d'organisation, les graphes Metabase étaient donc incomplets.
> Modifie la console d'administration pour utiliser consigneCompletudeDansJournal

- consoleAdministration.js
...afin de limiter les appels à l'API recherche entreprise, qui est limitée à 7 appels par seconde
> Temporise la génération d'évènements complétude dans la console d'administration

- public/service/descriptionService.js
Modification de l'ordre de Fonctionnalités et Données pour une meilleure cohérence avec le reste de la page
> Amélioration du titre dans la partie décrire

- svelte/lib/mesure/mesure.api.ts
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
- svelte/lib/tableauDesMesures/tableauDesMesures.api.ts
dans le tableau des mesures.
Les mesures générales sont mises à jour unitairement. Les mesures spécifiques sont mises à jour toutes ensemble
> Mets à jour les mesures de façon unitaire

- src/vues/service/indiceCyber.pug
> Mentionne les mesures partielles dans les explications de l'indice cyber

- .env.template
- src/adaptateurs/adaptateurCmsCrisp.js
... qui permet de récupérer, via l'API Crisp, le contenu d'un article spécifique en fonction d'un `id`.
> [CMS CRISP] Ajoute l'adaptateur CMS Crisp

- public/assets/fichiers/sitemap.xml
- public/assets/styles/article.css
- server.js
- src/cms/cmsCrisp.js
- src/cms/crispMarkdown.js
- src/cms/fabriqueCrispMarkdown.js
- src/mss.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/article.pug
- test/cms/cmsCrisp.spec.js
- test/cms/crispMarkdown.spec.js
- test/routes/nonConnecte/routesNonConnectePage.spec.js
- test/routes/testeurMSS.js
On souhait afficher, de manière caché (via URL uniquement), les premières pages utilisant le CMS Crisp.
> [CMS CRISP] Ajout des premières pages utilisant le CMS Crisp

- public/assets/styles/article.css
- public/scripts/article.js
- src/adaptateurs/adaptateurCmsCrisp.js
- src/cms/cmsCrisp.js
- src/cms/crispMarkdown.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/article.pug
- test/cms/cmsCrisp.spec.js
- test/cms/crispMarkdown.spec.js
On souhaite dans cette PR :
- Afficher un icône spécifique à coter des liens portant la mention "Télécharger"
- Corriger quelques affichages via le CSS
- Afficher une table des matières
> [CMS CRISP] Intégrations complementaires

- public/assets/images/icone_recherche.svg
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
... afin de coller avec les nouvelles maquettes :point_down:
> [PLAN D'ACTION] Ajoute une icône dans la barre de recherche

- svelte/lib/ui/SelectionStatut.svelte
... afin de suivre le nouveau design :point_down:
> [PLAN D'ACTION] Applique le nouveau style de la sélection de statut de mesure

- public/assets/images/icone_export_gris.svg
- public/assets/images/icone_plus_gris.svg
- public/assets/styles/homologation/mesures.css
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
- svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
- svelte/lib/ui/CartoucheReferentiel.svelte
- svelte/lib/ui/SelectionStatut.svelte
... afin de suivre le nouveau design de la page :point_down:
> [PLAN D'ACTION] Affichage des mesures au format "tableau"

- donneesReferentiel.js
... afin de pouvoir les afficher sur le tableau des mesures
> [PLAN D'ACTION] Ajoute un identifiant numérique à toute les mesures du référentiel

- public/assets/styles/homologation/mesures.css
... afin de laisser "respirer" le titre
> [PLAN D'ACTION] Corrige l'espacement du titre du tiroir

- src/vues/confidentialite.pug
Changement du mail lab incorrect
> Mise à jour de la politique de confidentialité

- src/adaptateurs/adaptateurGestionErreurSentry.js
... afin d'essayer d'en comprendre la cause.
> [INVESTIGATION] Ajoute un 'log' dédié dans Sentry pour les erreurs CSRF

- public/scripts/menuNavigation.js
- public/service/descriptionService.js
- svelte/lib/niveauxDeSecurite/NiveauxDeSecurite.svelte
- svelte/lib/niveauxDeSecurite/niveauxDeSecurite.d.ts
- svelte/lib/visiteGuidee/etapes/decrire/EtapeDecrire.svelte
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.d.ts
- svelte/lib/visiteGuidee/kit/ModaleSousEtape.svelte
Ajoute l'étape de sélection du niveau de sécurité dans la visite guidée, en seconde sous étape de l'étape Décrire.
> [VISITE GUIDEE] Etape 3 de DECRIRE

- .github/workflows/deploiement.yml
Cette PR permet de déployer vers la DÉMO depuis un workflow Github.
Le déploiement se déclenche manuellement.
> [Déploiement continu] Démarrage du déploiement via la CI/CD

- svelte/lib/mesure/Mesure.svelte
... en attendant de pouvoir mettre les liens direct vers MSS
> [TEMPORAIRE] Masque les liens vers les articles de blog

- donneesReferentiel.js
- svelte/lib/mesure/Mesure.svelte
...et les réaffiche dans le tiroir des mesures.
Attention: a besoin de https://github.com/betagouv/mon-service-securise/pull/1637
> [SÉCURISER] Remplace les liens vers le blog par des liens internes

- .env.template
- public/assets/styles/article.css
- src/adaptateurs/adaptateurCmsCrisp.js
- src/cms/cmsCrisp.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/article.pug
- test/cms/cmsCrisp.spec.js
- test/routes/nonConnecte/routesNonConnectePage.spec.js
- test/routes/testeurMSS.js
... afin de pouvoir l'ajouter dans la navigation de la Home.
> [HOME] Ajout de la page "Promouvoir MSS"

- public/assets/styles/article.css
- src/cms/crispMarkdown.js
- test/cms/crispMarkdown.spec.js
Petites corrections esthétiques
> [CRISP] Modifications de contenu et affichage des articles

- .env.template
- src/adaptateurs/adaptateurCmsCrisp.js
- src/cms/cmsCrisp.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/fragments/navigationSiteVitrine.pug
- test/cms/cmsCrisp.spec.js
- test/routes/nonConnecte/routesNonConnectePage.spec.js
- test/routes/testeurMSS.js
... afin d'étoffer le contenu "Site vitrine"
> [HOME] Ajoute de la page "Roadmap" du site vitrine

- creeUtilisateurDemo.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- test/creeUtilisateurDemo.spec.js
... à l'utilisateur de démo, afin de pouvoir vérifier la non régression de ces fonctionnalités
> [UTILISATEUR DÉMO] Ajoute une suggestion d'action et une tâche de service

- src/vues/home.pug
Mise à jour du nombre d'utilisateurs
> Changement du nombre d'utilisateurs

- donneesReferentiel.js
> [CORRECTION] Corrige le lien vers l’article SecNumCloud

- svelte/lib/mesure/ContenuOngletMesure.svelte
- svelte/lib/mesure/Mesure.svelte
- svelte/lib/mesure/contenus/ContenuOngletMesure.svelte
- svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte
- svelte/lib/mesure/mesure.api.ts
- svelte/lib/mesure/mesure.d.ts
- svelte/lib/ui/Formulaire.svelte
- svelte/lib/ui/Onglet.svelte
- svelte/lib/ui/SelectionPriorite.svelte
Cet onglet contient pour le moment uniquement la priorité :
> [PLAN D’ACTION] Ajoute l’onglet du plan d’action dans le tiroir des mesures

- .github/workflows/deploiement.yml
C'est une duplication du déploiement en DÉMO.
On verra ensuite pour factoriser.
> [CI/CD] Ajoute le job de déploiement en PROD

- TODO.md
- svelte/lib/centreNotifications/CentreNotifications.svelte
- svelte/lib/mesure/Mesure.svelte
- svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
- svelte/lib/ui/Onglet.svelte
- svelte/lib/ui/SelectionPriorite.svelte
- svelte/lib/ui/SelectionStatut.svelte
...on ne peut modifier le plan d'action que si le statut de la mesure est `en action` (`à lancer` ou `partielle`)
> Désactive le plan d'action selon le statut de la mesure

- .github/workflows/deploiement.yml
... en utilisant la CLI CleverCloud.
> [CI/CD] Autorise le redéploiement d'un même commit

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesHomologations.js
- test/depots/depotDonneesHomologations.spec.js
- test/depots/depotDonneesServices.spec.js
...en déplaçant son contenu dans la méthode `service`.
> [SOIN] Supprime la méthode `homologation` de la persistance

- creeUtilisateurDemo.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesHomologations.js
- test/creeUtilisateurDemo.spec.js
dans les adaptateurs de persistance
> [SOIN] Renomme homologations et homologationAvecNomService

- public/modules/soumetsHomologation.mjs
- public/service/risques.js
- public/service/rolesResponsabilites.js
- src/routes/connecte/routesConnecteApi.js
- src/routes/connecte/routesConnectePage.js
- src/routes/connecte/routesConnectePageService.js
- src/vues/fragments/formulaireDescriptionService.pug
- src/vues/fragments/menuNavigation.pug
- src/vues/service/risques.pug
- src/vues/service/rolesResponsabilites.pug
- svelte/lib/gestionContributeurs/suppression/SuppressionContributeur.svelte
- test/modeles/autorisations/ajoutContributeurSurServices.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
> [SOIN] Renomme homologation dans les vues

- clevercloud/cron.json
Dans ce premier commit, on `echo` une phrase pour valider le fonctionnement.
> Ajoute un crontab dédié à Clever

- clevercloud/cron.json
Le test avec `echo` est OK. On passe au code réel. Si c'est bon, il ne restera qu'à changer les horaires d'exécution.
> Déclenche la vraie tâche à mettre en CRON

- public/assets/styles/article.css
- src/cms/cmsCrisp.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/article.pug
- svelte/lib/blog/Blog.svelte
- test/cms/cmsCrisp.spec.js
... afin de pouvoir retourner à la "home" des articles de blog.
> [BLOG] Ajout du fil d'Ariane

- public/assets/fichiers/sitemap.xml
- src/routes/nonConnecte/routesNonConnectePage.js
... afin de le maintenir à jour.
> [CORRECTION] Corrige le `sitemap`

- clevercloud/cron.json
- scripts/taches/tacheEnvoieMailsNotificationExpiration.sh
C'est la façon de faire chez Clever Cloud.
https://developers.clever-cloud.com/doc/administrate/cron/#access-environment-variables
> Utilise un script shell pour avoir accès aux variables d'environnement

- clevercloud/cron.json
- scripts/taches/tacheEnvoieMailsNotificationExpiration.sh
Cette PR met en place la planification réelle du CRON, et assure que seule l'instance principale de MSS exécute des CRON.
> Finalisation de la mise en place des CRON chez Clever Cloud

- src/erreurs.js
- src/modeles/mesure.js
- src/modeles/mesureGenerale.js
- src/modeles/mesureSpecifique.js
- src/routes/connecte/routesConnecteApiService.js
- test/modeles/mesure.spec.js
- test/modeles/mesureGenerale.spec.js
- test/modeles/mesureSpecifique.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
et valide que l'échéance est bien une date
> [PLAN D'ACTION] Ajoute l'échéance à la mesure

- svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte
- svelte/lib/mesure/mesure.api.ts
- svelte/lib/mesure/mesure.d.ts
- svelte/lib/tableauDesMesures/ligne/SelectionEcheance.svelte
- svelte/lib/tableauDesMesures/tableauDesMesures.api.ts
... afin de pouvoir ajouter une échéance depuis le tiroir.
On en profite pour formatter toutes les dates envoyées au back au format "MM/DD/YYYY" car 
> Note that the Date() constructor requires you to pass a date in the format of YYYY/MM/DD or MM/DD/YYYY. If you pass a date in DD/MM/YYYY format, the contructor also returns an Invalid Date.
> [PLAN D'ACTION] Ajout du champ "Échéance" dans le tiroir d'édition/création de mesure

- public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
... en attendant que l'appel API soit fini.
> [CORRECTION] Désactive le bouton "inscription"

- src/vues/service/etapeDossier/autorite.pug
... car l'ancien lien n'existe plus dans la FAQ.
> Met à jour le lien de blog sur l'homologation

- .github/workflows/deploiement.yml
Cette PR rajoute l'invalidation du cache Baleen au workflow de CI/CD.
> [CI/CD] Ajoute une étape d'invalidation du cache Baleen

- donneesReferentiel.js
Ajout des liens d'articles (de notre blog) dans certaines mesures.
> Ajout de lien vers des articles dans certaines mesures

- src/depots/depotDonneesServices.js
- src/erreurs.js
- src/modeles/mesureGenerale.js
- src/modeles/mesureSpecifique.js
- src/modeles/mesures.js
- src/modeles/service.js
- src/routes/connecte/routesConnecteApiService.js
- test/modeles/mesureGenerale.spec.js
- test/modeles/mesureSpecifique.spec.js
- test/modeles/mesures.spec.js
- test/modeles/service.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
Les responsables doivent être des contributeurs du service, sinon l'API retourne 403 Forbidden.
> [PLAN D'ACTION] Ajoute les responsables aux mesures spécifiques et générales

- public/assets/styles/palette.css
- svelte/lib/gestionContributeurs/kit/Initiales.svelte
- svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte
- svelte/lib/gestionContributeurs/personnalisation/TagLectureEcriture.svelte
... afin d'harmoniser avec les nouvelles couleurs qui seront présentes dans le tableau des mesures.
> [UI] Modification des couleurs des niveaux de droits

- svelte/lib/gestionContributeurs/gestionContributeurs.d.ts
- svelte/lib/gestionContributeurs/invitation/ListeInvitations.svelte
- svelte/lib/gestionContributeurs/kit/ChampAvecSuggestions.svelte
- svelte/lib/gestionContributeurs/kit/LigneContributeur.svelte
- svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte
- svelte/lib/ui/Initiales.svelte
- svelte/lib/ui/SelectionResponsables.svelte
- svelte/lib/ui/types.d.ts
Pour pouvoir le réutiliser dans le tiroir des mesures, sur l'onglet du plan d'action.
Cette PR l'utilise à 2 endroits 👇
> [Svelte] Mutualisation du composant `<Initiales />`

- src/depots/depotDonneesUtilisateurs.js
On prépare l'arrivée du chiffrement donc on veut mettre sous contrôle tous les appels à l'`adaptateurPersistance`
> [SOIN] Le dépôt données Utilisateur a le moins d’accroche possible avec la persistance

- donneesReferentiel.js
...qui n’est plus disponible (404) et qui est désormais disponible sur FeatureBase
> [CORRECTION] Remplace le lien de la première nouveauté

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depots/depotDonneesServices.js
- src/depots/depotDonneesUtilisateurs.js
- test/constructeurs/constructeurDepotDonneesServices.js
- test/creeUtilisateurDemo.spec.js
- test/depots/depotDonneesAutorisations.spec.js
- test/depots/depotDonneesNotifications.spec.js
- test/depots/depotDonneesServices.spec.js
Afin de pouvoir déchiffrer le contenu des utilisateurs.
> [PRÉPARATION CHIFFREMENT] Déporte la lecture des contributeurs et suggestions dans le dépôt de données

- svelte/lib/tableauDesMesures/BandeauActions.svelte
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
- svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
- svelte/lib/tableauDesMesures/ligne/SelectionEcheance.svelte
- svelte/lib/ui/SelectionPriorite.svelte
- svelte/lib/ui/SelectionResponsables.svelte
La liste exhaustive des retours est disponible sur Outline.
> [PLAN D'ACTION] Derniers retours UI/UX

- src/adaptateurs/adaptateurChiffrementVault.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/annuaire/serviceAnnuaire.js
- src/depots/depotDonneesServices.js
- src/depots/depotDonneesUtilisateurs.js
- test/annuaire/serviceAnnuaire.spec.js
- test/bus/abonnements/envoieMailFelicitationHomologation.spec.js
- test/constructeurs/constructeurAdaptateurPersistanceMemoire.js
- test/constructeurs/constructeurDepotDonneesServices.js
- test/constructeurs/constructeurUtilisateur.js
- test/depots/depotDonneesAutorisations.spec.js
- test/depots/depotDonneesNotifications.spec.js
- test/depots/depotDonneesServices.spec.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/taches/envoieMailsNotificationExpirationHomologation.spec.js
Chiffre les données de l'utilisateur.
Pour la mise à jour des données, on applique le delta après déchiffrement des données persistées et on chiffre de nouveau avant de mettre à jour en base.
> Chiffre le contenu de l'utilisateur

- src/depotDonnees.js
... de notification d'expiration d'homologation.
Pour cela on ajoute la valeur par défaut pour qu'une création de dépôt soit toujours fonctionnelle.
> [CORRECTION] Ajoute l'adaptateur chiffrement dans le dépôt créé par la tâche d'envoi de mails

- svelte/lib/tableauDesMesures/aucunResultat/AucunResultat.svelte
- svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
- svelte/lib/tableauDesMesures/stores/contributeurs.store.ts
- svelte/lib/tableauDesMesures/stores/nombreDeResultats.store.ts
- svelte/lib/tableauDesMesures/stores/rechercheMesMesures.store.ts
- svelte/lib/tableauDesMesures/stores/resultatsDeRecherche.store.ts
- svelte/test/tableauDesMesures/stores/nombreDeResultats.store.spec.ts
- svelte/test/tableauDesMesures/stores/resultatsDeRecheche.store.spec.ts
...dans le store des résultats de recherche, afin de ne filtrer que les mesures dont l’utilisateur courant est responsable
> Ajoute un filtre pour mes mesures

- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
- svelte/lib/tableauDesMesures/aucunResultat/AucunResultat.svelte
- svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
...entre les composants `AucunResultat` et `MenuFiltres`
> [SOIN] Mutualise la gestion de la suppression des filtres

- consoleAdministration.js
Lorsque l'on basculera sur les données chiffrées, il ne sera plus possible de faire des `SELECT` en base.
On s'outille donc avec les requêtes les plus courantes (lire un utilisateur, ses services et autorisations) pour se préparer aux demandes futures.
> [CONSOLE ADMIN] Ajoute des utilitaires pour lire/déchiffrer des utilisateurs/services

- svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte
- svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
- svelte/lib/ui/SelectionEcheance.svelte
- svelte/lib/ui/SelectionPriorite.svelte
- Ajout d’un liseré sur la sélection de priorité vide
- Déplacement du composant `SélectionEchéance` dans le dossier UI
> Ajustements UI

- svelte/lib/ui/SelectionResponsables.svelte
> Correction d'un mot

- src/routes/connecte/routesConnecteApi.js
- src/routes/connecte/routesConnecteApiService.js
- svelte/lib/gestionContributeurs/gestionContributeurs.d.ts
- svelte/lib/gestionContributeurs/invitation/InvitationContributeur.svelte
- svelte/lib/gestionContributeurs/personnalisation/PersonnalisationDroits.svelte
- test/routes/connecte/routesConnecteApi.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
... sinon l'objet de droit est incomplet, et les droits personnalisés affichent des `undefined`
> [CORRECTION] Ajoute les droits en écriture sur toutes les rubriques pour un propriétaire

- migrations/20240828065734_ajouteColonneIdMesureSurActivites.js
- src/adaptateurs/adaptateurPostgres.js
- src/bus/abonnements/consigneActiviteMesure.js
- src/depots/depotDonneesActivitesMesure.js
- src/modeles/activiteMesure.js
- test/bus/abonnements/consigneActiviteMesure.spec.js
- test/depots/depotDonneesActivitesMesure.spec.js
Cette id permet de savoir sur quelle mesure porte l’activité
> [HISTORIQUE] Ajoute id de la mesure sur les activités de mesure

- src/pdf/modeles/indiceCyberPersonnalise/scoreIndiceCyberPersonnalise.pug
- src/pdf/modeles/ressources/styles.css
- src/pdf/modeles/syntheseSecurite.pug
- svelte/lib/indiceCyberPersonnalise/IndiceCyberPersonnalise.svelte
... afin de le rendre visible aux utilisateurs.
> [INDICE CYBER PERSONNALISÉ] Ajout dans le PDF de synthèse de sécurité

- src/vues/service/indiceCyber.pug
Mise au pluriel de terme "même"
> correction de l'orthographe d'un terme

- svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte
Modification d'un terme et correction d'orthographe
> Ajout d'un accent sur un mot

- public/assets/styles/tiroir.css
... car certain contenu ne s'affiche plus correctement suite à l'agrandissement du tiroir.
> [CORRECTION] Affiche correctement le contenu des tiroirs

- src/depotDonnees.js
- src/depots/depotDonneesServices.js
- src/modeles/mesuresSpecifiques.js
- src/modeles/service.js
- src/routes/connecte/routesConnecteApiService.js
- svelte/lib/mesure/mesure.api.ts
- test/depots/depotDonneesServices.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
On ajoute une route pour ajouter une mesure spécifique
> [HISTORIQUE] Ajoute une mesure specifique unitairement via l’API

- src/tracking/serviceTracking.js
- test/tracking/serviceTracking.spec.js
Renommages et déduplication de l'appel aux services de l'utilisateur
> [SOIN] Soins sur le service de tracking

- public/assets/styles/utilisateur.css
- public/inscription.js
- public/modules/suggestion/suggestionEntite.js
- server.js
- src/adaptateurs/adaptateurJWT.js
- src/adaptateurs/adaptateurOidc.js
- src/depots/depotDonneesUtilisateurs.js
- src/modeles/inscriptionUtilisateur.js
- src/modeles/sourceAuthentification.js
- src/modeles/utilisateur.js
- src/mss.js
- src/routes/connecte/routesConnecteApi.js
- src/routes/nonConnecte/routesNonConnecteApi.js
- src/routes/nonConnecte/routesNonConnecteOidc.js
- src/routes/nonConnecte/routesNonConnectePage.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/mocks/adaptateurChiffrement.js
- test/modeles/utilisateur.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
- test/routes/nonConnecte/routesNonConnecteApi.spec.js
- test/routes/nonConnecte/routesNonConnecteOidc.spec.js
- test/routes/nonConnecte/routesNonConnectePage.spec.js
- test/routes/testeurMSS.js
Lors de la connexion OIDC Agent Connect, si le compte n'existe pas dans MSS, on le crée via la page d'inscription, avec les champs nom/prénom/email/siret pré remplis
> [AGENT CONNECT] Inscription via Agent Connect

- public/acceptationCGU.js
- src/http/middleware.js
- src/routes/connecte/routesConnecteApi.js
- src/routes/connecte/routesConnectePage.js
- src/vues/acceptationCGU.pug
- test/aides/cookie.js
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/routes/connecte/routesConnecteApi.spec.js
- test/routes/nonConnecte/routesNonConnecteApi.spec.js
- test/routes/nonConnecte/routesNonConnecteOidc.spec.js
Lorsqu'on est invité dans MSS, et qu'on souhaite se connecter avec Agent Connect, on doit accepter les CGU.
Cette PR ajoute la page pour ce faire.
> [AGENT CONNECT] Ajoute une page pour les invités Agent connectés

- src/modeles/utilisateur.js
- src/routes/nonConnecte/routesNonConnecteOidc.js
- test/modeles/utilisateur.spec.js
- test/routes/nonConnecte/routesNonConnecteOidc.spec.js
... afin de pré-remplir les informations qui sont disponibles dans AgentConnect au moment de la première connexion.
> [AGENT CONNECT] Reconciliation des informations utilisateur pour un invité

- public/assets/images/icone_envoyer.svg
- svelte/lib/mesure/Mesure.svelte
- svelte/lib/mesure/commentaire/CommentaireMesure.svelte
- svelte/lib/mesure/contenus/ContenuOngletActivite.svelte
- svelte/lib/mesure/contenus/activites/ActiviteAjoutCommentaire.svelte
- svelte/lib/mesure/contenus/activites/visualisation.ts
- svelte/lib/mesure/mesure.api.ts
- svelte/lib/mesure/mesure.d.ts
... sans "mention" pour l'instant.
> [COMMENTAIRE] Ajout de commentaire dans les activités de mesure

- .github/workflows/deploiement-dev.yml
... afin de pouvoir envoyer une branche vers l'environnement de PR.
> Ajoute une action de déploiement vers un environnement de "DEV" dédié

- .env.template
- src/adaptateurs/adaptateurCsv.js
- src/adaptateurs/adaptateurEnvironnement.js
- svelte/lib/featureFlags.ts
- svelte/lib/mesure/Mesure.svelte
- svelte/lib/tableauDesMesures/TableauDesMesures.svelte
- svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
Ce flag est désormais inutile car le plan d’action est activé partout
> Supprime le feature flag `plan action`

- src/routes/nonConnecte/routesNonConnecteOidc.js
Afin de comprendre une erreur en production
> Loggue les informations de l’exception levée après l’authentification

- svelte/lib/mesure/contenus/activites/Activite.svelte
- svelte/lib/mesure/contenus/activites/ActiviteAjoutEcheance.svelte
- svelte/lib/mesure/contenus/activites/ActiviteAjoutPriorite.svelte
- svelte/lib/mesure/contenus/activites/ActiviteAjoutResponsable.svelte
- svelte/lib/mesure/contenus/activites/ActiviteAjoutStatut.svelte
- svelte/lib/mesure/contenus/activites/ActiviteMiseAJourEcheance.svelte
- svelte/lib/mesure/contenus/activites/ActiviteMiseAJourPriorite.svelte
- svelte/lib/mesure/contenus/activites/ActiviteMiseAJourStatut.svelte
- svelte/lib/mesure/contenus/activites/ActiviteSuppressionEcheance.svelte
- svelte/lib/mesure/contenus/activites/ActiviteSuppressionResponsable.svelte
- svelte/lib/mesure/contenus/activites/visualisation.ts
… concernant les propriétés passées aux composants d’activité
> [SOIN] Supprime les avertissement dans eslint et dans le navigateur

- src/adaptateurs/adaptateurEnvironnement.js
- src/http/middleware.js
- src/mss.js
- test/http/middleware.spec.js
- test/mocks/middleware.js
...et ce afin de n'avoir qu'un domaine à gérer dans l'authentification AgentConnect
> Redirige vers l'url de base de MSS si la requête arrive par un sous domaine

- server.js
- src/mss.js
- src/routes/nonConnecte/routesNonConnecteOidc.js
- test/routes/nonConnecte/routesNonConnecteOidc.spec.js
- test/routes/testeurMSS.js
...en considérant l'url de redirection comme une url relative
> [CORRECTION] Redirige correctement après connexion OIDC

- src/routes/nonConnecte/routesNonConnecteOidc.js
- test/routes/nonConnecte/routesNonConnecteOidc.spec.js
... à cause d'un bug vu en prod.
> [CORRECTION] N'ajoute pas d'URL de redirection si aucune n'est spécifiée

- public/assets/styles/inscription-v2.css
- public/inscription-v2.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/inscription-v2.pug
- svelte/lib/inscription/Inscription.svelte
- svelte/lib/inscription/SelectionFonction.svelte
- svelte/lib/inscription/inscription.d.ts
- svelte/lib/inscription/inscription.ts
- svelte/lib/ui/Bouton.svelte
- svelte/lib/ui/Etapier.svelte
- svelte/lib/ui/MenuFlottant.svelte
- test/routes/nonConnecte/routesNonConnectePage.spec.js
Formulaire en trois étapes pour créer un nouvel utilisateur. Pour l’instant, ce formulaire est inactif et ne soumet rien à l’API. 
Première étape :
Deuxième étape :
Troisième étape :
> [CONNEXION / INSCRIPTION] Ajout de la première version du parcours d'inscription V2

- svelte/lib/inscription/SelectionFonction.svelte
- svelte/lib/ui/ChampTexte.svelte
... afin de pouvoir le réutiliser dans les différents formulaires d'inscription et de connexion, et plus généralement dans nos futurs composant Svelte.
> [SOIN] Extrais un composant svelte champ de saisie texte

- src/routes/connecte/routesConnecteApiService.js
- test/routes/connecte/routesConnecteApiService.spec.js
afin de pouvoir l'utiliser dans la nouvelle page de risques
> Ajoute une route pour mettre à jour un risque général de manière unitaire

- donneesReferentiel.js
Mets à jour les descriptions courtes et ajoute un identifiant numérique et des catégories aux risques du référentiel
> Mets à jour le référentiel des risques

- migrations/20240926145355_ajouteIdentifiantRisquesSpecifiques.js
- src/depots/depotDonneesServices.js
- src/modeles/risque.js
- src/modeles/risqueGeneral.js
- test/depots/depotDonneesServices.spec.js
- test/modeles/risques.spec.js
...afin de pouvoir ensuite les sauvegarder unitairement.
Migre les données en considérant qu'elles ne sont pas chiffrées...
> Ajoute un identifiant aux risques spécifiques

- public/inscription-v2.js
- src/mss.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/inscription-v2.pug
- svelte/lib/inscription/Inscription.svelte
- svelte/lib/inscription/SelectionFonction.svelte
- svelte/lib/inscription/inscription.d.ts
- svelte/lib/ui/Formulaire.svelte
- svelte/lib/ui/MenuFlottant.svelte
- test/aides/http.js
- test/routes/nonConnecte/routesNonConnectePage.spec.js
Le formulaire en trois étapes ne faisait rien jusqu’à présent. Désormais, il est envoyé à l’API à la fin de la troisième étape. Chaque étape est validée pour vérifier la possibilité de passer à l’étape suivante.
> Ajoute le comportement de soumission et de validation du formulaire d’inscription

- LICENSE
- README.md
> Remplace les liens en `.ssi` par `.cyber`

- svelte/lib/inscription/Inscription.svelte
- svelte/lib/inscription/SelectionDomaineSpecialite.svelte
- svelte/lib/inscription/inscription.d.ts
- svelte/lib/ui/ChampTexte.svelte
- Renomme les fonctions en domaine de spécialité
- Ajoute le numéro de téléphone
> Ameliore la saisie de l’identité pendant l’inscription

- public/assets/styles/home.css
- src/vues/home.pug
... car elle est maintenant disponible.
> Ajoute la vidéo de présentation sur la home

- public/assets/styles/home.css
- public/assets/styles/home.desktop.css
- src/vues/home.pug
> [HOME] Ajuste la taille de l'image et des polices du bloc "communauté"

- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/http/middleware.js
- src/mss.js
- src/routes/nonConnecte/routesNonConnecteApi.js
- test/routes/nonConnecte/routesNonConnecteApi.spec.js
... afin de pouvoir monitorer l'état de santé de la base de données.
Une protection de traffic est présente sur cette route, au même titre que les "endpoint sensibles"
> Ajout d'une route de `health check`

- src/vues/aPropos.pug
J'ai MàJ la page à propos suite retours juridiques
> Mets à jour le texte de la page "à propos"

- src/notifications/centreNotifications.js
- test/constructeurs/constructeurUtilisateur.js
- test/notifications/centreNotifications.spec.js
- test/routes/connecte/routesConnecteApiNotifications.spec.js
... pour éviter de montrer beaucoup de notification dès la première connexion.
> Ne considère que les nouveautés après la date d'inscription d'un utilisateur

- src/vues/mentionsLegales.pug
... suite à des retours du pôle juridique.
> Modification du contenu de la page "Mentions légales"

- public/profil.js
- src/routes/connecte/routesConnectePage.js
- src/vues/profil.pug
- svelte/lib/inscription/Inscription.svelte
- svelte/lib/inscription/SelectionDomaineSpecialite.svelte
- svelte/lib/inscription/SelectionNombreServices.svelte
- svelte/lib/inscription/SelectionOrganisation.svelte
- svelte/lib/inscription/inscription.d.ts
- svelte/lib/profil/Profil.svelte
- svelte/lib/profil/profil.d.ts
- svelte/lib/profil/profil.ts
- svelte/lib/ui/Bouton.svelte
- svelte/lib/ui/Formulaire.svelte
- test/routes/connecte/routesConnectePage.spec.js
Pour les nouveaux utilisateurs qui ont créé leur compte via ProConnect
> Ajoute une page de mise à jour de profil

- src/depotDonnees.js
- src/depots/depotDonneesServices.js
- src/modeles/listeRisques.js
- src/modeles/service.js
- src/routes/connecte/routesConnecteApiService.js
- test/depots/depotDonneesServices.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
...sur le modèle des mesures spécifiques, et afin de préparer la nouvelle page de risques (route non utilisée dans la page actuelle).
> [RISQUE] Supprime unitairement un risque spécifique

- src/adaptateurs/adaptateurMailSendinblue.js
- src/modeles/autorisations/ajoutContributeurSurServices.js
- test/modeles/autorisations/ajoutContributeurSurServices.spec.js
...pour pointer sur la nouvelle inscription
> Change l'url du mail d'invitation

- public/assets/styles/homologation/risques-v2.css
- public/service/risques-v2.js
- src/modeles/risqueGeneral.js
- src/modeles/risqueSpecifique.js
- src/referentiel.js
- src/routes/connecte/routesConnectePageService.js
- src/vues/service/risques-v2.pug
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/risques.d.ts
- svelte/lib/risques/risques.ts
- svelte/lib/ui/types.d.ts
- test/modeles/risqueGeneral.spec.js
- test/modeles/risqueSpecifique.spec.js
- test/modeles/service.spec.js
- test/routes/connecte/routesConnectePageService.spec.js
... avec un format "tableau".
Les risques ne sont pas modifiables pour l'instant.
> [RISQUES] Ajout de la première version de la page Risques "V2"

- public/service/risques-v2.js
- src/routes/connecte/routesConnectePageService.js
- src/vues/service/risques-v2.pug
- svelte/lib/risques/LigneRisque.svelte
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/risques/risques.d.ts
- svelte/lib/ui/CartoucheCategorieRisque.svelte
- svelte/lib/ui/CartoucheIdentifiantRisque.svelte
- svelte/lib/ui/Tiroir.svelte
- test/routes/connecte/routesConnectePageService.spec.js
Le risque en édition s’ouvre dans un tiroir latéral, comme pour les mesures
> Permet la visualisation d’un risque général

- svelte/lib/risques/LigneRisque.svelte
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/SelectionGravite.svelte
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/risques/risque.api.ts
- svelte/lib/risques/risques.d.ts
- svelte/lib/ui/ControleFormulaireTiroir.svelte
- svelte/lib/ui/ZoneTexte.svelte
> Permet la modification d’un risque général dans le tiroir

- svelte/lib/risques/LigneRisque.svelte
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/SelectionCategorieRisque.svelte
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/risques/risque.api.ts
- svelte/lib/risques/risques.d.ts
- svelte/lib/risques/risques.ts
- svelte/lib/ui/ZoneTexte.svelte
> Permet la modification d’un risque specifique

- donneesReferentiel.js
- public/service/risques-v2.js
- src/erreurs.js
- src/modeles/risque.js
- src/modeles/risqueGeneral.js
- src/modeles/risqueSpecifique.js
- src/referentiel.js
- src/routes/connecte/routesConnecteApiService.js
- src/vues/service/risques-v2.pug
- svelte/lib/risques/LigneRisque.svelte
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/SelectionGravite.svelte
- svelte/lib/risques/SelectionVraisemblance.svelte
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/risques/risque.api.ts
- svelte/lib/risques/risques.d.ts
- svelte/lib/risques/risques.ts
- svelte/lib/ui/ControleFormulaireTiroir.svelte
- test/modeles/risques.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
... aux risques généraux et spécifiques.
La vraisemblance initiale est un niveau de 0 à 4 comme la gravité potentielle.
> [RISQUES] Ajout de la vraisemblance

- svelte/lib/risques/SelectionGravite.svelte
- svelte/lib/risques/SelectionVraisemblance.svelte
- svelte/lib/ui/ControleFormulaireTiroir.svelte
En utilisant 100% de la largeur disponible
> Corrige la largeur de la sélection de catégorie

- public/assets/images/icone_poubelle.svg
- svelte/lib/mesure/Mesure.svelte
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/risques/risque.api.ts
- svelte/lib/ui/Avertissement.svelte
- svelte/lib/ui/Bouton.svelte
> [RISQUES] Suppression d'un risque spécifique

- src/adaptateurs/adaptateurStatistiquesMetabase.js
- src/vues/statistiques.pug
L'évolution du chiffre est de 3 points
> [STATISTIQUES] Corrige l'affichage de la progression de l'indice cyber

- src/routes/connecte/routesConnecteApiService.js
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/risques/risque.api.ts
- svelte/lib/risques/risques.ts
- svelte/lib/ui/Bouton.svelte
- test/routes/connecte/routesConnecteApiService.spec.js
Permets la création d'un nouveau risque spécifique via le tiroir
> [RISQUES] Ajoute un risque spécifique

- public/assets/styles/homologation/risques-v2.css
- svelte/lib/risques/LigneRisque.svelte
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/SelectionGravite.svelte
- svelte/lib/risques/SelectionVraisemblance.svelte
notamment au niveau des sélecteurs
> [RISQUES] Corrige l'affichage du tableau de risques

- donneesReferentiel.js
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/TiroirLegende.svelte
- svelte/lib/risques/TiroirLegendeGravite.svelte
- svelte/lib/risques/TiroirLegendeVraisemblance.svelte
- svelte/lib/risques/risques.d.ts
> Ajoute des tiroirs de légende

- migrations/20241022145938_ajouteIdentifiantNumeriqueRisquesSpecifiques.js
- src/modeles/risqueSpecifique.js
- src/modeles/service.js
- test/modeles/risqueSpecifique.spec.js
- test/modeles/risques.spec.js
- test/modeles/service.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
Les identifiants sont séquentiels et ont le propriétés suivantes :
- ils recommencent à 0 pour chaque service,
- ils ne sont jamais réutilisés, même en cas de suppression
> Ajoute un identifiant numerique aux risques specifiques

- donneesReferentiel.js
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/ui/ControleFormulaireTiroir.svelte
- Taille des libellés
- Aides à la saisie
- Mise en forme de la description longue pour les risques généraux
> Ajuste l’affichage du tiroir des risques

- svelte/lib/risques/LegendeMatriceRisques.svelte
- svelte/lib/risques/MatriceRisques.svelte
- svelte/lib/risques/Risques.svelte
> Affiche la cartographie des risques 

- src/adaptateurs/adaptateurJWT.js
- src/modeles/utilisateur.js
- test/modeles/utilisateur.spec.js
Cette PR change le design des tests pour ne plus avoir besoin de ce callback qui complexifie le raisonnement.
> [SOIN] Suppression d'un callback uniquement destiné aux tests

- public/assets/styles/homologation/mesures.css
- public/assets/styles/tiroir.css
- public/modules/tableauDeBord/gestionnaireTiroir.mjs
- src/vues/tiroirs/tiroir.pug
- svelte/lib/mesure/mesure.ts
- svelte/lib/risques/IdentifiantRisque.svelte
- svelte/lib/ui/CartoucheCategorieRisque.svelte
- svelte/lib/ui/CartoucheIdentifiantMesure.svelte
- svelte/lib/ui/CartoucheIndispensable.svelte
- svelte/lib/ui/CartoucheReferentiel.svelte
pour les padding des cartouches et l'affichage du mot "Mesure" en haut du tiroir de mesure
> Harmonise les tiroirs de mesure et risque

- svelte/lib/risques/Risques.svelte
- svelte/lib/ui/BoutonIcone.svelte
... par gravité et/ou vraisemblance
> [RISQUES] Tri du tableau

- svelte/lib/risques/Risques.svelte
Qui ouvre l'article dans un nouvel onglet du navigateur
> Ajoute un encart d'aide sur la page de risque

- src/adaptateurs/adaptateurPdf.js
- src/modeles/objetsPDF/objetPDFAnnexeRisques.js
- src/pdf/modeles/annexeRisques.pug
- src/pdf/modeles/ressources/styles.css
- test/modeles/objetsPDF/objetPDFAnnexeRisques.spec.js
> Ajoute la matrice des risques au PDF d'annexes

- donneesReferentiel.js
- server.js
- src/adaptateurs/adaptateurEnvironnement.js
- src/depotDonnees.js
- src/depots/depotDonneesUtilisateurs.js
- src/referentiel.js
- src/serviceCgu.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/depots/depotVide.js
Cette PR introduit un service CGU indépendant du lieu de stockage de la version actuelle des CGU (référentiel ou environnement).
> Lis la version des cgu depuis le référentiel

- public/assets/styles/cgu.css
- public/scripts/cgu.js
- src/http/middleware.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/cgu.pug
- test/http/middleware.spec.js
... lorsque l’utilisateur a accepté des CGU plus anciennes que la valeur actuelle.
> [CGU] Permets d’accepter les nouvelles CGU 

- donneesReferentiel.js
- src/vues/cgu.pug
> Mets à disposition les nouvelles CGU

- svelte/lib/risques/Risques.svelte
... afin de fonctionner sur les autres environnements.
> [CORRECTION] Utilise un lien relatif pour l'article des risques

- public/assets/styles/documentation.css
- public/scripts/matomo.js
- public/scripts/matomoGestionnaireTag.js
- public/scripts/optOutMatomo.js
- src/vues/confidentialite.pug
... et ajout de la checkbox pour opt-out sur Matomo.
> [POLITIQUE DE CONFIDENTIALITÉ] Mise à jour du contenu

- consoleAdministration.js
- src/adaptateurs/adaptateurSupervision.js
- src/bus/abonnements/delieServiceEtSuperviseurs.js
- src/bus/cablage.js
- test/bus/abonnements/delieServiceEtSuperviseurs.spec.js
... afin de maintenir à jour la table des `superivseurs` coté Metabase.
> [SUPERVISION] Suppression du lien entre superviseur et service à la suppression d'un service

- consoleAdministration.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesServices.js
- src/depots/depotDonneesSuperviseurs.js
- test/constructeurs/constructeurAdaptateurPersistanceMemoire.js
- test/depots/depotDonneesServices.spec.js
- test/depots/depotDonneesSuperviseurs.spec.js
... afin de pouvoir créer des superviseurs à la demande, pour les administrateurs.
> [SUPERVISEUR] Ajoute la méthode d'administration dans la console

- donneesReferentiel.js
- public/assets/images/ui-kit/chevron_droite.svg
- public/assets/styles/palette.css
- public/supervision.js
- src/adaptateurs/adaptateurSupervision.js
- src/referentiel.js
- src/routes/connecte/routesConnecteApi.js
- src/routes/connecte/routesConnectePage.js
- src/supervision/serviceSupervision.js
- src/vues/supervision.pug
- svelte/lib/superviseur/Supervision.svelte
- svelte/lib/superviseur/supervision.d.ts
- svelte/lib/superviseur/supervision.ts
- svelte/lib/ui/FilAriane.svelte
- svelte/lib/ui/ListeDeroulante.svelte
- svelte/lib/ui/ui.types.d.ts
- svelte/lib/uiKit/UiKit.svelte
- test/routes/connecte/routesConnecteApi.spec.js
- test/supervision/serviceSupervision.spec.js
Permet à l'utilisateur de filtrer le tableau de supervision sur une période donnée
> [Supervision] Filtre sur la date

- public/scripts/csrf.js
… afin d'essayer d'améliorer l'expérience utilisateur.
> [CORRECTION] Affiche la modale de reconnexion si une erreur "CSRF mismatch" est interceptée par le front

- src/adaptateurs/adaptateurSupervision.js
- src/adaptateurs/adaptateurSupervisionMetabase.js
- src/adaptateurs/fabriqueAdaptateurSupervision.js
- src/modeles/descriptionService.js
- src/routes/connecte/routesConnecteApi.js
- src/supervision/serviceSupervision.js
- svelte/lib/superviseur/Supervision.svelte
- test/modeles/descriptionService.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
... afin de pouvoir filtrer les services du tableau de supervision selon leur besoin de sécurité
> [SUPERVISION] Ajoute un filtre sur les besoins de sécurité

- migrations/20241119160421_ajoutColonnesSuperviseurs.js
- public/supervision.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/adaptateurs/adaptateurSupervisionMetabase.js
- src/depotDonnees.js
- src/depots/depotDonneesSuperviseurs.js
- src/modeles/superviseur.js
- src/routes/connecte/routesConnecteApi.js
- src/routes/connecte/routesConnectePage.js
- src/vues/supervision.pug
- svelte/lib/superviseur/Supervision.svelte
- svelte/lib/superviseur/supervision.d.ts
- svelte/lib/ui/ListeDeroulante.svelte
- test/depots/depotDonneesSuperviseurs.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
- test/routes/connecte/routesConnectePage.spec.js
Ajoute un filtre pour limiter le dashboard de supervision à une des entités supervisées.
> [SUPERVISION] Filtre sur les entités supervisées

- svelte/lib/profil/Profil.svelte
> [CORRECTION] Ajoute un accent sur MonServiceSécurisé

- svelte/lib/tableauDeBord/TableauDeBord.svelte
- svelte/lib/tableauDeBord/elementsDeService/EtiquetteHomologation.svelte
... afin de l'afficher dans le tableau des services.
> [TABLEAU DE BORD] Ajoute le badge du statut d'homologation

- src/vues/home.pug
Changement mineur du lien de prise de rendez-vous pour la présentation de MonServiceSécurisé. Le lien de Calendly de Henri a été remplacé par celui de Fabien
> Mise à jour du lien Calendly pour les rendez-vous de présentation

- public/assets/images/icone_plus_dsfr.svg
- svelte/lib/tableauDeBord/BandeauFiltres.svelte
- svelte/lib/ui/Lien.svelte
... permettant de rediriger vers la page de création.
> [TABLEAU DE BORD V2] Ajout du bouton de création de service

- public/accueilInscription.js
- public/connexion-v2.js
- public/creation-compte.js
- public/modules/donneesPartagees.mjs
- public/modules/suggestion/suggestionEntite.js
- public/modules/tableauDeBord/actions/ActionMesure.mjs
- public/modules/tableauDeBord/tableauDesServices.mjs
- public/motDePasse/edition.js
- public/mssConnecte.js
- public/profil.js
- public/scripts/conseilsCyber.js
- public/scripts/csrf.js
- public/scripts/menuNavigation.js
- public/service/descriptionService.js
- public/service/homologation/formulaireEtape.js
- public/service/indiceCyber.js
- public/service/mesures.js
- public/service/risques-v2.js
- public/supervision.js
- public/tableauDeBord-v2.js
...qui sont écrites par le pug dans une balise script
> [SOIN] Extrais une fonction pour lire les données partagées

- .env.template
- src/adaptateurs/adaptateurEnvironnement.js
- src/http/middleware.js
- src/vues/mssConnecte.pug
- test/http/middleware.spec.js
- Visite guidée
- pas d’autre feature flag inutilisé pour le moment
> [SOIN] Supprime les feature flags inutilisés

- .eslintrc.js
- nodemon.json
- Ameliore les performances de nodemon en ne surveillant que le répertoire source
- Corrige les erreurs d’import ESlint
> [SOIN] Améliore nos outils Typescript

- svelte/lib/tableauDeBord/TableauDesServices.svelte
… permettant par la suite de réaliser des actions groupées.
> [TDB] Ajoute les cases à cocher devant les noms de service et le nombre de lignes sélectionnées

- svelte/lib/tableauDeBord/TableauDesServices.svelte
> [TDB] Ajoute le nom de l'organisation responsable

- svelte/lib/uiKit/UiKit.svelte
... afin de visualiser tous les composants.
> [UI Kit] Ajoute un menu de navigation dans l'UI Kit

- svelte/lib/gestionContributeurs/invitation/InvitationContributeur.svelte
- svelte/lib/gestionContributeurs/suppression/SuppressionContributeur.svelte
- svelte/lib/tableauDeBord/TableauDeBord.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/stores/selectionService.store.ts
Extrais la sélection de services du TDB v2 dans un store dédié. Corrige la sélection et ajoute des toasters pour rendre plus clair que l'ajout/suppression de contributeur ont été un succès
> [SOIN] Store de sélection de service

- src/routes/connecte/routesConnecteApiService.js
- test/routes/connecte/routesConnecteApiService.spec.js
car on passe par une vérification front maintenant
> [Correction] Retire le challenge mot de passe sur la suppression de dossier

- src/adaptateurs/adaptateurStatistiquesMetabase.js
- src/vues/statistiques.pug
... avec les nouveaux chiffres à jour.
> [STATISTIQUES] Mets à jour la valeur de l'évolution de l'indice cyber

- .env.template
- README.md
- docker-compose.yml
- src/adaptateurs/adaptateurEnvironnement.js
- src/adaptateurs/adaptateurProfilAnssi.js
- src/adaptateurs/adaptateurProfilAnssiVide.js
- src/adaptateurs/fabriqueAdaptateurProfilAnssi.js
- src/depotDonnees.js
- src/depots/depotDonneesUtilisateurs.js
- test/creeUtilisateurDemo.spec.js
- test/depots/depotDonneesUtilisateurs.spec.js
Pour l'instant, le service MonProfilAnssi est derrière un feature flag. Par défaut, il y a un adaptateur vide.
Cette PR ne gère que l'inscription directe, pas l'inscription après invitation.
> [MonProfilAnssi] Inscris les nouveaux utilisateurs

- src/adaptateurs/adaptateurProfilAnssi.js
- src/adaptateurs/adaptateurProfilAnssiVide.js
- src/depots/depotDonneesUtilisateurs.js
- test/depots/depotDonneesUtilisateurs.spec.js
... lors de la mise à jour du profil MSS. La requête PUT est émise vers MonProfilAnssi.
> [MonProfilAnssi] Mets à jour le profil ANSSI

- server.ts
...pour récupérer la logique de feature flag
> [CORRECTION] Utilise la fabrique d'adaptateurProfilAnssi

- public/assets/styles/dossiers.css
- src/vues/service/dossiers.pug
Cette PR modifie l'encart de projet d'homologation.
On part de l'existant 👇 
… et on modifie 👇 
… pour arriver au résultat 👇
> [HOMOLOGUER] Modifications UI de l'encart de projet d'homologation

- src/vues/service/mesures.pug
Simple changement de wording.
Nouvelle version 👇
> Change la formulation du sous-titre

- svelte/lib/ui/tiroirs/TiroirSuppression.svelte
… afin de ne pas afficher des caractères HTML.
> [CORRECTION] Décode le nom du service pour la confirmation de suppression

- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/TableauVide.svelte
- svelte/lib/tableauDeBord/stores/affichageParStatutHomologation.ts
- svelte/lib/tableauDeBord/stores/affichageTableauVide.ts
... par statut d'homologation.
> [TBD V2] Ajoute des onglets pour filtrer les services

- src/adaptateurs/adaptateurProfilAnssi.js
- src/adaptateurs/adaptateurProfilAnssiVide.js
- src/depots/depotDonneesUtilisateurs.js
- test/depots/depotDonneesUtilisateurs.spec.js
... suite à la simplification de MonProfilAnssi
> Utilise la route de mise à jour de profil pour l’inscription

- svelte/lib/tableauDeBord/BandeauFiltres.svelte
- svelte/lib/tableauDeBord/TableauDeBord.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/stores/affichageParStatutHomologation.ts
- svelte/lib/tableauDeBord/stores/filtrageServices.store.ts
- svelte/lib/tableauDeBord/stores/rechercheTextuelle.store.ts
- svelte/lib/tableauDeBord/stores/resultatDeRecherche.store.ts
- svelte/lib/tableauDeBord/stores/services.store.ts
- svelte/lib/tableauDeBord/tableauDeBord.d.ts
- svelte/lib/tableauDeBord/tableauDeBord.ts
- svelte/lib/ui/ListeDeroulanteRiche.svelte
- svelte/lib/ui/Onglet.svelte
- svelte/lib/ui/Pastille.svelte
... en ajoutant un nouveau composant "Liste déroulante riche".
Pour l'instant ce composant n'est pas customisable, car pas nécessaire.
On filtre sur la propriété des services, ainsi que les tranches d'indice cyber.
> [TDB] Ajoute les filtres de propriété et d'indice cyber

- src/modeles/objetsApi/objetGetService.js
- svelte/lib/tableauDeBord/BandeauFiltres.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/stores/filtrageServices.store.ts
- svelte/lib/tableauDeBord/stores/resultatDeRecherche.store.ts
- svelte/lib/tableauDeBord/tableauDeBord.d.ts
- test/modeles/objetsApi/objetGetService.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
> [TDB] Ajoute les besoins de sécurité

- src/modeles/objetsApi/objetGetService.js
- svelte/lib/tableauDeBord/BandeauFiltres.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/TableauVide.svelte
- svelte/lib/tableauDeBord/elementsDeService/EtiquetteCompletude.svelte
- svelte/lib/tableauDeBord/stores/filtrageServices.store.ts
- svelte/lib/tableauDeBord/stores/resultatDeRecherche.store.ts
- svelte/lib/tableauDeBord/tableauDeBord.d.ts
- test/modeles/objetsApi/objetGetService.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
> [TDB] Ajoute la complétude

- .env.template
- package-lock.json
- package.json
- public/scripts/sentry.js
- src/adaptateurs/adaptateurGestionErreurSentry.js
- src/http/middleware.js
- src/vues/base.pug
- svelte/vite.config.mts
- test/http/middleware.spec.js
afin de récupérer les erreurs client
> Ajoute Sentry côté frontend

- svelte/lib/tableauDeBord/elementsDeService/EtiquetteCompletude.svelte
- svelte/lib/tableauDeBord/tableauDeBord.ts
... car il manquait les informations de complétude et de niveau de sécurité.
> [CORRECTION] Affiche correctement la visite guidée

- public/assets/styles/etapesDossier.css
- public/assets/styles/homologation/descriptionService.css
- svelte/lib/niveauxDeSecurite/NiveauxDeSecurite.svelte
- svelte/lib/tableauDeBord/BandeauBlog.svelte
- ordre des articles du bandeau blog suite à une décision métier
- flêches bleues sur les pages homologation/décrire qui ont été impactées par le changement de celle sur le tableau de bord
> [CORRECTIONS] Corrige le tableau de bord

- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/elementsDeService/EtiquetteContributeurs.svelte
- svelte/lib/tableauDeBord/elementsDeService/EtiquetteHomologation.svelte
- svelte/lib/tableauDeBord/elementsDeService/EtiquetteIndiceCyber.svelte
... afin de pouvoir faire du tracking Matomo.
> Ajoute des sélecteurs pour Matomo

- svelte/lib/tableauDeBord/BandeauFiltres.svelte
- svelte/lib/tableauDeBord/BandeauInfo.svelte
- svelte/lib/tableauDeBord/TableauDeBord.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
... afin de pouvoir utiliser les filtres n'importe où sur le tableau.
> [TDB] Ajoute la barre "sticky" du tableau des services

- svelte/lib/tableauDeBord/BandeauInfo.svelte
sur les cartouches en haut du TDB
> Corrige une faute d'orthographe

- server.ts
- src/adaptateurs/adaptateurJWT.js
- src/http/middleware.js
- src/modeles/utilisateur.js
- src/mss.ts
- src/routes/connecte/routesConnecteApi.js
- src/routes/nonConnecte/routesNonConnecteApi.js
- src/routes/nonConnecte/routesNonConnecteOidc.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/session/serviceGestionnaireSession.js
- test/aides/cookie.js
- test/http/middleware.spec.js
- test/modeles/utilisateur.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
- test/routes/nonConnecte/routesNonConnecteApi.spec.js
- test/routes/nonConnecte/routesNonConnecteOidc.spec.js
- test/routes/nonConnecte/routesNonConnectePage.spec.js
- test/routes/testeurMSS.js
- test/session/serviceGestionnaireSession.spec.js
... pour les écrire simplement au niveau de la `session`.
> [SOIN] Retire les paramètes `cguAcceptees` et `estInvite` du JWT utilisateur

- consoleAdministration.js
...qui ne supprimait pas les autorisations et les contributions au plan d'action des mesures.
Cela avait pour impact de bloquer la mise à jour du plan d'action.
> [CORRECTION] Corrige la suppression d'utilisateur dans la console admin

- src/modeles/autorisations/autorisation.js
- src/modeles/objetsApi/objetGetService.js
- svelte/lib/tableauDeBord/TableauDeBord.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/elementsDeService/EtiquetteCompletude.svelte
- svelte/lib/tableauDeBord/stores/filtrageServices.store.ts
- svelte/lib/tableauDeBord/stores/services.store.ts
- svelte/lib/tableauDeBord/tableauDeBord.d.ts
- svelte/lib/ui/Lien.svelte
- test/modeles/objetsApi/objetGetService.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
... sur le niveau de sécurité et le taux de complétion
> [TDB V2] Ajoute des liens

- src/adaptateurs/adaptateurMailSendinblue.js
- src/taches/envoieMailsNotificationExpirationHomologation.js
- test/taches/envoieMailsNotificationExpirationHomologation.spec.js
... et non pas qu'au propriétaire.
> Envoi les notifications d'expiration d'homologation à tous les contributeurs d'un service

- README.md
... avec des badges et illustrations.
> Améliore le README

- svelte/lib/tableauDeBord/BandeauInfo.svelte
- svelte/lib/tableauDeBord/TableauDeBord.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
... afin d'afficher correctement le TDB sur les "petits écrans".
> [TDB] Affichage du tableau de bord sur les "petits écrans"

- svelte/lib/tableauDeBord/BandeauInfo.svelte
- svelte/lib/tableauDeBord/TableauDeBord.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/tableauDeBord/TableauVide.svelte
- svelte/lib/ui/Bouton.svelte
...suite à une décision métier.
> [TDB] Dernière correction d'affichage

- scripts/taches/tacheEnvoieMailsNotificationExpiration.js
…d'envoi d'emails de notification.
Cette fonction n'était pas disponible dans l'ancien SDK de Sentry.
> Utilise la fonction `captureCheckIn` afin de monitorer correctement l'exécution de la tâche

- consoleAdministration.js
- src/adaptateurs/adaptateurPostgres.js
- src/adaptateurs/adaptateurSupervisionMetabase.js
- src/depotDonnees.js
- src/depots/depotDonneesSuperviseurs.js
- src/supervision/serviceSupervision.js
- test/depots/depotDonneesSuperviseurs.spec.js
- test/supervision/serviceSupervision.spec.js
Vérifie également sur la suppression d'un utilisateur s'il est superviseur, et révoque ses droits de supervision si c'est le cas.
> [ADMIN] Ajoute à la console la possibilité de supprimer un superviseur

- .env.template
- consoleAdministration.js
- src/adaptateurs/adaptateurChiffrementChaCha20.js
- src/adaptateurs/adaptateurEnvironnement.js
- src/adaptateurs/fabriqueAdaptateurChiffrement.js
- test/adaptateurs/adaptateurChiffrementChaCha20.spec.js
> Active le chiffrement des données

- src/vues/securite.pug
> Change le wording hébergement

- src/vues/maintenance.pug
... afin de mettre en avant l'aspect "volontaire" de cette maintenance.
> Corrige le wording de la page de maintenance

- src/vues/aPropos.pug
> Ajoute la mention de "Cloud temple" pour Clever Cloud

- public/assets/styles/dossiers.css
... pour corriger un affichage incorrect.
> Empêche le bouton du tampon d'homologation de passer sur 2 lignes

- src/vues/fragments/composantSvelte.pug
... en rajoutant un "-" devant les "//"
> [SOIN] Supprime l'affichage des commentaires dans le pug

- migrationHash.js
... afin d'obtenir un "feedback" lors des migrations.
> Affiche l'avancement des modifications des `evenements` du journal

- public/scripts/csrf.mjs
> [CORRECTION] Vérifie si la réponse axios contient bien une payload

- svelte/lib/tableauDeBord/BandeauInfo.svelte
… afin d'afficher correctement les cartes.
> Ajoute la condition singulier/pluriel sur les cartes d'informations du tableau de bord

- src/adaptateurs/adaptateurChiffrement.js
- src/http/middleware.js
- src/routes/connecte/routesConnectePage.js
- src/routes/connecte/routesConnectePageService.js
- test/http/middleware.spec.js
- test/mocks/middleware.js
- test/sel/serviceVerificationCoherenceSels.spec.js
... qui sera maintenant nécessaire pour toutes les pages utilisants l'UI Kit.
> Ajoute un `nonce` via le middelware

- src/vues/home.pug
> Mets à jour le nombre d'utilisateurs de MSS

- public/assets/styles/mss.css
- src/vues/mss.pug
... car sur la page connexion, on a pas le bloc "Utilisateur".
| ![image](https://github.com/user-attachments/assets/3df6eb85-933c-4078-b182-0d8c1ed35e9b) | ![image](https://github.com/user-attachments/assets/980a70df-0097-4e2a-b0c4-8bdaa53bc663) |
> Corrige l'affichage de la suite cyber sur la page de connexion

- src/vues/mss.pug
... Suite à des décisions métiers.
> Met à jour la version de l'UI Kit

- svelte/lib/doctrineHomologation/DoctrineHomologation.svelte
> Modifie le wording de la doctrine d'homologation

- src/vues/fragments/navigationSiteVitrine.pug
> modif-menu-nav

- svelte/lib/doctrineHomologation/DoctrineHomologation.svelte
- svelte/lib/doctrineHomologation/composants/CarrouselTuiles.svelte
... en utilisant plutôt le terme "homologation simplifiée".
> Modifie le wording de la "doctrine" d'homologation

- public/assets/styles/homologation/formulaire.css
... car il passait devant le centre d'aide
> [CORRECTION] Place le bandeau d'enregistrement en arrière-plan

- src/modeles/objetsPDF/objetPDFAnnexeRisques.js
- src/modeles/risqueGeneral.js
- src/routes/connecte/routesConnecteApiService.js
- svelte/lib/risques/IdentifiantRisque.svelte
- svelte/lib/risques/LigneRisque.svelte
- svelte/lib/risques/MatriceRisques.svelte
- svelte/lib/risques/Risques.svelte
- svelte/lib/risques/SelectionGravite.svelte
- svelte/lib/risques/SelectionVraisemblance.svelte
- svelte/lib/risques/TiroirRisque.svelte
- svelte/lib/risques/risque.api.ts
- svelte/lib/risques/risques.d.ts
- svelte/lib/ui/Switch.svelte
- test/modeles/objetsPDF/objetPDFAnnexeRisques.spec.js
- test/modeles/risqueGeneral.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
Cette PR ajouter une propriété "désactivé" aux risques généraux.
Un risque désactivé :
- N'apparait plus dans la matrice sur la page des risques
- Est masqué dans le PDF d'annexe
> Désactive un risque général

- src/vues/mss.pug
- src/vues/securite.pug
... afin d'uniformiser la page sécurité sur tous nos sites.
> Utilise le composant lab-anssi-resume-pssi

- src/vues/home.pug
... en ajoutant "Innovation ANSSI".
> Modification du wording du bloc "communauté" de la home

- src/utilisateur/serviceApresAuthentification.js
- test/utilisateur/serviceApresAuthentification.spec.js
… afin de rechercher un utilisateur sur MPA.
> [CORRECTION] Utilise l'email des informations ProConnect

- src/adaptateurs/adaptateurGestionErreurSentry.js
On veut éviter d'avoir des Sentry où la seule information qu'on obtienne est « ça ne marche pas ».
Pour enrichir, on détecte le cas où il s'agit d'une erreur Axios et on extrait les informations de celle-ci.
Avec cette PR, on obtient des infos dans Sentry 👇 
Ici on voit bien « BOOM CRICRI » qui est le message d'erreur que j'ai renvoyé depuis mon instance MPA locale pendant les tests.
> [Sentry] Ajoute des éléments de contexte lors du log d'erreur Axios

- docker-compose.yml
- src/vues/service/modaleParcoursHomologation.pug
Cette PR corrige un oubli dans les changements de wording :
* élémentaire ➡️ basiques
* importants ➡️ avancés 
On gagne aussi un peu de couleur dans le terminal de dev 👇
> Corrige du wording sur la modale d'Homologation

- .eslintrc.js
- admin/consoleAdministration.js
- package-lock.json
- package.json
… en s'appuyant sur la `lab-anssi-lib`.
On pourra par la suite, remplacer l'adaptateurProfilAnssi partout dans le code.
> Ajoute une méthode `admin` permettant de migrer les profils utilisateurs complets vers MonProfilANSSI

- admin/consoleAdministration.js
... car certains profils n'ont jamais fini de compléter leur entité.
> [CORRECTION] Filtre les profils qui n'ont pas une entité complète

- public/assets/styles/mss.css
- svelte/lib/doctrineHomologation/DoctrineHomologation.svelte
Cette PR change 2 choses :
* 1 ancre sur la vidéo explicative, pour pouvoir la linker depuis les posts sur les réseaux sociaux
* le lien de téléchargement en haut de page, qui renvoie vers tous les docs en bas de page
> Changements sur le front de la nouvelle doctrine

- migrations/20250513125549_creationTableTeleversementServices.js
- package-lock.json
- package.json
- server.ts
- src/adaptateurs/adaptateurControleFichier.js
- src/adaptateurs/adaptateurPostgres.js
- src/adaptateurs/adaptateurXLS.js
- src/depotDonnees.js
- src/depots/depotDonneesTeleversementServices.js
Cette PR implémente les adaptateurs de contrôle de fichier et d'extraction de données depuis le fichier template XLSX.
Ces données sont persistées chiffrées en BDD.
> [TÉLÉVERSEMENT] Implémente les adaptateurs de contrôle et extraction de fichier XLS

- package-lock.json
- package.json
... en suivant la documentation https://docs.sheetjs.com/docs/getting-started/installation/nodejs
> Met à jour la version de `xlsx`

- src/modeles/televersement/televersementServices.js
- test/modeles/televersement/televersementServices.spec.js
... en masse, en utilisant le modèle de la PR #2171 précédente.
Ce nouveau modèle est de type `ElementsConstructibles`.
> [TÉLÉVERSEMENT] Ajout d'un modèle métier de "Téléversement de services" permettant de réaliser des validations

- src/vues/home.pug
Car le CTA actuel n'est pas assez clair pour les users
> Modifie le wording du bouton de webinaire

- .github/workflows/node.js.yml
- .gitignore
- .mocharc.js
- package.json
... en utilisant le rapport `json` de mocha et `dorny`.
> Ajoute un rapport de tests dans la CI

- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesTeleversementServices.js
- src/routes/connecte/routesConnecteApiTeleversement.js
- test/routes/connecte/routesConnecteApiTeleversement.spec.js
... afin de nettoyer si le processus de téléversement est abandonné.
> [TÉLÉVERSEMENT] Ajout de la route de suppression d'un téléversement

- src/bus/abonnements/consigneNouvelleHomologationCreeeDansJournal.js
- src/bus/abonnements/consigneTeleversementServicesRealiseDansJournal.js
- src/bus/cablage.js
- src/bus/evenementDossierHomologationImporte.js
- src/bus/evenementServicesImportes.js
- src/modeles/journalMSS/erreurs.js
- src/modeles/journalMSS/evenementNouvelleHomologationCreee.js
- src/modeles/journalMSS/evenementServicesImportes.js
- src/modeles/televersement/televersementServices.js
- test/bus/abonnements/consigneNouvelleHomologationCreeeDansJournal.spec.js
- test/bus/abonnements/consigneTeleversementServicesRealiseDansJournal.spec.js
- test/bus/evenementDossierHomologationImporte.spec.js
- test/bus/evenementServicesImportes.spec.js
- test/modeles/journalMSS/evenementNouvelleHomologationCreee.spec.js
- test/modeles/journalMSS/evenementServicesImportes.spec.js
- test/modeles/televersement/televersementServices.spec.js
... en les cablant vers :
- Pour le dossier d'homologation importé
- Une consigne vers le journal
- Une planification de notification d'échéance
- Pour le téléversement complet réalisé
- Une consigne vers le journal
> [TÉLÉVERSEMENT] Ajoute les évènements d'homologation importé et de services importés

- public/scripts/sentry.js
- public/service/descriptionService.mjs
... afin de ne pas polluer Sentry.
> [SENTRY] Ignore les erreurs de requête annulée

- src/routes/connecte/routesConnecteApiService.js
- test/routes/connecte/routesConnecteApiService.spec.js
On ne retourne pas une chaîne sans l'échapper sachant que le message contient une entrée utilisateur.
> Corrige alerte #189 #190 #191 et #192

- public/assets/styles/article.css
- public/listeMesures.mjs
- src/routes/connecte/routesConnectePage.js
- src/vues/article.pug
- src/vues/listeMesures.pug
- src/vues/mss.pug
- svelte/lib/listeMesures/AucunResultat.svelte
- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/listeMesures.ts
- svelte/lib/ui/CartoucheCategorieMesure.svelte
- svelte/lib/ui/types.d.ts
- test/routes/connecte/routesConnectePage.spec.js
La page est accessible sur /mesures
> Affiche la liste des mesures du référentiel

- svelte/lib/listeMesures/BarreFiltres.svelte
- svelte/lib/listeMesures/LigneMesure.svelte
- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/filtrageMesures.store.ts
- svelte/lib/listeMesures/listeMesures.d.ts
- svelte/lib/listeMesures/mesuresAvecServicesAssocies.store.ts
- svelte/lib/listeMesures/mesuresReferentiel.store.ts
- svelte/lib/listeMesures/mesuresReferentielFiltrees.store.ts
- svelte/lib/listeMesures/rechercheMesures.store.ts
- svelte/lib/listeMesures/servicesAvecMesuresAssociees.store.ts
- svelte/lib/ui/types.d.ts
- svelte/test/listeMesures/mesuresAvecServicesAssocies.store.spec.ts
> Affiche le nombre de services associés à chaque mesure

- public/listeMesures.mjs
- src/routes/connecte/routesConnectePage.js
- src/vues/listeMesures.pug
- svelte/lib/listeMesures/DetailsMesure.svelte
- svelte/lib/listeMesures/LigneMesure.svelte
- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/listeMesures.d.ts
- svelte/lib/listeMesures/listeMesures.ts
- svelte/lib/listeMesures/mesuresAvecServicesAssocies.store.ts
- svelte/lib/mesure/contenus/ContenuOngletMesure.svelte
- svelte/lib/rapportTeleversement/RapportTeleversement.svelte
- svelte/lib/ui/Bouton.svelte
- svelte/lib/ui/DescriptionLongueMesure.svelte
- svelte/lib/ui/types.d.ts
> Affiche une modale avec les détails de la mesure

- svelte/lib/listeMesures/kit/tiroir/TiroirConfigurationMesure.svelte
- svelte/lib/listeMesures/kit/tiroir/etapes/TroisiemeEtape.svelte
- svelte/lib/listeMesures/listeMesures.api.ts
- svelte/lib/ui/Tableau.svelte
... avant d'afficher une modale de rapport.
L'appel API de modification est bien effectué.
> [LISTE MESURES] Ajoute la troisième et dernière étape du tiroir

- src/depotDonnees.js
- src/depots/depotDonneesAutorisations.js
- src/routes/connecte/routesConnecteApi.js
- svelte/lib/listeMesures/kit/tiroir/etapes/SecondeEtape.svelte
- svelte/lib/listeMesures/listeMesures.d.ts
- svelte/lib/ui/Tableau.svelte
- svelte/test/listeMesures/mesuresAvecServicesAssocies.store.spec.ts
- test/depots/depotDonneesAutorisations.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
... en cas d'absence de droit ou de modification de précision uniquement.
> [LISTE MESURES] Ajout le statut "désactivé" pour les services non modifiables

- src/adaptateurs/adaptateurCsv.js
- src/routes/connecte/routesConnectePage.js
- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/ui/Tableau.svelte
- test/routes/connecte/routesConnectePage.spec.js
> Exporte les mesures en CSV

- svelte/lib/ui/Toast.svelte
- svelte/lib/ui/Toaster.svelte
- svelte/lib/ui/stores/toaster.store.ts
... du toaster, avec une croix de fermeture.
> Ajoute la possibilité de fermeture des "Toast" 

- src/modeles/mesureSpecifique.js
- tdd-todo/import_mesures_specifiques.md
- test/modeles/mesureSpecifique.spec.js
... à l'image des mesures générales. Pour l'instant, cette propriété n'est pas éditable par l'utilisateur.
> Ajoute la propriété facultative de "Description longue" sur les mesures spécifiques

- migrations/20250711082001_creationTableModelesMesureSpecifique.js
- migrations/20250711082610_creationTableAssociationModelesMesureSpecifiqueEtService.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesModelesMesureSpecifique.js
- test/constructeurs/constructeurAdaptateurPersistanceMemoire.js
- test/depots/depotDonneesModelesMesureSpecifique.spec.js
... afin de pouvoir commencer à manipuler de la vrai données.
On a donc :
- Une table qui contient le détail du modèle de mesure, son `id` et l'`id` de son propriétaire
- Le détail sera chiffré 
- Une table qui reliera un modèle de mesure à un ou plusieurs services
> [MODELE MESURE SPÉCIFIQUE] Ajoute la persistance des modèles et des associations aux services

- .env.template
- public/listeMesures.mjs
- src/adaptateurs/adaptateurEnvironnement.js
- src/depotDonnees.js
- src/http/middleware.js
- src/routes/connecte/routesConnecteApi.js
- src/vues/listeMesures.pug
- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/kit/OngletsListeMesures.svelte
- svelte/lib/listeMesures/listeMesures.d.ts
- svelte/lib/listeMesures/stores/modelesMesureSpecifique.store.ts
- svelte/lib/ui/CartoucheIdentifiantMesure.svelte
- svelte/lib/ui/CartoucheReferentiel.svelte
- svelte/lib/ui/Tableau.svelte
- svelte/lib/ui/types.d.ts
- tdd-todo/import_mesures_specifiques.md
- test/http/middleware.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
... masqué par un feature flag `FEATURE_FLAG_MODELES_MESURE_SPECIFIQUE`.
> [MODÈLES MESURE SPÉCIFIQUE] Affiche les modèles dans la liste de mesure

- public/creation-compte.mjs
- src/mss.ts
- src/routes/nonConnecte/routesNonConnecteApi.js
- src/routes/nonConnecte/routesNonConnectePage.js
- src/vues/creation-compte.pug
- svelte/lib/inscription/Inscription.svelte
- svelte/lib/inscription/inscription.d.ts
- test/routes/nonConnecte/routesNonConnecteApi.spec.js
- test/routes/nonConnecte/routesNonConnectePage.spec.js
... au moment de la création de compte.
Afin de vérifier que l'email et les informations de ProConnect soient valides au moment de la soumission du formulaire de création de compte.
> [INSCRIPTION] Extrait les informations du token signé

- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/kit/tiroir/TiroirTeleversementModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/televersement/TiroirTeleversementModeleMesureSpecifique.svelte
- svelte/lib/ui/televersement/KitDeTeleversement.svelte
- svelte/lib/ui/televersement/KitDeTeleversement.types.ts
- svelte/lib/ui/tiroirs/TiroirTeleversementServices.svelte
- tdd-todo/televersement_mesures_specifiques.md
Cette PR déplace dans `<KitDeTeleversement />` tout ce qui est techniquement lié à du téléversement et qui pourra donc être mutualisé entre le téléversement des services (déjà en PROD) et celui des modèles de mesure (à venir en PROD).
> [REMANIEMENT] Extraction de `KitDeTeleversement`

- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/kit/ModaleDetailsMesure.svelte
- svelte/lib/listeMesures/kit/ServicesAssociesModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/kit/tiroir/TiroirAjoutModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/kit/tiroir/TiroirConfigurationModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/kit/tiroir/TiroirModificationMultipleMesuresGenerales.svelte
- svelte/lib/listeMesures/kit/tiroir/etapes/EtapesModificationMultipleStatutPrecision.svelte
- svelte/lib/listeMesures/kit/tiroir/etapes/SecondeEtape.svelte
- svelte/lib/listeMesures/kit/tiroir/etapes/TroisiemeEtape.svelte
- svelte/lib/listeMesures/listeMesures.api.ts
- svelte/lib/ui/types.d.ts
qui utilise les mêmes composants que la mise à jour en masse de statut et précision de mesure générale.
> [MODELES MESURES] Onglets de mise à jour en masse de statut et précision

- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/mesureSpecifique/TableauVideMesuresSpecifiques.svelte
- svelte/lib/ui/Tableau.svelte
- tdd-todo/import_mesures_specifiques.md
- corrige les filtres et la recherche
- affiche un contenu spécifique quand il n'y a aucun modèle
> [CORRECTIONS] Corrige l'affichage de la liste de mesures

- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/ui/Tableau.svelte
- tdd-todo/import_mesures_specifiques.md
... qui regroupe les mesures générales et les modèles de mesure spécifique.
> Ajoute l'onglet "Toutes les mesures"

- svelte/lib/listeMesures/mesureSpecifique/ServicesAssociesModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/mesureSpecifique/configuration/TiroirConfigurationModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/mesureSpecifique/modification/ConfirmationModificationModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/servicesAssocies/TableauServicesAssocies.svelte
- svelte/lib/tableauDeBord/BandeauFiltres.svelte
- svelte/lib/tableauDeBord/TableauDesServices.svelte
- svelte/lib/ui/referentielNiveauxSecurite.ts
- tdd-todo/import_mesures_specifiques.md
... afin de suivre le cheminement de la maquette.
> Ajoute l'étape de confirmation de modification d'un modèle de mesure spécifique

- src/depotDonnees.js
- src/depots/depotDonneesModelesMesureSpecifique.js
- src/routes/connecte/routesConnecteApi.js
- svelte/lib/ui/BoutonsRadio.svelte
- tdd-todo/import_mesures_specifiques.md
- test/depots/depotDonneesModelesMesureSpecifique.spec.js
- test/routes/connecte/routesConnecteApi.spec.js
... afin de laisser la possiblité à l'utilisateur de choisir sur quel service il veut supprimer la mesure.
> Supprime une liste de mesures spécifiques associées à un modèle

- svelte/lib/listeMesures/kit/TableauSelectionServices.svelte
- svelte/lib/listeMesures/listeMesures.api.ts
- svelte/lib/listeMesures/mesureSpecifique/suppression/TiroirSuppressionModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/modificationStatutPrecision/etapes/SecondeEtape.svelte
- tdd-todo/import_mesures_specifiques.md
> Affiche l'étape de suppression de mesures associées

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesModelesMesureSpecifique.js
- src/depots/modelesMesureSpecifique/VerificationsUtilisateurPeutMuterModele.js
- src/routes/connecte/routesConnecteApiService.js
- tdd-todo/import_mesures_specifiques.md
- test/depots/depotDonneesModelesMesureSpecifique.spec.js
- test/routes/connecte/routesConnecteApiService.spec.js
... afin de préparer le tiroir d'association multiple sur SÉCURISER.
> Ajoute une route permettant l'sssociation de plusieurs modeles à un service

- src/erreurs.js
- src/routes/connecte/routesConnecteApi.js
- svelte/lib/listeMesures/ListeMesures.svelte
- svelte/lib/listeMesures/mesureSpecifique/ServicesAssociesModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/mesureSpecifique/TableauVideMesuresSpecifiques.svelte
- svelte/lib/listeMesures/mesureSpecifique/configuration/TiroirConfigurationModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/mesureSpecifique/modification/ConfirmationModificationModeleMesureSpecifique.svelte
- svelte/lib/listeMesures/mesureSpecifique/suppression/TiroirSuppressionModeleMesureSpecifique.svelte
- svelte/lib/ui/Bouton.svelte
- svelte/lib/ui/BoutonAvecListeDeroulante.svelte
- svelte/lib/ui/ListeDeroulante.svelte
- tdd-todo/import_mesures_specifiques.md
- test/routes/connecte/routesConnecteApi.spec.js
> Applique les corrections suite à la recette

- svelte/lib/mesure/contenus/ContenuOngletMesure.svelte
- svelte/lib/mesure/mesure.store.ts
- svelte/lib/ui/DescriptionLongueMesure.svelte
- tdd-todo/import_mesures_specifiques.md
… ajoutée manuellement, afin d'être cohérent avec les mesures ajoutées via un modèle.
> Ajoute un champ d'édition pour la description longue d'une mesure spécifique

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesTeleversementModelesMesureSpecifique.js
- src/routes/connecte/routesConnecteApiTeleversement.modelesMesureSpecifique.js
- svelte/lib/listeMesures/televersement/RapportTeleversementModelesMesureSpecifique.svelte
- svelte/lib/listeMesures/televersement/rapportTeleversementModelesMesureSpecifique.api.ts
- tdd-todo/televersement_mesures_specifiques.md
- test/depots/depotDonneesTeleversementModelesMesureSpecifique.spec.js
- test/routes/connecte/routesConnecteApiTeleversement.modelesMesureSpecifique.spec.js
... soit via les boutons de la modale (Annuler, Fermer), soit lorsqu'il "retente" un import après erreurs.
> Supprime le téléversement en cours lorsque l'utilisateur annule

- src/bus/abonnements/consigneTeleversementModelesMesureSpecifiqueRealiseDansJournal.js
- src/bus/cablage.js
- src/bus/evenementModelesMesureSpecifiqueImportes.js
- src/depotDonnees.js
- src/depots/depotDonneesTeleversementModelesMesureSpecifique.js
- src/modeles/journalMSS/erreurs.js
- src/modeles/journalMSS/evenementModelesMesureSpecifiqueImportes.js
- tdd-todo/televersement_mesures_specifiques.md
- test/bus/abonnements/consigneTeleversementModelesMesureSpecifiqueRealiseDansJournal.spec.js
- test/depots/depotDonneesTeleversementModelesMesureSpecifique.spec.js
- test/modeles/journalMSS/evenementModelesMesureSpecifiqueImportes.spec.js
et consigne l'information dans le journal
> Publie un évènement de modèles de mesure spécifique importés

- README.md
... qui a probablement été cassé par #2255.
> Répare le badge indiquant la version de NodeJS

- .eslintrc.js
… des éléments inutiles. Ça fonctionne tout aussi bien sans.
> Nettoie la configuration ESLint

- admin/consoleAdministration.js
- admin/duplicationEnMasseDeServices/duplicationEnMasseDeServices.js
- creeUtilisateurDemo.js
- scripts/taches/tacheEnvoieMailsNotificationExpiration.js
- server.ts
- src/adaptateurs/adaptateurGestionErreurVide.js
- src/adaptateurs/adaptateurHorloge.js
- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurProfilAnssiVide.js
- src/adaptateurs/fabriqueAdaptateurGestionErreur.js
- src/adaptateurs/fabriqueAdaptateurProfilAnssi.js
- src/depots/depotDonneesUtilisateurs.js
- src/modeles/dossier.js
- src/modeles/etapes/decision.js
- src/modeles/parcoursUtilisateur.js
- src/mss.ts
- test/constructeurs/constructeurDossier.js
- test/depots/depotDonneesUtilisateurs.spec.js
- test/http/middleware.spec.js
- test/modeles/parcoursUtilisateur.spec.js
- test/notifications/centreNotifications.spec.js
- test/routes/testeurMSS.js
- test/taches/envoieMailsNotificationExpirationHomologation.spec.js
En créant #2344 on a découvert qq travaux de nettoyages qui seraient plus simples à relire s'ils étaient dans une PR dédiée.
Donc on crée cette PR ci.
> 🧹 Nettoyage avant le passage à ESM

- docker-compose.yml
- package-lock.json
- package.json
- src/http/middleware.js
- src/routes/nonConnecte/routesNonConnecteApiBibliotheques.js
- src/vues/base.pug
- src/vues/fragments/composantSvelte.pug
- svelte/lib/index.html
- svelte/vite.config.mts
... pour le dev local.
Cette fonctionnalité permet de recharger automatiquement notre front lorsque des changements sont effectués sur les composants Svelte.
Elle peut être lancé via
```sh
./scripts/dev.sh
```
> Ajoute le "Hot Reload" de Svelte

- src/adaptateurs/adaptateurPersistanceMemoire.js
- src/adaptateurs/adaptateurPostgres.js
- src/depotDonnees.js
- src/depots/depotDonneesBrouillonService.ts
- src/modeles/brouillonService.ts
- src/routes/connecte/routesConnecteApiBrouillonService.ts
- svelte/lib/creationV2/CreationV2.svelte
- svelte/lib/creationV2/creationV2.api.ts
- svelte/lib/ui/ChampTexte.svelte
- tdd/fil_rouge_decrire_v2.md
- test/depots/depotDonneesBrouillonService.spec.ts
- test/modeles/brouillonService.spec.ts
- test/routes/connecte/routesConnecteApiBrouillonService.spec.ts
... afin de pouvoir mettre en place la mise à jour des champs au fil de l'eau.
> Ajoute le champ "siret" dans la création d'un brouillon de service

- svelte/lib/creationV2/etapes/etape1/QuestionNomService.svelte
- svelte/lib/creationV2/etapes/etape2/QuestionSpecificitesProjet.svelte
- svelte/lib/creationV2/etapes/toutesEtapes.ts
> Modifie le wording des questions

- svelte/lib/creationV2/CreationV2.svelte
- svelte/lib/creationV2/creationV2.types.ts
- svelte/lib/creationV2/etapes/BrouillonDeServiceEditable.svelte
- svelte/lib/creationV2/etapes/ListeChampTexte.svelte
- svelte/lib/creationV2/etapes/brouillon.store.ts
- svelte/lib/creationV2/etapes/brouillonEstComplet.store.ts
- svelte/lib/creationV2/etapes/etapeCourante.store.ts
- svelte/lib/creationV2/etapes/modeRapide/EtapeCreationEnModeRapide.svelte
- svelte/lib/creationV2/etapes/navigation.store.ts
- svelte/lib/creationV2/etapes/resume/EtapeResumeDuService.svelte
- svelte/lib/creationV2/etapes/resume/resume.store.ts
- svelte/lib/creationV2/etapes/toutesEtapes.ts
- svelte/lib/ui/Switch.svelte
Ajoute un mode rapide qui reprend le résumé éditable
> PR #2: Ajoute le mode rapide

- public/assets/styles/home.desktop.css
- src/vues/home.pug
Ceci est un revert du commit d31e9d687d404bf8fbb48c6ddfa9cdc526fa4d92. 
On avait du revert un commit à cause d'un problème d'UI Kit.
-> Utilise le composant de l'ui kit pour afficher la présentation ANSSI
> Utilise <lab-anssi-presentation-anssi>
